### ISSUE TITLE
Docview查看Office文档失败。

### ISSUE THREAD

**Issue by zheng7fu2** [redguardtoo/emacs.d#1002]
显示出错信息：DocView: process pdf/ps->png changed status to exited abnormally with code 1.

GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-04-28
安装了 GhostScript 9.56.1-1 unoconv-0.9-2  mupdf-tools 1.20.3-1

查看PDF文档、txt文档 是可以的。

**Comment by redguardtoo** [comment]
I think docview supports pdf only.

**Comment by zheng7fu2** [comment]
不是的，我找到原因了。
查看Office文档需要 “unoconv” 来源 https://www.gnu.org/software/emacs/manual/html_node/emacs/Document-View.html
unoconv  是依赖 libreoffice 或 OpenOffice 的。来源 https://github.com/unoconv/unoconv
libreoffice 在启动时会找JRE，找不到也不影响主要功能。
javaldx: Could not find a Java Runtime Environment!
Warning: failed to read path from javaldx

搜索发现  java支持 是libreoffice 的可选功能，来源 https://archlinux.org/packages/extra/x86_64/libreoffice-fresh/
于是安装 jre-openjdk 包。
可以查看Office文档了。
