### ISSUE TITLE
sdcv-search-input+ 函数调用后没有结果显示出来

### ISSUE THREAD

**Issue by hhcwyx** [redguardtoo/emacs.d#1004]
现象：光标在一个单词内，比如：china，此时按“; d t”组合，在china单词的旁边没有任何结果显示出来。在message buffer里也没看到什么错误信息。尝试了一下mybigword-pronounce-word函数，这个函数正常，会读出单词。
系统是新装的archlinux，装了stardict,sdcv,在～/.stardict/dic目录下下载解压了字典文件。

**Comment by redguardtoo** [comment]
确认一下sdcv,
```
$ sdcv --help
Usage:
  sdcv [OPTION…]  words

Help Options:
  -h, --help                     Show help options

Application Options:
  -v, --version                  display version information and exit
  -l, --list-dicts               display list of available dictionaries and exit
  -u, --use-dict=bookname        for search use only dictionary with this bookname
  -n, --non-interactive          for use in scripts
  -j, --json-output              print the result formatted as JSON
  --json                         print the result formatted as JSON
  -e, --exact-search             do not fuzzy-search for similar words, only return exact matches
  -0, --utf8-output              output must be in utf8
  -1, --utf8-input               input of sdcv in utf8
  -2, --data-dir=path/to/dir     use this directory as path to stardict data directory
  -x, --only-data-dir            only use the dictionaries in data-dir, do not search in user and system directories
  -c, --color                    colorize the output
```

**Comment by redguardtoo** [comment]
确认一下sdcv,
```
$ sdcv --help
Usage:
  sdcv [OPTION…]  words

Help Options:
  -h, --help                     Show help options

Application Options:
  -v, --version                  display version information and exit
  -l, --list-dicts               display list of available dictionaries and exit
  -u, --use-dict=bookname        for search use only dictionary with this bookname
  -n, --non-interactive          for use in scripts
  -j, --json-output              print the result formatted as JSON
  --json                         print the result formatted as JSON
  -e, --exact-search             do not fuzzy-search for similar words, only return exact matches
  -0, --utf8-output              output must be in utf8
  -1, --utf8-input               input of sdcv in utf8
  -2, --data-dir=path/to/dir     use this directory as path to stardict data directory
  -x, --only-data-dir            only use the dictionaries in data-dir, do not search in user and system directories
  -c, --color                    colorize the output
```

**Comment by hhcwyx** [comment]
% sdcv --help 输出如下：
用法：
  sdcv [选项…]  words

帮助选项：
  -h, --help                     显示帮助选项

应用程序选项：
  -v, --version                  display version information and exit
  -l, --list-dicts               display list of available dictionaries and exit
  -u, --use-dict=bookname        for search use only dictionary with this bookname
  -n, --non-interactive          for use in scripts
  -j, --json-output              print the result formatted as JSON
  --json                         print the result formatted as JSON
  -e, --exact-search             do not fuzzy-search for similar words, only return exact matches
  -0, --utf8-output              output must be in utf8
  -1, --utf8-input               input of sdcv in utf8
  -2, --data-dir=path/to/dir     use this directory as path to stardict data directory
  -x, --only-data-dir            only use the dictionaries in data-dir, do not search in user and system directories
  -c, --color                    colorize the output

**Comment by hhcwyx** [comment]
% sdcv china 输出如下：
 Found 2 items, similar to china.
-->dictd_www.dict.org_gcide
-->China

Porcelain \Por"ce*lain\ (277), n. [F. porcelaine, It.
   porcellana, orig., the porcelain shell, or Venus shell
   (Cypr[ae]a porcellana), from a dim. fr. L. porcus pig,
   probably from the resemblance of the shell in shape to a
   pig's back. Porcelain was called after this shell, either on
   account of its smoothness and whiteness, or because it was
   believed to be made from it. See {Pork}.]
   A fine translucent or semitransculent kind of earthenware,
   made first in China and Japan, but now also in Europe and
   America; -- called also {China}, or {China ware}.
   [1913 Webster]

         Porcelain, by being pure, is apt to break. --Dryden.
   [1913 Webster]

   {Ivory porcelain}, porcelain with a surface like ivory,
      produced by depolishing. See {Depolishing}.

   {Porcelain clay}. See under {Clay}.

   {Porcelain crab} (Zo["o]l.), any crab of the genus
      {Porcellana} and allied genera (family {Porcellanid[ae]}).
      They have a smooth, polished carapace.

   {Porcelain jasper}. (Min.) See {Porcelanite}.

   {Porcelain printing}, the transferring of an impression of an
      engraving to porcelain.

   {Porcelain shell} (Zo["o]l.), a cowry.
      [1913 Webster]


China \Chi"na\, n.
   1. A country in Eastern Asia.
      [1913 Webster]

   2. China ware, which is the modern popular term for
      porcelain. See {Porcelain}.
      [1913 Webster]

   {China aster} (Bot.), a well-known garden flower and plant.
      See {Aster}.

   {China bean}. See under {Bean}, 1.

   {China clay} See {Kaolin}.

   {China grass}, Same as {Ramie}.

   {China ink}. See {India ink}.

   {China pink} (Bot.), an anual or biennial species of
      {Dianthus} ({Dianthus Chiensis}) having variously colored
      single or double flowers; Indian pink.

   {China root} (Med.), the rootstock of a species of {Smilax}
      ({Smilax China}, from the East Indies; -- formerly much
      esteemed for the purposes that sarsaparilla is now used
      for. Also the galanga root (from {Alpinia Gallanga} and
      {Alpinia officinarum}).

   {China rose}. (Bot.)
      (a) A popular name for several free-blooming varieties of
          rose derived from the {Rosa Indica}, and perhaps other
          species.
      (b) A flowering hothouse plant ({Hibiscus Rosa-Sinensis})
          of the Mallow family, common in the gardens of China
          and the east Indies.

   {China shop}, a shop or store for the sale of China ware or
      of crockery.

   {Pride of China}, {China tree}. (Bot.) See {Azedarach}.
      [1913 Webster]


-->StarDict dictionary
-->china

瓷器

**Comment by hhcwyx** [comment]
sdcv应该是正常的吧？

**Comment by redguardtoo** [comment]
`~/.emas.d/elpa/popup-0.5.9`在吗? 

`M-x toggle-debug-on-error` 重现一下issue.  相关插件很稳定.不应该有问题的.

**Comment by hhcwyx** [comment]
～/.emacs.d/elpa/popup-0.5.9在的。
M-x toggle-debug-on-error 执行后，mini-buffer 里显示：Debug on Error enabled globally;
然后光标放到china单词上，按“; d t”后，mini-buffer里出现：
Word （china）：
直接按enter，仍然没有输出。
messages  buffer里也没有错误信息。

**Comment by redguardtoo** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/184553/193731145-ed554c95-87d6-4ca8-b1f3-d81de784cc49.png">

**Comment by hhcwyx** [comment]
Try M-x eval-expression ENTER (popup-tip "===hello world==="),
有一个弹出框，显示正常。
 sdcv-dictionary-simple-list is a variable defined in sdcv.el.
Value
("朗道英汉字典5.0")
Original Value
nil

**Comment by hhcwyx** [comment]
~/.stardict/ 目录下的结构是：
.
├── dic
│   ├── stardict-dictd_www.dict.org_wn-2.4.2
│   │   ├── stardict-dictd_www.dict.org_wn-2.4.2.dict.dz
│   │   ├── stardict-dictd_www.dict.org_wn-2.4.2.idx
│   │   ├── stardict-dictd_www.dict.org_wn-2.4.2.idx.oft
│   │   └── stardict-dictd_www.dict.org_wn-2.4.2.ifo
│   └── stardict-langdao-ce-gb-2.4.2
│       ├── langdao-ce-gb.dict.dz
│       ├── langdao-ce-gb.idx
│       ├── langdao-ce-gb.idx.oft
│       └── langdao-ce-gb.ifo
└── stardict-langdao-ce-gb-2.4.2.tar.bz2

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/193803900-159b0284-4efa-4b5b-b15c-216cfdf653d5.png)

**Comment by hhcwyx** [comment]
下载了stardict-langdao-ec-gb-2.4.2 字典后，一切正常了。感情这是缺少字典文件啊。
谢谢陈老师！！！
