### ISSUE TITLE
TAGS file too big in frontend project?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#1006]
i don't know where the exactly issue is, but my frontend project auto-completion always stucks with `Please be patient when loading TAGS`. then i check the TAGS file, it is 97M in my fronend project. (while at the same time my nodejs server project only has 1.8M TAGS). i don't know if anything error with my frontend project to make TAGS file so large (or it is still normal ?  i tried to run `ctags -R .` in my frontend it get 300M ctags file).  
and with this 97M TAGS, loading it seems really slow in emacs. it is really annoying me since emacs stop working when loading TAGS. any idea on this issue?

BTW, i had a similiar frontend project only has 8.9M TAGS. sounds more strange. since 97M project is just like, double the file (i.e. copy file1 to file2 and keep both version in project for every files). i don't think such files increase 10x times of TAGS size?

**Comment by smallst** [comment]
btw. the 8.9M TAGS project contains `.vue, .js, .coffee` files, while 97M project contains `.a.js, .b.js, .a.coffee, .b.coffee` (since i duplicate the files) would this affect the TAGS file to verify the file(programming language) format?

**Comment by redguardtoo** [comment]
If you use `counsel-etag` to generate tags file, you can set `counsel-etags-ignore-filenames` and `counsel-etags-ignore-directories`. 

Or else you set ctags cli options by yourself,
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/184553/194784461-0fac6454-4f08-40d7-a8e4-07c84a4a2598.png">

**Comment by smallst** [comment]
oh thanks! i found my `public` dir isn't in ingore path. add it. make sense!
