### ISSUE TITLE
Emacs 28.2 term terminal only support 8 colors.

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1011]
I use `M+x, term` to open `zsh`, but the color number is only 8 colors, which is not enough to display the powerlevel10k them prefectly.

I have tried to set   `TERM=xterm-256color` , but the disply in the emacs is very wired.

![image](https://user-images.githubusercontent.com/48000576/202429716-49b04143-bb8e-46b5-b803-47c39bd21b43.png)

The normal looking should be like this:

![image](https://user-images.githubusercontent.com/48000576/202429858-58ad7f2b-ce52-4885-91c2-ed4c6691e34f.png)

**Comment by redguardtoo** [comment]
I have no idea. Set `TERM` won't help anyway.

**Comment by sbwcwso** [comment]
> I have no idea. Set `TERM` won't help anyway. If the teminal supports 256 color, it usually just works out of box.

Thank you for replay.

I give up, I use the .zshrc file to detect if it is in the emacs, then I set two different theme. Just like this.

![image](https://user-images.githubusercontent.com/48000576/203277674-5bc4aef0-88e0-4124-8973-7f8e52d7c523.png)

Enough for me.
