### ISSUE TITLE
autosave will delete the blank at current cursor.

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1014]
In the C mode, when I input a blank and thinking what to input next, the blank will disapper. It seems that the autosave delete the blank at the cursor, how to avoid this? 

Thank you very much.

**Comment by redguardtoo** [comment]
Comment out `(ws-butler-mode 1)` or change your coding workflow.

**Comment by sbwcwso** [comment]
> Comment out `(ws-butler-mode 1)` or change your coding workflow.

It seems that change my coding workflow is more reasonable, then I may input fewer things. Thank you very much, I have learned a lot.
