### ISSUE TITLE
How to disable pyim, I want to use package rime instead.

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1015]

**Comment by redguardtoo** [comment]
550852f2 pyim is optional (Chen Bin)

**Comment by sbwcwso** [comment]
> [550852f](https://github.com/redguardtoo/emacs.d/commit/550852f25187ad8b9418ebe2f6335c7c3d1888c6) pyim is optional (Chen Bin)

Thank you very much. I comment out this line: 

https://github.com/redguardtoo/emacs.d/blob/550852f25187ad8b9418ebe2f6335c7c3d1888c6/lisp/init-chinese.el#L45

And it worked very well now.

**Comment by redguardtoo** [comment]
You could just `(setq my-toggle-ime-init-function nil)`,
