### ISSUE TITLE
How to use wrap-region in evil-mode?

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1016]
I want to use the [wrap-region](https://github.com/rejeep/wrap-region.el), but it doesn't work in the evil mode, whem I type 'V' to select the region, but it works well outside the evil mode.

How can I make it work in evil-mode, or is there anything similar function in your setting?

**Comment by redguardtoo** [comment]
Evil users usually use builtin evil text object, `evil-surround`, `evil-matchit`.

**Comment by sbwcwso** [comment]
> Evil users usually use builtin evil text object, `evil-surround`, `evil-matchit`.

I am a novice of emacs, can you give me an example please?

For example, I want to  implement the following functions:

[emacs-how-to-wrap-selection-in-org-mode-source-code-block](https://stackoverflow.com/a/61724486/11152760)

**Comment by sbwcwso** [comment]
I have found the package there, [emacs-evil/evil-surround: you will be surrounded (surround.vim for evil, the extensible vi layer)](https://github.com/emacs-evil/evil-surround), thank you very much.
