### ISSUE TITLE
evil-vim mode repeate doen't support `F f` find a character command?

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1018]
In the normal vim, in visual mode, after I press `f a`, it will find the next `a` charater, when I press `;`, it will find the next.

But this feature seems not work now? How can I make this work?

**Comment by redguardtoo** [comment]
comment out `my-semicolon-leader-def` stuff. 

BTW, in Emacs, you can use `ace-jump` or `ace-pinyin-jump` instead.

**Comment by sbwcwso** [comment]
> comment out `my-semicolon-leader-def` stuff.
> 
> BTW, in Emacs, you can use `ace-jump` or `ace-pinyin-jump` instead.

The `ace-pinyin-jump-char-2` is more powerful than what I used before, thank you very much.
