### ISSUE TITLE
mybigword-pronunce-word function not work

### ISSUE THREAD

**Issue by hhcwyx** [redguardtoo/emacs.d#1022]
光标置于一个单词,运行mybigword-pronunce-word ,输出以下信息:
error in process filter: gnutls-error: (gnutls-error dictionary.cambridge.org -110)
Sorry, can’t find pronunciation for "bothered"

**Comment by redguardtoo** [comment]
blocked by firewall?

**Comment by hhcwyx** [comment]
谢谢!
