### ISSUE TITLE
Disable using number keys as shortcus for company candidates

### ISSUE THREAD

**Issue by Stumble** [redguardtoo/emacs.d#1027]
Hi Bin, I am trying to find out where could I disable using number-keys when selecting auto complete candidates.

Example situation:
When I want to type ‘past24Hour’, it becomes very tricky: after typing 'past', the selection menu showed up and when I press '2',
it just auto complete to 'past7Hour', instead of allowing me to just type 'past24Hour'.

![image](https://user-images.githubusercontent.com/3461891/217081535-fcd62602-669a-4325-87b5-bf264c8ff224.png)

I remember the behavior used to be using 'M-number' keys as bindings, which is good, any idea of how to get back to it?

**Comment by suliveevil** [comment]
Seems it matches the comment string `string (Variable) 2` when there are few candidates.

It may be a feature of auto-completion when candidate less than certain numbers

**Comment by BlacAmDK** [comment]
https://github.com/redguardtoo/emacs.d/blob/1c69820c658fb1ac91d4f3860fd64926f847acb7/lisp/init-company.el#L51-L59

**Comment by Stumble** [comment]
> https://github.com/redguardtoo/emacs.d#code-auto-completion
> 
> https://github.com/redguardtoo/emacs.d/blob/1c69820c658fb1ac91d4f3860fd64926f847acb7/lisp/init-company.el#L7-L8

Oh Thanks! Can't believe I missed this line.
