### ISSUE TITLE
请问 emacs 调用外部的 look 命令有什么用吗？我应该怎么关掉？

### ISSUE THREAD

**Issue by sui4444** [redguardtoo/emacs.d#1035]

**Comment by redguardtoo** [comment]
Could you give me more details?

**Comment by sui4444** [comment]
在使用 org-mode 输入的时候，Starting "look" process... [10 times] 。尤其是使用输入法的时候，会卡一下。

**Comment by redguardtoo** [comment]
must be `company-ispell` which auto-completes English words. You can turn off it by `(setq company-ispell-available nil)`. Or you can assign a plain text dictionary to `company-ispell-dictionary`. If you use my seiup, all is setup.

The cli program `look` is used to look up word. If you use Cygwin or MSYS2 and add its executables to OS env variable `PATH`, emacs will find `look` out of box.

**Comment by sui4444** [comment]
good，问题解决了。
