### ISSUE TITLE
error: Package ‘majapahit-theme-’ is unavailable

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#1036]
git clone  

emacs first setup

error: Package ‘majapahit-theme-’ is unavailable

Debugger entered--Lisp error: (error "Package ‘majapahit-theme-’ is unavailable")
  error("Package `%s-%s' is unavailable" majapahit-theme "")
  package-compute-transaction(nil ((majapahit-theme)))
  package-install(majapahit-theme)
  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-contents) no-refresh) nil (message "Missing package: %s" package) (package-refresh-contents)) (package-install package))
  require-package(majapahit-theme)
  (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- my-color-themes)) (while --dolist-tail-- (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (if my-disable-idle-timer nil (let ((--dolist-tail-- my-color-themes)) (while --dolist-tail-- (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  load-with-code-conversion("c:/Users/kk/AppData/Roaming/.emacs.d/lisp/init-elp..." "c:/Users/kk/AppData/Roaming/.emacs.d/lisp/init-elp..." t t)
  load("c:/Users/kk/AppData/Roaming/.emacs.d/lisp/init-elp..." t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not my-lightweight-mode-p)) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if (or my-lightweight-mode-p my-disable-idle-timer) (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-bookmark) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-term-mode) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emms t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (if my-lightweight-mode-p (progn (require-init 'init-ediff))) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-no-byte-compile t) (if my-lightweight-mode-p nil (setq custom-file (concat my-emacs-d "custom-set-variables.el")) (if (file-exists-p custom-file) (load custom-file t t)) (my-run-with-idle-timer 1 #'(lambda nil (load "~/.custom.el" t nil)))))
  load-with-code-conversion("c:/Users/kk/AppData/Roaming/.emacs.d/init.el" "c:/Users/kk/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/kk/AppData/Roaming/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x9d32dad0cc4b4e8>) #f(compiled-function () #<bytecode -0x1f3c686ddc0da035>) t)
  command-line()
  normal-top-level()

**Comment by vipzrx** [comment]
init-elpa.el 中majapahit-theme

改成     majapahit-themes

**Comment by redguardtoo** [comment]
sure. ur request merged.
