### ISSUE TITLE
When I set byte-compile-warnings globaly, it not working for flymake.

### ISSUE THREAD

**Issue by sbwcwso** [redguardtoo/emacs.d#1038]
I put this sentence in my init.el  `(setq byte-compile-warnings '(not free-vars unresolved))`, but the flymake will still warning.

![image](https://user-images.githubusercontent.com/48000576/227768659-376903e6-f20a-4351-9e4c-efd80fe99656.png)

**Comment by redguardtoo** [comment]
that's ok .  You can ignore those warnings.

**Comment by sbwcwso** [comment]
> That's ok . You can ignore those warnings.
> 
> BTW, byte compile your "emacs.d" won't speed up emacs and could bring more trouble (you changed your emacs.d but forgot to compile the latest init.el). I remember I wrote some article about this issue.

But when I put the follow code in the init.el, there is no such warning in the flaymake intermately.

```
;; Local Variables:
;; byte-compile-warnings: (not free-vars unresolved callargs)
;; End:
```

I get this from [https://emacs.stackexchange.com/a/19507](https://emacs.stackexchange.com/a/19507)

**Comment by sbwcwso** [comment]
I know how to deal with the `free-vars` and `unresolved` problems, I add the following code to my init.el and there is no warning any more.

```
(setq elisp-flymake-byte-compile-load-path load-path)
(add-to-list 'elisp-flymake-byte-compile-load-path "~/.emacs.d/lisp")
```

I am not sure whether this have side effect or not.
