### ISSUE TITLE
Symbol's function definition is void: linum-mode

### ISSUE THREAD

**Issue by iFHiGM** [redguardtoo/emacs.d#1039]
大佬你好，

我的配置环境：
系统：windows11
emacs环境：MSYS2 MinGW 64
emacs版本：源码自编译（MINGW工具链），30.0.50
基于您的配置版本：9ebe7fdf476d1a6d8c4e64cd9c0207da5b36b9e7
我的fork: https://github.com/iFHiGM/emacs.d/tree/my_emacs_setting

最近打开emacs的时候总会出现：

> Error running timer 'global-git-gutter-mode': (void-variable global-linum-mode)

这样子的报错。

而且当我在package-list-packages界面，使用U, x更新包时，会提示：

> Symbol's function definition is void: linum-mode

遂查了一下[相关的文档](https://emacs.stackexchange.com/questions/45604/permanently-display-line-numbers-in-emacs)，怀疑是linum-mode的问题，在我做了[如下修改](https://github.com/redguardtoo/emacs.d/commit/b85828901b94f9941cd82ff4b930c66b2e35b21a)之后，相关错误消失了。

请问，这个算是bug吗？

**Comment by phye** [comment]
Same issue here with emacs-plus@29 on macos
May be linum-mode is deprecated?

**Comment by redguardtoo** [comment]
eb3824a5 drop support of linum-mode which is not useful since emacs27 (Chen Bin)

**Comment by lianghao13** [comment]
_Same issue here with Emacs v29_ 

我的配置环境：
  - OS：fedora 40
  - emacs版本：fedora 官方源中的 29.4
  
使用您的 emacs.d 最新版本，刚升级了 fedora ，想按照您提供的方案全功能配置使用，结果编译完 myelpa 下的包后也报了同样的错误，然后参考了下面两个 issue，都是个 emacs 29 startup 相关的， 解释是 Emacs 29 master declares global-linum-mode obsoleted.
  https://github.com/emacsorphanage/git-gutter/issues/221
  https://github.com/emacsorphanage/git-gutter/pull/222
采用的方法是用最新的 git-gutter.el 替换 ./sit-lisp/git-gutter/git-gutter.el ，可以正常启动了。
呼吁大佬更新一下！谢谢

> [eb3824a](https://github.com/redguardtoo/emacs.d/commit/eb3824a59646df52c5df392203f8d32a6550ff5f) drop support for linum-mode which is not useful since emacs27 (Chen Bin)
> 
> linum 应该emacs27就没什么用了.

**Comment by redguardtoo** [comment]
Thanks, f0817307 upgrade git-gutter (Chen Bin)
