### ISSUE TITLE
Question about replace default ctags path.

### ISSUE THREAD

**Issue by eslrahc-swa** [redguardtoo/emacs.d#1041]
Hey there, I recently run into an issue where:

```
Failed to create tags file. Error=exited abnormally with code 1
 CLI=/usr/bin/ctags  .....
```

I use M1 chip macbook pro and it has default ctags under `/usr/bin/ctags` whereas I want to adopt `/opt/homebrew/bin/ctags` instead

just want to know if there are some workaround to specify executable myself.

**Comment by redguardtoo** [comment]
`(setq counsel-etags-ctags-program "/whatever-path/ctags")`

**Comment by eslrahc-swa** [comment]
Thanks for the help, I installed ctags using [https://github.com/universal-ctags/homebrew-universal-ctags](homebrew-universal-ctags) and set `(setq counsel-etags-ctags-program "/opt/homebrew/bin/ctags")` but when I ctags, it shows something like
```
 No tag is found. Grep "xxxxx" at xxxxxxx (7.6 seconds): 
```

How that might happen? Am I missing someting?
