### ISSUE TITLE
void-variable read-symbol-positions-list

### ISSUE THREAD

**Issue by iFHiGM** [redguardtoo/emacs.d#1044]
> 我的配置环境：
> 系统：windows11
> emacs版本：GNU Emacs 30.0.50 (build 2, x86_64-w64-mingw32) of 2023-03-02

大佬你好，

今天在使用`C-h f`查询一个函数（`my-comma-leader-def`）时，出现了如下报错：

> elisp-refs--read-all-buffer-forms: Unexpected error whilst reading ~/.emacs.d/lisp/init-evil.el position 129: (void-variable read-symbol-positions-list)

在网上查了下，原因似乎是Emacs 29中把`read-symbol-position-list`给删了：

- https://emacs-china.org/t/emacs-lisp-plantuml/22367/8
- https://github.com/Wilfred/helpful/issues/282
- https://github.com/doomemacs/doomemacs/issues/6127

我尝试了第二个链接里的两个方案：

1.
```elisp
(defvar read-symbol-positions-list nil)
```
2.
```elisp
(defun helpful--autoloaded-p (sym buf)
  "Return non-nil if function SYM is autoloaded."
  (-when-let (file-name (buffer-file-name buf))
    (setq file-name (s-chop-suffix ".gz" file-name))
    (help-fns--autoloaded-p sym)))

(defun helpful--skip-advice (docstring)
  "Remove mentions of advice from DOCSTRING."
  (let* ((lines (s-lines docstring))
         (relevant-lines
          (--take-while
           (not (or (s-starts-with-p ":around advice:" it)
                    (s-starts-with-p "This function has :around advice:" it)))
           lines)))
    (s-trim (s-join "\n" relevant-lines))))
```

其中方案1无效（与[第二个链接里](https://github.com/Wilfred/helpful/issues/282#issuecomment-1040126127)提到的报错一致），方案2能解决我的问题。

目前不清楚是否还有其他的问题。

**Comment by redguardtoo** [comment]
ca28835f use helpful unstable version (Chen Bin)

**Comment by iFHiGM** [comment]
感谢！
