### ISSUE TITLE
Duplicate key binding

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#1045]
In
https://github.com/redguardtoo/emacs.d/blob/fed98a5cbd0eb632239e7aaa8fae30beeaa8c864/lisp/init-hydra.el#L7-L29

`Typewriter on/off` and `Emms replay` bind the same key `E`
https://github.com/redguardtoo/emacs.d/blob/fed98a5cbd0eb632239e7aaa8fae30beeaa8c864/lisp/init-hydra.el#L62
https://github.com/redguardtoo/emacs.d/blob/fed98a5cbd0eb632239e7aaa8fae30beeaa8c864/lisp/init-hydra.el#L47

**Comment by redguardtoo** [comment]
4807cec7 hydra setup (Chen Bin)

**Comment by BlacAmDK** [comment]
> 4807cec7 hydra setup (Chen Bin)

好像忘了push
