### ISSUE TITLE
org-mode: evil-auto-indent should be set as local variable

### ISSUE THREAD

**Issue by karta0807913** [redguardtoo/emacs.d#1046]
https://github.com/redguardtoo/emacs.d/blob/4807cec78f90d705f7a9569519bc0167aac32825/lisp/init-org.el#L69

In this file, `evil-auto-indent` is set to `nil` every time when we turn on the `org-mode`. It will cause the indent not to work in another buffer. Therefore, I think we should use `set-local` function here :D

**Comment by redguardtoo** [comment]
make sense.

ea61d2e8 org-mode: evil-auto-indent should be set as local variable #1046 (Chen Bin)

**Comment by karta0807913** [comment]
great
