### ISSUE TITLE
中文引号导致光标位置不准确

### ISSUE THREAD

**Issue by mortimerzhu** [redguardtoo/emacs.d#1047]
使用终端的方式打开emacs，在一行中如果包含了中文引号（半角字符），会导致光标移动出现错位，引号实际上占了2个字符，终端显示时只以一个字符显示，所以在引号位置右移光标，会导致显示上光标已经在下一个字符后面了，但实际上没有。

在远程装等宽中文字体，emacs里无法生效，在本地终端使用等宽字体，也没有解决问题。

相比的话，vim就不存在这个问题，vim下似乎认为中文引号就是一个字符，显示时是一个字符，在引号位置移动时也是一个字符。

emacs的这种处理行为有点奇怪，其他的半角符号都没问题，只有中文引号有问题，有没有解决方法呀？

**Comment by redguardtoo** [comment]
这个没研究过,我一般都用英文. 换个terminal试试.

**Comment by mortimerzhu** [comment]
解决了，专门给亚洲字体设置成中文，还有一个ambiguous字符设置为宽字符就可以了
