### ISSUE TITLE
define-key碰到Wrong type argument: Commandp问题

### ISSUE THREAD

**Issue by citemp** [redguardtoo/emacs.d#1051]
1、初始状态 ace-pinyin-jump-char-in-line 可以正常使用
2、在 .custom.el 添加 (define-key evil-motion-state-map "f" 'ace-pinyin-jump-char-in-line)
3、重启emacs后，按 f 键，提示 Wrong type argument: Commandp ace-pinyin-jump-char-in-line
4、这时在 M-x 列表中已经找不到 ace-pinyin-jump-char-in-line
5、无意中发现，如果运行一下 ace-pinyin-jump-char 命令，f 键就能正常调用 ace-pinyin-jump-char-in-line，M-x 列表中也能再次找到 ace-pinyin-jump-char-in-line。
6、再次重启emacs后，f 键又失效了，还是得先手动调用一下ace-pinyin-jump-char命令后 f 键才正常。

emacs 28.1
ace-pinyin-20210827.355
evil-find-char-pinyin-20160514.2041

**Comment by citemp** [comment]
另外，ace-pinyin-jump-char命令，应该要支持中文拼音才对，但实际用的时候只能匹配到英文。

**Comment by redguardtoo** [comment]
> 另外，ace-pinyin-jump-char命令，应该要支持中文拼音才对，但实际用的时候只能匹配到英文。

You need install pinyinlib

**Comment by redguardtoo** [comment]
> emacs 28.1 ace-pinyin-20210827.355 evil-find-char-pinyin-20160514.2041
it's because `ace-pinyin-jump-char-in-line` is not marked `autoload`, it's package author's setup.

You could add `(require 'ace-pinyin)` in your setup.
