### ISSUE TITLE
flymake频繁报错

### ISSUE THREAD

**Issue by heheda123123** [redguardtoo/emacs.d#1053]
用的大佬的默认配置，emacs是windows上最新git源码编译的版本
如图，编辑eslip文件就频繁报错，导致卡顿
![image](https://github.com/redguardtoo/emacs.d/assets/97490782/8dc915bc-8817-4199-b9b0-e4e05c89cf05)

**Comment by redguardtoo** [comment]
You can disable flymake in `init-misc.el`, or you can try set environment variable `HOME` in windows.

**Comment by heheda123123** [comment]
已经设置过HOME环境变量了，貌似是flymake的那个byte-compile的后端有问题，我用`-Q`的环境也会报这个错

**Comment by redguardtoo** [comment]
见我的配置里lazymake插件,elisp语法检查后端是我自己写的.没有这个问题. 这个后端和flymake的后端是通用的.

**Comment by oxsard** [comment]
my-disable-lazyflymake 应该设置为什么才能关闭报错？我设置为t或者nil都会还有报错。。。

**Comment by redguardtoo** [comment]
`my-disable-lazyflymake`关掉lazymake,启用系统默认的flymake-mode.见`my-generic-prog-mode-hook-setup`.
我建议还是研究一下flymake,很简单的.
