### ISSUE TITLE
my-dict-simple-definition执行后显示“File not found”.

### ISSUE THREAD

**Issue by oxsard** [redguardtoo/emacs.d#1054]
`ls stardict-ecdict-2.4.2 -lh`
>-rw-r--r-- 1 oxsard oxsard 113M  8月 4日 20:42 stardict-ecdict-2.4.2.dict
>-rw-r--r-- 1 oxsard oxsard  79M  8月 4日 20:42 stardict-ecdict-2.4.2.idx
>-rw-r--r-- 1 oxsard oxsard 416K  8月 4日 20:42 stardict-ecdict-2.4.2.idx.oft
>-rw-r--r-- 1 oxsard oxsard  171  8月 4日 20:42 stardict-ecdict-2.4.2.ifo

`tree ~/.stardict/dic`
>/home/oxsard/.stardict/dic
>└── stardict-ecdict-2.4.2
>    （缩进）├── stardict-ecdict-2.4.2.dict
>    （缩进）├── stardict-ecdict-2.4.2.idx
>    （缩进）├── stardict-ecdict-2.4.2.idx.oft
>    （缩进）└── stardict-ecdict-2.4.2.ifo
>
>2 directories, 4 files

`(setq my-dict-simple
      '("~/.stardict/dic/stardict-ecdict-2.4.2" "ecdict"))
`

执行my-dict-simple-definition后输入单词，回车后minibuffer显示“File not found”

**Comment by oxsard** [comment]
使用斌哥提供的词典可以正常使用，可能是我自定义词库的问题。

**Comment by redguardtoo** [comment]
![image](https://github.com/redguardtoo/emacs.d/assets/184553/b84b0f20-2730-4720-a18f-6bf870f9bc2e)

**Comment by oxsard** [comment]
没有。是第二个参数name要写全（不包括扩展名）
正确写法应为

> (setq my-dict-simple '("~/.stardict/dic/stardict-ecdict-2.4.2" "stardict-ecdict-2.4.2"))
