### ISSUE TITLE
my-imenu don't show result correctly for .org file

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#1059]
Emacs info:
GNU Emacs 29.1 (build 2, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66)) of 2023-09-27

Org version:
Org mode version 9.6.6 (release_9.6.6 @ /opt/homebrew/Cellar/emacs-plus@29/29.1/share/emacs/29.1/lisp/org/)

When I run ,ii, nothing to show and there is not error message occur. but when I run imenu command, got errors:
`
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match(#("\\`Any\\'" 2 5 (isearch-open-invisible org-fold-core--isearch-show isearch-open-invisible-temporary org-fold-core--isearch-show-temporary font-lock-fontified t fontified t src-block t line-prefix #("  " 0 2 (face org-indent)) wrap-prefix #("  " 0 2 (face org-indent)) font-lock-multiline t face (font-lock-comment-face org-block))) nil)
  imenu-find-default(#("Any" 0 3 (face (font-lock-comment-face org-block) font-lock-multiline t wrap-prefix #("  " 0 2 (face org-indent)) line-prefix #("  " 0 2 (face org-indent)) src-block t fontified t font-lock-fontified t isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show)) (("*Rescan*" . -99) (nil)))
  imenu--completion-buffer((("*Rescan*" . -99) nil) nil)
  imenu-choose-buffer-index()
  byte-code("\300 C\207" [imenu-choose-buffer-index] 1)
  command-execute(imenu record)
  counsel-M-x-action("imenu")
  ivy-call()
  #<subr ivy-read>("M-x " ("my-imenu-or-list-tag-in-current-file" "my-imenu-comments" "my-counsel-imenu" "my-counsel-git-find-file" "toggle-debug-on-error" "counsel-etags-find-tag" "menu-set-font" "org-babel-tangle" "restart-emacs" "org-clock-goto" "easy-hugo" "org-add-note" "org-roam-db-sync" "deadgrep" "yank" "query-replace" "org-hugo-export-to-md" "erase-buffer" "tomyli/new-daily-review" "replace-string" "imenu" "scratch" "org-indent-mode" "org-set-property" "maple-preview-mode" "split-line" "indent-region" "org-clock-out" "markdown-preview" "text-scale-adjust" "org-table-delete-column" "global-text-scale-adjust" "orgtbl-create-or-convert-from-region" "erc" "find-tag" "join-line" "counsel-rg" "flush-lines" "recentf-open" "set-frame-font" "package-upgrade" "org-table-create" "tomyli/dailyplan" "evil-split-buffer" "json-pretty-print" "org-todo-yesterday" "table-delete-column" "org-transclusion-mode" "json-pretty-print-buffer" "markdown-export-and-preview" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (11 . kill-line) (27 keymap (121 . paste-from-x-clipboard)) (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  ivy-posframe--read(#<subr ivy-read> "M-x " ("my-imenu-or-list-tag-in-current-file" "my-imenu-comments" "my-counsel-imenu" "my-counsel-git-find-file" "toggle-debug-on-error" "counsel-etags-find-tag" "menu-set-font" "org-babel-tangle" "restart-emacs" "org-clock-goto" "easy-hugo" "org-add-note" "org-roam-db-sync" "deadgrep" "yank" "query-replace" "org-hugo-export-to-md" "erase-buffer" "tomyli/new-daily-review" "replace-string" "imenu" "scratch" "org-indent-mode" "org-set-property" "maple-preview-mode" "split-line" "indent-region" "org-clock-out" "markdown-preview" "text-scale-adjust" "org-table-delete-column" "global-text-scale-adjust" "orgtbl-create-or-convert-from-region" "erc" "find-tag" "join-line" "counsel-rg" "flush-lines" "recentf-open" "set-frame-font" "package-upgrade" "org-table-create" "tomyli/dailyplan" "evil-split-buffer" "json-pretty-print" "org-todo-yesterday" "table-delete-column" "org-transclusion-mode" "json-pretty-print-buffer" "markdown-export-and-preview" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (11 . kill-line) (27 keymap (121 . paste-from-x-clipboard)) (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  apply(ivy-posframe--read #<subr ivy-read> ("M-x " ("my-imenu-or-list-tag-in-current-file" "my-imenu-comments" "my-counsel-imenu" "my-counsel-git-find-file" "toggle-debug-on-error" "counsel-etags-find-tag" "menu-set-font" "org-babel-tangle" "restart-emacs" "org-clock-goto" "easy-hugo" "org-add-note" "org-roam-db-sync" "deadgrep" "yank" "query-replace" "org-hugo-export-to-md" "erase-buffer" "tomyli/new-daily-review" "replace-string" "imenu" "scratch" "org-indent-mode" "org-set-property" "maple-preview-mode" "split-line" "indent-region" "org-clock-out" "markdown-preview" "text-scale-adjust" "org-table-delete-column" "global-text-scale-adjust" "orgtbl-create-or-convert-from-region" "erc" "find-tag" "join-line" "counsel-rg" "flush-lines" "recentf-open" "set-frame-font" "package-upgrade" "org-table-create" "tomyli/dailyplan" "evil-split-buffer" "json-pretty-print" "org-todo-yesterday" "table-delete-column" "org-transclusion-mode" "json-pretty-print-buffer" "markdown-export-and-preview" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (11 . kill-line) (27 keymap (121 . paste-from-x-clipboard)) (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x))
  ivy-read("M-x " ("my-imenu-or-list-tag-in-current-file" "my-imenu-comments" "my-counsel-imenu" "my-counsel-git-find-file" "toggle-debug-on-error" "counsel-etags-find-tag" "menu-set-font" "org-babel-tangle" "restart-emacs" "org-clock-goto" "easy-hugo" "org-add-note" "org-roam-db-sync" "deadgrep" "yank" "query-replace" "org-hugo-export-to-md" "erase-buffer" "tomyli/new-daily-review" "replace-string" "imenu" "scratch" "org-indent-mode" "org-set-property" "maple-preview-mode" "split-line" "indent-region" "org-clock-out" "markdown-preview" "text-scale-adjust" "org-table-delete-column" "global-text-scale-adjust" "orgtbl-create-or-convert-from-region" "erc" "find-tag" "join-line" "counsel-rg" "flush-lines" "recentf-open" "set-frame-font" "package-upgrade" "org-table-create" "tomyli/dailyplan" "evil-split-buffer" "json-pretty-print" "org-todo-yesterday" "table-delete-column" "org-transclusion-mode" "json-pretty-print-buffer" "markdown-export-and-preview" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (11 . kill-line) (27 keymap (121 . paste-from-x-clipboard)) (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)
`

What should I do?

**Comment by redguardtoo** [comment]
can't reproduce issue. Could you provide some sample org file?

**Comment by peng051410** [comment]
> can't reproduce issue. Could you provide some sample org file?↳

Just simple org file like this:
`* Test

** Hello

** World`


![testorg](https://github.com/redguardtoo/emacs.d/assets/5512326/917be10e-eaff-401a-8669-88bb6cd9f5d6)

**Comment by redguardtoo** [comment]
![image](https://github.com/redguardtoo/emacs.d/assets/184553/1e434d69-c1ab-40c1-b5a5-c6452827e890)
imenu is ok at my computer.

Maybe its some extra org package you use?

**Comment by peng051410** [comment]
Test ok without my personal config, I will check my own config! Thanks a lot!
