### ISSUE TITLE
有关于sourceinsight在emacs的问题

### ISSUE THREAD

**Issue by zhongqian97** [redguardtoo/emacs.d#1060]
陈哥，现在在emacs上，有没有能够替代sourceinsight软件的插件呢？

**Comment by redguardtoo** [comment]
如果是看c++代码的话没有, C我觉得emacs+ctags就够了.

**Comment by zhongqian97** [comment]
ctags有办法做到查某一个结构体当中的变量显示当前工程的使用位置嘛？
