### ISSUE TITLE
Can't not install with Emacs 29.1 on Windows 11

### ISSUE THREAD

**Issue by ihaaae** [redguardtoo/emacs.d#1061]
I tried all three melpa site and all get the same error.
**Following is the error message:**
Debugger entered--Lisp error: (error "Need package ‘compat-29.1.4.4’, but only 29.1.4.1 ...")
  error("Need package `%s-%s', but only %s is available" compat "29.1.4.4" "29.1.4.1")
  package-compute-transaction((#s(package-desc :name transient :version (0 5 3) :summary "Transient commands" :reqs ((emacs (26 1)) (compat (29 1 4 4)) (seq (2 24))) :kind tar :archive "melpa-stable" :dir nil :extras ((:commit . "72cf67d7e047a4f82e0e18bd016c7826bf2efde0") (:authors ("Jonas Bernoulli" . "jonas@bernoul.li")) (:maintainers ("Jonas Bernoulli" . "jonas@bernoul.li")) (:maintainer "Jonas Bernoulli" . "jonas@bernoul.li") (:keywords "extensions") (:url . "https://github.com/magit/transient")) :signed nil) #s(package-desc :name git-timemachine :version (20230630 1214) :summary "Walk through git revisions of a file" :reqs ((emacs (24 3)) (transient (0 1 0))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "ac933e5cd29583c131401f3bd991d98129c316df") (:authors ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainers ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainer "Peter Stiernström" . "peter@stiernstrom.se") (:keywords "vc") (:url . "https://gitlab.com/pidu/git-timemachine")) :signed nil)) ((emacs (26 1)) (compat (29 1 4 4)) (seq (2 24))) (#s(package-desc :name transient :version (0 5 3) :summary "Transient commands" :reqs ((emacs (26 1)) (compat (29 1 4 4)) (seq (2 24))) :kind tar :archive "melpa-stable" :dir nil :extras ((:commit . "72cf67d7e047a4f82e0e18bd016c7826bf2efde0") (:authors ("Jonas Bernoulli" . "jonas@bernoul.li")) (:maintainers ("Jonas Bernoulli" . "jonas@bernoul.li")) (:maintainer "Jonas Bernoulli" . "jonas@bernoul.li") (:keywords "extensions") (:url . "https://github.com/magit/transient")) :signed nil) #s(package-desc :name git-timemachine :version (20230630 1214) :summary "Walk through git revisions of a file" :reqs ((emacs (24 3)) (transient (0 1 0))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "ac933e5cd29583c131401f3bd991d98129c316df") (:authors ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainers ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainer "Peter Stiernström" . "peter@stiernstrom.se") (:keywords "vc") (:url . "https://gitlab.com/pidu/git-timemachine")) :signed nil)))
  package-compute-transaction((#s(package-desc :name git-timemachine :version (20230630 1214) :summary "Walk through git revisions of a file" :reqs ((emacs (24 3)) (transient (0 1 0))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "ac933e5cd29583c131401f3bd991d98129c316df") (:authors ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainers ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainer "Peter Stiernström" . "peter@stiernstrom.se") (:keywords "vc") (:url . "https://gitlab.com/pidu/git-timemachine")) :signed nil)) ((emacs (24 3)) (transient (0 1 0))) (#s(package-desc :name git-timemachine :version (20230630 1214) :summary "Walk through git revisions of a file" :reqs ((emacs (24 3)) (transient (0 1 0))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "ac933e5cd29583c131401f3bd991d98129c316df") (:authors ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainers ("Peter Stiernström" . "peter@stiernstrom.se")) (:maintainer "Peter Stiernström" . "peter@stiernstrom.se") (:keywords "vc") (:url . "https://gitlab.com/pidu/git-timemachine")) :signed nil)))
  package-compute-transaction(nil ((git-timemachine)))
  package-install(git-timemachine)
  (if (package-installed-p package min-version) nil (if (or (assoc package package-archive-contents) no-refresh) nil (message "Missing package: %s" package) (package-refresh-contents)) (package-install package))
  require-package(git-timemachine)
  load-with-code-conversion("c:/Users/24973/AppData/Roaming/.emacs.d/lisp/init-..." "c:/Users/24973/AppData/Roaming/.emacs.d/lisp/init-..." t t)
  load("c:/Users/24973/AppData/Roaming/.emacs.d/lisp/init-..." t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not my-lightweight-mode-p)) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (if (or my-lightweight-mode-p my-disable-idle-timer) (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (require-init 'init-spelling t) (require-init 'init-ibuffer t) (require-init 'init-bookmark) (require-init 'init-ivy) (require-init 'init-windows) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-term-mode) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-dictionary t) (require-init 'init-emms t) (require-init 'init-browser t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-pdf) (if my-lightweight-mode-p (progn (require-init 'init-ediff))) (if my-disable-idle-timer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init 'init-no-byte-compile t) (if my-lightweight-mode-p nil (setq custom-file (concat my-emacs-d "custom-set-variables.el")) (if (file-exists-p custom-file) (load custom-file t t)) (my-run-with-idle-timer 1 #'(lambda nil (load "~/.custom.el" t nil)))))
  load-with-code-conversion("c:/Users/24973/AppData/Roaming/.emacs.d/init.el" "c:/Users/24973/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/24973/AppData/Roaming/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1c29b5302a7106de>) #f(compiled-function () #<bytecode -0x1f3c61addc0c4f35>) t)
  command-line()
  normal-top-level()

**Comment by ihaaae** [comment]
solved by manually download **compat** package. The **seq** package is also out of date

**Comment by redguardtoo** [comment]
just wait for a few days before its author publishing latest version
