### ISSUE TITLE
Support open recent file in other frame?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#1063]
The current `my-counsel-recentf` is already very handy and I'm using it many times daily. However when I try to extend it to support open recent file in other frame (I want to separate tasks into different frames, such as one for org and another frame for code), I'm stucked due to this command does not return file or buffer opened.

My request is:
1. Can you extend it more to support open rencent file in other frame?
2. If not, can you enhance it a little to return buffer opened?

Thanks

**Comment by redguardtoo** [comment]
3971bfba `my-counsel-recentf` can return a file buffer (Chen Bin)

**Comment by phye** [comment]
Thanks
