### ISSUE TITLE
回车后第二行会有自动缩进，但是这个缩进会在一两秒钟以后自动移动到改行行首，需要自己修正缩进的问题。

### ISSUE THREAD

**Issue by oxsard** [redguardtoo/emacs.d#1065]
环境为archlinux，emacs29.3
配置文件为重新git clone后，重新运行。

编辑python文件和shell文件都有如此现象，不知道这个是特性吗，翻了一下说明好像都没找到相关的信息。

**Comment by redguardtoo** [comment]
It seems 3rd party package `auto-save.el` problem. Since  builtin `auto-save-visited-mode' could do the same thing. I use the builtin mode instead.

df3fe2a8 use builtin `auto-save-visited-mode' instead 3rd party packages (Chen Bin)

**Comment by oxsard** [comment]
Thank you very much. The problem has been completely solved. Your configuration is once again the smoothest .emacs.d
