### ISSUE TITLE
the cursor is always  bar, 

### ISSUE THREAD

**Issue by xiandu568** [redguardtoo/emacs.d#1074]
I use Emacs on the Windows system, but I found that the cursor does not change with the evil mode.  
I try to use these code to set 
``` lisp
 (setq evil-normal-state-cursor '(box "green"))
 (setq evil-insert-state-cursor '(bar "green"))
  (setq evil-visual-state-cursor '(box "green"))
  ```
But they don't seem to work.

**Comment by redguardtoo** [comment]
I tested in macOS GUI emacs. Looks it's fine. Terminal is a differnt story,
See https://www.gnu.org/software/emacs/manual/html_node/emacs/Cursor-Display.html

**Comment by xiandu568** [comment]
Okay, thank you so much for your help. I have found the solution from the evil-terminal-cursor-changer project.
