### ISSUE TITLE
regression test of my emacs.d

### ISSUE THREAD

**Issue by redguardtoo** [redguardtoo/emacs.d#169]
Next test will be on April 13, 2015. I MAY need new guys in the future.

I need 3-4 volunteers to test my emacs.d every two months.

you need some basic knowledge of Linux, like how to install software, how to run the command line in shell

please leave your email if you are interested.

The https://github.com/redguardtoo/emacs.d/blob/master/BETA.org  is the test document.

**Comment by liangyaozhan** [comment]
ivws02@126.com 梁生

**Comment by liangyaozhan** [comment]
为何我在windows下用这个配置这么慢？

**Comment by redguardtoo** [comment]
cygwin or native windows?

**Comment by liangyaozhan** [comment]
cygwin, 可能跟公司的某些软件有冲突。

**Comment by redguardtoo** [comment]
try to disable flymake-mode

**Comment by redguardtoo** [comment]
855140a use improved flymake (Chen Bin)

**Comment by liangyaozhan** [comment]
improved flymake 有错误的行被标记为红色后，无法区分被选中的内容。

**Comment by redguardtoo** [comment]
更多细节？

**Comment by xtaens** [comment]
大牛好，你的这个配置文件怎么使用呢？

怎么没有.emacs文件呢？

我在xp下使用

**Comment by redguardtoo** [comment]
看过我的<一年成为emacs高手>一文吗?设置一下HOME环境变量.

**Comment by mustkass** [comment]
你好, 请问, 我下载你的配置放在.emacs.d 的这个文件里, 然后在.emacs里加入了(load "~/.emacs.d/init.el"), 重启emacs不生效, 请问怎么解决?

**Comment by redguardtoo** [comment]
remove .emacs

**Comment by d0f** [comment]
0.0
