### ISSUE TITLE
debian 中M-x无法使用

### ISSUE THREAD

**Issue by mashomee** [redguardtoo/emacs.d#221]
看到你的"一年"的文章后,就下载了你的配置使用了,但是现在突然出现了个问题
在emacs启动后显示M-x undefined.起初以为无意间动了什么东西,又重新了下载了那两个zip文件,
解压后安装都正常,就只有这个问题.
1. 在gnome-terminal中使用emacs -nw 启动, 快捷键M-x正常, 其他也都正常
2. 在窗口中启动就不正常, 有undefined的提示信息,但是这时候按C-h k 然后输入M-x,会有显示
    M-x runs the command smex, which is an interactive autoloaded Lisp function in `smex.el'.
    It is bound to , x m, M-x.
    [Arg list not available until function definition is loaded.]
     Not documented
3. 使用emacs -q M-x也正常的
4. 这是版本信息GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.3)

另外, 用了你的配置一段时间了,都习惯了evil中M-k  和 kj 退出insert模式, 用fd 和df反而妨碍了输入,
问下,evil-escape不用的话,对其他的功能有什么影响吗
谢谢啦

**Comment by redguardtoo** [comment]
my critical bug is fixed.
