### ISSUE TITLE
eim 将 "-""=" 修改为 "," "." 出现问题

### ISSUE THREAD

**Issue by mozeroman** [redguardtoo/emacs.d#227]
我在.custom.el修改了eim的换页来符合我输入法的习惯.
(defun my-eim-py-activate-function ()
  (add-hook 'eim-active-hook
            (lambda ()
              (let ((map (eim-mode-map)))
                (define-key eim-mode-map "," 'eim-previous-page)
                (define-key eim-mode-map "." 'eim-next-page)))))

当使用eim尝试输入中文词语/句子,输入到最后一个字时,如果使用",""."切换page,则出现错误无法正常输入.
可能是只输出最后一个字,或者无法输出(在底部显示"* 0 2").
怀疑是不是按键冲突,望解答,谢谢

**Comment by redguardtoo** [comment]
无法重现,我觉得你的快捷键设置的idea不错,现在我也改成你的快捷键翻页了,没有遇到任何问题.

**Comment by mozeroman** [comment]
我刚刚试了下，这个版本没问题了，有可能是过去版本的.emacs.d的快捷键冲突问题。
关于eim的py.txt，在网上找了个搜狗拼音转成了utf-8的词库（http://code.google.com/p/hslinuxextra/downloads/list下的fcitx-sougou-phrase-full.7z）貌似转成py.txt问题不大，不知道有没有版权问题。
还有弱弱地问一句：在insert模式下(非org-mode)如何使光标跳转到行尾？

**Comment by redguardtoo** [comment]
C-e
