### ISSUE TITLE
htmlize.el无法工作（emacs版本为24.4）

### ISSUE THREAD

**Issue by passchaos** [redguardtoo/emacs.d#232]
从melpa安装的htmlize，在输出html时总是提醒：let: Wrong type argument: stringp, nil，使用org-mode的contrib中的htmlize.el也是同样的问题。

**Comment by redguardtoo** [comment]
check `is-buffer-file-temp` in init-utils.el.

I discussed this issue and gave the solution in my post http://blog.binchen.org/posts/export-org-file-embedded-with-code-snippets.html
