### ISSUE TITLE
No browser defined('browse-url-generic-program)

### ISSUE THREAD

**Issue by programes** [redguardtoo/emacs.d#235]
emacs 24.4   windows下cygwin，怎么解决？
是在init.el下添加
(setq gnus-button-url 'browse-url-generic
          browse-url-generic-program "firefox"
          browse-url-browser-function gnus-button-url)
么？

**Comment by redguardtoo** [comment]
under cygwin, use w3m instead. `(if *cygwin* (setq browse-url-generic-program "w3m"))`,

**Comment by programes** [comment]
我用的是emacs-w32.exe 而不是emacs-nw还可以用firefox么

**Comment by programes** [comment]
在init.el添加了(if *cygwin* (setq browse-url-generic-program "w3m"))后
试了一下，第一次可以打开浏览器，也可以打开浏览的页面，但是切换浏览目标之后就打不开了，
就会反馈No browser defined('browse-url-generic-program‘)

**Comment by redguardtoo** [comment]
无所谓的,直接指定firefox全路径也可以.

On Sat, Jan 3, 2015 at 2:48 PM, programes <notifications@github.com> wrote:

> 我用的是emacs-w32.exe 而不是emacs-nw还可以用firefox么
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/235#issuecomment-68582036>.
>



-- 
help me, help you.

**Comment by programes** [comment]
按照你的代码只有第一次打开连接可以打开网页，第二次开始就再也打不开了，只能重启emacs

**Comment by redguardtoo** [comment]
Steps to reproduce bug?

**Comment by redguardtoo** [comment]
I noticed you use gnus-button-url, As I stated in README, I installed w3m and it's already integrated into gnus seamlessly, The hotkey is `C-u Enter` or `C-u M-x w3m-safe-view-this-url`
