### ISSUE TITLE
evil-quit will close the whole client

### ISSUE THREAD

**Issue by jesse23** [redguardtoo/emacs.d#236]
https://bitbucket.org/lyro/evil/issue/430/evil-quit-should-not-always-kill-a-client

There is 2 option to fix it, I chose the opt1 in my fork...

**Comment by redguardtoo** [comment]
interesting. I will merge the fix into my setup.

**Comment by redguardtoo** [comment]
since I already upgraded to evil 1.2.3, this issue should be resolved.
