### ISSUE TITLE
emacs stop working after i open a xxx.py file

### ISSUE THREAD

**Issue by freealong** [redguardtoo/emacs.d#238]
emacs stop working after i open a xxx.py file ：

![image](https://cloud.githubusercontent.com/assets/8717689/5647622/9ebd1c5c-96c2-11e4-85bf-7af1a6fb9197.png)

**Comment by redguardtoo** [comment]
python version, emacs version. os ?

please install pyflakes, if issue resolved?

anaconda version? I'm using 20140703.1247

**Comment by freealong** [comment]
it works fine after i installed pyflakes. Thanks~~~

**Comment by redguardtoo** [comment]
thanks for the feedback, I added some patch to detect pyflake before use it.
