### ISSUE TITLE
cygwin config code will cause ftp auto-complete failure

### ISSUE THREAD

**Issue by jesse23** [redguardtoo/emacs.d#239]
Enable code below:
;; win32 auto configuration, assuming that cygwin is installed at "c:/cygwin"
;;(condition-case nil
;;    (when *win32*
;;      (setq cygwin-mount-cygwin-bin-directory "c:/cygwin64/bin")
;;      (require 'setup-cygwin)
;;      ;; better to set HOME env in GUI
;;      ;; (setenv "HOME" "c:/cygwin/home/someuser")
;;      )
;;  (error
;;   (message "setup-cygwin failed, continue anyway")
;;   ))

Then use /ftp:user@server:/ to access server, the auto complete function will fails by:
CD "/cygwin64/cygwin64/cygwin64/" no such file or directly.

It works correctly after comments that block.

**Comment by redguardtoo** [comment]
interesting. I'll look into this.

**Comment by redguardtoo** [comment]
Looks it's because the package is not upgraded to support 64 bit windows. I upgraded and DISABLED it by default.

17c972f upgrade cygwin-setup.el and NOT load it by default (Chen Bin)
