### ISSUE TITLE
org-mode output Chinese pdf problem

### ISSUE THREAD

**Issue by reboothit** [redguardtoo/emacs.d#24]
why I can not output it to pdf correct?  I can output English pdf correct.

```
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{SimSun}

* 近期工作
** 学业<2013-05-21 Tue>
你好，你好你好你好

** 论文 <2013-06-17 Mon>
*** 论文
** job-hunting
```

**Comment by redguardtoo** [comment]
so the conclusion is using xelatex

**Comment by robin2003** [comment]
i have use the following tex file:
\documentclass{article}
\usepackage{CJK}
\begin{document}
\begin{CJK}{UTF8}{gkai}
\title{APM源码笔记{}}
\author{菜刀}
测试abc
\end{CJK}
\end{document}


i use the follow command to generate pdf file:
robin@ubuntu:~/Program/org-mode/meeting/20170223$ xelatex test2.tex 

the following is log
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./test2.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 10 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf/tex/latex/CJK/CJK.sty
(/usr/share/texmf/tex/latex/CJK/mule/MULEenc.sty)
(/usr/share/texmf/tex/latex/CJK/CJK.enc)) (./test2.aux)
(/usr/share/texmf/tex/latex/CJK/UTF8/UTF8.bdg)
(/usr/share/texmf/tex/latex/CJK/UTF8/UTF8.enc)
(/usr/share/texmf/tex/latex/CJK/UTF8/UTF8.chr) [1] (./test2.aux) )
(see the transcript file for additional information)
Output written on test2.pdf (1 page).
Transcript written on test2.log.

but still do not have chinese charactor in pdf file.

i'm sure that i have install latex-cjk:
robin@ubuntu:~$ dpkg -l | grep latex
ii  cjk-latex                                             4.8.3+git20120914-2ubuntu1                          all          installs all LaTeX CJK packages
ii  latex-beamer                                          3.24-1                                              all          LaTeX class to produce presentations
ii  latex-cjk-all                                         4.8.3+git20120914-2ubuntu1                          all          installs all LaTeX CJK packages
ii  latex-cjk-chinese                                     4.8.3+git20120914-2ubuntu1                          amd64        Chinese module of LaTeX CJK
ii  latex-cjk-chinese-arphic-bkai00mp                     1.23                                                all          AR PL KaitiM Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-bsmi00lp                     1.23                                                all          AR PL Mingti2L Big5 fonts for CJK
ii  latex-cjk-chinese-arphic-gbsn00lp                     1.23                                                all          AR PL SungtiL GB fonts for CJK
ii  latex-cjk-chinese-arphic-gkai00mp                     1.23                                                all          AR PL KaitiM GB fonts for CJK
ii  latex-cjk-common                                      4.8.3+git20120914-2ubuntu1                          amd64        LaTeX macro package for CJK (Chinese/Japanese/Korean)
ii  latex-cjk-japanese                                    4.8.3+git20120914-2ubuntu1                          amd64        Japanese module of LaTeX CJK
ii  latex-cjk-japanese-wadalab                            0.20050817-16                                       all          type1 and tfm DNP Japanese fonts for latex-cjk
ii  latex-cjk-korean                                      4.8.3+git20120914-2ubuntu1                          all          Korean module of LaTeX CJK
ii  latex-cjk-thai                                        4.8.3+git20120914-2ubuntu1                          all          Thai module of LaTeX CJK
ii  latex-xcolor                                          2.11-1.1                                            all          Easy driver-independent TeX class for color
ii  latexmk                                               1:4.35-0ubuntu1                                     all          Perl script for running LaTeX the correct number of times
ii  libpod-latex-perl                                     0.61-1                                              all          module to convert Pod data to formatted LaTeX
ii  preview-latex-style                                   11.87-1ubuntu2                                      all          extraction of elements from LaTeX documents as graphics
ii  texlive-latex-base                                    2013.20140215-1                                     all          TeX Live: LaTeX fundamental packages
ii  texlive-latex-base-doc                                2013.20140215-1                                     all          TeX Live: Documentation files for texlive-latex-base
ii  texlive-latex-extra                                   2013.20140215-2                                     all          TeX Live: LaTeX additional packages
ii  texlive-latex-extra-doc                               2013.20140215-2                                     all          TeX Live: Documentation files for texlive-latex-extra
ii  texlive-latex-recommended                             2013.20140215-1                                     all          TeX Live: LaTeX recommended packages
ii  texlive-latex-recommended-doc                         2013.20140215-1                                     all          TeX Live: Documentation files for texlive-latex-recommended
ii  texlive-latex3                                        2013.20140215-2                                     all          TeX Live: transitional dummy package


any one help me?

**Comment by redguardtoo** [comment]
Have you considered ask at https://emacs-china.org/t/spacemacs-xelatex-latex/293 ?

**Comment by robin2003** [comment]
dear redguardtoo,
thanks for your guide.
i will fire a question on that.

**Comment by russellfei** [comment]
@robin2003 
Maybe `\usepackage{CJK}` should be replaced by **`\usepackage{CJKutf8}`**, because you used `\begin{CJK}{UTF8}{gkai}` just as I did. Since your system is Ubuntu, you need to install fonts in TeXLive.
Furthermore, `XeLaTeX` is good support for Unicode characters, including Chinese, which is worth to have a try, but you might need to reference **local** fonts on your system.
