### ISSUE TITLE
Error enabling flyspell mode (stringp nil) on OS X Terminal

### ISSUE THREAD

**Issue by Adward-R** [redguardtoo/emacs.d#240]
I just used your STABLE version (two zip files) to reinstall my emacs configures on OS X, but everytime when I open a file with either Terminal or GUI ver of Emacs, it suggests the error info as I wrote in the issue's title; and when I tried "M-x flyspell-mode", the same message emerged; when I tried "M-x flymake-mode", the message said it enabled, but no real effect while coding simple C/C++ file ( with a Makefile in the same directory and can be build using "M-x fly-compile" or "M-x compile" ). What may cause this kind of problems, or there is something more I should alter in the config files?

**Comment by Adward-R** [comment]
sorry i've found the solution...

**Comment by redguardtoo** [comment]
it's some major-modes notifying that the cli tools are not installed. you can ignore them. or you can check my README where the OPTIONAL cli tools are listed.
