### ISSUE TITLE
Error opening "Edit" menu in OS X Terminal Version

### ISSUE THREAD

**Issue by Adward-R** [redguardtoo/emacs.d#241]
As F10 is caught, I just use "M-`" and choose "e" in the given list of menu items, but "OpenStep is not in use or not initialized " is warned at the bottom and the item did not open as others?

**Comment by redguardtoo** [comment]
need more information, check README.

**Comment by redguardtoo** [comment]
it's emacs's own problem, `emacs -Q` and you still have the issue.

looks like it's the submenu need call api x-selection-exists-p but that API is removed in nox version.
