### ISSUE TITLE
company-clang 补全时经常输出错误提示,并且出现的时候就很明显的卡一下

### ISSUE THREAD

**Issue by mashomee** [redguardtoo/emacs.d#242]
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
Global-Flycheck mode disabled
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: company-clang--handle-error: Args out of range: #<buffer *clang-output*>, 0, 1
error in process sentinel: Args out of range: #<buffer *clang-output*>, 0, 1
这个上面是错误提示,每次错误出现的时候都会很明显的卡一下, 麻烦帮看一下,或者提供个解决思路也可以

**Comment by redguardtoo** [comment]
Could you reproduce with a simple example? company-mode version? emacs version?

**Comment by mashomee** [comment]
company-mode:: # Version: 0.8.7
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)
 of 2014-12-09 on gaia, modified by Debian
修改了
````elisp
(setq company-clang-arguments '(...))
(setq company-idle-delay 0.2
        company-minimum-prefix-length 2
        company-clang-insert-arguments t)
(setq company-clang-arguments
      '("-I./"
        "-I/usr/include/x86_64-linux-gnu/qt5"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent"
        "-I/usr/include/x86_64-linux-gnu/qt5/QtCore"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtDBus"
        "-I/usr/include/x86_64-linux-gnu/qt5/QtGui"
        "-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtOpenGLExtensions"
;;;        "-I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtSql"
        "-I/usr/include/x86_64-linux-gnu/qt5/QtTest"
        "-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets"
        ;; "-I/usr/include/x86_64-linux-gnu/qt5/QtXml"
        ))
````
````c++
#include <QApplication>
#include <QDialog>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QDialog *login = new QDialog;
    login->resize(300, 250);
    // 定义组件指针
    QLabel *acct1;
    QLabel *passwd1;
    QLineEdit *acct2;
    QLineEdit *passwd2;
    QPushButton *blogin;
    QPushButton *bcanc;
    // 组件指针赋值
    acct1 = new QLabel("Account", login);
    passwd1 = new QLabel("Password", login);
    acct2 = new QLineEdit(login);
    passwd2 = new QLineEdit(login);
    blogin = new QPushButton("login", login);
    bcanc = new QPushButton("cancel", login);

    acct1->move(60, 40);
    acct2->move(150, 40);
    passwd1->move(60, 80);
    passwd2->move(150, 80);
    blogin->move(40, 175);
    bcanc->move(170, 175);
    QObject::connect(bcanc, SIGNAL(clicked()), login, SLOT(close()));
    login->show();
    return app.exec();
}
````

**Comment by redguardtoo** [comment]
M-x toggle-debug-on-error reproduce

**Comment by mashomee** [comment]
错误提示:`error in process sentinel: company-clang--handle-error: Args out of range: #, 0, 1`的debug信息
````elisp
Debugger entered--Lisp error: (args-out-of-range #<buffer *clang-output*> 0 1)
  buffer-substring-no-properties(1 0)
  company-clang--handle-error(1 ("-fsyntax-only" "-Xclang" "-code-completion-macros" "-x" "c++" "-I./" "-I/usr/include/x86_64-linux-gnu/qt5" "-I/usr/include/x86_64-linux-gnu/qt5/QtCore" "-I/usr/include/x86_64-linux-gnu/qt5/QtGui" "-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork" "-I/usr/include/x86_64-linux-gnu/qt5/QtTest" "-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets" "-Xclang" "-code-completion-at=-:29:5" "-"))
  #[514 "\306\307\310\311#)\266\203?\205,
````

我这次只能重现这个错误了

**Comment by mashomee** [comment]
刚把我的.emacs.d删掉又重新下了git clone了一遍, 还是有这个错误

**Comment by mashomee** [comment]
我把vim更新到https://gitorious.org/evil的版本,还是出现同样的问题(但是那里的evil)好像可以使用M-x了

**Comment by redguardtoo** [comment]
evil的bug我知道，没有更新是因为我偏向用稳定版。 M-x的问题已有很多替代法，比如“C-x C-m“或”，xm“

**Comment by mashomee** [comment]
嗯,再问一下,在w3m中能使用hjkl移动吗

**Comment by russellfei** [comment]
@mashomee 我记得是可以的，你可以查看帮助

**Comment by redguardtoo** [comment]
1. w3m, check init-evil.el, major-mode is `w3m-mode`, you have to freedom to choose keybindings.

2. c++, for the code completion, you need make sure all the c++ header directories is included in `company-clang-arguments`, and you c++ code should be error free. That's the way of clang. In your specific error, run "clang" with the arguments printed in  the line started with `company-clang--handle-error`. What's the result?

**Comment by mashomee** [comment]
@russellfei 我看帮助里能说是可以使用info或lynx的按键模式

**Comment by mashomee** [comment]
````sh
clang -fsyntax-only -Xclang -code-completion-macros -x c++ -I./ -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -Xclang -code-completion-at=temp.cpp:23:5 temp.cpp
````
使用上面的命令可以正常补全,一共3000多条结果,
下面的错误信息中这个命令后还有一串命令,其中还有几个是'\00',直接重emacs中复制不过来,到'\00'那个地方就断了.是不是字符'\0'的问题呢
````elisp
Debugger entered--Lisp error: (args-out-of-range #<buffer *clang-output*> 0 1)
  buffer-substring-no-properties(1 0)
  company-clang--handle-error(1 ("-fsyntax-only" "-Xclang" "-code-completion-macros" "-x" "c++" "-I./" "-I/usr/include/x86_64-linux-gnu/qt5" "-I/usr/include/x86_64-linux-gnu/qt5/QtCore" "-I/usr/include/x86_64-linux-gnu/qt5/QtGui" "-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork" "-I/usr/include/x86_64-linux-gnu/qt5/QtTest" "-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets" "-Xclang" "-code-completion-at=-:23:5" "-"))
  #[514 "\306\307\310\311#)\266\203?\205,\00\301\312!r\304q\210\211\313=\204$\00\314\302\"\210\315\300\303\")\262!\207" [#("ac" 0 1 (fontified t face font-lock-type-face) 1 2 (fontified t c-type c-decl-id-start face font-lock-type-face)) #[257 "\211\203\00\301\242\307=\204\00\301\240\207\306\n\300\310!BC\311\302\303\304\305$\207" [#("ac" 0 1 (fontified t face font-lock-type-face) 1 2 (fontified t c-type c-decl-id-start face font-lock-type-face)) (done) #<buffer temp.cpp> #<window 3 on temp.cpp> 241 529 company-clang done company--preprocess-candidates company-idle-begin company-backend company-candidates-cache] 6 "\n\n(fn CANDIDATES)"] ("-fsyntax-only" "-Xclang" "-code-completion-macros" "-x" "c++" "-I./" "-I/usr/include/x86_64-linux-gnu/qt5" "-I/usr/include/x86_64-linux-gnu/qt5/QtCore" "-I/usr/include/x86_64-linux-gnu/qt5/QtGui" "-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork" "-I/usr/include/x86_64-linux-gnu/qt5/QtTest" "-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets" "-Xclang" "-code-completion-at=-:23:5" "-") nil #<buffer *clang-output*> inhibit-changing-match-data "hangup" nil t string-match process-exit-status 0 company-clang--handle-error company-clang--parse-output] 9 "\n\n(fn PROC STATUS)"](#<process company-clang> "exited abnormally with code 1\n")
````

**Comment by redguardtoo** [comment]
send the bug to the company-mode, with full stacktrace and all the other information, I guess it's the performance issue of company-mode,  I saw some related 1discussion on company-mode issue tracker.
setup is fine.

**Comment by mashomee** [comment]
@redguardtoo 在init-evil里面major mode里面有w3m,可是在w3m里面按键绑定是info里面的.

**Comment by redguardtoo** [comment]
so your choice, you can uncomment my code.

**Comment by mashomee** [comment]
i'll stick to your config. perhaps it's better in w3m.

**Comment by redguardtoo** [comment]
l tested with qt4, deibian7, cmake 2.8, company 0.8.7, clang 3.0,  cpputil-cmake 0.4.22. Looks everything is working.


![152754-26_1331x1162](https://cloud.githubusercontent.com/assets/184553/5895338/2e0ff616-a570-11e4-8e8a-09abe675a788.png)

Please `M-x list-packages`  and make sure you've upgraded to latest company-mode, All obsolete packages should be deleted. 

Here is the output of clang-company-arguments:
![153112-26_1873x1084](https://cloud.githubusercontent.com/assets/184553/5895341/6a22749e-a570-11e4-96e5-c8e24420abcc.png)

**Comment by mashomee** [comment]
谢谢你,我再检查检查

**Comment by mashomee** [comment]
````
error in process sentinel: Args out of range: #, 0, 1
````
刚发现,这个错误在其他mode下也会出现,可能是其他的包之间的冲突.

**Comment by moyotar** [comment]
@redguardtoo  company-clang 在补全c++的时候很慢很慢，是本身就这效率吗？（补全c的时候很快的）

**Comment by redguardtoo** [comment]
depends how many C++ header files to scan.

You can use global instead, http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html
