### ISSUE TITLE
about compile

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#243]
Scene： I work at two projects A and B meantime.

I compile A by "M-x compile", the command line is right.
Then, i switch to B project by "C-x C-o", a compie command  for A project keeping rather than for B.

Do you have this problem？ 

Thank you！

**Comment by redguardtoo** [comment]
if you use cpputils-cmake and cmake, `cppcm-reload-all` anytime when you find any mimatch issue. everything wil be re-caculated by the current cpp file your are editing. 

If you are not using cpputils-cmake, then that's the emacs way because there is no project file in Emacs.
