### ISSUE TITLE
An error occurred while customizing color theme

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#244]
I see the instruction at the section called "Preview&apply a color theme" in ".emacs.d-master/README.org". So I check a theme called "ample-zen-theme" on "http://emacsthemes.caisah.info/ample-zen-theme/", then write this code
```(require 'color-theme-ample-zen)  
(color-theme-ample-zen)  ```
 in the `init.el`. After restart the emacs, I got the error message ` Cannot open load file, No such file or directory, color-theme-ample-zen`

It seems that there is no package has been installed. I was confused, because I thought that `init.el` will download the package automatically.

Then I try to install that theme through the package manager. After `M-x package-install [RET] ample-zen-theme` I have been told "No match". It seems `marmalade repo` is not include in packages archive list. 

I want to add `marmalade repo`, but I don't know where is the right place I can add my customized code. Though I can add some code at the end of ".emacs.d/init.el".

**Comment by zarzen** [comment]
If I create `~/.emacs` file your configuration `.emacs.d/init.el` doesn't work anymore.

**Comment by russellfei** [comment]
Actually, you should not let `.emacs` exist in your `~` directory, which is a common sense.

**Comment by redguardtoo** [comment]
rm ~/.emacs
for the color theme, you need download it either through melpa.org

**Comment by zarzen** [comment]
Thanks!

But is there any tutorial for customisation?
For example, which file I can add some `elisp` for customising and overlap your default configuration.
I mean the way to organize my own customisation with your `.emacs` configuration. 
Because I want to manage my configuration separate from yours, I think it will easier to managing than modifying your configurations.
Is there any tips?

**Comment by russellfei** [comment]
Learn elisp and hack your own emacs.d, I think that's worth a lot ;-)
Emacs is built for every one, and the .emacs.d is adapted to everyone with elisp

**Comment by mashomee** [comment]
在~/.emacs.d/init.el:170行
````elisp
;;----------------------------------------------------------------------------
;; Variables configured via the interactive 'customize' interface
;;----------------------------------------------------------------------------
(if (file-exists-p "~/.custom.el") (load-file "~/.custom.el"))
````
你可以直接在这个文件里写你的配置,也可以直接修改emacs.d里的
不过更好是使用eval随时调试

**Comment by zarzen** [comment]
Thanks！
还没好好看过init.el @mashomee 
@russellfei elisp 毕竟学一下得花点功夫，而且主要想借助已有的配置做修改这样会快捷点。自己配，总是会把配置弄得略七八糟的，最好配置的模式可以是CSS那种覆盖的模式。

**Comment by russellfei** [comment]
@zarzen 你是用git去下载配置,然后可以随意改，repo里有git来控制代码修改 ;-)
我最近才开始用git做version control，不用担心代码混乱
