### ISSUE TITLE
How to use C-/ or C-@ ..etc with emacs -nw

### ISSUE THREAD

**Issue by Stumble** [redguardtoo/emacs.d#245]
Hi Bin,

I'm not a evil-mode user, and these key-bindings do not work well under terminal.

Should I bind these keys in my custom configuration or ?

**Comment by redguardtoo** [comment]
check README, you can uncomment the evil module.

Basically I didn't re-bind any keys. So you should get more ORIGINAL emacs key bindings after remove evil modules.

**Comment by Stumble** [comment]
In the original emacs key bindings, C-/ is undo and C-@ is mark, but in the configuration these key bindings do not work under terminal.

(already commment evil mode)

**Comment by redguardtoo** [comment]
`C-h k` will show you which package take over the key binding. As I can see, `Ctrl-/` is taken over by undo-tree-undo, and `C-@` could be taken over by expand-region.el.

To restore the keybinding you can simply re-bind the keys or just uninstall these two packages.

you need uncomment `(require 'init-evil)` in init.el, btw.

**Comment by Stumble** [comment]
I use guake as my terminal, and it does not send C-. to the running program. So now I bind set-mark-command to "M-." but it does 'seem to work'

Then I find out that it is because I did not use 'TERM=xterm-256color emacs -nw' to start emacs under terminal. So problem solved!

btw, undo-tree-undo does not work if I comment (require 'init-evil)

**Comment by redguardtoo** [comment]
because that version of undo-tree-undo is loaded by evil manually, maybe, but you install it as independent package.

**Comment by Stumble** [comment]
One question, If I prefer to add undo-tree-mode manually, how should I do?

I download undo-tree-mode.el , and then I put it in site-lisp

Then I try to (require 'unto-tree), but it seems wrong~~

I was always confussed about site-lisp/localelpa/defun folders, what's use of them? And how should I add undo-tree mannually?

**Comment by Stumble** [comment]
Thx :+1:

**Comment by redguardtoo** [comment]
localelap and defun should be ignored. it's for emacs23 compatibles issues, just check README. for undo-tree, read emacswiki.

**Comment by Stumble** [comment]
Thanks,

I mange my own emacs configuration here https://github.com/Stumble/emacs.d , it derives from your configuration, and I periodly merge from your configuration.

So I want to keep the file structure cool and aligned with yours.

Could you please tell me If you were me, how will you add undo-tree?

**Comment by Stumble** [comment]
For now, I use these code to make it work
in custom.el

<code>
https://github.com/Stumble/emacs.d
load-file "~/.emacs.d/site-lisp/undo-tree-mode/undo-tree-0.6.4.el")                                                       
(require 'undo-tree)                                                                                                      
(global-undo-tree-mode)        
</code>

**Comment by redguardtoo** [comment]
That's OK.
