### ISSUE TITLE
高亮代码注释中的 TODO FIXME 等关键词

### ISSUE THREAD

**Issue by imtxc** [redguardtoo/emacs.d#246]
是否可以把高亮代码注释中的 TODO， FIXME， XXX 等关键字加入配置，如
http://www.gnu.org/software/emacs/manual/html_node/emacs/Font-Lock.html
和
http://emacs-fu.blogspot.com/2008/12/highlighting-todo-fixme-and-friends.html
的配置这样.

**Comment by redguardtoo** [comment]
I already use fic-mode to do the same.

I tweak it a little bit to make fic-mode works in all languages. 
5e4a582 upgrade fic-mode (Chen Bin)
