### ISSUE TITLE
added elpa.gnu.org to package list but still can't install packages which I need.

### ISSUE THREAD

**Issue by ypwu1** [redguardtoo/emacs.d#247]
The flycheck package requires let-alist package as dependency which is under elpa.gnu.org source.  However, after added gnu source to list,  I couldn't find the let-alist on package-list. I am new to emacs, please help. By the way, is there a way I could download and install it locally?

**Comment by redguardtoo** [comment]
your emacs version?

**Comment by redguardtoo** [comment]
c1a8201 GNU elpa is optional though not enabled by default (Chen Bin)

**Comment by ypwu1** [comment]
Hi, my version is 24.4, environment is mac yosemite

**Comment by ypwu1** [comment]
Fixed. Thanks for help!
