### ISSUE TITLE
mac下面启动emacs最大化的时候最上面几行总是看不见

### ISSUE THREAD

**Issue by hanzejl** [redguardtoo/emacs.d#248]

**Comment by redguardtoo** [comment]
more information, os? emacs version?

**Comment by hanzejl** [comment]
emacs：24.4
os：OS X Yosemite 10.10.2

**Comment by redguardtoo** [comment]
https://www.google.com.au/search?q=osx+maximine+window&ie=utf-8&oe=utf-8&gws_rd=cr&ei=zBvTVI2QMeitmAXHtoDQAg#q=osx+maximine+window+emacs+yosemite 

`grep keyword lisp/*.el`, I always use Emacs in terminal, so don't have this issue. As I remember, this is some solved problem in GUI emacs, but I don't have yosemite.

**Comment by ysonggit** [comment]
是有这个问题.启动窗口最大化定义在
.emacs.d/lisp/init-misc.el
(add-hook 'window-setup-hook 'maximize-frame t)
我把这行注释了,启动的是默认的窗口大小

**Comment by hanzejl** [comment]
我也注释掉了，按照默认的窗口打开就不会出现问题了
你的这个Emacs配置文件用起来太舒服了，基本上需要的功能都有了，节省了很多自己配置的时间
在此表示深深的感谢
