### ISSUE TITLE
Too high cpu consumption

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#250]
hello. i have a problem about too high cpu consumption.
When i have some action in emacs24, the cpu consumption will up to 40%-70%.

OS: ubuntu  Cpu: corei3  Memort: 4G

Can you give me some tips about how to debug about it, then to find the plugins resulting this problem.
I install some other plugins for myself..

Best regards.
thank you!!

**Comment by redguardtoo** [comment]
what major-modes you are using?

**Comment by fenxian** [comment]
C++ and Python

**Comment by redguardtoo** [comment]
`C-h m` what minor modes you are using? More details, what's the issue?

**Comment by fenxian** [comment]
![screenshot from 2015-02-09 16 39 27](https://cloud.githubusercontent.com/assets/5669903/6103081/d841c5dc-b07a-11e4-92aa-c7aa9f555aed.png)

**Comment by redguardtoo** [comment]
looks fine to me, try to disable flyspell and flymake, though I think flyspell and flymake is must have plugins.

**Comment by russellfei** [comment]
I never found emacs consumes too much high cpu usage, or did you use any packages/softwares outside emacs providing something like semantic understanding?

PS: too many lines in a script makes a lot of burden for `linum` and something like `gtags`, just my perosnal guess

You remind me some packages we seldom use current time, like `cscope`
