### ISSUE TITLE
有没有每个插件介绍的文档

### ISSUE THREAD

**Issue by brucedeng** [redguardtoo/emacs.d#251]
感谢作者的贡献！emacs上手快多了，但是有个问题，作者帮忙集成了很多插件，有没有这些介绍用法的一些文档？这样使得新手上手有个感觉。

**Comment by redguardtoo** [comment]
in readme or in wiki page?

**Comment by yunhaia** [comment]
同感，作者很强大，有个问题想问一下，mark-set怎么用？

**Comment by redguardtoo** [comment]
now I use expand-region.el only, so don't bother setting mark, it's to slow. 

I do use `C-x C-x` often

**Comment by brucedeng** [comment]
在readme貌似我没有找到链接，只看到总体的介绍？

On Thu, Feb 12, 2015 at 9:58 PM, chen bin <notifications@github.com> wrote:

> in readme or in wiki page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/251#issuecomment-74208984>.
>



-- 
Jingjing Deng

**Comment by redguardtoo** [comment]
还没开始写呢. 我问的是,放在哪里比较好,readme还是wiki?

**Comment by brucedeng** [comment]
readme的话方便一些,多谢！
可否放入一些截图或者GIF，对我这样初学者很有帮助！（我是看到类似这个的教程
http://tuhdo.github.io/emacs-tutor.html）


On Fri, Feb 13, 2015 at 4:07 PM, chen bin <notifications@github.com> wrote:

> 还没开始写呢. 我问的是,放在哪里比较好,readme还是wiki?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/251#issuecomment-74349343>.
>



-- 
Jingjing Deng

**Comment by russellfei** [comment]
我一般是看readme，然后查redguardtoo个人博客，剩下的google。
工具介绍不错，可以放个人博客，也可以给这个repo建立wiki页面。;-)

**Comment by standino** [comment]
readme

**Comment by liuxianming** [comment]
@redguardtoo 我也同好奇怎么用set-mark，谢谢解释。ps，很好很强大！！！

**Comment by redguardtoo** [comment]
https://www.gnu.org/software/emacs/manual/html_node/emacs/Setting-Mark.html

不过已经落伍了，不是最有效的用法，见我前文。

**Comment by liuxianming** [comment]
谢谢。有一个比较初级的问题。我在用expand-region.el的时候，为什么没有办法选中region呢？一直就是现实matched的括号但是没有办法选中需要的区域。谢谢

**Comment by redguardtoo** [comment]
I don't understand, select by mouse?

**Comment by liuxianming** [comment]
not by mouse. C-@, then no region is selected, by the cursor jumped to the right bracket.

**Comment by liuxianming** [comment]
Like this, 
![screen shot 2015-03-11 at 2 10 19 am](https://cloud.githubusercontent.com/assets/1305722/6591857/ce8bb644-c793-11e4-9caf-038dd5e711ed.png)

**Comment by redguardtoo** [comment]
what's your major-mode?

**Comment by liuxianming** [comment]
Thanks, major-mode? c++?

**Comment by redguardtoo** [comment]
还是用中文说吧，我试了下都没问题。

**Comment by liuxianming** [comment]
好的。我这个貌似目前就是不能选择。比较诡异。也不知道问题出在哪。我去debug模式下看一下。

**Comment by lczch** [comment]
wiki是不是可以大家一起贡献，作者负责审核就可以了？

**Comment by wubinjie** [comment]
插件手册在哪里更新？可以一起参与么？

**Comment by redguardtoo** [comment]
目前还没有，再等两个月吧。

**Comment by liangyaozhan** [comment]
C-.就是set-mark啊。

**Comment by yangdaweihit** [comment]
最好是由你来审核，大家来共建文档的方式好一些。

**Comment by lln133208** [comment]
> Ensure that the init.el contained in this repo ends up at ~/.emacs.d/init.el.

上面这句话是什么意思？意思是`init.el`的最后一行是`~/.emacs.d/init.el`？谢谢回答

**Comment by lln133208** [comment]
> Ensure that the init.el contained in this repo ends up at ~/.emacs.d/init.el.

上面这句话是什么意思？意思是`init.el`的最后一行是`~/.emacs.d/init.el`？谢谢回答

**Comment by lln133208** [comment]
> Ensure that the init.el contained in this repo ends up at ~/.emacs.d/init.el.

上面这句话是什么意思？意思是`init.el`的最后一行是`~/.emacs.d/init.el`？谢谢回答

**Comment by redguardtoo** [comment]
This is copied from purcell's README.

He basically means `rm ~/.emacs" make sure `~/.emacs.d/init.el` exists

**Comment by lln133208** [comment]
编辑python时，总是报错 **blocking call to accept-process-output with quit inhibited!!**

**Comment by redguardtoo** [comment]
I will look into this, I guess it's you need install 3rd party tools for anaconda-mode (check its github site).

regard the message as warning though. If you don't use intellisense, you don't need anaconda-mode.

**Comment by lln133208** [comment]
> I will look into this, I guess it's you need install 3rd party tools for anaconda-mode (check its github site).
> 
> regard the message as warning though. If you don't use intellisense, you don't need anaconda-mode.

嗯，我不需要`anacodda-mode`，就是出个问题在编辑代码的时候会卡顿，很影响写代码。顺便，谢谢关注我的问题:smile:

**Comment by redguardtoo** [comment]
That's totally OK. I don't use anaconda-mode too when writing python code.

On Fri, Jun 5, 2015 at 10:06 PM, RenYuan <notifications@github.com> wrote:

> I will look into this, I guess it's you need install 3rd party tools for
> anaconda-mode (check its github site).
>
> regard the message as warning though. If you don't use intellisense, you
> don't need anaconda-mode.
>
> 嗯，我不需要anacodda-mode，就是出个问题在编辑代码的时候会卡顿，很影响写代码。顺便，谢谢关注我的问题[image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/251#issuecomment-109269636>
> .
>



-- 
help me, help you.
