### ISSUE TITLE
为什么通过list-package安装的一些插件没法使用？

### ISSUE THREAD

**Issue by brucedeng** [redguardtoo/emacs.d#252]
刚刚起步，我通过list-package 装了两个插件，一个是golden-ratio,另外一个是gotham-theme, 两个安装了之后都没有什么效果，是不是我需要修改哪些东西？谢谢！

**Comment by russellfei** [comment]
是不是还需要外部依赖的库？如果需要外部依赖的库，而你没有安装，那就是用不起来。

**Comment by redguardtoo** [comment]
list-packages will handle dependency automatically, check `init.el`, replace line ` (require 'color-theme-molokai)`.

**Comment by brucedeng** [comment]
I replaced that with color-theme-gotham, but it looks still not working; do
I need to add more lines etc for this?

Many thanks!


On Sun, Feb 15, 2015 at 3:17 PM, chen bin <notifications@github.com> wrote:

> list-packages will handle dependency automatically, check init.el,
> replace line (require 'color-theme-molokai).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/252#issuecomment-74443085>.
>



-- 
Jingjing Deng

**Comment by redguardtoo** [comment]
https://github.com/wasamasa/gotham-theme

`(load-theme 'gotham t)`

please always check the header of the the el file.

For some reason, the Emacs has two sets of color theme APIs. It's because people are always busy re-invent the wheel.

**Comment by brucedeng** [comment]
I tried that ((load-theme 'gotham t)) and comment out the
color-theme-molokai; but it looks it is not taking effect. May I know if I
need to change other part of the configurations as well?

Many thanks!

On Sun, Feb 15, 2015 at 7:52 PM, chen bin <notifications@github.com> wrote:

> https://github.com/wasamasa/gotham-theme
>
> (load-theme 'gotham t)
>
> please always check the header of the the el file.
>
> For some reason, the Emacs has two sets of color theme APIs. It's because
> people are always busy re-invent the wheel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/252#issuecomment-74456966>.
>



-- 
Jingjing Deng

**Comment by redguardtoo** [comment]
Looks fine on my computer.

![screen shot 2015-02-17 at 1 47 50 am](https://cloud.githubusercontent.com/assets/184553/6213755/104b2ea6-b647-11e4-9d0c-0184c3b1a8a4.png)

**Comment by redguardtoo** [comment]
golden-ratio会修改API,可能会和其他插件冲突.
