### ISSUE TITLE
Unexpected background highlights for a certain set of keywords

### ISSUE THREAD

**Issue by Goldiorl** [redguardtoo/emacs.d#253]
Imported default configurations and somehow when opening txt files, (or some org files, but not all) will have unexpected background-highlighted words.

A notable pattern is that all verbs that following a "be" indefinite verb are all highlighted.

Example
![image](https://cloud.githubusercontent.com/assets/6183114/6202878/acee0be4-b53d-11e4-85da-8b90cafbc2c9.png)

**Comment by Goldiorl** [comment]
Now I see where is the problem, the "font-lock"

But still have no clue where those keywords rules were originally added

I choose to close font-lock mode on those circumstances

For other's interests, you may delete those keywords
https://www.gnu.org/software/emacs/manual/html_node/elisp/Customizing-Keywords.html

**Comment by redguardtoo** [comment]
disabled `artbollocks-mode` which highlight some weak words I should use less. It's just hint for writing style.
