### ISSUE TITLE
Windows 下不能checkout 如下文件，因为文件系统命名规则。

### ISSUE THREAD

**Issue by lianliuwei** [redguardtoo/emacs.d#254]
$ git reset --hard
error: Invalid path 'snippets/c++-mode/d_operator<<'
error: Invalid path 'snippets/c++-mode/operator<<'
error: Invalid path 'snippets/c++-mode/operator>>'
error: Invalid path 'snippets/c++-mode/std::'
error: Invalid path 'snippets/ruby-mode/:'
HEAD is now at 7470929 evil-escape upgraded

**Comment by redguardtoo** [comment]
dacc60b make file names windows friendly (Chen Bin)
