### ISSUE TITLE
typo in README.org

### ISSUE THREAD

**Issue by mogeiwang** [redguardtoo/emacs.d#256]
1) In “apt-get uninstall emacs-w3m”, "uninstall" should be "autoremove" (remove automatically installed packages) or "remove" (remove one or more packages). The operation of "uninstall" is invalid.

2) "Uncomment below code in nit-elpa.el and start Emacs now!" I am not very sure about this, but it seems "nit-elpa.el" should be "init-elpa.el".

**Comment by redguardtoo** [comment]
d2d71b0 fixed typo (Chen Bin)

thanks

**Comment by mogeiwang** [comment]
There is another “apt-get uninstall emacs-w3m”.

**Comment by redguardtoo** [comment]
thanks. fixed
