### ISSUE TITLE
请问没有翻墙会影响哪些插件和功能的使用？

### ISSUE THREAD

**Issue by Elu0** [redguardtoo/emacs.d#257]
我没有翻墙，也能成功配置并使用emacs，所以现在很好奇有哪些插件需要翻墙

**Comment by russellfei** [comment]
比如说，有时候melpa就会被墙。
如果你是教育网用户，可以无视这点。
或者，你遍历下每个插件也行(quite looking forward to it ;-)

**Comment by redguardtoo** [comment]
目前不需要翻墙

发自我的 iPhone

**Comment by standino** [comment]
谁好心在国内建一个melpa镜像就好了。呵呵。

**Comment by redguardtoo** [comment]
you can build a mirror for your own at github or dropbox, check my project elpa-mirror
