### ISSUE TITLE
怎样屏蔽idle-require的minibuffer中的显示?

### ISSUE THREAD

**Issue by lhrkkk** [redguardtoo/emacs.d#258]
idle require 在minibuffer里面的提示信息有时候会覆盖你当前在mini-buffer里面的操作, 怎样让它们不显示? 因为这个idle require 显示的信息一般来说可以不用去看. 平时使用的时候要是能屏蔽就好了.

**Comment by redguardtoo** [comment]
5a79108 flag to turn off idle-require messages (Chen Bin)

`(setq idle-require-message-verbose nil)` to turn off messages

**Comment by lhrkkk** [comment]
got it! thanks!
