### ISSUE TITLE
Blocking call to accept-process-output with quit inhibited!!

### ISSUE THREAD

**Issue by murphytsai** [redguardtoo/emacs.d#261]
Every time I open emacs in evil mode and "Blocking call to accept-process-output with quit inhibited!!" will  displayed as below while moving cursor .
![image](https://cloud.githubusercontent.com/assets/215310/6613984/2a8e36c4-c8cf-11e4-8a66-777f5009ee74.png) . 

My environment is 
CentOS 6.5
emacs version: 24.3.1
emacs.d: stable version.

**Comment by redguardtoo** [comment]
that's fine, looks all you needb to do is just upgrade anaconda-mode, see https://github.com/proofit404/anaconda-mode/issues/33

The purpose of anaconda-mode is code completion. If you don't use it, you can ignore the error. or just download the latest emacs.d

**Comment by murphytsai** [comment]
Thanks Bin, it's resolved now.
