### ISSUE TITLE
gc part of init.el

### ISSUE THREAD

**Issue by douxing** [redguardtoo/emacs.d#262]
In your GC part of your init.el(currently in line 41~49), your comments says that you need 1G of memory, but there are only [eight zeros in your code and comment](https://github.com/redguardtoo/emacs.d/blob/master/init.el#L46~L48), which i think there should be nine zeros for 1G, because the example in your comment of gc-cons-threshold == 800000 is indeed 0.78M.

Are there any misunderstandings for me?

**Comment by redguardtoo** [comment]
thanks. on second thought, I though 1G is too much but forgot updating doc. Now I use 512M for gc.
33db77e gc setup (Chen Bin)
