### ISSUE TITLE
A bug about cpputils-cmake

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#263]
![test](https://cloud.githubusercontent.com/assets/5669903/6634390/b82d06ea-c992-11e4-9422-b46aca0a9a46.png)

Here is your "hello" project. It is work well at first. But "cppcm-reload-all" can't work right after i change CMakeLists.txt like upon image.

Please check it. Thank you.

**Comment by redguardtoo** [comment]
cppcm-reload-all only works on cpp file

**Comment by fenxian** [comment]
I think i can use cppcm-reload-all by a right way. In here, i may encounter a bug. Your can have try your "hello” project (demo in https://github.com/redguardtoo/cpputils-cmake) after replacing CMakeLists.txt in image.

Certainly, i am not famiilar cmake well. May be it is my fault in using it.

**Comment by redguardtoo** [comment]
OK, I'll have a look this weekend. you're using cmake 2.6 or 2.8?

**Comment by fenxian** [comment]
cmake version : 2.8.

**Comment by fenxian** [comment]
How to debug program with gdb in emacs.
Follow your "hello" project, i get follow information：
===============================================================
Type "apropos word" to search for commands related to "word".
(gdb) l 0
No symbol table is loaded.  Use the "file" command.
(gdb) file ../build/main
Reading symbols from ../build/main...(no debugging symbols found)...done.
(gdb) 
================================================================
I add those flags in order to debug. 

Can you give me more manual for debug?
Do you debug on gdb-many-windows? or only with a gdb terminal？

**Comment by redguardtoo** [comment]
check README of cpputils-cmake, it's in the optional setup.

I only use the gud-gdb because the gdb on my os x 10.7.3 does not support gdb-many-windows.

exactly same workflow as gdb cli, so knowledge of gdb will help.
