### ISSUE TITLE
About org version

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#264]
Hi~

It is better to update org version to 8.2.x.
You can check that "#+HTML_HEAD: ..." is only work version 8.2.x.

"#+HTML_HEAD: ..." works on exporting HTML file.

Thanks.

**Comment by redguardtoo** [comment]
yes, but I'm still even support old version emacs now.  The emacs23 support will be dropped next month. Emacs 24.3 which use org7 still use org7.
