### ISSUE TITLE
How to show the definition of function in minor buffer?

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#265]
We can have a look about definition in popup.
But we can't check definition about function after select it from popup.

How to show thus information in minor buffer or other window??

Thank you.

![1](https://cloud.githubusercontent.com/assets/5669903/6635037/09e8aa1c-c99c-11e4-93b4-0d5f90ddb30a.gif)

**Comment by redguardtoo** [comment]
for code navigation, use gnu global.

**Comment by fenxian** [comment]
..Sorry, i am confusioin about "navigation with gnu global".
In here, my requirement is to have a tip when I insert a function which may be have much parameters.
This tip can give me function declaration include type and sort of parameters. I think those information can be showed in minor buffer just as locating at a function in popup window.

**Comment by redguardtoo** [comment]
check company-mode, I'm sure it's implemented in company-gtags

**Comment by fenxian** [comment]
oh, sorry. I can not find an appropriate way to get it.
The required information can be showed in minor buffer before I type <TAB> or <ENTER> to determine candidate. However, it will automatically dismissed when i determine it. You know, i will input parameters at this time. .. . but. . 
I have tried many short keys and commands in company-mode. All are failed.
How you do it?
Thank you .

**Comment by redguardtoo** [comment]
I understand now,  the feature you required is handled by a minor mode called eldoc-mode http://emacswiki.org/emacs/ElDoc

but I never bothered to set it up. Currently company-mode does everything by itself. Its developer choose close the hint in mini-buffer when *you are not typing*. You need contact him if you need this feature (or maybe it's already there?)

For me, company-mode gives me enough information when *I am typing*. After that, I just use ggtags.el to jump to the declaration. That's not as efficient as eldoc, but good enough for me.

**Comment by Stumble** [comment]
Eldoc seems not perfect for what @fenxian wants.

I am looking for a way to have the same feature of he wants too, hope @fenxian  could find a perfect way and share .

**Comment by fenxian** [comment]
We can find it together.
