### ISSUE TITLE
Can it auto-complete headers?

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#268]
Can it complete header similar auto-complete function and variable when we edit #include<.?
Can it have a popup tips after typing "<"?

**Comment by redguardtoo** [comment]
see cpputils-cmake home page, it's supported in this emacs.d, `company-c-headers`

**Comment by fenxian** [comment]
hello, i find the reason about it.
company-c-headers  can complete header with "#include < ". "#include<" will be fail. The space is important.

I check the company-c-headers.el
![a](https://cloud.githubusercontent.com/assets/5669903/12061965/49e734da-afce-11e5-8ab2-a3e625330858.png)

**Comment by redguardtoo** [comment]
if it's a issue of company-c-headers, raise a issue to its developer.
