### ISSUE TITLE
关于sudo 

### ISSUE THREAD

**Issue by lczch** [redguardtoo/emacs.d#269]
我现在发现每次打开emacs的时候，随意打开一个文件夹，就会要求要输入root密码，我觉得这样很麻烦。
在init-misc.el中我找到了(defadvice ido-find-file)，去看了相关的内容之后，它的功能似乎是自动检验当前文件夹里是否有你无法写的文件，如果有，就需要你输入root密码。
这样是不是太激进了？

**Comment by redguardtoo** [comment]
you can remove that snippet. It works fine in my use cases.

**Comment by Stumble** [comment]
I was bothered by this feature before, but later I got used to it. 

I Just type C-g for once to avoid this message.
