### ISSUE TITLE
About some variables

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#270]
### Follow your project "hello" in 
https://github.com/redguardtoo/cpputils-cmake.
1. Create project "hello" 
2. Create build and implement cmake ../src in build
3. M-x cppcm-reload-all
4. M-x compile
5. M-x cppcm-reload-all
### Now, we check some variables by "C-h v": 

1. "cppcm-include-dirs" :   Its value is ("-I\"/home/USER/hello/src/\"")
2. “company-c-headers-path-system" :   Its value is ("/home/USER/hello/src/")   Original value was ("/usr/include/" "/usr/local/include/")
3. ”ac-clang-flags“  value is ("-I/home/USER/hello/src/")
4. “company-clang-arguments” : Its value is ("-I/home/USER/hello/src/") Original value was nil

### Confusion
* My other projects are configured "opencv" "boost" in CMakeLists.txt. Your emacs.d can set those include paths well. 

* A problem is that:  Upon variables haven't system paths, for examples, "/user/include/" "/user/local/include". In particular, "company-c-headers-path-system" looses those original paths!

* I have reported a problems. In your guide, i know some variables need to be configured. I am confusion about too much variables. I have a right configuration for "company-clang-arguments" at once. 

#### I need your help for all those variable. How to configure it right ? May be it is confusion for many newbies.

Please check it detail. After all, almost of all functions rely on those variables in here. 
Thank you very much.

**Comment by redguardtoo** [comment]
If you use cpputils-cmake and cmake, you don't need set up any variables, you don't need any setup.

looks your setup is fine.

*The original path* does not matter, any emacs variable has *original value*. forget them.

**Comment by fenxian** [comment]
Yes, i use cpputils-cmake and cmake.
