### ISSUE TITLE
How to generate c++ implementation 

### ISSUE THREAD

**Issue by andyque** [redguardtoo/emacs.d#272]
When I define a new method in a class, I want to let Emacs generate the implementation skeleton.

Is there any package could do this?

I found this http://www.emacswiki.org/emacs/member-functions.el , but it's not working.

And the wiki page: http://www.emacswiki.org/emacs/ExpandMemberFunctions

Any suggestions would be appreciated. 

Thanks.

**Comment by redguardtoo** [comment]
用yasnippets就可以了,在我的博客上有关于yasnippets比较advanced的文章,虽然是用于javascript,但是你可以举一反三.

另外可以读一下我的"一年成为Emacs高手一文",类似问题你都可以触类旁通了.

比如说C++,你可以follow越南高手(https://github.com/tuhdo), 他有一篇关于C++的guide写得很好,我也有一篇提纲在https://github.com/redguardtoo/mastering-emacs-in-one-year-guide, 也基本面面俱到了,但是没有他细节多.

**Comment by redguardtoo** [comment]
emacswki上代码质量参差不齐,现在好的代码基本都在github了,这和其他语言都一样的.

我在"一年"一文里明确提过emacswiki作为了解问题的最新进展和全貌很好,但是是否要采用其方案要仔细考虑. 可能说得还是婉转,实际意思就是上面的第一段的意思.
