### ISSUE TITLE
Flymake work in emacs terminal mode

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#273]
How to show error information of flymake when emacs work in terminal?

In terminal, GUI menu can not popup. ... So i add (setq flymake-gui-warnings-enabled nil) in ini-flymake.el.

But, the error message can not be showed, include *Message* buffer.

Can you give me some tips?
Thank you.

**Comment by redguardtoo** [comment]
which language? more information.

flymake should work out of the box.

**Comment by fenxian** [comment]
C/C++
Emacs version: 24.3.1
error part:
![screenshot from 2015-03-18 09 32 45](https://cloud.githubusercontent.com/assets/5669903/6701048/22a4f8c6-cd52-11e4-92b2-68fda229b9aa.png)

"M-x flymake-display-err-menu-for -current-line"
flymake-popup-menu: Can not put GUI menu on this terminal 
which can be restrained by setting "(setq flymake-gui-warnings-enabled nil)", but the error information don't show.

**Comment by redguardtoo** [comment]
menu is desigined for GUI version, as I understand from the error message. use `flymake-goto-next-error`, the error message should be displayed in mini-buffer, check my flymake setup and read emacswiki

**Comment by fenxian** [comment]
i want to use you short key "C-`" which work well in gui mode.

But in my terminal, a problme appear showed following:
* "M-x flymake-goto-next-error"
![0](https://cloud.githubusercontent.com/assets/5669903/6705356/08b5b422-cd8f-11e4-9abb-94d04f50bb30.png)

* Short key "C-`"
![1](https://cloud.githubusercontent.com/assets/5669903/6705347/e11fad5a-cd8e-11e4-90b9-effaf90c9cae.png)

* "C-h C-k" and "C-1"
![2](https://cloud.githubusercontent.com/assets/5669903/6705362/13bff97c-cd8f-11e4-8fce-60fa611d1f87.png)

Do you happend it? "`" seem to be regard as "@".. 
Thank you.

**Comment by redguardtoo** [comment]
I don't use these hot keys any more. It could be the legacy setup from steve purcell.

I just `M-x flymake-goto-next-error` or use evil-leader.

You've read my "one year", right? I did mention that I remember no more than 20 key bindings. I just use smex and evil-leader.

**Comment by fenxian** [comment]
thank you!
