### ISSUE TITLE
helm could not supports fuzzy matching

### ISSUE THREAD

**Issue by lhrkkk** [redguardtoo/emacs.d#274]
all helm window could not support fuzzy matching, 

the configuration method of helm is here  https://github.com/emacs-helm/helm
![image](https://cloud.githubusercontent.com/assets/934669/6726931/013cc8a6-ce58-11e4-9bdc-2290c27846f7.png)

but this do not have effect.

**Comment by redguardtoo** [comment]
Ｉ　ｐｒｅｆｅｒ　ｄｅｆａｕｌｔ　ｒｅｇｅｘ　ｍａｔｃｈ，　ｂｕｔ　ｙｏｕ　ｃａｎ　ｔｕｒｎ　ｏｎ　ｆｕｚｚ　ｍａｔｃｈ

**Comment by lhrkkk** [comment]
Thanks, I find mistype the (setq helm-M-x-fuzzy-match t)  to  (setq helm-m-x-fuzzy-match t), with the upcase M to lowercase m. I'm sorry for my fault. You can close this issuse. *^_^*
