### ISSUE TITLE
不使用花括号把single-substatement括起来的话，不能正确缩进。

### ISSUE THREAD

**Issue by firnsan** [redguardtoo/emacs.d#275]
（c/c++）如果的if/while/for的子语句只有一条，不加花括号的话，不能正确缩进，用M-x indent-region也不行：
```
if (1)  
i++;
```

加了花括号可以缩进：
```
if (1)  {
    i++;
}
```
 
我的解决方法是用c-set-style明确指定风格，才可以正确缩进。
不知道你用的是什么c-style呢?

**Comment by redguardtoo** [comment]
看一下，虽然我一直用花括号的。

**Comment by redguardtoo** [comment]
check http://blog.binchen.org/posts/ccjava-code-indentation-in-emacs.html
the style2, it's not bug. it's intentional setup.

**Comment by Stumble** [comment]
Hi Chenbin,

我觉得这应该是一个bug，@firnsan的意思应该是在没有花括号时候，不能在缩进一个TAB的距离，这个对于不带花括号的情况来说，应该是不正确的，除非说给就算只有一行的if/while/for等也加上花括号。

**Comment by firnsan** [comment]
注释掉
(fix-c-indent-offset-according-to-syntax-context 'substatement 0)
可以修复。

其实，我发现用substatement-open 0 就可以实现你说的style2。你的配置里也有的：


  48  ;if (0)      becomes     if (0)

  49  ;    {                          {

  50  ;       ;                           ;

  51  ;    }                          }

  52  (c-set-offset 'substatement-open 0)

2015-03-20 9:25 GMT+08:00 chen bin <notifications@github.com>:
