### ISSUE TITLE
how to add flycheck in emacs

### ISSUE THREAD

**Issue by dzhwinter** [redguardtoo/emacs.d#276]
package-refresh-content
package-install flycheck
It says 'package 'let alist 1.0.1 is unavaliable'. 

I checked  this package owner on github.
There is an issue:
"This is a known issue which relates to a big refactoring of flycheck. All packages dependent from flycheck must be recompiled. The easiest way to do it is to wipe out your elpa directory.

source: flycheck/flycheck#524"
which says need to re-compile the dependency packages.
how to solve it? Does these packages in your emacs.d directory are the latest ones?

**Comment by redguardtoo** [comment]
`M-x list-packages`, remove its dependencies, then install flycheck.

如果你读过我的“一年成为emacs高手一文”，可以看到我的第一选择是flymake，原因就是诸如此类的问题。

**Comment by dzhwinter** [comment]
多谢回复。emacs GUI版本常常假死，使用terminal还没出现这个问题。 TERM=xterm-256color emacs -nw 加在哪里好呢？在zshrc里alias='''不起作用

**Comment by redguardtoo** [comment]
ｅｍａｃｓ版本，　操作系统，否则无法判断假死问题。

ｚｓｈｒｃ有自己的语法的吧，我没用过。

**Comment by dzhwinter** [comment]
emacs 24.4.1
OS: ubuntu 14.04 x64 
现象：开启emacs --daemon,  emacsclient -c在c++mode中写代码，偶尔会发生所有窗口僵死的现象，有时能自动恢复过来。推测是daemon进程可能出问题。
博主是如何启动emacs的呢？ 每次都是在终端中 “TERM=xterm-256color emacs -nw 编辑的文件”启动吗？



dzhwinter@gmail.com
 
From: chen bin
Date: 2015-03-26 11:09
To: redguardtoo/emacs.d
CC: dzhwinter
Subject: Re: [emacs.d] how to add flycheck in emacs (#276)
ｅｍａｃｓ版本，　操作系统，否则无法判断假死问题。
ｚｓｈｒｃ有自己的语法的吧，我没用过。

**Comment by redguardtoo** [comment]
我不用daemon，装了插件后不稳定，很久以前的事了，记不清是插件的原因的还是emacs的原因。
zsh可以设alias的，自己搜一下。

**Comment by gttiankai** [comment]
如果不用 daemon的话 ,感觉现在emacs 的启动速度太慢了! 请问有什么好的方式吗?

**Comment by redguardtoo** [comment]
为什么要关闭ｅｍａｃｓ？

**Comment by dzhwinter** [comment]
服！ 这是最佳答案！



dzhwinter@gmail.com
 
From: chen bin
Date: 2015-03-26 12:21
To: redguardtoo/emacs.d
CC: dzhwinter
Subject: Re: [emacs.d] how to add flycheck in emacs (#276)
为什么要关闭ｅｍａｃｓ？

**Comment by redguardtoo** [comment]
如果你想在emacs中快速打开文件，见http://blog.binchen.org/posts/how-to-do-the-file-navigation-efficiently.html

在Emacs中我已设定M-y为从剪贴板中粘贴，当当前焦点在mini-buffer中，这大概是世界上最快的方案了。

**Comment by redguardtoo** [comment]
I added lots of commits to improve startup performance. It's not magic, just use lazy load and autoload aggressively, check my blog, I've written many post about this subject.

For example:
41ea497 optimize startup (Chen Bin)

**Comment by dzhwinter** [comment]
Thanks for this commits and your time! 



dzhwinter@gmail.com
 
From: chen bin
Date: 2015-03-27 14:16
To: redguardtoo/emacs.d
CC: dzhwinter
Subject: Re: [emacs.d] how to add flycheck in emacs (#276)
I added lots of commits to improve startup performance. It's not magic, just use lazy load and autoload aggressively, check my blog, I've written many post about this subject.
For example:
41ea497 optimize startup (Chen Bin)
