### ISSUE TITLE
snippets 无法使用

### ISSUE THREAD

**Issue by imtxc** [redguardtoo/emacs.d#277]
在 .c, .py, .cpp 文件中，无法使用 snippets 补全功能， 例如在 a.cpp 文件中输入 fori 按 tab 无效.
`C-h k TAB` 结果：
```
TAB runs the command c-indent-line-or-region, which is an interactive
compiled Lisp function in `cc-cmds.el'.

It is bound to TAB, <menu-bar> <C++> <Indent Line or Region>.
```

**Comment by redguardtoo** [comment]
f8655bc yasnippet can also use TAB (Chen Bin)

personally I always use `M-j`. To many plugins use TAB key.
