### ISSUE TITLE
在 .c 文件中没有加载 helm-gtags

### ISSUE THREAD

**Issue by imtxc** [redguardtoo/emacs.d#278]
在 .c 文件中，需要手动加载 helm-gtags

**Comment by redguardtoo** [comment]
helm-gtags is fine, it's just c-eldoc not loaded properly

9a9ea17 require c-eldoc when necessary (Chen Bin)

**Comment by imtxc** [comment]
使用最新的配置，问题依然存在, 在 .c 文件中按 M-t 执行的是 subword-transpose ARG 而不是 helm-gtags-find-tag

**Comment by redguardtoo** [comment]
you need assign hotkey by yourselves.  I didn't create any new hotkey.
or you can turn off subword-mode in init-misc.el

I think the best way is to use evil and evil-leader.

**Comment by imtxc** [comment]
原因应该还是没有自动加载 helm-gtags-mode 的原因， 执行 `M-x helm-gtags-find-tag` 会提示 
```
Symbol's function definition is void: helm-gtags-find-tag
```
错误，在手动执行了 `M-x helm-gtags-mode` 之后就会正常，使用 `M-t` 或者 `M-x helm-gtags-find-tag` 都没有问题.

**Comment by redguardtoo** [comment]
helm and helm-gtags is locked in `site-lisp/`, so make sure you didn't install helm by yourself

**Comment by imtxc** [comment]
我是直接 git clone 你的 emacs.d, 然后 `http_proxy=http://127.0.0.1:8118 emacs -nw` 的，没有进行过任何自定义的配置.

**Comment by redguardtoo** [comment]
emacs version? os ?

**Comment by imtxc** [comment]
GNU Emacs 24.4.1, archlinux x86_64

**Comment by redguardtoo** [comment]
Sorry, I double checked my gtags setup in init-evil.el, actually I'm using ggtags.el which is better than helm. use ggtags.el instead, pls study my init-evil.el

I will remove helm-gtags-mode.
