### ISSUE TITLE
clang parse error

### ISSUE THREAD

**Issue by dzhwinter** [redguardtoo/emacs.d#279]
failed with error 1:
/usr/bin/clang -fsyntax-only -Xclagn -code-completion-macros -x c++ -I/home/dzh/Downlaods/caffe/include/ -I/usr/local/include
a just add clang-arguments as your suggestion in README file.  I  changed nothing about company mode.
But It can not really parsing my project head file and get the right completion.

I check the company-mode repo owner answer in his issue list of  
https://github.com/company-mode/company-mode/issues/80

 still not work.

emacs version is 24.3.1
clang 3.4
os. ubuntu 14.04

**Comment by redguardtoo** [comment]
I said  "assign reasonable value into company-clang-arguments"  in README. If you've already done this and you are sure that ALL the header files you project required exists in "/home/dzh/Downlaods/caffe/include/", then run the command line /usr/bin/clang -fsyntax-only -Xclagn -code-completion-macros -x c++ -I/home/dzh/Downlaods/caffe/include/ -I/usr/local/include yourcppfile.cpp" in shell and try to fix your syntax error in that yourcppfile.cpp

**Comment by liangyaozhan** [comment]
感觉现在配置clang的company-clang-arguments不是很方便，如果能在.dir-local.el里指定就好了，不知道能不能这样做呢？

**Comment by dzhwinter** [comment]
你写的很棒的插件cpputil-cmake 可以自动定义clang-complete-args 这个参数。如果自己手动设定参数，每次新添加一个头文件，必会出错。然后 /usr/bin/clang -fsyntax-only -Xclagn -code-completion-macros -x c++ -I/home/dzh/Downlaods/caffe/include/ -I/usr/local/include yourcppfile.cpp  这活真干不下去了。尤其是c++ 多重继承下去，没补全真的会吐血的。
现在是每个工程先把依赖的文件写到cmakelist 的add_library里， M-x cpputil-recompile ，然后自动补全就好了。还有更简洁的办法吗？


dzhwinter@gmail.com
 
From: chen bin
Date: 2015-04-02 21:22
To: redguardtoo/emacs.d
CC: dzhwinter
Subject: Re: [emacs.d] clang parse error (#279)
I said "assign reasonable value into company-clang-arguments" in README. If you've already done this and you are sure that ALL the header files you project required exists in "/home/dzh/Downlaods/caffe/include/", then run the command line /usr/bin/clang -fsyntax-only -Xclagn -code-completion-macros -x c++ -I/home/dzh/Downlaods/caffe/include/ -I/usr/local/include yourcppfile.cpp" in shell and try to fix your syntax error in that yourcppfile.cpp

**Comment by redguardtoo** [comment]
`(setq cppcm-extra-preprocss-flags-from-user '("-I/usr/src/linux/include" "-DNDEBUG"))` 由用户手动指定的flag和头文件目录,cpputils-cmake会把自动扫描得到的信息和这个flag中信息合并.

手动添加头文件后,compile,然后`M-x cppcm-reload-all`就行了.这不是什么问题吧,你新建任何头文件,必然要重新编译一遍.

cpputils-cmake只是告诉第三方插件头文件的目录在哪里,实际扫描都是第三方插件做的,

我用cpputills-cmake开发过大型程序,没有任何问题.你的难点在哪里?

**Comment by dzhwinter** [comment]
补全过程我理解应该是没有错。clang提供词法解析，company做为前端显示出来。本来需要手动设定company -clang-args这个参数，现在有cpputils-cmake扫描生成的cmakeFiles里的flags和include，设定前面那个参数。
我现在在别人的框架下开发程序。依赖的文件只有系统库，这个框架的库。这个框架是auto configure 构建的。没有CMakeLists.txt。
于是我分别把所有的cpp，hpp, .h .cu .c 等文件添加到一个add_library。然mkdir build. make。
我的问题上个截图吧

**Comment by dzhwinter** [comment]
this computer has no chinese input. just paste some screenshot.
╭─dzh@G406  ~  
╰─$ clang++ -v -x c++ /dev/null -fsyntax-only  
and i get this.

 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward
 /usr/local/include
 /usr/lib/llvm-3.5/bin/../lib/clang/3.5.0/include
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.

**Comment by redguardtoo** [comment]
手动设定cppcm-extra-preprocss-flags-from-user

**Comment by dzhwinter** [comment]
chen,
Thanks for your time!

this is my setup of my init.el.
(setq company-clang-arguments '(                                                                                                          
=167                                "-I/usr/local/include"                                                                                    
=168                                "-I/usr/include/clang/clang3.4/include"                                                                   
=169                                "-I/usr/include/x86_64-linux-gnu"                                                                         
=170                                "-I/usr/include/c++/4.8"                                                                                  
=171                                "-I/home/dzh/Downloads/caffe/include"                                                                     
=172                                ))                                                                                                        
=173(Setq cppcm-extra-preprocss-flags-from-user '(                                                                                            
=174                                "-I/usr/local/include"                                                                                    
=175                                "-I/usr/include/clang/clang3.4/include"                                                                   
=176                                "-I/usr/include/x86_64-linux-gnu"                                                                         
=177                                "-I/usr/include/c++/4.8"                                                                                  
=178                                "-I/home/dzh/Downloads/caffe/include"                                                                     
=179                                "-DNDEBUG"                                                                                                
=180                                ))                                                                                                        
=181(setq cppcm-include-dirs '(                                                                                                               
=182                           "-I/usr/local/include"                                                                                         
=183                           "-I/usr/include/clang/clang3.4/include"                                                                        
=184                           "-I/usr/include/x86_64-linux-gnu"                                                                              
=185                           "-I/usr/include/c++/4.8"                                                                                       
=186                           "-I/home/dzh/Downloads/caffe/include"))       

But i run M-x cppcm-reload-all command.
The Compile-Log output is
cppcm-scan-info-from-cmake called => /home/dzh/Downloads/caffe_video /home/dzh/Downloads/caffe_video/docs/images /home/dzh/Downloads/caffe_vi\
deo/build/                                                                                                                                    
cppcm-scan-info-from-cmake called => /home/dzh/Downloads/caffe_video /home/dzh/Downloads/caffe_video/docs/stylesheets /home/dzh/Downloads/caf\
fe_video/build/                                                                                                                               
cppcm-scan-info-from-cmake called => /home/dzh/Downloads/caffe_video /home/dzh/Downloads/caffe_video/docs/tutorial /home/dzh/Downloads/caffe_\
video/build/                                                                                                                                  
cppcm-scan-info-from-cmake called => /home/dzh/Downloads/caffe_video /home/dzh/Downloads/caffe_video/docs/tutorial/fig /home/dzh/Downloads/ca\
ffe_video/build/                                                                                                                              
cppcm-scan-info-from-cmake called => /home/dzh/Downloads/caffe_video /home/dzh/Downloads/caffe_video/examples /home/dzh/Downloads/caffe_video\
/build/                                                                                                                                       
CMakeLists.txt=/home/dzh/Downloads/caffe_video/examples/CMakeLists.txt                                                                        
possible-targets=((add_executable ${name}))                                                                                                   
cppcm--query-var-from-lines called                                                                                                            
Failed to create Makefile for flymake. Continue anyway.                                                                                       
cppcm-include-dirs=nil                                                                                                                        
progn: End of buffer                                                                                                                          
progn: Beginning of buffer [7 times]                                                                                                          
Quit  

look , the cppcm-include-dirs is nil !!  i can't understand.

**Comment by redguardtoo** [comment]
you should set cppcm-extra-preprocss-flags-from-user instead company-clang-arguments instead, because cpputils-cmake will override company-clang-arguments

what's the value of ${name}, cpputils-cmake use regualar expression, so it has limited power to get the actual value of ${name} but the actual value of ${name} is needed

**Comment by redguardtoo** [comment]
在我的cpputils-cmake，有一个example project，都是标准c++写的，你可以尝试加入第三方库的代码（最简单的比如unix c 的printf之类），然后设置cppcm-extra-preprocss-flags-from-user，以你的配置测试一下是否OK

**Comment by dzhwinter** [comment]
i use irony-mode and set .clang_complete instead this error. that arguments annoy me for two weekend.  I love emacs, but sometimes it sucks me.  I'm doubt my waste time on that. I have followed you configuration near 1 year. But I want to quit emacs sometime.  Chen.

**Comment by redguardtoo** [comment]
If you do the C++ development on windows only, I suggest VisualStudio instead. I use VisualStudio plus Vim.

If you are on Linux, Emacs plus my setup is much better than any IDE (QTCreator, for example)

On OSX, Emacs is fine, but I don't think it can handle obj-c.

My point is to be practical on this issue. Enjoy the benefit you can take from Emacs (org-mode, for example).
