### ISSUE TITLE
windows 下使用 git clone 时，出现 clone 成功但 checkout 错误

### ISSUE THREAD

**Issue by dujnan** [redguardtoo/emacs.d#280]
命令：git clone https://github.com/redguardtoo/emacs.d.git .emacs.d
报错：
error: unable to create file snippets/ruby-mode/: (Invalid argument)
Checking out files: 100% (1240/1240), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
原因是 windows 系统的文件名中不能使用英文冒号":"。直接下载压缩包解压时，会把文件"snippets/ruby-mode/:"重命名为"snippets/ruby-mode/_"。

**Comment by redguardtoo** [comment]
b06d379 windows compatible file name (Chen Bin)
