### ISSUE TITLE
关于flymake自动生成的filename_flymake.c文件

### ISSUE THREAD

**Issue by gttiankai** [redguardtoo/emacs.d#281]
使用您最新的配置文件时, 我发现一个问题就是flymake自动生成文件.

比如打开一个 test.c 文件,emacs 会自动进行语法检查,然后生成一个test_flymake.c文件,我想问一下为什么要生成这样一个文件呢? 这样做有什么好处?
如果我不想生成这样一个文件该怎么做呢?
(ps; 我已经找到了init-cc-mode.el中的my-c-mode-hook函数,发现该函数就是进行新建文件的函数)

os:ubuntu 12.04 64位
emacs: emacs 24.3.1

**Comment by redguardtoo** [comment]
it's created by flymake.

you can disable flymake if you don't like it in `my-c-mode-hook`, it's used for syntax check.
