### ISSUE TITLE
emacs --no-window-system shotkey error

### ISSUE THREAD

**Issue by dzhwinter** [redguardtoo/emacs.d#282]
emacs --no-window-system mode 
下大键盘以外所有按键都映射M-[  都映射到paredit-wrap-square，在paredit.el中定义。
例如按Ctrl+up 键GUI下查找上一条命令，显示出来的是M-[。

Ctrl+up Ctrl+down 主要用于shell mode 中查找上一条，下一条命令。这看到同样的三个问题，博主说从不用小键盘。shell mode这两个按键有什么好替代办法？

另有一个小问题。在shell mode中使用ipython 有一点别扭，不能提示成员。相比于 terminal 还是要差一些。

以前一直是使用vim+tmux。切换到emacs之后一直使用分割窗口+shell mode 还是不太舒服。博主有什么好办法？

**Comment by dzhwinter** [comment]
补充一下，第一个问题不是快捷键占用造成的。因为无论Ctrl+up Ctrl+down Ctrl+pageup Ctrl+pagedown等等按键都会显示出来的是M-[。已经尝试过global define key。不起作用。

**Comment by redguardtoo** [comment]
`C-p` or `M-p`, 这在emacs中是约定俗成的.

**Comment by dzhwinter** [comment]
我也使用evil， C-p or M-p绑定的是evil-paste。 
在检查terminal设置前我想问问，博主平时操作习惯是怎样的？ 我在普通模式中我的常用hjkl 移动。编辑时候配合使用C-a C-e 。基本也不用方向键。但是一旦到shell mode中，常常会用到上一条命令。因为在GUI模式下绑定了backward-paragraph函数，非常好用。C-up C-up这个键还是需要的。但是终端中就不能用了。而且之前说过，小键盘上按键配合C 和M 都被映射成了M- [。我自己重新绑定backward-paragraph函数可能和其他按键冲突。
博主平时如何切换终端和emacs， 用shell mode吗？ 这两个键有什么好的替代办法？

**Comment by redguardtoo** [comment]
I use emacs-nox, so never has this issue.
