### ISSUE TITLE
行号和正文显示距离是否可以设置

### ISSUE THREAD

**Issue by imtxc** [redguardtoo/emacs.d#284]
![scrot](https://cloud.githubusercontent.com/assets/1161807/7082511/326a5cf4-df88-11e4-9f1a-4d304c65e33d.png)
![scrot](https://cloud.githubusercontent.com/assets/1161807/7082533/6d9576a6-df88-11e4-89ce-e5f70a13d006.png)

如图中，在 xterm + tmux 中使用 emacs 24.4, 行号距离地一个字符特别近， 是否可以设置这个显示距离？
或者在默认状态关闭行号显示？
ps: 在使用 X 的时候行号和正文有一个竖行分割，如图
![scrot](https://cloud.githubusercontent.com/assets/1161807/7082564/c7919004-df88-11e4-97c0-9f8e15f0640a.png)

**Comment by redguardtoo** [comment]
check `linum-format`, you could insert an extra space at the right side.
