### ISSUE TITLE
set-cursor-color fail

### ISSUE THREAD

**Issue by remerci** [redguardtoo/emacs.d#285]
在ubuntu上cursor颜色是正常的，也可以通过set-cursor-color设置。
但在单位的win xp上，cursor是黑色的，在solarized theme下经常找不到光标。set-cursor-color也不起作用。我用emacs -q，不带设置的emacs是白底黑色cursor，并且可以用set-cursor-color设置新颜色。
在配置文件中也找不到关于设置cursor颜色不起作用的配置，求助！

**Comment by redguardtoo** [comment]
evil的问题,应该早就修复了.

```lisp
;; @see https://bitbucket.org/lyro/evil/issue/342/evil-default-cursor-setting-should-default
;; cursor is alway black because of evil
;; here is the workaround
(setq evil-default-cursor t)
```

**Comment by remerci** [comment]
thanks, 问题解决！
