### ISSUE TITLE
Obselete macro flet in init-ido.el

### ISSUE THREAD

**Issue by LesleyLai** [redguardtoo/emacs.d#286]
Hello Chen. After I cloned and used your configuration I had noticed a message which said "*.emacs.d/lisp/init-ido.el: \`flet' is an obsolete macro (as of 24.3); use either \`cl-flet' or \`cl-letf'.*"

Then I replaced *flet* with *cl-flet*. But after that *ido-imenu* did not work and just output "*cond: Symbol's function definition is void: addsymbols*".

Do you know why that happened and how can I fix it? Or just keep using *flet*? Thanks.

OS: Ubuntu 14.4 
Emacs: 24.5.2 GTK+ version

**Comment by redguardtoo** [comment]
keep using flet, emacs23 need this, emacs24 will ignore it and show some warning.
