### ISSUE TITLE
emacs 调用gdb调试C语言程序问题

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#287]
gdb调试C语言
1、在"input/output"窗口输入完之后，会在该窗口自动显示刚才输入的数据，这样感觉有点乱
2、ctrl+d，是EOF信号，但在"input/output"却不能识别，如果直接在终端使用gdb就可以

**Comment by redguardtoo** [comment]
1. don't know how to handle it
2. Try `C-c C-c`
