### ISSUE TITLE
"use improved flymake"

### ISSUE THREAD

**Issue by LesleyLai** [redguardtoo/emacs.d#289]
OS:Ubuntu 14.4
Emacs: 24.5.2

Hi, Cheng. After I synchronized with your repo my emacs' starting speed became very slow (freezed about 2 minutes each time). No error message are generated even when I used "--debug-init".  I found the problem rooted in site-lisp/flymake/flymake.el you added in 855140ac5cade72b04ad08126e7895b1e5605b45. I deleted this file and my emacs return back to normal.

I am not sure the cause of problem is emacs 24.5, my personal environment or other stuff. Can you give me some advice? Thanks.

**Comment by redguardtoo** [comment]
what's your major-mode? what file you are editing?

I added that file for the intention to improve the performance of flymake :(

**Comment by LesleyLai** [comment]
1 What does "my major-mode" mean? I edit different files in different major mods.

2 I added some customize stuff(eg. key binding). Remove those file cannot solve problem. Other modifications are all in my personal branch.

**Comment by redguardtoo** [comment]
my emacs startup in one second. could you reproduce the issue and give more details?

**Comment by LesleyLai** [comment]
1 Recover that file can reproduce the problem. 

2 Sorry, I cannot give you more detail because there are not any error message. I am now downloading 24.3 and I will try if the problem exist in that version.

**Comment by LesleyLai** [comment]
Emacs-24.3.1 do not have any problem. : - (

**Comment by redguardtoo** [comment]
send the bug report to the emacs developers. That's normal,

**Comment by LesleyLai** [comment]
My fault! The problem have nothing to do with emacs versions. But because I have connected to vpn when I tested it with emacs 24.3. When I connect to vpn my emacs startup less than a second. When I disconnect vpn emacs startup time becomes 128 seconds. I'm glad I have not send the bug report to emacs teams yet.

Anyway, does flymake.el try to do something which may upset the GWF?

**Comment by redguardtoo** [comment]
no, nothing,

**Comment by LesleyLai** [comment]
I remove that file as a expedient. Thank you spend so much time on me.
