### ISSUE TITLE
win xp 下 ipython 调用问题

### ISSUE THREAD

**Issue by remerci** [redguardtoo/emacs.d#290]
默认用的python自带解释器， 想用ipython，C-c C-z时输入c:\anaconda\scripts\ipython.exe，可以调出，但没有提示符，功能上也不太正常。搜了下，.emacs.d中没有ipython.el，把linux下emacs自带的ipython.el拷贝过来，(require 'ipython)提示无法加载。
有什么办法解决么？

**Comment by redguardtoo** [comment]
Read Emacswiki ipython section, looks it's obsolete,
`Various Python Interpreters`

I don't use ipython these days, so I don't know how to setup it.

At least pyflakes and ananconda-mode is already setup, Could you use cygwin?
