### ISSUE TITLE
C 语言程序缩进

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#291]
刚装了最新的配置后，发现按Tab，不会自动缩进，错误提示 Lisp nesting exceeds max-lisp-eval-depth

**Comment by redguardtoo** [comment]
我基本上没有改过任何默认配置,这是yasnippet占用了这个快捷键.

另外一点提示,我写代码从不手动缩进,会打断思路,写完在整个文件indent,在evil中就是`gg=G`

**Comment by ly0303521** [comment]
还有一个问题就是，不论我选什么模式，比如cc-mode，最后排版的时候，if else语句会这样
if(a==1)
printf("...");
else
printf("...");
本来printf语句应该要缩进才对。
之后我在配置中添加如下语句才是正确的，不知道为什么
(add-hook 'c-mode-common-hook '(lambda()
                           (c-set-style "cc-mode")))

**Comment by redguardtoo** [comment]
because I always write
```c
if(a==1)
{
  printf("");
}
```
instead,

search my article "C++/Java indentation emacs blah blah"

**Comment by redguardtoo** [comment]
缩进问题基本解决了，是因为emacs24.4+设置问题。
