### ISSUE TITLE
python interactive error

### ISSUE THREAD

**Issue by dzhwinter** [redguardtoo/emacs.d#292]
将python CC 启动ipython ，执行的执行环境在ipython 中不起作用，没有触发提示，,号总是让emacs很困惑。自己配置过python-mode,  也有这个问题。博主有没有好解决办法？

**Comment by dzhwinter** [comment]
还是询问下博主平时python程序用得多么  博主的python配置已经很赞了，这个属于强迫症。
现在主要想解决的是ipython里能够TAB触发提示就完美了。
问题描述：
python -i  触发没问题
ipython 不能触发
换成anaconda 里的ipython 又可以触发。 但是问题是anaconda里的包不全，自带的自动包管理工具常常找不到我要的包。然后用pip 安装的ipython 又有以上问题

**Comment by redguardtoo** [comment]
如果你要装最新的anaconda包，见readme开头一段，我禁止了所有melpa-unstable上的包（可以手动恢复），因为这个配置稳定性是第一位的。

我现在不用python，你可以咨询anacoda的作者关于ipython的问题。
