### ISSUE TITLE
在debian中启动emacs报错

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#293]
环境：debian 
下载了.emacs.d后启动emacs报错：

Warning (initialization): An error occurred while loading `/home/ydw/.emacs.d/init.el':

File error: Cannot open load file, package

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

根目录下没有.emacs。

请问可能是什么原因？谢谢您的回答。

**Comment by LesleyLai** [comment]
Try `emacs --debug-init'

**Comment by yangdaweihit** [comment]
I had tried doing so, but just it shows that cannot finding ***.el files, but the files are there as usual.

**Comment by redguardtoo** [comment]
`emacs --version`

Please note the latest version of this setup dropped emacs23 support.

**Comment by redguardtoo** [comment]
see http://www.plusastra.com/2012/11/installing-emacs-24-on-debian-wheezy.html
