### ISSUE TITLE
高版本emacs(24/25)中，在写C语言代码时缩进问题

### ISSUE THREAD

**Issue by tylinux** [redguardtoo/emacs.d#294]
就像这样：
![screenshot_2015-04-26_22-17-34](https://cloud.githubusercontent.com/assets/1974874/7337607/57099f8e-ec62-11e4-9edb-9f3a27f7326a.png)
不管左括号是在右边还是下边，回车后都会变成这个样子。。。

**Comment by redguardtoo** [comment]
让我调查一下.

**Comment by redguardtoo** [comment]
和我的配置无关，即使关掉我的设置，还是能重现。

**Comment by redguardtoo** [comment]
bdb5b55 #294 electric-indent-mode should NOT be turned of globally (Chen Bin)

**Comment by tylinux** [comment]
Thanks ~
