### ISSUE TITLE
为什么今天更新了一下，重新编译之后yasnippet用不了了？

### ISSUE THREAD

**Issue by Univerfly** [redguardtoo/emacs.d#298]
菜单栏也没有yasnippet了

**Comment by redguardtoo** [comment]
yasnippet 没有问题,我一直用我的封装my-yas-expand,只有当我按下`M-j`时才开始载入yasnippet,这是为了优化emacs启动速度,

**Comment by Univerfly** [comment]
那对于用emacs快捷键的用户，有什么好的建议？

**Comment by redguardtoo** [comment]
在init-yasnippet.el里已经给my-yas-expand设置了`C-c k`,可以改成你习惯的快捷键。

**Comment by redguardtoo** [comment]
如果你想用原生的yasnippet，不在乎速度的话，insert `(require 'yasnippet)` into anywhere (~/.emacs.d/init.el, or init-yasnippet.el, or custom.el ....)
