### ISSUE TITLE
如何设置中文字体

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#299]
原来一直显示的是仿宋字体，觉得挺不错的。今天不知怎么回事变成了隶书。请问如何设置中英文字体?
![emacs thinkpad-t430u_020](https://cloud.githubusercontent.com/assets/10682606/7440777/7561d5ae-f0fa-11e4-8449-f739540d3c51.png)

**Comment by redguardtoo** [comment]
系统, emacs 版本?

**Comment by yangdaweihit** [comment]
sorry，这几天忙事情。这里没有回复您的帮助。我发现是安装了wps之后产生的问题。后面在init.el里加了一段字体设置的代码:

;;;; FONTS
(set-language-environment 'UTF-8)
(set-locale-environment "UTF-8")
(set-default-font "Dejavu Sans Mono 10")
(if (and (fboundp 'daemonp) (daemonp))
(add-hook 'after-make-frame-functions
(lambda (frame)
(with-selected-frame frame
(set-fontset-font "fontset-default"
'unicode "WenQuanyi Micro Hei Mono 12"))))
;;(set-fontset-font "fontset-default" 'unicode "WenQuanYi Micro Hei Mono 12")
)
(set-fontset-font "fontset-default" 'unicode "仿宋 12"))


但只在一台机器上实现了字体的恢复，另一台也是ubuntu系统，却没有效果。请帮我看看是怎么回事。

**Comment by redguardtoo** [comment]
我都是在console里使用emacs,而且只用wqy字体.

**Comment by yangdaweihit** [comment]
删除了前面的语句，只留了是后一条。汉字一样为仿宋了。

> (set-fontset-font "fontset-default" 'unicode "仿宋 12"))
