### ISSUE TITLE
Company Clang Insert Arguments Save for Future Sessions NOT works.

### ISSUE THREAD

**Issue by liangyaozhan** [redguardtoo/emacs.d#301]
1. M-x customize
2. Search clang
3. Toggle "Company Clang Insert Arguments" ==> on
4. State ==> Save for Future Sessions

resart emacs, it is still in 'off' state.

**Comment by redguardtoo** [comment]
just `(setq company-clang-insert-arguments t)` in .emacs, besides, it's already true by default.

**Comment by liangyaozhan** [comment]
ok, thanks.
