### ISSUE TITLE
Real cl-lib shadowed by compatibility cl-lib?

### ISSUE THREAD

**Issue by xiaoxinyi** [redguardtoo/emacs.d#302]
Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50autoconf.el (source)...done
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
Loading /etc/emacs/site-start.d/50global.el (source)...done
<code>Real cl-lib shadowed by compatibility cl-lib? (/home/kg/.emacs.d/lisp/cl-lib.el)
cl-letf already defined, not rebinding
`flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.</code>
Loading /home/kg/.emacs.d/site-lisp/helm/helm-autoloads.el (source)...done
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a valid place expression")
Loading /home/kg/.emacs.d/.session...done
No desktop file.
Flymake unable to run without a buffer file name
Starting new Ispell process [aspell::default] ...
For information about GNU Emacs and the GNU system, type C-h C-a.
Loading /home/kg/.recentf...done
Cleaning up the recentf list...done (0 removed)
kefreq data saved into ~/.emacs.keyfreq
Complete, but not unique
Making completion list...
Complete, but not unique
byte-code: Beginning of buffer [4 times]

**Comment by redguardtoo** [comment]
that's just some warning message you can ignore.

the cl-lib.el exists because I need support emacs23 ages ago. Since emacs23 support is dropped, I will remove that file.

10e58ac remove emacs23 legacy el files (Chen Bin)
