### ISSUE TITLE
org-mode 表格中的单元格合并怎么做。如图。

### ISSUE THREAD

**Issue by xiaoxinyi** [redguardtoo/emacs.d#304]
![org](https://cloud.githubusercontent.com/assets/8276101/7519730/8db5a7a2-f514-11e4-82ff-bdfb704da165.png)

**Comment by standino** [comment]
还有这高级用法？

**Comment by redguardtoo** [comment]
I don't know, ask org-mode guys and englighten me.

**Comment by dzhwinter** [comment]
use excel instead !!! crazy guy
