### ISSUE TITLE
org-mode 下提示 “No images to display inline”

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#305]
想要用org mode做笔记插入图片`C-c C-l`插入链接，
链接`[[file:~/Pictures/Screenshot from 2015-04-22 10:44:25.png][test]]`
然后显示了test，单击链接可以显示图片
![screenshot from 2015-05-10 16 16 49](https://cloud.githubusercontent.com/assets/1150493/7553529/fc814084-f72f-11e4-9f29-eba52b045554.png)
但是按照官网的说法`C-c C-x C-v` 提示说“No images to display inline”
主要是想图片能显示在文本中间，而不是单独需要查看显示
已经尝试了`iimage-mode` 打开的模式还是没显示出来。这点在我另一个mac上倒是显示出来了，不过那个emacs 没有用博主的配置。

**Comment by zarzen** [comment]
把link的description删了就好了…… 不懂诶

**Comment by redguardtoo** [comment]
org-mode我没改过,就是用编辑器自带的.

**Comment by zarzen** [comment]
@redguardtoo 是我用法不对。
