### ISSUE TITLE
如何启用smart-compile？

### ISSUE THREAD

**Issue by molisiye** [redguardtoo/emacs.d#306]
你好！很感激你提供的这么好的emacs配置文件。也不知道用这种方式向您请教是否合适！如有不妥，请见谅！
我想问下，如果我要使用smart-compile来实现一键编译python单文件，应该怎么设置？
我刚开始用emacs24.5才2天，希望能得到您的帮助！我使用的系统是windows8.1。

我在.emacs.d/lisp下建了个init-smart-compile.el，内容如下：
```lisp
(autoload 'smart-compile nil t)
(global-set-key (kbd "<f9>") 'smart-compile
(provide 'init-smart-compile)
```

**Comment by redguardtoo** [comment]
why python need compiling? Run the py and it's automatically compiled into *.pyc
