### ISSUE TITLE
auctex插入宏的问题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#307]
在加入了auctex插件后其它功能都正常使用，但在插入宏时却出现了问题。
插入宏的方式是：
C-c Ret

在回显区提示：Macro (default ...): \ 
输入date Ret
提示： Date (default 2015/05/15):
输入 Ret
结果，命令参数却置于命令之前，如图所示。
![selection_004](https://cloud.githubusercontent.com/assets/10682606/7652149/d7b84116-fb3b-11e4-9001-bbae3459d8ea.png)

我将Auctex的配置命令单独放在.emacs文件中加载后该问题消失，故判断可能是之前的某个设置导致了这个结果。请帮我看看哪里出了问题。将auctex配置部分移至文件前面也未能解决问题。

**Comment by yangdaweihit** [comment]
刚发现在启动emacs后第一次执行插入宏或插入环境时，选项可以显示在正确位置，但再次执行时就会出现上述问题。

**Comment by yangdaweihit** [comment]
又找到一条线索：将~/.emacs.d/init.el持贝为~/.emacs后启动，问题消失。

**Comment by yangdaweihit** [comment]
问题初步得到了解决，和配置文件没关系，是由于我在加载matlab-mode的插件中使用的语句有问题，细述如下。

原增加路径的语句为：
> (add-to-list 'load-path "~/.emacs.d/matlab-emacs/matlab-emacs" )

修改为：
> (add-to-list 'load-path "/home/yangdawei/.emacs.d/matlab-emacs/matlab-emacs" )

再次启动emacs后问题消失。但不明白这是什么原因。

**Comment by redguardtoo** [comment]
在window下要设置HOME环境变量,*nix没有问题.

**Comment by yangdaweihit** [comment]
刚才又试了下，我之前的方法还是不行，只要添加了这一行就是不行。无论是：

> (add-to-list 'load-path "/home/yangdawei/.emacs.d/matlab-emacs/matlab-emacs" )

还是:

> (file-truename "~/.emacs.d/matlab-emacs/matlab-emacs")

**Comment by yangdaweihit** [comment]
发现原来问题出在空闲时间加载宏包之后，不清楚具体问题出在哪里，但注释这一段代码后问题消失了。

; {{ idle require other stuff
;(setq idle-require-idle-delay 3)
;(setq idle-require-symbols '(init-misc-lazy
;                             init-which-func
;                             init-fonts
;                             init-hs-minor-mode
;                             init-stripe-buffer
;                             init-textile
;                             init-csv
;                             init-writting
;                             init-elnode
;                             init-doxygen
;                             init-pomodoro
;                             init-emacspeak
;                             init-artbollocks-mode
;                             init-semantic))
;(idle-require-mode 1) ;; starts loading
;; }}

**Comment by yangdaweihit** [comment]
我在stackexchange 上也提交了问题，受回答启发，找到了引起问题的插件为init-misc-lazy，当不加载该项时则没有问题。
http://tex.stackexchange.com/questions/245235/why-the-option-label-are-always-put-in-before-command-in-auctex-mode-and-how-to?noredirect=1#comment582949_245235

**Comment by yangdaweihit** [comment]
void main()
     adsfsadf

**Comment by ufengger** [comment]
@yangdaweihit 
这是pointback-mode的问题。并且pointback-mode也会令cdlatex出现严重的问题，可以在你的auctex设置中把pointback-mode关掉。

```elisp
(add-hook 'LaTeX-mode-hook
  (lambda ()
    (pointback-mode -1)))
```

**Comment by redguardtoo** [comment]
thanks, I will update my setup.
