### ISSUE TITLE
和中文输入法冲突问题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#308]
Emacs的C-SPC和中文输入法冲突是个很典型的问题。网上有很多种解决办法。我提交现在采用的方法，请问是否有更合理的解决方法？

(1) 在init.el中添加语句注销C-SPC

> (global-set-key (kbd "C-SPC") nil)

这样做之后，仍然无法激活中文输入法（我用的是fcitx）

(2) 在.bashrc中添加emacs别名

> alias emacs='LC_CTYPE=zh_CN.utf8 emacs'

再次启动emacs后即可启动fcitx了。这种做法有两个问题：

+ C-SPC标记功能被禁用了；

+ 在.bashrc中添加别名后，当使用root操作时，emacs的别名不能使用。当然，也可以在其它脚本启动配置中定义别名，但总感觉这样解决不是个办法。

**Comment by redguardtoo** [comment]
我把shift-space设为启动fcitx.

**Comment by yangdaweihit** [comment]
恩，我现在也这样做了。
