### ISSUE TITLE
中文输入法报错

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#310]
C-\ 调用中文输入后， 按a（想打‘啊’出来）结果报错：
`(文件类型错误！ *Chinese-pyim*-617693 的第 11 行没有词条！)`
检查了放在 `~/.eim/py.txt`里包含了a开头的那些词

**Comment by zarzen** [comment]
换了这个人的词库然后就好了：`https://github.com/tumashu/chinese-pyim-bigdict`
另外，项目ReadMe里给出的 `~/.eim/py.txt`示例的url似乎失效了。

**Comment by redguardtoo** [comment]
thanks, I updated the link,
 225a91b update py.txt link (Chen Bin)
