### ISSUE TITLE
How to add the line number and wrap the line in org-mode.

### ISSUE THREAD

**Issue by lijingjiang** [redguardtoo/emacs.d#311]
Dear Mr. Chen.

I have used your emacs configuration for several months, it works pretty well and I like the org-mode especially. Is there anyway to display the line number in the org-mode based on your emacs configuration? And I used the Day-agenda mode frequently (ctrl + [; then ctrl+a a), is there anyway to wrap the line in the Day-agenda mode? Thank you very much!

Yours,
Jingjiang Li

**Comment by redguardtoo** [comment]
check init-linum.el, I turned off it in org-mode.

**Comment by lijingjiang** [comment]
The problem has solved, thank you very much!

Yours,
Jingjiang Li
