### ISSUE TITLE
如果重新clone运行emacs现在似乎缺少一些软件包

### ISSUE THREAD

**Issue by liangyaozhan** [redguardtoo/emacs.d#312]
有些软件包u无法自动找到了。
rm ~/.emacs.d -rvf
cd ~
git clone  https://github.com/redguardtoo/emacs.d.git .emacs.d
emacs
发现有些包无法自动下载了
Warning (initialization): An error occurred while loading `/home/lyzh/.emacs.d/init.el':

File error: http://stable.melpa.org/packages/haskell-mode-13.12.tar, Found

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

emacs --debug-init
Debugger entered--Lisp error: (file-error "http://stable.melpa.org/packages/haskell-mode-13.12.tar" "Found")
  signal(file-error ("http://stable.melpa.org/packages/haskell-mode-13.12.tar" "Found"))
  url-insert-file-contents("http://stable.melpa.org/packages/haskell-mode-13.12.tar")
  package-install-from-archive([cl-struct-package-desc haskell-mode (13 12) "A Haskell editing mode" ((cl-lib (0 5))) tar "melpa-stable" nil nil nil])
  mapc(package-install-from-archive ([cl-struct-package-desc haskell-mode (13 12) "A Haskell editing mode" ((cl-lib (0 5))) tar "melpa-stable" nil nil nil]))
  package-download-transaction(([cl-struct-package-desc haskell-mode (13 12) "A Haskell editing mode" ((cl-lib (0 5))) tar "melpa-stable" nil nil nil]))
  package-install(haskell-mode)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(haskell-mode)
  eval-buffer(#<buffer  *load*-918815> nil "/home/lyzh/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 6621
  load-with-code-conversion("/home/lyzh/.emacs.d/lisp/init-elpa.el" "/home/lyzh/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/home/lyzh/.emacs.d/init.el" nil t)  ; Reading at buffer position 2389
  load-with-code-conversion("/home/lyzh/.emacs.d/init.el" "/home/lyzh/.emacs.d/init.el" t t)
  load("/home/lyzh/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment]
It's fine on my machine. could be network issue, just start from the scratch.

Or you can comment the line from init-elpa.el temporarily.

**Comment by liangyaozhan** [comment]
难道被墙了？

**Comment by redguardtoo** [comment]
Yes, try goagent
