### ISSUE TITLE
About helm-files

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#313]
I hava a problem when i use helm-files with the following operations:
1. M-x helm-buffers-list
2. Choice a buffer item
3. here, i want to rename or other operate with helm-files (example, M-R bound to helm-ff-run-rename-file in helm-files.el). Howerve, i found that, in fact, M-R bound to previous-matching-history-element.

Do you have some suggestions?
Thank you.

**Comment by redguardtoo** [comment]
```lisp
 (define-key helm-map (kbd "C-p")   'helm-previous-line)
 (define-key helm-map (kbd "C-n")   'helm-next-line)
```
?

**Comment by fenxian** [comment]
Yes, C-p / C-n can Forward / Backward a line.
I can choice the object buffer after helm-buffers-list.
But i can't operate the buffer in that environment. For example, i can't rename it.

**Comment by redguardtoo** [comment]
If you re-bind `M-R`, right?

**Comment by fenxian** [comment]
It still doesn't work  after i re-bind it.
In addition, helm-files have many function which can't work well.
Do you use those function?
Do you have a better way to rename or move a file by emacs?

**Comment by redguardtoo** [comment]
Currently I just used wdired to rename files.

But you remind me to search my own git log about helm, so I find my own commit 450726
