### ISSUE TITLE
About global

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#314]
Hi, the version of global is old in ubuntu when we install it by apt-get.
The version 6.2 will be better to work well. 
May be you can have a remind in ReadMe.

Thank you.

**Comment by fenxian** [comment]
The old version have a problem. Sorry, i cann't recurrent it. ..

**Comment by redguardtoo** [comment]
what's the problem of old version of global?

**Comment by fenxian** [comment]
Sorry, i have update it before a long time. I can't give you more detail information.
In my memory, it will have a error information about global in minibuffer.

**Comment by redguardtoo** [comment]
gtags - GNU GLOBAL 5.7.1

tested without any issues.

I only use basic functionality of global:
- env variable "GTAGSPATH"
- jump to definition
- only create tags for C++/Java

**Comment by fenxian** [comment]
I think GNU GLOBAL 5.7.1 have a little problem.
In this version, global: both of -s and -r are not allowed.

The same issue.
https://github.com/leoliu/ggtags/issues/31
