### ISSUE TITLE
Cannot publish org files

### ISSUE THREAD

**Issue by LesleyLai** [redguardtoo/emacs.d#316]
When I tried to publish some org files, I got an error message

     `open-network-stream: make client process failed: connection refused, :name, MozRepl, :buffer, *MozRepl*, :host, localhost, :service, 4242, :nowait, nil

How can I fix this? Or just remove moz-repl(I never use it)? Thanks.

**Comment by redguardtoo** [comment]
warning u can ignore

**Comment by LesleyLai** [comment]
But the publish process is interrupted. It only converts one .org file when I want it publish a whole directory.

**Comment by redguardtoo** [comment]
more information? which commands you use? org version? emacs version? os?

On Wed, Jun 3, 2015 at 9:13 AM, Lesley Lai <notifications@github.com> wrote:

> But the publish process is interrupted. It only converts one .org file
> when I want it publish a whole directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/316#issuecomment-108125999>
> .
>



-- 
help me, help you.

**Comment by LesleyLai** [comment]
I use `org-publish-project`.  My project has two components. The major one uses `org-html-publish-to-html`.

*--debug-init* cannot provide any extra detials. 

There is no problem when I use *emacs -q* and manually evaluate `org-publish-project-alist`.

OS: ubuntu 14.04
emacs: 24.5
Org:8.2.10

**Comment by redguardtoo** [comment]
Can you give a complete sample? I'm unfamilar with org-publish-project

**Comment by LesleyLai** [comment]
``` elisp
(require 'ox-publish)
(setq org-publish-project-alist
      '(

  ("org-blog"
          :base-directory "~/blog/src/"
          :base-extension "org"
          :publishing-directory "~/blog/site/"
          :recursive t
          :publishing-function org-html-publish-to-html
          :headline-levels 4jekyll
          :html-extension "html"
          :section-numbers nil
          :with-toc  nil ;; No default table of contents
          :body-only t ;; Only export section between <body> </body>
    )


    ("org-static-blog"
          :base-directory "~/blog/src/"
          :base-extension "css\\|scss\\|xml\\|js\\|rb\\|png\\|jpg\\|gif\\|svg\\|pdf\\|mp3\\|ogg\\|swf\\|php"
          :publishing-directory "~/blog/site/"
          :recursive t
          :publishing-function org-publish-attachment)

    ("blog" :components ("org-blog" "org-static-blog"))

))

(defun blog-publish nil
  "Publish my blog."
  (interactive)
  (org-publish-project "blog")
  (save-buffers-kill-terminal) ;; exit emacs
)
```

I have to use a Makefile to manually evaluate this file with *emacs -q* now.

**Comment by redguardtoo** [comment]
332a871 tweak all the mode-hooks to be org export friendly (Chen Bin)

This is actually more complicated than it looks. But luckily, I have done some research on this topic half a year ago, http://blog.binchen.org/posts/export-org-file-embedded-with-code-snippets.html

So now a little more tweak is enough.

Now you understand why I suggest NOT to start from scratch in https://github.com/redguardtoo/mastering-emacs-in-one-year-guide

**Comment by LesleyLai** [comment]
Thanks.
