### ISSUE TITLE
max-lisp-eval-depth when open *.c

### ISSUE THREAD

**Issue by Tinker-S** [redguardtoo/emacs.d#318]
My emacs version is 24.5. I can't open *.c file because the minibuffer always show max-lisp-eval-depth (both happens on my macosx and ubuntu os version). I debug into this and found that it's yasnippet config which do the matter. When I delete 'yasnippet-0.8' on 'site-lisp' folder and install the latest version on melpa, everything becomes ok. I have no idea why this happen.

**Comment by redguardtoo** [comment]
got, I will look into this.

**Comment by redguardtoo** [comment]
0f8151e use yasnippet 9 (Chen Bin)
