### ISSUE TITLE
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a valid place expression")

### ISSUE THREAD

**Issue by haikzhang** [redguardtoo/emacs.d#319]
# emacs -nw --debug--init 
报错.
("emacs")
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a valid place expression")
[yas] Prepared just-in-time loading for /root/.emacs.d/site-lisp/yasnippet-0.8.0/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
evil-escape enabled, press "kj" to escape from anything.
Emacs startup time: 3 seconds.
Loading /root/.emacs.d/.session...done
No desktop file.
Loading /root/.emacs.d/company-statistics-cache.el (source)...done
Starting new Ispell process [aspell::default] ...
For information about GNU Emacs and the GNU system, type C-h C-a.
Beginning idle-require
idle-require: require init-misc-lazy
Loading /root/.recentf...done
Cleaning up the recentf list...done (0 removed)
Failed to access ~/.emacs.d/history
Package assoc is obsolete!
idle-require: require init-which-func
idle-require: require init-fonts
idle-require: require init-hs-minor-mode
idle-require: require init-stripe-buffer
idle-require: require init-textile
idle-require: require init-csv
idle-require: require init-writting
idle-require: require init-doxygen
mic-paren caught error (please report): (void-function finish) [2 times]

---------------------------------------
c-mode,c++ - mode  用不了yasnippet
第一次发言，不懂规矩，见谅

**Comment by redguardtoo** [comment]
以修复,升级了yasnippet到9.0
