### ISSUE TITLE
org-capture 无法正常使用

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#321]
定义一个template：

(setq org-capture-templates
  '(("t" "Todo" entry (file "~/.org/gtd.org")
   "* TODO %?\n %T\n %a\n %i\n")
  )
)

打开template光标无法定位，直接打开了整个gtd.org文件，C-c C-k现实如下错误：

org-capture-finalize: Capture process aborted, but target buffer could not be cleaned up correctly

使用emacs24.5, 没有做任何自定义配置

**Comment by albert748** [comment]
我使用了这种方式来调用org-capture会有以上问题:

 '(org-agenda-custom-commands (quote (("c" "org capture" ((org-capture ""))))))

如果是直接使用M-x org-capture就不会有问题。

为什么呢？

我刚使用emacs，希望能够指点一下。。。

**Comment by redguardtoo** [comment]
thanks for asking, I usually keep the plugin's original setup without any modification. In your case, you need setup `org-default-notes-file` before use `org-capture`.

See http://orgmode.org/manual/Setting-up-capture.html#Setting-up-capture

The easiest setup is:
1. add `(setq org-default-notes.org "~/.org/gtd.org")` into ~/.emacs
2. make sure ~/.org/gtd.org actually exist
