### ISSUE TITLE
取消org－mode的自动换行

### ISSUE THREAD

**Issue by lijingjiang** [redguardtoo/emacs.d#322]
您好！最近一直在用org－mode制作表格。但是有些表格的项目比较多，就会出现自动换行的情况。整个表格会变的很难看，不知道怎样才能取消org－mode下的自动换行。

谢谢！

**Comment by redguardtoo** [comment]
```lisp
(defun truncate-lines-setup ()
  (toggle-truncate-lines 1))
(add-hook 'org-mode-hook 'truncate-lines-setup)
```

**Comment by lijingjiang** [comment]
问题已经解决！非常感谢！

**Comment by jain0y** [comment]
我加了，没有起作用啊。

打开org文件的时候，这个message出了，但是org-mode的文件还会自动换行。
Truncate long lines enabled

**Comment by redguardtoo** [comment]
see http://www.emacswiki.org/emacs/TruncateLines
should work in my setup.

**Comment by jain0y** [comment]
Comment (;; setq truncate-lines nil)  work well.
