### ISSUE TITLE
当使用emacs时,浏览上下文会有卡顿,就是上一篇会暂停一会儿,而且有时候会跳跃,特别使用鼠标滑轮浏览效果更明显

### ISSUE THREAD

**Issue by programes** [redguardtoo/emacs.d#323]

**Comment by programes** [comment]
是正常现象么?还是我的电脑问题

**Comment by programes** [comment]
系统是ubuntu 14.04 x64 内存4g

**Comment by redguardtoo** [comment]
what's your major-mode? `C-h v major-mode`

**Comment by programes** [comment]
c-h m  里面没有major-mode

**Comment by programes** [comment]
major-mode is a variable defined in  'C source code'

**Comment by redguardtoo** [comment]
press `C-h v major-mode`, then press return. Besides, give me some sample.

**Comment by programes** [comment]
![screenshot from 2015-07-13 14 27 15](https://cloud.githubusercontent.com/assets/6359325/8643817/6369fc92-296b-11e5-8b76-6047db63aeba.png)

**Comment by liangyaozhan** [comment]
在我这里，发现这个是nvidia的显卡驱动的问题。使用nvidia-340分支能改善这个情况。

**Comment by redguardtoo** [comment]
This is typical in Emacs, it has nothing to do with Emacs setup. It's not show stopper.
