### ISSUE TITLE
error: Package `git-commit-mode-' is unavailable

### ISSUE THREAD

**Issue by LOVEMUSCLE** [redguardtoo/emacs.d#325]
Warning (initialization): An error occurred while loading `/Users/hejing/.emacs.d/init.el':

error: Package `git-commit-mode-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by redguardtoo** [comment]
9e489ff git-commit-mode change name (Chen Bin)
