### ISSUE TITLE
Cannot open load file, no such file or directory, magit-key-mode

### ISSUE THREAD

**Issue by LOVEMUSCLE** [redguardtoo/emacs.d#326]
Warning (:warning): : `lexical-binding' at end of file unreliable
Warning (initialization): An error occurred while loading `/Users/hejing/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, magit-key-mode

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by redguardtoo** [comment]
5361762 remove dependency on magit-key-mode (Chen Bin)
