### ISSUE TITLE
helm mode can't enable .

### ISSUE THREAD

**Issue by mh29110** [redguardtoo/emacs.d#327]
symbol's function definition is void : helm-autoresize-mode 

Emacs version 24.5

**Comment by redguardtoo** [comment]
I''ve locked my helm version by copy its source code into `~/.emacs.d/site-lisp/helm`. So for that version of helm, it should work? do you install the helm from elpa?

**Comment by mh29110** [comment]
this problem was solved when update helm to v2015+ . thanks 

by the way ,i want to know how company-mode works on your config?
i tested in cpp-mode and js2-mode ,there was no auto complete,no auto popup tips . 
and in the init-company No keymap for company-complete .
did i miss something? or just use the M-x company-complete cmd?
