### ISSUE TITLE
Error: No word lists can be found for the language "en_US"

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#328]
使用过程倒是没什么问题，但是看到了Message buffer报了这个错误：
```
Starting new Ispell process aspell with default dictionary...
Error enabling Flyspell mode:
(Error: No word lists can be found for the language "en_US".)
```
环境是cygwin
emacs24.5.1

**Comment by redguardtoo** [comment]
install aspell-en

**Comment by zarzen** [comment]
ok

**Comment by Inc0ns1st3nt** [comment]
Hello, i think I have set my system locale to `en_uk` or something along that line, which cause me to have this issue?
Could you tell how to configure `flyspell` properly so it recognizes and uses the correct locale.
Thanks

**Comment by redguardtoo** [comment]
@Inc0ns1st3nt  , see 746679ad spell check dictionary setup (Chen Bin)
Not sure about `aspell-uk`, I use `aspell-en`, please note `en` is valid value for aspell's `--lang` option.

**Comment by Inc0ns1st3nt** [comment]
Hmm, i seems `aspell-uk` is for Ukrainian.... 🤦‍♂️ Therefore, `aspell-en` being the only package for english should be used instead. After installing the right package, it works fine now...

**Comment by redguardtoo** [comment]
aspell takes 90% work of camel cased word check. My Lisp code does the remaining 10%. Hunspell force the lisp code to do 100% camel cased word check. So hunspell is slower than aspell.
