### ISSUE TITLE
终端下emacs-multi-term环境下怎么看历史？

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#330]
搜到的这个：http://stackoverflow.com/questions/5981151/how-to-scroll-up-in-emacs-ansi-term
提出的`C-c C-j`，提示是未定义的。
回答中还有一个Shift-page up/down的方法倒是可以用，不过不太好用的感觉。
利用`xterm-mouse-mode`倒是可以滚轮滚屏

**Comment by redguardtoo** [comment]
This is a great question. My solution is actually much better than all the other solutions in the world.

I press `C-z` to switch evil-mode

**Comment by zarzen** [comment]
great trick!
