### ISSUE TITLE
如何实现类似ST2下面的goto anything功能？

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#331]
如题

**Comment by redguardtoo** [comment]
helm

**Comment by stevenswong** [comment]
嗯，谢谢你的回答。我用了你的配置有1年多，每天都在用emacs，主要用于c/c++，python, shell开发。你能说下helm使用什么命令完成goto anything的功能？

另外，我最近用了你的最新配置，“{}”配对上有些问题，如：
----->c++代码开始
// 这是一个测试
<------c++代码
我在上面的注释代码前面增加if判断，右边的花括号不会自动输入，即实现效果是这样的：
----->c++代码开始
if (a != b)
{
// 这是一个测试
<------c++代码

**Comment by stevenswong** [comment]
目前的highlight-symbol只能对当前窗口的buffer高亮，有没有能同时对多个窗口高亮的功能?

**Comment by redguardtoo** [comment]
imenu jump in current buffer,
helm-etags-select to find tag (need ctags)

**Comment by stevenswong** [comment]
好的，学习了，谢谢！
