### ISSUE TITLE
使用你的配置打开原来的文件后对齐，缩进变化极大【缩进全部使用的空格，无table】

### ISSUE THREAD

**Issue by xtaens** [redguardtoo/emacs.d#333]
楼主好，我用你的配置打开我以前的文件[在xp下写的]，对齐和缩进怎么变化这么大？

我用默认的配置时直接在末尾显示了一个回车的符号，非常的混乱。

**Comment by redguardtoo** [comment]
具体什么变化?用的什么major-mode

**Comment by xtaens** [comment]
我上传图片了，这里怎么没有显示。

对齐全部乱了。

就只是打开，没有用什么mode，也不知道怎么弄。

**Comment by redguardtoo** [comment]
图片发到我邮箱里 chenbin.sh AT gmail, 另外创建一个最小的例子.

**Comment by xtaens** [comment]
问题找到了。

是我测试的文件中有几个table键造成的，刚才仔细对比了文件，发现在缩进不齐的地方有table键，其他地方没有，所以很对齐。我一直觉得我的文件中无table的，不知哪里复制的代码中可能含了几个。
