### ISSUE TITLE
部分文字出现遮挡

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#335]
![capture](https://cloud.githubusercontent.com/assets/1150493/8927904/58cebfbe-354d-11e5-90cf-17d8dfcaaeaa.PNG)

system： cygwin
emacs：24.5.1

**Comment by redguardtoo** [comment]
major-mode? `C-h v major-mode`

**Comment by zarzen** [comment]
@redguardtoo major-mode 是org-mode
今天开起来看上去正常了。。也不知道什么情况

**Comment by redguardtoo** [comment]
maybe it's because init-artbollocks-mode.el, a feature instead a bug

**Comment by zarzen** [comment]
在非cygwin的windows环境下打开又出现了。
disable了artbollocks-mode之后问题还是存在，不过gui环境下，倒是可以看清楚其中的内容。
![capture2](https://cloud.githubusercontent.com/assets/1150493/8979751/7bb75936-36de-11e5-80bb-14da6c2c38d1.PNG)

**Comment by redguardtoo** [comment]
it's a feature instead of a bug, if you don't like it `(setq artbollocks-passive-voice nil)`.

**Comment by redguardtoo** [comment]
check the doc of artbollocks-mode

**Comment by zarzen** [comment]
在custom.el中添加了
`(setq artbollocks-passive-voice nil)` 发现不起作用，不过确定了是这个mode的作用。
在`M-x artbollocks-mode` disable `artbollocks-mode`之后还需要调用`M-x font-lock-fontify-buffer`才能生效。
另外发现在`.custom.el`中添加了
```
(require 'powerline)
(powerline-center-evil-theme)
```
发现也没有起效，感觉是不是设置有优先级？

**Comment by zarzen** [comment]
不好意思，是因为改错custom.el文件了，在机子上装了cygwin的和windows版的，刚刚改了cygwin的那个配置却在windows版看效果。
不过powerline的问题还是没有起效，这点在我的mac上也有问题。我新开一个issue吧。
