### ISSUE TITLE
powerline not working

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#336]
在安装powerline之后
在`~/.custom.el`中添加了
```
(require 'powerline)
(powerline-center-evil-theme)
```
发现不起作用。
后来尝试了在`~/.emacs.d/init.el`中添加上述两行配置也没有作用。

环境：cygwin，emacs 24.5.1
这点在Mac环境也测了，也不行

**Comment by redguardtoo** [comment]
you need install powerline at first.

**Comment by zarzen** [comment]
这个可以确认已经安装了

**Comment by redguardtoo** [comment]
comment out init-modeline.el

**Comment by zarzen** [comment]
Thanks! It works

**Comment by redguardtoo** [comment]
I will update README.
