### ISSUE TITLE
s-key

### ISSUE THREAD

**Issue by xiaoxinyi** [redguardtoo/emacs.d#337]
遇到这样的问题。比如：alt + x  在minibuffer 中显示的命令确实 m-s-x。 无论我按什么键（key）, 在minibuffer中都显示 s-key。 遇到这个问题，每次我都得结束进程重启。我是通过ssh连接Unbuntu 使用的emacs。

**Comment by redguardtoo** [comment]
After pressing "M-x", can you execute the command?

Besides, check you terminal setup.

**Comment by xiaoxinyi** [comment]
这个问题你们没有遇到过么？

**Comment by redguardtoo** [comment]
os, terminal, emacs info ...

**Comment by jinnwu** [comment]
我之前使用Xmanager打开时碰到过，当出现这种情况时，只要在按下Win键就又恢复正常了，具体是什么原因，没深入研究过，可能是误按了哪个键。

**Comment by redguardtoo** [comment]
usually it's your terminal setup, I suggest using cygwin instead putty under windows.
