### ISSUE TITLE
配置CDLaTeX

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#340]
将cdlatex.el拷贝到～/.emacs.d/中后，尝试在init.el中加入elisp配置CDLaTeX：
           (add-to-list 'load-path "~/.emacs.d")
           (add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)   ; with AUCTeX LaTeX mode
           (add-hook 'latex-mode-hook 'turn-on-cdlatex) ; with Emacs latex mode
再次启动后配置成功，打开tex文件时看到CDLTX菜单：
![psb](https://cloud.githubusercontent.com/assets/10682606/9248736/0733d2d8-41f1-11e5-85e7-2b09cb5ac806.png)
然而之后再次打启动Emacs打开tex文件后再也看不到CDLTX： 
![emacs thinkpad-t430u_025](https://cloud.githubusercontent.com/assets/10682606/9248757/31b142e8-41f1-11e5-9d7e-ae6441b60332.png)

请问如何解决这个问题？ 

下面是我在init.el后面加的代码：
(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)   ; with AUCTeX LaTeX mode
(add-hook 'latex-mode-hook 'turn-on-cdlatex) ; with Emacs latex mode

;;;;;;;;;;;;;;;;;
;;Auctex
;;;;;;;;;;;;;;;;;
(load "auctex.el" nil t t)
(load "preview-latex.el" nil t t)
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)
(mapc (lambda (mode)
(add-hook 'LaTeX-mode-hook mode))
      (list ;'auto-complete-mode
   'auto-fill-mode
   'LaTeX-math-mode
   'turn-on-reftex
   'linum-mode))
(add-hook 'LaTeX-mode-hook
          (lambda ()
            (setq TeX-auto-untabify t     ; remove all tabs before saving
                  TeX-engine 'xetex       ; use xelatex default
                  TeX-show-compilation t) ; display compilation windows
            (TeX-global-PDF-mode t)       ; PDF mode enable, not plain
            (setq TeX-save-query nil)
            (imenu-add-menubar-index)
            (define-key LaTeX-mode-map (kbd "TAB") 'TeX-complete-symbol)))
; set pdf view tool
(setq TeX-view-program-list '(("Evince" "evince %o")))
(cond
 ((eq system-type 'windows-nt)
  (add-hook 'LaTeX-mode-hook
            (lambda ()
              (setq TeX-view-program-selection '((output-pdf "SumatraPDF")
                                                 (output-dvi "Yap"))))))

 ((eq system-type 'gnu/linux)
  (add-hook 'LaTeX-mode-hook
            (lambda ()
              (setq TeX-view-program-selection '((output-pdf "Evince")
                                                 (output-dvi "Evince")))))))
; XeLaTeX
(add-hook 'LaTeX-mode-hook (lambda()
    (add-to-list 'TeX-command-list '("XeLaTeX" "%`xelatex%(mode)%' %t" TeX-run-TeX nil t))
    (setq TeX-command-default "XeLaTeX")
    (setq TeX-save-query  nil )
    (setq TeX-show-compilation t)
    ))

**Comment by redguardtoo** [comment]
- `mkdir -p ~/.emacs.d/site-lisp/whatevername; mv cdlatex.el ~/.emacs.d/site-lisp/whatevername`.

- in your ~/.emacs.d/init.el, insert `(require 'cdlatex)`, 

- then continue insert your ow cdlatex setup below that line.

**Comment by yangdaweihit** [comment]
居然好使了。
![emacs thinkpad-t430u_027](https://cloud.githubusercontent.com/assets/10682606/9250700/b9233f78-4201-11e5-86e7-9c0e1c6f76ad.png)

一直盼你出个教程，有这个打算吗？

**Comment by redguardtoo** [comment]
What's missing in official Emacs tutorial?

I would write my own guide if I could provide something better and different.

**Comment by yangdaweihit** [comment]
我知道，新英文教材并不会因为英语字典或旧教材的存在而失去价值，技术探讨也是没有止境的。使用你的模板，大家受益颇多。相信这个模板若被视为一个案例加以分析讲解，则更能使大家边用边学，推进Elisp的应用。网络上散见的博文良莠不齐，我认为发布一个结合一整套脚本讲解Elisp的教程，其立意有别于官方教程，当是有意义的。加之以你的水平也非常合适，故有了这样的建议。无论如何，感谢你做出的贡献。

**Comment by redguardtoo** [comment]
Yes, I will think about this.

For now, you could stick to my "one year" guide. It already covers everything you need to be great at Emacs.

For example, if you use Steve Purcell's setup, the cdlatex.el could be installed through melpa, so those `require` code is not necessary anymore, you just insert your own setup into custom.el (check its README). Besides, Steve Purcell's is the founder and maintainer of melpa, so you will never have  issue on installing packages.

**Comment by yangdaweihit** [comment]
Thank you for considering this advise. After all, this project means consuming much of your time.

As for MELPA or something else, through I have reading the guide of it (http://melpa.org/#/getting-started), it maybe too advance for me as a Emacs newbie. Such that again, it proves the reason why someone should write a tutorial to save the thousands of Emacs idiots.
