### ISSUE TITLE
启动时在minibuffer中显示的信息

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#341]
启动时显示在minibuffer中的加载信息中似乎显示有一些错误，但信息闪过太快，不知道在哪里查找。请给我一些提示。谢谢。

**Comment by fenguoerbian** [comment]
可以及时print screen 之后再查看的，我的是类似于flet已经淘汰，请采用cl-flet或cl-letf类似的报错内容

**Comment by yangdaweihit** [comment]
闪得太快了，截不下来。Emacs启动过程中不留点log文件吗？

**Comment by fenguoerbian** [comment]
有log文件的，启动emacs之后，C-x, C-b 查看buffer，其中*Message*应该就是log。可以直接光标移动选中后RET查看，也可以C-x, *Message*,RET 查看。

**Comment by yangdaweihit** [comment]
Error while loading 50dictionaries-common: Symbol's value as variable is void: debian-aspell-only-dictionary-alist
Loading /etc/emacs/site-start.d/50mew.el (source)...done
`flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a valid place expression")

在Message中找到这些信息，怎么去除这些错误呢？

**Comment by yangdaweihit** [comment]
`somehting'

**Comment by fenguoerbian** [comment]
第一个的话，能找到这一条：https://github.com/redguardtoo/emacs.d/issues/163 好像是说服务器关了？

第二个关于flet的，直接忽略

第三条找到了https://github.com/redguardtoo/emacs.d/issues/319，不确定有用。。。

**Comment by yangdaweihit** [comment]
看来需要麻烦陈斌解释一下了。:-)

**Comment by redguardtoo** [comment]
all these messages ignorable

**Comment by yangdaweihit** [comment]
不理它吗？

**Comment by redguardtoo** [comment]
yes

**Comment by yangdaweihit** [comment]
好吧
