### ISSUE TITLE
创建文件时文件名自动匹配查找令人烦恼

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#342]
在创建一个文件时，输入文件名过程中会自动查找与之匹配的已有文件名子；若在当前文件夹中找不到就会自动在上一级目录中查找这个名子的文件，这样就无法在当前文件夹中创建这个名字的文件。

比如在 /a 中已经存在  test.txt，现要在 /a/b/ 中创建一个test.txt 时失败，因为Completion模式会自动匹配找到 /a/test.txt而打开该文件。请问如何避免上述问题。

**Comment by Stumble** [comment]
Press C-f before you create a  new file, this will enable the edit-mode to avoid completion.

**Comment by yangdaweihit** [comment]
That seems to do not work~~
