### ISSUE TITLE
smex doesn't get the command by command use history frequency

### ISSUE THREAD

**Issue by tadegenban** [redguardtoo/emacs.d#343]
I used this config one years ago, at that time, when I M-x called smex, then type 'w', I can get whitespace-clean at the first command which is the most frequency used command . 
recently ,I have update the config, and M-x then type 'w', the command begin with 'w' will not be list by use frequency . which seems caused by fix-ido .
So, how can I enable the old feature of smex ?
Disable fix-ido mode can fix this ?

**Comment by yangdaweihit** [comment]
Of course disabling the mode works out for the problem. Maybe the better answer is : 'C-x C-f C-f', which is proposed from stackoverflow.

**Comment by yangdaweihit** [comment]
Of course disabling the mode works out for the problem. Maybe the better answer is : `C-x C-f C-f`, which is proposed from stackoverflow.

**Comment by tadegenban** [comment]
@yangdaweihit 
Sorry I have not describe my request clearly, I have update my comment

**Comment by redguardtoo** [comment]
I guess it's flx-ido problem, because it change the default algorithm of ido. and smex is based on ido.

personally I prefer flx-ido's matching algorithm. but you have full freedom to tweak smex, for example wrap the smex in your own smex

```lisp
(defun my-smex ()
   (interactive)
   (flx-ido-mode -1) ;; turn off flx-ido temporarily
   (smex)
   (flx-ido-mode 1) ;; turn of flx-ido
    ))
(global-set-key (kbd "M-x") 'my-smex)
```

**Comment by tadegenban** [comment]
@redguardtoo It works for me, thanks
