### ISSUE TITLE
emacs C 语言编译

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#345]
现在编译的时候只有出现了错误，compilation buffer才会出现在右侧窗口，如果编译出现了警告，也要使complication buffer出现在右侧窗口，请问应该如何设置

**Comment by redguardtoo** [comment]
https://gcc.gnu.org/ml/gcc/2006-05/msg00275.html

whatever compiler you use, there should exist an option to treat the warning as error.

**Comment by ly0303521** [comment]
如果将警告当成错误的话，一旦有警告出现，编译会停止，但我不希望它停止，我只是想此时能够弹出complication buffer，让我看到有哪些警告

**Comment by redguardtoo** [comment]
自己wrap一下gcc 只要exit status 不等于0就可以了

**Comment by ly0303521** [comment]
我刚在网上查了一下，没找到如何修改gcc的exit status，可以再说详细一点吗

**Comment by redguardtoo** [comment]
by default `M-x compile` will run "make -k", so here is a makefile containing `exit 0`

```makefile
.PHONY = all clean
TARGET = main
SOURCES = main.c
OPT = -O2 -Wall
CC = gcc
CFLAGS = $(OPT) -L /usr/X11R6/lib -lX11 -lm
all: $(SOURCES)
	$(CC) -o $(TARGET) $^ $(CFLAGS); exit 0
clean:
	rm -rf *.o $(TARGET)
```

**Comment by redguardtoo** [comment]
btw, it's not gcc specific, all the process in Linux/Unix world has exit status, see http://www.gnu.org/software/libc/manual/html_node/Exit-Status.html , just search "Linux exit status"
