### ISSUE TITLE
补全功能失效

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#346]
写C文件在输入头文件的时候，使用inc, 有两个选择 include <> 1， include " " 2， 选择其中一个之后，会自动空出下一行，且在输入头文件比如 string 时，本来输入str就可以选择string选项，可实际却怎么也选不出来

**Comment by redguardtoo** [comment]
https://github.com/redguardtoo/cpputils-cmake

setup company-c-headers-path-system from company-c-headers

**Comment by ly0303521** [comment]
按照我前面的步骤，输入str，是可以看到选择项，但是按M-num (num为对应的数字）进行选择的时候不成功

**Comment by redguardtoo** [comment]
`M-x company-version`, mine is 0.8.12

**Comment by ly0303521** [comment]
我的版本也是 0.8.12，我觉得问题是这样的：当我输入 inc，再输入TAB，进入#include < >。
此时第一个snippet，还没有退出，当我再输入str的并按M-num选择的时候，会提示exit snippet first ，
这个提示存在时间非常短，一闪而过

**Comment by redguardtoo** [comment]
it's because the snippet bundled with yasnippet9.0.1. It should use `#include <$0>` instead of `#include <$1>`.

anyway, you can use my snippet defined in `~/.emacs.d/snippets/c-mode`, press `i`, then TAB.

Treat yasnippets as a great platform.
