### ISSUE TITLE
cygwin下使用serail-term不能正常的打开串口

### ISSUE THREAD

**Issue by feidouqwer** [redguardtoo/emacs.d#347]
你好，我fork了你的emacs配置脚本，非常不错，谢谢

我在通过cygwin使用serial-term时不能正常打开串口进行通信。
请问有什么方法可以解决吗？

**Comment by redguardtoo** [comment]
Cygwin won't work in this case. You need try native Emacs.

**Comment by feidouqwer** [comment]
Thank you very much
