### ISSUE TITLE
 emacs 调用gdb多进程调试问题

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#348]
emacs调用gdb调试多进程，进入gdb，”set follow-fork-mode child“ ，本来这样就能调试子进程了，但是发现当父进程退出时，gdb就不能调试了。后来在终端打开gdb调试程序时，是正常的，请问emacs要怎么设置才能正常调试多进程

**Comment by redguardtoo** [comment]
没经验 不过我直觉是无解的
你可以给emacs抱bug
