### ISSUE TITLE
我用来配置 iPhone 开发，卡到死

### ISSUE THREAD

**Issue by ForrestAlfred** [redguardtoo/emacs.d#349]
这样的，我用了你的配置，然后给 yasnippet 导入了 iOS 8.4 的Framworks 的头文件（.h), 然后打开了 .m 的 Objc 文件以后, 就开始卡了. 第一个卡是载入文件卡, 会等好半天, 然后打开文件以后过一会儿就卡一下, 不知道是否是 autoSave 的时候卡. 用两分钟就卡， 然后开个 M-x 也卡半天 .  终端的emacs倒是没有 使用时卡顿的情况, 但就是 M-x 无法使用, 按了没有反应, 不知道是什么事情造成的.

**Comment by ForrestAlfred** [comment]
我尝试关闭了autosave，但仍然是隔几秒就卡死一会儿

**Comment by redguardtoo** [comment]
导入文件什么意思

**Comment by ForrestAlfred** [comment]
这样的，我参考了 这篇文章 http://roupam.github.io 来配置我的Emacs

**Comment by redguardtoo** [comment]
I'm not sure about yasnippets part in that article. But other parts looks fine.

It could be your Emacs installer issue? Use http://emacsformacosx.com/

**Comment by ForrestAlfred** [comment]
确实不知道什么造成的卡顿， 我现在用 Aquamacs 要稍微比 GNU Emacs 好一些， 只在打开 M-x 以及 切从 M-x 换回文本编辑的时候卡一会儿。

**Comment by redguardtoo** [comment]
besides,I use yansippets to insert logging code. I think the way to create snippet from all *.h is kind of overkill.

**Comment by ForrestAlfred** [comment]
恩，是的， 当我把生成的那个文件夹删除以后， 确实不卡了

**Comment by ForrestAlfred** [comment]
但是大神， 我就想用它来编程呀， 没有自动补全很难过的， 你有什么好的解决办法吗？让我可以用头文件里的方法来补全我的代码。

**Comment by ForrestAlfred** [comment]
你是说你的配置用了 Yasnippet 来插入登陆代码吗？ 我之前没用过emacs， 不知道生成 snippet 的正确方法是什么

**Comment by ForrestAlfred** [comment]
那我改用tags来补全吧，可能会好一些

**Comment by ForrestAlfred** [comment]
Thanks

**Comment by redguardtoo** [comment]
The easiest way is create TAGS by using ctags/etags (I recommend ctags),  then place the TAGS at your project root directory. The company-mode (more specifically company-etags.el) will automatically do the remaining stuff.

网上文章良莠不齐，如果你读过我的一年一文，一开始限于我提到的几个信息源就可以了。tuhdo是我认为写得比较好的， http://tuhdo.github.io/c-ide.html ， 

如果你emacs，linux还比较熟悉，可以用gnu global，更精确一点。

**Comment by ForrestAlfred** [comment]
恩，读过好几遍， 恩，昨天我下载了global 编译一个了一个，

**Comment by ForrestAlfred** [comment]
是这样的，其实在终端下面使用起来一点不卡，但就是不知道为什么终端下面打不开M-x， 即使按esc-x

**Comment by ForrestAlfred** [comment]
就是不太熟悉呢， 之前用 了好多年 Windows， 解除了 Mac OS 才开始接触编程。哈哈， 好多需要手动的地方还不太会用呢

**Comment by redguardtoo** [comment]
press `Alt-x`

**Comment by ForrestAlfred** [comment]
好啦！ 终端的emacs用起来非常好。 我更新了终端 emacs 的版本到 24.5.1。 尽管 x11 的 24.5.1 Emacs 还是那么卡， 不过有流畅的终端 Emacs了，Awesome！

**Comment by ForrestAlfred** [comment]
Thanks
