### ISSUE TITLE
How to fill it

### ISSUE THREAD

**Issue by ForrestAlfred** [redguardtoo/emacs.d#350]
![2015-09-21 2 01 14](https://cloud.githubusercontent.com/assets/8122371/9986038/7c1c797e-6069-11e5-815f-7c27536303a2.png)

**Comment by ForrestAlfred** [comment]
Mr. Chen,  thanks for your generous help, I got my Emacs work. And at present, I meet something weird. I want to make auto completion,  and when I input NSLog the prompt would appear at the bottom. But the question is that I don't know which plugin make this happened, and still cannot get the prompt to be used. (Tab or Return makes no sense)

**Comment by redguardtoo** [comment]
That's fine, I guess it's from company-mode, it's hint of the interface because you've already finished the function name. It's not exactly same as IDE.

**Comment by ForrestAlfred** [comment]
Thanks， additonally. I would like to solve the gtags problem, that is gtags cannot  track all of my words, many times  I can travel to a header from , g t at  #<import> "xxx.h"  ,    but I cannot travel to an class implement file where I use the class, like at    Item *item =... , at this place after I use  , g t  ,  that said  find 0 global definitions ....

**Comment by redguardtoo** [comment]
not sure, somebody uses ctags+global

see https://github.com/leoliu/ggtags/wiki/Install-Global-with-support-for-exuberant-ctags

**Comment by ForrestAlfred** [comment]
我现在还是乖乖用 Xcode了， 毕竟也可以装很多插件，也能自己做插件， 上面的 Xvim 目前也能满足我的使用了。

**Comment by ForrestAlfred** [comment]
谢谢你的帮助，以后再来折腾 Emacs。
