### ISSUE TITLE
auto-complete打开ac-auto-start后，行号显示混乱

### ISSUE THREAD

**Issue by lolosssss** [redguardtoo/emacs.d#351]
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "/home/lolo/.emacs.d/plugins/auto-complete/dict")
(ac-config-default)

(setq ac-use-quick-help t)
(setq ac-quick-help-delay 1.0)

;; set using mode of tab
(setq ac-dwim t)

;; set trigger key of auto-complete
(setq ac-auto-start t)
(ac-set-trigger-key "<C-return>")

(setq ac-trigger-commands
      (cons 'backward-delete-char-untabify ac-trigger-commands))

输入时自动提示，但是前面的行号会出现错误，比如只有16行，输入时会突然出现很多行，停止输入时16行下面多了一行，行号显示19。
请问该如何解决？

**Comment by redguardtoo** [comment]
send bug report to https://github.com/auto-complete/auto-complete

You can also use company-mode

**Comment by lolosssss** [comment]
Thanks
