### ISSUE TITLE
elisp编辑怎么了？

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#352]
现在我完全不懂怎么编辑elisp了，是加入了什么导致的？

1. 我想要注释，结果代码跑到下一行，搞半天单行，批量注释代码都不行，逼得我只能删除代码。。
2. 我想要删除括号，按backspace直接不理我，我擦。（evil下可以，emacs模式下不行）
3. 我想要删除函数内的一行，直接把整个函数给我删掉。
4. 按反括号直接给我乱跳，我想要在指定的位置输入反括号好吗？

帮帮忙，这是什么东西啊，这个东西必须被干掉！我都要泪奔了。。。。

**Comment by redguardtoo** [comment]
paredit-mode, see http://stackoverflow.com/questions/14170649/how-to-delete-extra-parens-in-paredit-mode , it you use emacs key bindings. paredit-mode is really useful.

**Comment by albert748** [comment]
@redguardtoo 感谢，至少我可以在编辑时暂时禁用这个了。
