### ISSUE TITLE
OS X 10.11 erlang报错

### ISSUE THREAD

**Issue by lanceflee** [redguardtoo/emacs.d#353]
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a v\
alid place expression")
这是什么鬼...刚想试试从vim转evil...

10.11系统
emacs24.5.1

**Comment by albert748** [comment]
Arch下同样遇到这个问题，会在这里卡“4分钟”左右, 我想了解在这种情况下应该怎么debug？

Emacs startup time: 257 seconds....

**Comment by lanceflee** [comment]
感觉跟init-erlang 那几个路径有关系，折腾了一会，发现没什么用，看不懂lisp
OS X 更新到10.11 加了rootless特性。用户只能在/usr/local/bin下面玩耍了...
arch是不是也一样？

**Comment by albert748** [comment]
把init erlang注释掉之后加载还是被卡住，应该不是erlang加载造成的问题，不知道怎么调试。。。

OSX我还没更新，只要能用brew就够了。

**Comment by lanceflee** [comment]
尝尝鲜，还是GM版，过几天才有正式版，现在Xcode7.0了 brew能用，所以不影响什么。

刚开始尝试从vim转到emacs...都不太懂。
主要做C/Cpp，好多插件看起来用不到的样子...
慢慢熟悉，生命在于折腾，总有适合自己的...

**Comment by redguardtoo** [comment]
because it will download packages at first time.
