### ISSUE TITLE
web-mode 引号问题

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#356]
使用web-mode时，输入引号总是 先单个“ ，再输入时为一对”“ 。导致正常输入时出现三个引号。
或者说，自动补全双引号的效果仅在前面有引号时出现。而第一个双引号并没有自动补全后引号。
一直没有找到哪里修改引号（包括括号）自动补全的行为，希望得到帮助

**Comment by redguardtoo** [comment]
cannot reproduced, need more info and some sample

**Comment by smallst** [comment]
oh，it's my own fault. sorry to bother you.

**Comment by redguardtoo** [comment]
it's controlled by electic-pair-mode.
