### ISSUE TITLE
load init-elisp cost  a lot of time in emacs 24.5

### ISSUE THREAD

**Issue by SmartAI** [redguardtoo/emacs.d#357]
Emacs startup time: 77 seconds.
Loading /Users/smart/.emacs.d/.session...done
No desktop file.
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
ibuffer-vc: groups set
Formats have changed, recompiling...done
Updating buffer list...done
GNU Emacs 24.5.1 (x86_64-apple-darwin15.0.0, Carbon Version 157 AppKit 1404.11) of 2015-10-19 on MacBook-Pro.local

Finally I am sure that the problem is caused by file init-elisp.

**Comment by redguardtoo** [comment]
see https://github.com/redguardtoo/emacs.d/issues/354

What's your network environment? Have you tried the setup at home?

I can't reproduce the issue, exactly same environment.

**Comment by SmartAI** [comment]
I am sorry about having not search the old issues before post this one.
The good thing is that I have just solved the problem after I put `(require 'init-elisp)` after other init-xxx.el files which have been loaded.

**Comment by redguardtoo** [comment]
6e7237f remove obsolete flymake.el (Chen Bin)
this happens only at 24.5, use latest setup. Thanks for reporting this issue.
