### ISSUE TITLE
简单的两点建议

### ISSUE THREAD

**Issue by worldlove** [redguardtoo/emacs.d#358]
你好，我看了你的blog之后，一直使用你的emacs配置，关于lisp暂时懒得折腾，只希望能有一个强大的编辑器，能稳定地完成工作。使用一段时间后有一些建议：
1. 主分支之上另建开发分支，在开发分支上测试稳定之后再合并到主分支，之前有几次更新配置后没法使用，不得不回退；
2.js官方推荐是2个空格的缩进，工作团队也要求2个空格，而你的配置一直是4个空格，尝试过修改init-javascript文件，但没法生效，能不能简单说一下修改方法?
感谢你分享如此好用的代码，谢谢！

**Comment by redguardtoo** [comment]
1. `git pull https://redguardtoo@github.com/redguardtoo/emacs.d.git stable`

2. `(setq js2-basic-offset 2)`, actually 4 is the default value of js2-mode

**Comment by redguardtoo** [comment]
anywhere, here is a sample,
```diff
diff --git a/lisp/init-javascript.el b/lisp/init-javascript.el
index d1f397d..1101e2a 100644
--- a/lisp/init-javascript.el
+++ b/lisp/init-javascript.el
@@ -15,6 +15,7 @@
               js2-skip-preprocessor-directives t
               js2-strict-inconsistent-return-warning nil ; return <=> return null
               js2-enter-indents-newline nil
+              js2-basic-offset 2
               js2-bounce-indent-p t)
 
 (setq javascript-common-imenu-regex-list
```
