### ISSUE TITLE
在编写c++代码时，调用一个函数的时候打了括号就在minibufer里面见不到函数定义了

### ISSUE THREAD

**Issue by stcai** [redguardtoo/emacs.d#359]
问题是这样子的，例如我写了如下的类定义：
```c++
class Parser
{
      void parse(string& expr, bool isCompatible);
};
```
在写调用代码时
```c++
Parser parser;
parser.parse("hello", true);
```
上面打到parser.parse时在minibuffer能看到parse函数的定义，但是打了括号之后就看不到了。请问：
1.  如何才能在输入实参的时候能够同时看到函数的定义呢？
2. 在你的配置文件里面是哪个插件的代码实现此功能的呢？
3. 编写python代码时打完括号还是会有函数原型提示在minibuffer(这一点是符合我上面说的需求的），不过在idle的时候有一些信息会输出到minibuffer，会冲掉原型提示信息，有没有什么好办法可以解决这个问题呢？

**Comment by redguardtoo** [comment]
company-mode. ask its developer on github.

for python, I use company-mode plus anaconda-mode, but I'm thinking to replace anacoda-mode with elpy. ask anaconda-mode developer.

I don't have any magic setup. It's automatically enabled by the plugin.

**Comment by stcai** [comment]
I know, thanks so much. And your emacs configure is very helpful.

**Comment by redguardtoo** [comment]
I changed my python setup to elpy, pull my latest setup and check my readme.
