### ISSUE TITLE
每次打开emacs时都会跳出一个名为OpenSSH的对话框，让我填写密码，不知道这是什么东西。

### ISSUE THREAD

**Issue by Dronsure** [redguardtoo/emacs.d#360]
如题，请问如何解决？

**Comment by redguardtoo** [comment]
need more information, os, emacs version, exact steps, did you install openssh manually? how?

**Comment by Dronsure** [comment]
刚安装的ubuntu15.10-x64然后装emacs24.5,将您的配置下载下来按照步骤复制.emacs.d至家目录后，首次打开emacs时，您写的配置文件就自动执行，执行过程中会出现名为openssh对话框，要求我填写密码，强制取消填写密码后，您的配置运行完成。于是再打开emacs后还会让我输入密码。在fedora22-kde环境下也有这种现象，但是在fedora-kde环境下只是在安装您的过程中出现一次让我输入密码，之后再打开emacs就没有此现象了。

**Comment by redguardtoo** [comment]
`emacs --debug-init` in shell, when you see the popup, `C-x C-b` to *message* buffer, paste everything from that buffer here.

**Comment by Dronsure** [comment]
Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...done
Loading debian-ispell...done
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
.emacs.d/lisp/init-ido.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
Eager macro-expansion failure: (error "(quote erlang-compile-outdir) is not a valid place expression")

[yas] Discovered there was already *scratch* in fundamental-mode
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *load* in fundamental-mode
[yas] Discovered there was already  *load*-150281 in fundamental-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/dronsure/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading compiled snippets from /home/dronsure/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode
Loading /home/dronsure/.emacs.d/elpa/yasnippet-0.9.0.1/snippets/fundamental-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/dronsure/.emacs.d/elpa/yasnippet-0.9.0.1/snippets
[yas] Prepared just-in-time loading for ~/.emacs.d/snippets
[yas] Reloaded everything (snippets will load just-in-time)....
Emacs startup time: 12 seconds.
Loading /home/dronsure/.emacs.d/.session...done
No desktop file.
Loading /home/dronsure/.emacs.d/company-statistics-cache.el (source)...done
ad-handle-definition: `ispell-word' got redefined
Starting new Ispell process aspell with default dictionary...
For information about GNU Emacs and the GNU system, type C-h C-a.
Error during redisplay: (eval utf-8-unix) signaled (void-variable utf-8-unix) [43 times]
Error during redisplay: (eval utf-8) signaled (void-variable utf-8) [39 times]
user-error: Minibuffer window is not activeError during redisplay: (eval utf-8) signaled (void-variable utf-8)
Error during redisplay: (eval utf-8) signaled (void-variable utf-8) [26 times]
Beginning idle-require
idle-require: require init-misc-lazy
Loading /home/dronsure/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)

**Comment by redguardtoo** [comment]
6e7237f remove obsolete flymake.el (Chen Bin)
try pull the code, is it fixed?

**Comment by Dronsure** [comment]
应用了您的措施，已经没有问题了，谢谢了
