### ISSUE TITLE
在编写lua的时候tab键默认是3个空格

### ISSUE THREAD

**Issue by RequiemSouls** [redguardtoo/emacs.d#361]
在编写lua的时候tab键是三个空格，但是在配置里面没有发现tab_width 3的设置
C++代码并没有这个问题 不知道是不是有什么特别的地方

**Comment by redguardtoo** [comment]
8ddb82a indent 2 space in lua-mode (Chen Bin)
3 is the default value of `lua-indent-level`, that's weird. thanks for reporting the issue.
