### ISSUE TITLE
使用了您的配置，每次打开emacs就会加载一个名为company-statistics-cache.el的buffer

### ISSUE THREAD

**Issue by Dronsure** [redguardtoo/emacs.d#362]
使用了您的配置，每次打开emacs就会加载一个名为company-statistics-cache.el的buffer，于是每次退出emacs都要让我确认是否kill it。

![2015-10-26 11-26-24](https://cloud.githubusercontent.com/assets/13312424/10720699/e07ba472-7bd4-11e5-984c-e74b2cfad365.png)

**Comment by redguardtoo** [comment]
It's will sort the company-mode candidates by usage statistics. Sometimes when it's still sorting, you want to close the emacs. That's why you see this warning, just choose "Y".
