### ISSUE TITLE
mark set 后选中区域为什么没有高亮

### ISSUE THREAD

**Issue by kuangwangbing** [redguardtoo/emacs.d#363]
1. 通过putty登陆，ubuntu系统
2. emacs启动，默认界面，模式都是第一次启动的
3. 查询了网上， transient-mark-mode 是t
4. 如果 emacs -Q 可以看到选中区域高亮

**Comment by redguardtoo** [comment]
`TERM=xterm-256color emacs -nw` or just comment out line `(require 'init-color-theme)` in init.el

**Comment by kuangwangbing** [comment]
多谢，两者均验证可用。

ps：我理解是，init-color-theme 实际上是有高亮的，但是如果终端不支持256色的话是高亮不出来。所以我按照这种意图，将`export TERM=xterm-256color`添加到了终端登录脚本里。不知道此番理解对否？

**Comment by redguardtoo** [comment]
Yes. you are right. export should be fine because I've not find any terminal not supporting 256 these days.
