### ISSUE TITLE
当我要打开一个文件只知道名字不知道位置怎么办？

### ISSUE THREAD

**Issue by RequiemSouls** [redguardtoo/emacs.d#364]
很多时候跳转文件的时候都不想输入路径，进进出出很麻烦 ，是否有什么快捷的方式（想sublime Text中的ctrl + p 可以根据文件名在当前项目的所有文件中定位）

**Comment by redguardtoo** [comment]
https://github.com/technomancy/find-file-in-project, press `, kk`
