### ISSUE TITLE
terminal mode

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#365]
In my memory,`C-x e` goes to terminal mode,but now it doesnt work anymore. Could you tell me which package such command need or how can I fix it?

**Comment by redguardtoo** [comment]
`M-x multi-term` or insert below code into ~/.emacs.d/init.el:
```lisp
(define-key global-map (kbd "C-x e") 'multi-term)
```

**Comment by yangdaweihit** [comment]
Thanks, It works again.
