### ISSUE TITLE
elpy problems

### ISSUE THREAD

**Issue by CreatorB** [redguardtoo/emacs.d#367]
hi redguardo,

i have done follow up your configs, but when i'm launch my emacs, always show warning box, like this:

Warning (initialization): An error occurred while loading `/home/b/.emacs.d/init.el':
error: Package `elpy' is not available for installation

**Comment by redguardtoo** [comment]
`M-x list-packages` at least once. then restart emacs.

**Comment by CreatorB** [comment]
i have do that, but the messages still appears when first launch emacs, does it ok?

**Comment by redguardtoo** [comment]
http://stable.melpa.org/#/elpy , see? it's there

Did you modify my init-elpa.el?

**Comment by CreatorB** [comment]
thanks :smiley_cat: but have missed something again maybe... it warning changes to unable activate package elpy, require company-0.8.2 is unavailable, and under it show me `error: Package cliphist is not available for installation`
 
no, actually my local is uptodate with your repo's, must i re-clone your repo? maybe my problems is just missed some packages, i will try completing as manually

**Comment by redguardtoo** [comment]
all these packages should be installed automatically. If you have not modified init-elpa.py, then it must be network issue. maybe you should restart from the scratch.

**Comment by CreatorB** [comment]
Right, maybe it just my network issue so sorry sir.... now i'm using yours stable version and work like charm on slackware 14.1 :smiley_cat:
