### ISSUE TITLE
semicolon input bug in emacs-lisp major mode

### ISSUE THREAD

**Issue by SmartAI** [redguardtoo/emacs.d#368]
当我要`comment`一个多行的`S expresion`的时候每次输入`;`就会自动跳到上一行

**Comment by SmartAI** [comment]
this happens just on **multi line** s-expression

**Comment by redguardtoo** [comment]
which language? major-mode (C-h v major-mode)? sample code

**Comment by SmartAI** [comment]
1, open scratch buffer (Lisp Interaction mode)
2, input code 
![snip20151030_3](https://cloud.githubusercontent.com/assets/1811546/10824385/2406c3de-7e9b-11e5-8148-7d833dd81ad3.png)



3, insert `;` before `(cond` just at beginning of this line 1;

**Comment by redguardtoo** [comment]
paredit-mode

On Fri, Oct 30, 2015 at 3:15 AM, Smart <notifications@github.com> wrote:

> 1, open scratch buffer (Lisp Interaction mode)
> 2, input code
> [image: snip20151030_3]
> <https://cloud.githubusercontent.com/assets/1811546/10824385/2406c3de-7e9b-11e5-8148-7d833dd81ad3.png>
>
> 3, insert ; before (cond just at beginning of this line 1;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redguardtoo/emacs.d/issues/368#issuecomment-152231949>
> .
>



-- 
help me, help you.
