### ISSUE TITLE
Flymake:configuration error while running tidy

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#369]
i change flymake-gui-warnings-enabled to true in init-flymake.el,then i found flymake configuration error when i open an php(or html) file.
then i add this:
(setq flymake-log-level 3)
and see:

file /home/smallst/js/example.php, init=flymake-html-init
flymake is running: nil
file /home/smallst/js/example.php, init=flymake-html-init [3 times]
create-temp-inplace: file=/home/smallst/js/example.php temp=/home/smallst/js/example_flymake.php
saved buffer example.php in file /home/smallst/js/example_flymake.php
starting process on dir /home/smallst/js/
started process 4875, command=(tidy example_flymake.php)
moz-custom-setup called (buffer-file-name)=/home/smallst/js/example.php
received 695 byte(s) of output from process 4875
received process output: 
 d > line 3 column 5 - Warning: inserting missing 'title' element
 d > Info: Document content looks like HTML 3.2
 d > 1 warning, 0 errors were found!
 d > 
  d> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
  d> <html>
  d> <head>
  d> <meta name="generator" content=
  d> "HTML Tidy for Linux (vers 25 March 2009), see www.w3.org">
  d> <title></title>
  d> </head>
  d> <body>
  d> <h1>my first PHP page</h1>
  d> </body>
  d> </html>
  d> 
  d> To learn more about HTML Tidy see http://tidy.sourceforge.net
  d> Please fill bug reports and queries using the "tracker" on the Tidy web site.
  d> Additionally, questions can be sent to html-tidy@w3.org
  d> HTML and CSS specifications are available from http://www.w3.org/
  d> Lobby your company to join W3C, see http://www.w3.org/Consortium
  d> 
file /home/smallst/js/example.php, init=flymake-html-init
parsed 'line 3 column 5 - Warning: inserting missing 'title' element', no line-err-info
parsed 'Info: Document content looks like HTML 3.2', no line-err-info
parsed '1 warning, 0 errors were found!', no line-err-info
parsed '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">', no line-err-info
parsed '<html>', no line-err-info
parsed '<head>', no line-err-info
parsed '<meta name="generator" content=', no line-err-info
parsed '"HTML Tidy for Linux (vers 25 March 2009), see www.w3.org">', no line-err-info
parsed '<title></title>', no line-err-info
parsed '</head>', no line-err-info
parsed '<body>', no line-err-info
parsed '<h1>my first PHP page</h1>', no line-err-info
parsed '</body>', no line-err-info
parsed '</html>', no line-err-info
parsed 'To learn more about HTML Tidy see http://tidy.sourceforge.net', no line-err-info
parsed 'Please fill bug reports and queries using the "tracker" on the Tidy web site.', no line-err-info
parsed 'Additionally, questions can be sent to html-tidy@w3.org', no line-err-info
parsed 'HTML and CSS specifications are available from http://www.w3.org/', no line-err-info
parsed 'Lobby your company to join W3C, see http://www.w3.org/Consortium', no line-err-info
file /home/smallst/js/example.php, init=flymake-html-init
process 4875 exited with code 1
cleaning up using flymake-simple-cleanup
deleted file /home/smallst/js/example_flymake.php
example.php: 0 error(s), 0 warning(s), 0 info in 1.31 second(s)

it seems tidy run correctly(but exited with code 1?) and flymake closed.
what happend?

**Comment by smallst** [comment]
![screenshot_2015-10-29_18-01-54](https://cloud.githubusercontent.com/assets/11417632/10815457/2e35604c-7e67-11e5-9c40-7f841e70e729.png)
![screenshot_2015-10-29_18-02-14](https://cloud.githubusercontent.com/assets/11417632/10815463/393f03e4-7e67-11e5-9f6e-7176cd21d2df.png)

**Comment by redguardtoo** [comment]
That's fine. tidy is html4 linter which is too strict for modern html5 pages. It will exit with error number almost on any html files. I make it usable by filter out noises and keep only essential error messages.

**Comment by smallst** [comment]
so it is.thank you!
