### ISSUE TITLE
eim freeze emacs occasionally

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#370]
当前状况：
1. 如果使用外部IM+emacs，不会出现任何问题，可以长时间使用
2. 使用Emacs+eim偶尔会导致emacs被卡住，C-g退出无效，CPU使用率保持在30%左右。
3. 已经在windows和arch上都发现了这个问题，出现机率越来越频繁，无法无视。

猜测eim可能在某个位置陷入死循环，但如果是这样，C-g应该可以backtrace，无法退出，问题可能出现下层的C代码上。

windows版本：25.0.50.1
Linux版本：24.5.1

**Comment by redguardtoo** [comment]
emacs 一律用24.5, 用25就要做小白鼠的心理准备.

试一试 https://github.com/tumashu/chinese-pyim

**Comment by albert748** [comment]
sorry, 我搞混了，我并不是用的eim，describe-input-method: chinese-pyim

我只是怀疑chinese-pyim导致了冻结，但并没有相关的证据，我想可能需要用gdb才能检查出来。

**Comment by redguardtoo** [comment]
我升级到最新版的chinese-pyim,如果还有问题,给其作者发报告.

1b2f994 upgrade chinese-pyim (Chen Bin)
