### ISSUE TITLE
单词补全

### ISSUE THREAD

**Issue by Univerfly** [redguardtoo/emacs.d#371]
1.忘了从什么时候开始，好像输入前缀就能补全整个词的功能不见了。求解释和恢复方法。(我使用的是emacs快捷键写的是C++和C，没开evil)
2.写bash脚本的时候，好像打反引号会导致卡死。

**Comment by redguardtoo** [comment]
you need input at least 3 characters to trigger company-mode, it's original company-mode's setup, I didn't change it.  for the word completion, it's company-dabbrev, looks it's working on my computer. If you mean the C++, you need setup company-clang-arguments or company-gtags

looks fine when writing  bash script, you need sample and more information>

**Comment by Univerfly** [comment]
纯文本没事，就C和C++有问题，我也没动过您的配置，是不是因为最近把clang换成clang-3.6造成的？

**Comment by Univerfly** [comment]
把clang换回旧版本之后确实恢复了，因为现在ubuntu下，新版本的clang指令全部变成后面加-3.6的，不是clang了，可能是导致问题的原因。但问一下有没有可能适配一下clang-3.6或者教我改哪些文件可以适配新版本clang。谢谢。

**Comment by redguardtoo** [comment]
2015-11-05 1:43 GMT+11:00 Xie Yufei <notifications@github.com>:

>
> 把clang换回旧版本之后确实恢复了，因为现在ubuntu下，新版本的clang指令全部变成后面加-3.6的，不是clang了，可能是导致问题的原因。但问一下有没有可能适配一下clang-3.6或者教我改哪些文件可以适配新版本clang。
>
You could submit issue to company-mode (but with more details, os, clang
version ,company-mode version ....).


But you need double check at first. /usr/bin/clang usually is created
automatically by ubuntu. it's a link to actual clang binary, Why it's
missing? Did you clean uninstall old version of clang.


-- 
help me, help you.
