### ISSUE TITLE
80列格式化

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#372]
这是一个问题帖。当编辑tex文件时有个很多的功能——80列自动转行。这样看起来比较整齐。但对于已经存在的内容，是否有个快捷键格式化为80列限制的形式。

**Comment by redguardtoo** [comment]
`M-x fill-region`, suppose auto-fill-mode is on

**Comment by yangdaweihit** [comment]
it works, thank you!
