### ISSUE TITLE
org-mode table align

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#374]
当表格中有中文时，表格对齐不理想，请问有办法解决吗。
![emacs debian_025](https://cloud.githubusercontent.com/assets/10682606/11011937/6e7b9a6e-8528-11e5-9089-3356d71a948b.jpg)

在网上查了一圈，看来是个难题。感觉所见解决办法都是固定字号。可否写一段elisp解决这个问题，不用固定字号。

**Comment by redguardtoo** [comment]
用中英文等宽字体

**Comment by yangdaweihit** [comment]
网上一般也是这样解决的，能否给一段代码？

**Comment by redguardtoo** [comment]
http://li2.me/util/%E4%BD%BF%E7%94%A8%E4%B8%BA%E7%9F%A5%E7%AC%94%E8%AE%B0%E5%92%8Cemacs%E6%8F%90%E9%AB%98%E7%AC%94%E8%AE%B0%E6%95%B4%E7%90%86%E7%9A%84%E6%95%88%E7%8E%87/
