### ISSUE TITLE
Which-func-mode doesn't work well

### ISSUE THREAD

**Issue by garyDong** [redguardtoo/emacs.d#375]
Thanks for your work!
But something is wrong with the which-func-mode, it doesn't work.
I press "C-h m" to check if the which-func-mode is on. I'm sure the which-function-mode is on,  but I can't see the function name in the mode line.
I try to comment the "(require 'init-modeline)" and "init-which-funcin" in init.el, restart emacs ,and then turn on the which-function-mode, it works well.
so ,what causes this problem? I'm confused.
Thank you.

**Comment by redguardtoo** [comment]
what's your major-mode?

**Comment by garyDong** [comment]
I tried Emacs-Lisp and C/lhw mode, but neither of them can make which-func-mode work. It seems it has nothing to do with the major mode. Even I turn on the which-func-mode by typing "M-x which-func-mode",  I can't see the function name in the mode line.

**Comment by redguardtoo** [comment]
`M-x popup-which-function`

**Comment by redguardtoo** [comment]
I don't remember I did anything on which-func-mode, it's possible other plugins take over mode-line. anyway, I already provided better setup.
