### ISSUE TITLE
启动时加载很久以后显示json版本不可用？

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#376]
环境（win7 + win32_emacs24 + win32_cygwin）:

Warning (initialization): An error occurred while loading `c:/Users/y00329832.CHINA/AppData/Roaming/.emacs.d/init.el':

error: Need package `json-reformat-20141009.1155', but only 0.0.5 is available

我用list-packages手动安装了json-reformat-20141009.1728，然后重启，提示：

Warning (initialization): An error occurred while loading `c:/Users/y00329832.CHINA/AppData/Roaming/.emacs.d/init.el':

error: Package `json-snatcher-20131110.1107' is unavailable

是不是json系列的包自动加载脚本里面版本号都老了？？
手动加载比较麻烦就是每次都提示我
Select coding system (default utf-8)：
这个有办法去掉吗？？？

**Comment by redguardtoo** [comment]
remove json and jsons after `M-x list-packages`, it's not used. I remove them because the error you mentioned. then restart emacs.

to upgrade all the packages, `M-x list-packages ENTER U x`
