### ISSUE TITLE
行号边栏自动缩放

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#377]
当增大字体时（我使用的是C +方式），行号也同样增大，但留给行号的边栏并宽度没有相应的放大，导致行号在放大后不能完全显示。
![emacs debian_034](https://cloud.githubusercontent.com/assets/10682606/11052604/77007ede-8794-11e5-8d84-25e80f122219.jpg)

**Comment by redguardtoo** [comment]
No way. that's linum-mode
