### ISSUE TITLE
I can not change to another disk label in windows platform.

### ISSUE THREAD

**Issue by sxdxyxy** [redguardtoo/emacs.d#378]
In windows platform, when I press c-c,c-f, I can only change my directory beyond the C disk, but my files are located in disk d, so what should i do to solve the problem?

**Comment by redguardtoo** [comment]
what's `C-c C-f`?

**Comment by sxdxyxy** [comment]
when i c-c c-f , there is a path that i can change, but the root of path
can not be changed
, that's mean if the initial disk is c:, then you can not change to disk d:
that's the problem.

actually, i found that almost all emacs in windows platform has the same
problem.

余晓云
三峡大学水利与环境学院
TEL：+86-717-6392165
MOB：+86-13307208008
MSN：yuxiaoyun@ctgu.edu.cn
QQ:23937286
blog: http://yuxiaoyun.blogspot.com

**Comment by redguardtoo** [comment]
`C-h k C-c C-f`, then tell me the result.

**Comment by sxdxyxy** [comment]
c-c c-f runs the command org-forward-heading-same-level, which is an
interactive compiled Lisp function in 'org.el'.
It is bound to c-c c-f, <menu-bar> <Org> <navigate headings> <next same
level>.

余晓云
三峡大学水利与环境学院
TEL：+86-717-6392165
MOB：+86-13307208008
MSN：yuxiaoyun@ctgu.edu.cn
QQ:23937286
blog: http://yuxiaoyun.blogspot.com

**Comment by redguardtoo** [comment]
then why you say `In windows platform, when I press c-c,c-f, I can only change my directory beyond the C disk, but my files are located in disk d, so what should i do to solve the problem?`

**Comment by redguardtoo** [comment]
If your intention is open file by press `C-x C-f`, check README.
