### ISSUE TITLE
how can i set js2-mode offset as <script> in web mode?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#380]
i‘d like to konw which mode(or indent function) use for "script" tag in  web mode.
you see,when i add script in web mode ,it show like this:
![screenshot_2015-11-19_09-36-53](https://cloud.githubusercontent.com/assets/11417632/11259925/1c77763e-8ea1-11e5-8fd8-8bededbf9526.png)
 align with "."
but when i use js2-mode to write scirpts,it show like this:
![screenshot_2015-11-19_09-36-06](https://cloud.githubusercontent.com/assets/11417632/11259937/3d570720-8ea1-11e5-90d7-fa32e31cabcb.png)
,aling with tabs.

 i see the init-web-mode.el but do not find the function for script. or should i ask this question in mooz/js2-mode?

**Comment by redguardtoo** [comment]
http://blog.binchen.org/posts/easy-indentation-setup-in-emacs-for-web-development.html

**Comment by smallst** [comment]
oh,thank you.although variables in the blog aren't what i want,but i find the "."offset in site-lisp/web-mode according to describe-variables: web-mode-code-indent-offset.
this is what i find
![screenshot_2015-11-19_14-04-56](https://cloud.githubusercontent.com/assets/11417632/11263533/7f133876-8ec6-11e5-84cb-58ce0d115ed3.png)
since it is define in function in site-lisp, i think i don't have enough knowledge to add this to js2-mode in my own init.el . Anyway, thank you !

**Comment by redguardtoo** [comment]
looks it's hardcoded in web-mode, I suggest don't spend too much time on indentation.

**Comment by smallst** [comment]
i see. thank you for suggestion.
