### ISSUE TITLE
如何让helm-do-grep支持递归搜索，并且默认只在*.[ch]*后缀的文件上搜索？

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#382]
rt

**Comment by redguardtoo** [comment]
Preconfigured helm for grep.
Contrarily to Emacs `grep', no default directory is given, but
the full path of candidates in ONLY.
That allow to grep different files not only in `default-directory' but anywhere
by marking them (C-<SPACE>). If one or more directory is selected
grep will search in all files of these directories.
You can also use wildcard in the base name of candidate.
If a prefix arg is given use the -r option of grep (recurse).
The prefix arg can be passed before or after start file selection.
See also `helm-do-grep-1'.

**Comment by redguardtoo** [comment]
C-space to mark files or directories to grep, then enter

**Comment by redguardtoo** [comment]
If you want to recursive, just use `M-x grep`

**Comment by redguardtoo** [comment]
btw, try `M-x counsel-git-grep` with my latest setup.
