### ISSUE TITLE
How to change the color theme?

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#383]
I want to change the color theme molokai to vim color. It generated an error after the init-color-theme.el was changed. So, I selected the “tools", "color theme", "Vim color". It worked. But I don't know how to save the options. Help me, please. Thank you!

**Comment by redguardtoo** [comment]
check README.

**Comment by lxeg0429** [comment]
I changed the code in init.el as follows:

;; (if (or (display-graphic-p) (string-match-p "256color"(getenv "TERM")))
;;     (require 'init-color-theme))
(require 'color-theme-vim-colors)

but, it does not work. It shows "cannot load file"
By the way, I have read the README. I did not find the clue.
