### ISSUE TITLE
Seeking suggestion about using the evil mode or not.

### ISSUE THREAD

**Issue by cjack** [redguardtoo/emacs.d#384]
Hi, I am a completely new guy to Emacs, with limited knowledge about the basic operations on Vi. Since I have downloaded your version of emacs.d, there is a evil mode by default. I am not sure which is good for the beginner, because I can use the basic Vi operations to edit text files (far away from mastering the Vi, but enough for basic edit task), meanwhile I am not quite familiar with the Emacs Key map yet. So should I try to learn more about the Vi now, or just turn "evil" off and learn the emacs keys? (BTW, I have gone through the office guide by `M-x help-with-tutorial`)

**Comment by redguardtoo** [comment]
Definitely yes. half an hour to master a life time skill (vi model editing).

But you are totally fine to start with emacs keybindings.

As I said in "master emacs in one year", key bindings is the most trivial part of Emacs.

**Comment by cjack** [comment]
OK, thanks a lot. But half-an-hour seems too short for me to master the vi. LoL
