### ISSUE TITLE
clang syntax support c++11?

### ISSUE THREAD

**Issue by john-Ly** [redguardtoo/emacs.d#385]
-----------------------------------------------
clang failed with error 1:                                                             
/usr/local/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -I/home/john\
/catkin_ws/src/learning_actionlib/src/ -Xclang -code-completion-at=-:19:37 -  
----------------------------------------------
i wanna use std::bind(or boost::bind)(recently i just learn c++11)
ubuntu14.04(copy the clang binary package) just know add flags when using clang -std=c++11
I'm new to emacs & I'm confused how to google this problem, so ask directly. (i just git clone your configuration files, nothing changed)
something like add lib path? i guess... how?
Thank you for you time!

**Comment by redguardtoo** [comment]
more details, minimum example to reproduce the issue, plugin you are using.

**Comment by john-Ly** [comment]
firstly, thank you for the answer. I checked it again, actually i'm careless：( & I solved.
it's support c++11.

**Comment by redguardtoo** [comment]
cool. good to know
