### ISSUE TITLE
emacs多窗口编辑下与git的兼容有些问题

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#387]
你好！如果在init.el里打开(require 'init-git)，并且使用emacs多窗口编辑c++代码时，当C-x b切换buffer时，此时光标会跳来跳去，而且另一个窗口本来有行号显示的也变的没有。

emacs 版本24.5.1，mac和linux下都有这个问题。

谢谢！

**Comment by redguardtoo** [comment]
more information and screenshot. I can't reproduce it in Emacs 24.5.1 on Mac

**Comment by stevenswong** [comment]
本来是这样的：
![image](https://cloud.githubusercontent.com/assets/1772676/12019921/2817c6ea-adb1-11e5-933a-42fd7a39c009.png)
按了C-x b或C-x C-f后：左边的窗口变成这样了：
![image](https://cloud.githubusercontent.com/assets/1772676/12019973/b1335426-adb1-11e5-98f3-4125b0031ae0.png)

**Comment by redguardtoo** [comment]
Yes, I can reproduce, when mini-buffer is more than 2 lines, this could happen. I don't know the root cause, maybe linum-mode issue?

**Comment by stevenswong** [comment]
It's no problem if i comment “(require 'init-git)”

**Comment by redguardtoo** [comment]
I think it's git-gutter's problem, you can raise a issue there, or just `C-w =` to re-adjust window layout.
