### ISSUE TITLE
Win7_x64崩溃

### ISSUE THREAD

**Issue by DucielCity** [redguardtoo/emacs.d#388]
1. 直接点击关闭窗口或者C-x, C-c;
2. 弹出提示: Buffer "company-statistics-cache.el" has running process; kill it? (y or n)  -- 无论选y或n 都会弹出崩溃提示.
3. 弹出崩溃窗口
   "GNU Emacs: The extensible self-documenting text editor 已停止工作"
   "出现了一个问题, 导致程序停止正常工作. 请关闭该程序."
   "关闭程序"

Emacs版本: GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570

**Comment by redguardtoo** [comment]
check http://superuser.com/questions/576512/emacs-24-3-on-windows-7-does-not-close-properly
Looks it's not related to my setup.
