### ISSUE TITLE
how to cancel the information of ido in the minibuffer?

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#390]
I want to know how to cancel the information of ido and keyfrequent data in the minibuffer. And when I close the Emacs, it said: buffer "company-statistics-cache.el" has a running process; kill it or not?    I don't want it show this information. What should I do?
Thank you!

**Comment by redguardtoo** [comment]
Raise a issue at company-statistics-cache.el.  https://github.com/company-mode/company-statistics/blob/master/company-statistics.el

company-statistics.el improves the user experience, so don't disable it.
