### ISSUE TITLE
init-evil question

### ISSUE THREAD

**Issue by jcppython** [redguardtoo/emacs.d#391]
Hi~
I am doubt about the lines( 236~271) in init-evil.el.
I think you like vim key maps. Why you disable evil-mode for those mode?

**Comment by redguardtoo** [comment]
just my personal preference. for example, it's convention in shell emacs keybinds are used. I prefer keep this convention when start a shell in Emacs.

**Comment by fenxian** [comment]
Thank you for you reply.
In addition, I want to know how to edit files in remote server. Especially, the project is huge, which has many source files and big gtags files.

**Comment by redguardtoo** [comment]
Run Emacs in remote server.
