### ISSUE TITLE
the conflict between Yasnippet and company

### ISSUE THREAD

**Issue by fenxian** [redguardtoo/emacs.d#393]
With your configuration, I encounter the same issue described in: 
https://github.com/randomphrase/company-c-headers/issues/6

Do you encounter it?

**Comment by redguardtoo** [comment]
think the official snippet in `yasnipppet/snippets/cc-mode/inc` could be improved by replace `$1` with `$0`, anyway, regard yasnippet as a platform and write your own snippet instead. For example, check my `~/.emacs.d/snippets/c-mode/include.yasnippet`

**Comment by fenxian** [comment]
Thank you, It's great!
