### ISSUE TITLE
启动速度慢和 idle require 的干扰问题

### ISSUE THREAD

**Issue by huchhong** [redguardtoo/emacs.d#394]
我刚开始用这个配置，有两个很别扭的感受：
1. 启动速度慢。打开emacs，需要大概4秒才能开始编辑。
2. 这个配置空闲的时候会 idle-require 一些东西。可以理解这个想法，但是造成刚开始的一个阶段（这个阶段时间不短了）想要马上敲击一些命令的时候，只要稍微犹豫几秒，就会被idle-require干扰。

对第一个问题，能否解释一下什么原因？如果以后根据我的需要减少一些无用的插件，是否能降低启动时间。
对第二个问题，是否有配置可以让idle-require的输出静默，或者将输出放到更合适的地方，不要干扰敲击命令。

**Comment by redguardtoo** [comment]
`(setq idle-require-message-verbose nil)`

**Comment by huchhong** [comment]
Thanks
