### ISSUE TITLE
drupal-mode support

### ISSUE THREAD

**Issue by dashohoxha** [redguardtoo/emacs.d#395]
These scripts make Emacs shine, thanks for providing them.

I would like to add Drupal support but I am not quite familiar with emacs configuration/customization.
I have found these relevant links, but I ma not sure how to integrate them with the rest of the scripts:
 - https://github.com/arnested/drupal-mode
 - https://www.drupal.org/node/2327741
 - https://github.com/freeduck/drupal-emacs
 - https://www.drupal.org/node/2327299

Any help would be appreciated.

**Comment by redguardtoo** [comment]
I don't think you need drupal-mode. My setup provides everything needed for web development.

- web-mode is much more powerful than php-mode
- html syntax check is already setup, all you need to do is install tidy (a cli tool from w3c)
- spell check is working out of the box, you only need install aspell, aspell-en
- you can use find-and-ctags to create/update TAGS automatically
- auto-complete works out of box by company-mode if you TAGS are created
- find-file-in-project provides file navigation 
- ....

**Comment by dashohoxha** [comment]
Thanks for your answer. You are right about what you say.

But drupal-mode also supports some Drupal coding conventions (for example about whitespace and indentation, uppercase/lowercase, etc.) Also it reckognizes the files with extensions .inc, .profile, .module etc. as PHP files, reckognizes .make as a makefile, etc.

In specific domains general rules don't work 100% well, and that's why Emacs supports different editing modes.

**Comment by redguardtoo** [comment]
drupal-mode is minor mode, so you can use drupal-mode  plus web-mode (or php-mode) without any problem.

**Comment by dashohoxha** [comment]
It works by simply installing drupal-mode package from the package list. No tricks or complicated things.
It would be better if this package (drupal-mode) was installed automatically, but it is not a big problem.
