### ISSUE TITLE
recentf 没有正确记录最近打开的文件

### ISSUE THREAD

**Issue by huchhong** [redguardtoo/emacs.d#396]
我比较喜欢用recentf这个功能。但是使用你的配置过程中发现以下问题：
1.  recentf-mode 没有默认打开。我按EmacsWiki里说明的在init.el里加入了下面的代码
```
(require 'recentf)
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(global-set-key "\C-x\ r" 'recentf-open-files)
```
保存后，发现recentf-mode默认打开了，可是配置的快捷键 C-r 却没有起作用，不知道这是为什么？
2.  在用命令recentf-open-files查看最近打开的文件的时候，发现没有正确记录最近打开的文件。比如上一次编辑中打开了文件init.el。 然后关闭emacs，重新打开，执行recentf-open-files发现没有init.el这个文件，却有更早之前打开的文件记录。

**Comment by redguardtoo** [comment]
`grep recentf ~/.emacs.d/lisp/*.el`

I lazy-load the recentf-mode to speed up emacs startup.

besides, I use ivy-recentf (press `,rr`).

check below setup in init-misc.el:
```lisp
;; {{ recentf-mode
(setq recentf-keep '(file-remote-p file-readable-p))
(setq recentf-max-saved-items 1000
      recentf-exclude '("/tmp/"
                        "/ssh:"
                        "/sudo:"
                        "/home/[a-z]\+/\\."))
;; }}
```
