### ISSUE TITLE
有什么方法静默警告消息的输出？

### ISSUE THREAD

**Issue by huchhong** [redguardtoo/emacs.d#397]
我正在尝试helm的功能。第一次执行helm-buffers-list的时候，最下面一个窗口是一个警告窗口：
```
~/.emacs.d/site-lisp/helm/helm-types.el:Warning: Unused lexical variable `scoped-class'
```
这样的窗口看起来很不舒服，特别是上面还有两个helm的窗口。当然第二次执行的时候就不会这样了。

那么有什么办法可以静默警告消息的输出？我觉得这应该能带来比较好的体验。

**Comment by redguardtoo** [comment]
You need ask helm developer. Currently I'm using swiper/ivy-mode instead of helm-mode.
