### ISSUE TITLE
speedbar 怎么只显示当前文件的tag，且全部展开

### ISSUE THREAD

**Issue by huchhong** [redguardtoo/emacs.d#399]
这几天一直在寻找emacs类似vim里taglist这样的功能。找来找去，都指向了speedbar。我在你的配置里也看到了speedbar的配置。但是我只想要taglist这样的简单功能即可，不需要speedbar的目录功能，这样导致每次打开speedbar还需要定位到当前文件，而且所有tag居然还进一步折叠起来，太麻烦了。

有办法可以达到这一需求吗？

**Comment by redguardtoo** [comment]
看README关于init-evil.el， 具体来说搜索imenu

任何提到speedbar的文章，以5年前的标准算都过时了。

建议读我的”一年成为Emacs高手“一文。

**Comment by huchhong** [comment]
没有理解你的意思，init-evil.el里只看到定义了三个imenu的函数，和我想要的功能没有关系。
google上查imenu，只找到一个imenu list，不是很满意。

**Comment by redguardtoo** [comment]
`M-x ivy-imenu-goto`

**Comment by stevenswong** [comment]
ivy-imenu-goto能不能像helm-imenu一样，只占用当前窗口？

**Comment by redguardtoo** [comment]
no, ui is provided by swiper, actually, ask swiper developer for more details.

**Comment by huchhong** [comment]
我试了ivy-imenu-goto，效果还不错，但不是我想要的。我假设的场景是浏览不熟悉的代码，首先需要对这个文件内有大体的了解，vim的taglist能提供这个功能，ivy-imenu-goto提供的是快速跳转的功能，不适合这个场景。而speedbar折叠的太厉害，不够直接。

**Comment by huchhong** [comment]
我想了一下，如果将ivy-imenu-goto的窗口改为垂直分屏，效果就会好很多，因为大家的屏幕大都是宽屏，有足够的空间分出一个窗口，这样ivy-imenu-goto就可以显示更多的符号。

可以修改ivy-imenu-goto达到这一点吗？

**Comment by redguardtoo** [comment]
这个是ivy-mode控制的，我是做不到的。

作为ivy-mode用户，我的理解是因为生产代码的imenu item实际是很长一行，放到侧边不能完整显示整1行。另外现实应用都是多个子窗口，所以宽屏还是不够宽。

imenu和ctags用的都是同样的regular expression，所以本质上是一回事。

如果只是看overview的话，有很多方法，比如，
```lisp
(defun my-overview-of-current-buffer ()
  (interactive)
  (set-selective-display (if selective-display nil 1)))
```

**Comment by huchhong** [comment]
多谢
