### ISSUE TITLE
C++代码自动补全问题

### ISSUE THREAD

**Issue by huchhong** [redguardtoo/emacs.d#400]
你的配置里关于C++补全部分的配置是哪些代码？ 能达到比较好的语法解析效果吗？（我对ctags对C/C++的解析效果不满意，特别是C++）。

**Comment by redguardtoo** [comment]
check my plugin cpputils-cmake, at least read its README.

**Comment by huchhong** [comment]
我大概了解了一下cpputils-cmake集成的那些插件，我得到以下结论：
1. 如果是cmake工程，利用irony-mode可以实现完好的语义解析。如果是make工程，还可以利用bear构造compile flags database。但是bear需要起码监控一次build过程才能建立数据库，显然不适合实时代码编辑过程的语法解析。
2. 如果仅仅利用semantic和auto-complete-clang，我试验了一下，并不理想

我平时绝大部分接触的都是make工程，对这种工程的自动补全有什么好的建议？

**Comment by redguardtoo** [comment]
好像没办法，手动设置，就是告诉你用的plugin（比如company-clang）头文件位置。

**Comment by huchhong** [comment]
还是多谢回复
