### ISSUE TITLE
[求助]终端下使用Emacs，一些组合键没法使用的问题，怎么解决？

### ISSUE THREAD

**Issue by nasoundead** [redguardtoo/emacs.d#402]

**Comment by redguardtoo** [comment]
what keys? If you are using my setup, you should have no issue.

**Comment by nasoundead** [comment]
比如“Shift”相关的组合键，我是一个初学的菜鸟，听从你的建议，在终端下使用emacs（cygwin），先从org-mode开始熟悉，发现好多组合键需要用到“shift”。请大侠指点。

**Comment by redguardtoo** [comment]
for example?

**Comment by nasoundead** [comment]
M-S-RET   插入一个同级TODO 标题 
M-S-LEFT/RIGHT   将子树升/降级 
M-S-UP/DOWN   将子树上/下移

**Comment by redguardtoo** [comment]
that's not my setup, it's terminal or org-mode issue, maybe org-mode has not updated their doc. I've already double checked with native emacs. `C-h m` and find the command. Either `M-x command` or assign new hotkey

**Comment by nasoundead** [comment]
ok, it's terminal issue, i'll assign new hotkey to bypass. Thanks for your timely responses.
