### ISSUE TITLE
请问c++-mode如何支持#if 0的颜色注释

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#403]
hi，
在c++-mode，假设用 #if 注释，如下：
#if 0
something
#endif 

请问如何让被注释部分something的颜色，变成跟行注释//的颜色一样？

**Comment by redguardtoo** [comment]
http://stackoverflow.com/questions/4549015/in-c-c-mode-in-emacs-change-face-of-code-in-if-0-endif-block-to-comment-f

just search #if 0 c++ mode emacs

**Comment by stevenswong** [comment]
好的，谢谢。
