### ISSUE TITLE
创建新的目录时Emacs卡死

### ISSUE THREAD

**Issue by CangWolf** [redguardtoo/emacs.d#404]
请教前辈一个问题，当打开一个新目录中的文件时，会提示M-x mkdir来创建目录，但是输入之后就会卡死，在Debain Linux下．顺便问下会考虑增强java的支持吗

**Comment by redguardtoo** [comment]
press `C-g`. I can mkdir under debian. I don't use java, so have to add your own java plugins. I don't think Emacs can replace IDE on Java/C#

**Comment by CangWolf** [comment]
谢谢你．我今天把emacs升到24.5.1就可以了，也不会卡死．重现不了了，不过之前卡死之后什么按键都没有效果，右上角的关闭按钮　也没反应，只能去命令行里　kill.  
关于java：有时候需要改动很少的几个文件，启动一个IDE感觉有点儿慢．很感谢你提供的java相关Snippet

**Comment by redguardtoo** [comment]
gtags + grep is enough for minor editing of java

**Comment by CangWolf** [comment]
多谢　我去学习一下gtags
