### ISSUE TITLE
打开一个5000行c++的文件emacs需要15秒正常么

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#406]
你好，请问这正常吗？

linux机器配置是比较高级的，当前负载也比较低，init-cc-mode.cc是最新的。

GNU Emacs 24.5.1

谢谢！

**Comment by redguardtoo** [comment]
comment out below code in init-cc-mode.el,
```lisp
(when buffer-file-name
    ;; c-eldoc (https://github.com/mooz/c-eldoc)
    (c-turn-on-eldoc-mode)

    ;; @see https://github.com/redguardtoo/cpputils-cmake
    ;; Make sure your project use cmake!
    ;; Or else, you need comment out below code:
    ;; {{
    (flymake-mode 1)
    (if (executable-find "cmake")
        (if (not (or (string-match "^/usr/local/include/.*" buffer-file-name)
                     (string-match "^/usr/src/linux/include/.*" buffer-file-name)))
            (cppcm-reload-all)))
    ;; }}

    )
```

**Comment by stevenswong** [comment]
没有作用，仍然是15s，emacs的cpu 100%

**Comment by stevenswong** [comment]
2秒

**Comment by redguardtoo** [comment]
Send me 5000 line C++ file to chenbin.sh AT gmail

**Comment by stevenswong** [comment]
https://github.com/baidu/tera/blob/master/src/master/master_impl.cc

**Comment by redguardtoo** [comment]
update to my latest setup.

If there is still issue, comment out `init-cc-mode.el` in init.el

if there is still issue, edit generic-prog-mode-hook-setup in init-misc.el

**Comment by stevenswong** [comment]
ok if and only if commented out generic-prog-mode-hook-setup in init-misc.el, cost 2 second.

**Comment by stevenswong** [comment]
Just disable (require 'fic-mode) and (fic-mode 1) in generic-prog-mode-hook-setup, it also works. 

Thank you!

**Comment by redguardtoo** [comment]
Cool
