### ISSUE TITLE
如何自定义卸载插件

### ISSUE THREAD

**Issue by HapCoderWei** [redguardtoo/emacs.d#407]
你好,我clone了你的配置文件,在第一次启动时,emacs自动帮我下载好了所有需要的插件并配置好了,这很棒!但是,我想自己试着配置下emacs,所以我想在你的配置文件的基础上通过elpa卸载掉一些不用的插件,我发现我通过elpa卸载的插件在重启emacs之后,又会自动装上,请问在哪里修改配置可以减少这些插件的联网检测和自动安装.

**Comment by redguardtoo** [comment]
edit init-elpa.el

Basically I don't remember manage packages with `M-x list-packages`, everything should be written down in ~/.emacs.d/lisp/*.el, so you always get unified setup on all platforms and you can easily grep your setup.

**Comment by HapCoderWei** [comment]
Oh, I got it. Thanks a lot!
