### ISSUE TITLE
org-agenda-list

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#408]
你好！我想在emacs打开的时候就显示org-agenda-list，我在init.el里加了(org-agenda-list t)，这样出现了错误。是不是这样不对啊？那应该如何设置啊？望不吝赐教，谢谢！

**Comment by redguardtoo** [comment]
init-org.el, besides `C-h org-agentda-list`

**Comment by lxeg0429** [comment]
下面是运行 C-h f org-agenda-list 之后显示的代码，但是我不知道怎么设置，还请指教。
![default](https://cloud.githubusercontent.com/assets/16031564/12693370/f86938a6-c742-11e5-971d-be892c7e3b3d.png)

**Comment by redguardtoo** [comment]
(org-agenda-list) at the end of init.el

**Comment by lxeg0429** [comment]
出现错误，不知道是什么原因。
![default](https://cloud.githubusercontent.com/assets/16031564/12693633/521e8b2e-c74a-11e5-94bb-b4c02bb813b4.png)

**Comment by redguardtoo** [comment]
sorry, update from my setup, then insert `(org-agenda-list)` into init-misc-lazy.el

**Comment by lxeg0429** [comment]
It worked. Thank you!
