### ISSUE TITLE
字体设置与日历显示

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#409]
你好！我在init.el里面设置的中英文字体，代码如下：
;; Setting English Font
(set-face-attribute
 'default nil :font "Arial 12")
;; Setting Chinese Font
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font)
                    charset
                    (font-spec :family "Microsoft Yahei" :size 16)))
设置之后，字体显示没有问题，但是calendar的显示出现问题，出现排版错乱。

**Comment by redguardtoo** [comment]
https://www.google.com.au/search?q=emacs+%E7%AD%89%E5%AE%BD%E5%AD%97%E4%BD%93&ie=utf-8&oe=utf-8&gws_rd=cr&ei=Sy6sVqr2J6fTmwXf2qeADQ
