### ISSUE TITLE
smart-mode-line

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#410]
你好！我想用smart-mode-line，我下载了它的源文件，解压到site-lisp文件夹，然后在init.el里面把原来的modeline注释掉，然后加上(require 'smart-mode-line) (sml/setup)，重新运行时出错，不知道为什么会这样，还请指教。谢谢！

**Comment by redguardtoo** [comment]
https://github.com/Malabarba/smart-mode-line

there is nothing special in my setup, just follow its original installation guide.

**Comment by lxeg0429** [comment]
原来用的你的配置按照smart-mode-line的设置进行配置是没有问题的，现在的你的配置改了好多东西，我尝试了多次，一直配置不好。

**Comment by redguardtoo** [comment]
Not me, just install smart-mode-line through elpa, then insert its setup code into init-misc.el. I've already tested.

Those packages are keep changing.

**Comment by lxeg0429** [comment]
怎么才能在elpa上面安装smart-mode-line啊，M－x package-list-packages之后找不到smart-mode-line。

**Comment by redguardtoo** [comment]
It's there,

**Comment by lxeg0429** [comment]
![default](https://cloud.githubusercontent.com/assets/16031564/12708078/a1f883c4-c8d6-11e5-84d1-4818bdca9d8f.png)

**Comment by redguardtoo** [comment]
![162125-01_1920x1080](https://cloud.githubusercontent.com/assets/184553/12709553/627cbb7c-c901-11e5-91de-05202896dcc5.png)

I also double checked stable.melpa.org, http://stable.melpa.org/#/smart-mode-line

If you use my setup and doesn't change init-elpa.el ...

**Comment by lxeg0429** [comment]
我原来安装的离线稳定版，所以不行吧，我现在重新下载了最后的配置，安装好了，谢谢！

**Comment by redguardtoo** [comment]
离线稳定版是给北朝鲜伊朗人民用的,中国大陆目前还没有那么惨.
