### ISSUE TITLE
emacsformacosx进入term模式下中文显示为?????，命令行下的emacs又能正常显示

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#411]
你好！请问这个是什么问题？

http://emacsformacosx.com/

谢谢

**Comment by redguardtoo** [comment]
setup your terminal.app, besides, double check `locale` in shell.

This is terminal issue instead of Emacs issue. Make sure you choose correct font file for your terminal.

**Comment by redguardtoo** [comment]
see https://github.com/tumashu/chinese-fonts-setup
