### ISSUE TITLE
go-mode

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#414]
请教，是这样加载go-mode吗？

          (add-to-list 'load-path "~/.emacs.d/site-lisp/go-mode")
          (require 'go-mode-load)

我是这样填加到init.el之后的。不知道您的方式是什么。(我几乎不懂elisp，请多解释几句)

**Comment by redguardtoo** [comment]
check its readme https://github.com/dominikh/go-mode.el
