### ISSUE TITLE
evil与org-mode关于Shift a的冲突

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#418]
在evil模式中，A(恰为Shift a)用于转至句尾插入状态，在org-mode中是弹Agenda Commands列表。请问如何取消后者动作，仅保留这个快捷键的前一功能？

**Comment by redguardtoo** [comment]
b69a7a0 less evil hotkeys in org-mode (Chen Bin)

**Comment by yangdaweihit** [comment]
thanks
