### ISSUE TITLE
my-grep

### ISSUE THREAD

**Issue by kevincode** [redguardtoo/emacs.d#419]
您好，我调用你的 my－grep 函数搜索后，只是跳出一个空的buffer，没有显示搜索结果。
看了my－grep函数代码，也没找出原因。想着是不是我搜索输入不对，麻烦，您能写个
你的my－grep的搜索例子么？谢谢。

OSX 10.11.3
emacs 24.5.1

最后感谢下您，让我再次拿起emacs大杀器。

**Comment by redguardtoo** [comment]
my-grep grep the files in project which is the root directory containing ".git/.svn/.hg".
you also need have grep installed. if you just want to grep the current directory, use `M-x grep`

**Comment by kevincode** [comment]
谢谢回复。
cli grep version ：2.5.1-FreeBSD
检索后提示： grep：warning：recursive search of stdin

我推测应该是：(setq cmd (format "%s -rsn %s \"%s\""                                                                        
                                           grep-program my-grep-extra-opts keyword))   
这句中cmd 中没有 路径参数 导致的问题。
如果，我的关注点偏离了，请指正。谢谢。
M－X grep 检索正常。

**Comment by kevincode** [comment]
我明白了，osx 系统的grep版本和linux的grep在FILEs参数缺省时，的处理不一样，导致了上述问题。
谢谢。

**Comment by redguardtoo** [comment]
058c026 support osx grep (Chen Bin)
thanks
