### ISSUE TITLE
more elpa packages?

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#421]
看到了init-elpa里75行左右：
```
;; Feel free to add more packages!
```
在下面那个`defvar`结束的地方173行写着：
```
Don't install any Melpa packages except these packages
```
不大理解这个`melpa-include-packages`
意思是要安装这些？还是就是弄个list这些能被看到

**Comment by redguardtoo** [comment]
下面那个173行不用看， 是steve purcell写的，不是我写的。

9c10640 clean init-elpa.el (Chen Bin) 我清理了一下文档
