### ISSUE TITLE
GUI模式terminal中文乱码

### ISSUE THREAD

**Issue by zarzen** [redguardtoo/emacs.d#422]
终端下面的版本调出来的multi-term是好的
但是gui下面就会这样：
![screen shot 2016-03-05 at 5 55 43 pm](https://cloud.githubusercontent.com/assets/1150493/13547032/91cfbeb0-e2fb-11e5-9903-012bd403819a.png)
已经可以确认环境编码是utf-8
也使用了：
```
M-x set-terminal-coding-system utf-8-unix
```
还是不见好。
然后`eshell`下面是好的

Mac OS
emacs24.5.1

**Comment by redguardtoo** [comment]
参考”Setup fonts in GUI Emacs“，我的设置是原生态，原有的font和按键基本都没改。
