### ISSUE TITLE
使用c++无法跨文件函数声明与实现跳转

### ISSUE THREAD

**Issue by maozhiyong** [redguardtoo/emacs.d#423]
您好，使用了您的配置，我在使用M-x ct,显示no tags table loaded;try M-x visit-tag-table。然而我使用M-x visit-tag-table显示..我的工程目录...is not a valid tag table

**Comment by redguardtoo** [comment]
ggtags.el + gnu global, I use ",gt" and ",gr" for find definition and reference.

**Comment by maozhiyong** [comment]
那gnu global您的配置里面集成了吗？还是需要我自己去mac osx终端下载，然后自己创建database?

**Comment by redguardtoo** [comment]
`global --version` in shell, I don't know if it's already bundled with osx. if not, install it manually. use http://brew.sh/

**Comment by maozhiyong** [comment]
thanks,i have solved it when i brew install global. Then i use gtags in my project file . gt and gr is already can use!
