### ISSUE TITLE
使用evil,同时使用外部的输入法(搜狗)输入中文,如何自动切换输入法(这不是bug,只是求助)

### ISSUE THREAD

**Issue by gttiankai** [redguardtoo/emacs.d#424]
你好!首先非常感谢您对emacs的普及做出的工作.

我现在遇到一个问题,自己解决不了,在reddit等网上搜了很多资料,但是都没有解决,只能来找你了!
在现在使用evil模式时,同时使用外部的输入法(搜狗或者系统自带的输入法),进行中文的编辑的时候,切换模式的的时候,遇到中英文切换的问题.
例如:使用中文在编辑,切换到normal模式,输入法就需要切换到英文.然后在切换到insert模式的时候,就又切换到中文,很麻烦!.其实就是切换到normal模式,自动切换到英文,回到insert模式,切换到原来的中英文状态.类似于vim中的ybian/smartim这个插件

有没有什么办法可以解决这个问题吗?本人不怎么会elisp语言.

你的blog中的<<Switch input method in evil-mode (在Evil中快速切换输入法)>>这篇文章我也看了,发现eim是可以自动切换的,但是eim这个输入法实在用不惯.

希望您能指点一下!

ps: 
os  ox s 10.11
emacs version 24,5

**Comment by redguardtoo** [comment]
好像没办法，这也是我为什么用chinese-pyim的原因（不是eim),不过chinese-pyim很优秀，支持搜狗词库，不过由于版权的原因没有打包进去，你到chinese-pyim的网站问一下就知道了。
