### ISSUE TITLE
Starting "look" process... 造成延迟

### ISSUE THREAD

**Issue by gttiankai** [redguardtoo/emacs.d#425]
你好，今天更新了你的配置，发现和你以前有点卡顿，尤其是打字的时候，
分析发现后台执行一个程序Starting "look" process... 
请问怎么关闭这个进程！
多谢

**Comment by gttiankai** [comment]
any one can help me?

**Comment by redguardtoo** [comment]
what's your major-mode? on what platform?

**Comment by redguardtoo** [comment]
`M-x toggle-company-ispell` or just comment line `(add-to-list 'company-backends 'company-ispell)` in init-company.el.

company-ispell will auto-complete english words when your typing english in org-mode.

**Comment by gttiankai** [comment]
You are so nice! Thank you very much！
