### ISSUE TITLE
你好，我使用yasnippet 作为company-backends导致company不能补全我输入过的字符

### ISSUE THREAD

**Issue by gyzclw** [redguardtoo/emacs.d#426]
``` html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <div class="helloword">
        
    </div>

</html>
```
再输hello 无法补全helloworkd

**Comment by redguardtoo** [comment]
yasnippet should be at the end of the list, that's company-mode's feature, if the backend at the beginning of the list can provide candidates, the behind backends will NOT be called.

**Comment by redguardtoo** [comment]
btw, check my git log, there is reason why I don't use yasnippet with company or auto-complete and assign new hotkey to yasnippet.

**Comment by gyzclw** [comment]
thank you
