### ISSUE TITLE
terminal模式中的tab键失效

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#427]
在进入terminal模式(C-x e)中，tab键自动补齐功能失效，可能有人问过这个问题，请问如何解决。
注：我安装了oh my zsh，模糊记得有人说安装过这个之后，就出现了这个问题。见#386

**Comment by redguardtoo** [comment]
change init-term-mode.el, `(defvar my-term-shell "/bin/bash")`

**Comment by yangdaweihit** [comment]
how to change?  `(defvar my-term-shell "/bin/zsh")` not proved to be working.

**Comment by redguardtoo** [comment]
Can't reproduce, I need more details.

**Comment by yangdaweihit** [comment]
Sorry for my poor description. I changed `my-term-shell` as "/bin/zsh" in init-term-mode.el, but TAB could not provide auto-complete function in terminal mode. 
![screenshot_2016-04-15_09-57-16](https://cloud.githubusercontent.com/assets/10682606/14549217/9a11c8ba-02f0-11e6-940d-0c9f8b8abe0f.png)

**Comment by redguardtoo** [comment]
see http://superuser.com/questions/361566/zsh-completion-will-not-work-in-emacs-shell, try `M-x multi-term`

**Comment by yangdaweihit** [comment]
mutli-term也没凑效。

**Comment by redguardtoo** [comment]
I don't have gui emacs now. Will test at home.

**Comment by yangdaweihit** [comment]
昨天更新了配置，这个问题已经消失了。
