### ISSUE TITLE
块拷贝时常失效

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#428]
`C-x r w`时而失效，拷贝不了块。但`C-x r y`和`C-x r k`总是好用的。在执行块拷贝时会弹出窗口布置提示，猜想是否和某个功能冲突了，请教如何使块拷贝命令有效。
![screenshot_2016-04-15_11-25-13](https://cloud.githubusercontent.com/assets/10682606/14550638/e790659a-02fc-11e6-97d9-486bc0dcdb3a.png)

**Comment by redguardtoo** [comment]
That's default setup. `emacs -Q` you got same key binding. What guide you are reading?

**Comment by yangdaweihit** [comment]
没有读哪个指南，块拷贝的命令是在网上看到的。尝试进行块拷贝时就遇到了这个问题。刚查了下，说`C-x r w   Copy current window configuration to register.`  https://wiki.archlinux.org/index.php/Emacs
看来是命令冲突了吧。如何解决呢？

**Comment by redguardtoo** [comment]
网上教程普遍质量很低的，我写“一年成为emacs高手”一文的原因就是对这些教程不满意

如果你是初学者，建议一开始集中于文本操作，喜欢vim按键那么就是vimtutor，否则`C-h t`看emacs教程。比如拷贝块，难道不是通用的`M-w`吗？

**Comment by yangdaweihit** [comment]
基础差，见笑了。刚学了下，在evil模式中，用C-v可进行列选择，然后y (yank)和p (paste)就可以了。
