### ISSUE TITLE
使用ggtags的ggtags-find-tag-dwim跳到函数定义，有时无法实现跳转

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#429]
你好，

阅读c++代码，希望使用ggtags-find-tag-dwim跳转到函数定义时，只看到minibuff显示“Global found 1 definition”，而不会跳转到函数定义。需要再执行一遍ggtags-find-tag-dwim才实现跳转。

这种情况有时候才出现：即有时执行一次ggtags-find-tag-dwim就完成跳转。

谢谢~

**Comment by redguardtoo** [comment]
什么语言

**Comment by redguardtoo** [comment]
https://github.com/leoliu/ggtags/issues/89 有workaround，不过最好等最终方案

**Comment by stevenswong** [comment]
谢谢哈
