### ISSUE TITLE
color-themes bug with gtk3.20?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#430]
after i update my gtk+ to 3.20 version, i find a lot of applications base on gtk crash it's theme.
such as emacs menu in gui. it has no padding any more.
it is caused by css properties changed in gtk+ 3.20. 
then i update my gtk-theme. then i find emacs color-themes crash 囧
![emacsbug1](https://cloud.githubusercontent.com/assets/11417632/14577770/163af9ce-03ab-11e6-8750-f25394a0d0de.png)
![emacsbug2](https://cloud.githubusercontent.com/assets/11417632/14577777/24c372d2-03ab-11e6-82c5-0ef960d35cd2.png)

and the emacs' look change like this:
![emacsbug](https://cloud.githubusercontent.com/assets/11417632/14577787/4ade47d0-03ab-11e6-983f-dc0665646253.png)

i want to know is there anyone find the same bug as me? should i report this bug to [http://www.nongnu.org/color-theme/](url)  ?

**Comment by redguardtoo** [comment]
see https://wiki.archlinux.org/index.php/emacs

**Comment by smallst** [comment]
did you mean #Colored output issues in archwiki?
that(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on) doesn't work.

**Comment by redguardtoo** [comment]
gtk3 setup

**Comment by smallst** [comment]
可是我在整个页面里都没有找到gtk3 setup这一项内容……
事实上连setup这个词都找不到……
![untitled](https://cloud.githubusercontent.com/assets/11417632/14579493/6302936a-03de-11e6-8d3b-413faf536643.png)

**Comment by redguardtoo** [comment]
"KDE users may observe that the Emacs window does not resize properly, but rather, the resized portion is transparent and mouse clicks are sent to the underlying window. To correct this behavior, change KDE's GTK3 theme to something other than oxygen-gtk. For instance, use the Emacs theme which is included with gtk3. "

**Comment by smallst** [comment]
thank you!

in fact i hadn't find any gtk3.20 theme with emacs.css ... so i decide to use cli mode. That works fine :)

**Comment by redguardtoo** [comment]
http://linux.softpedia.com/blog/gtk-plus-3-20-2-gui-toolkit-released-to-fix-strange-blue-background-in-emacs-windows-502443.shtml

**Comment by smallst** [comment]
Thank you very much!
