### ISSUE TITLE
evil-numbers doesn't work.

### ISSUE THREAD

**Issue by ufengger** [redguardtoo/emacs.d#432]
I see there are keybindings for evil-numbers in init-evil.el, however, they don't work. It seems that evil-numbers.el is not installed.

**Comment by redguardtoo** [comment]
b16791e evil-numbers installed (Chen Bin)

What's your use case of evil-numbers?

**Comment by ufengger** [comment]
I don't use evil-numbers except when writing snippets. I am always confused about the order of TAB stops, evil-numbers could help me to control the order easily.
