### ISSUE TITLE
Tramp failed to connect.

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#434]
Maybe sometools in init-misc.el have conflicts with Tramp. When I want to edit a remote file through tramp, it always failed and told me "percent_expand: unknown key %C^M". If I comment (require 'init-misc), then everything is ok.

**Comment by ernest-dzf** [comment]
init-misc-lazy is also commented.

**Comment by redguardtoo** [comment]
more details? you use ssh?

**Comment by ernest-dzf** [comment]
Yes, I use ssh.
`ctrl-x ctrl-f`
`/ssh:pi@192.168.1.111:`
then it told me "percent_expand: unknown key %C^M".

**Comment by ernest-dzf** [comment]
some more details.

> Tramp failed to connect. If this happens repeatedly, try `M-x tramp-cleanup-this-connection`

I did as it told me, but it didn't help.

**Comment by redguardtoo** [comment]
comment out two lines containing `tramp-ssh-controlmaster-options` in init-misc.el.

Make sure you read https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org#why-is-spacemacs-hanging-on-startup at first.

It works fine on my computer.

**Comment by ernest-dzf** [comment]
Thanks!
I commented those two lines as you said, and it works.
Can you tell me what caused this problem? Maybe I should find it out myself.

**Comment by redguardtoo** [comment]
Don''t know, maybe some ssh setup.

**Comment by ernest-dzf** [comment]
I tried to replace`'tramp.%C'` with `/tmp/ssh-ControlPath-%%r@%%h:%%p` in init-misc.el. It also works.
[https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html](url)

**Comment by redguardtoo** [comment]
maybe I just comment out this line and add some faq
