### ISSUE TITLE
winner-redo is disabled?

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#435]
I know `,su` is binded to winner-undo if evil is enabled. `,xu` is binded to winner-undo too.(confused)
![2](https://cloud.githubusercontent.com/assets/16398130/14949747/fafb0466-107e-11e6-8ab6-7d5f0b379b2f.png)

But it seems that winner-redo is disabled. I can not find the hotkey of winner-redo, and also `M-x winner-redo` doesn't work.
![1](https://cloud.githubusercontent.com/assets/16398130/14949750/00458194-107f-11e6-8379-be865e01d766.png)

In the mini-buffer, it says 

> Previous command was not a 'winner-undo'
when I typed `M-x winner-redo`

**Comment by ernest-dzf** [comment]
I found an interesting thing.

I start emacs by `emacs -Q`, and then enable winner-mode. 

`c-c left` and `c-c right` work well. `M-x winner-undo` works well, but `M-x winner-redo` not. 

Isn't `c-c right` binded to `M-x winner-redo`?

**Comment by redguardtoo** [comment]
don't know. Looks it's emacs issue. I just add extra keybindings. As test, if you use keybinding instead of `M-x winner-redo` it works.
