### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#436]
I use emacs in graphical mode. I don't know why the emacs is stuck there once I use the mouse to click on the menu bar.
![4](https://cloud.githubusercontent.com/assets/16398130/14976523/ff02b08e-113e-11e6-8f67-b06e51f28e0c.png)

Also it ask me to input the password to connect with a remote machine. Even though I input the password, it failed and the emacs is stuck there. I had to kill the process in terminal.

It's a bug?

**Comment by redguardtoo** [comment]
can't reproduce on my computer.

You can always press `C-g` to quit any command.

**Comment by redguardtoo** [comment]
193cafa 2016-05-08 do NOT store back when editing tramp files
