### ISSUE TITLE
helm被去掉了？？

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#437]
为什么，感觉挺好用啊，特别是`helm-gtag`, `helm-swoop`,
去掉之后我不知道怎么浏览C工程了!

**Comment by redguardtoo** [comment]
it has performance issue.
use swiper/ivy instead

**Comment by redguardtoo** [comment]
for gtags, I can write one, that's easy.

**Comment by redguardtoo** [comment]
我给syohex提需求了，让他增加对ivy的支持，syohex是我相当尊敬的高手，我写得肯定没他好。

**Comment by redguardtoo** [comment]
this is original init-helm.el, https://github.com/redguardtoo/emacs.d/blob/c8da635/lisp/init-helm.el
you need add line `(require-package 'helm-gtags)` in init-elpa.el

**Comment by danyuhao** [comment]
感谢，我试试

**Comment by redguardtoo** [comment]
Good news. https://github.com/syohex/emacs-counsel-gtags @syohex who is also the developer of helm-gtags finally stareted gtags based on ivy-mode.

Ivy is much faster than helm
