### ISSUE TITLE
cancel auto-save-buffer idle timer

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#438]
because the auto-save-buffers is not suitable for me, so I think other people may also need a way to cancle it.

if it's useful, the code could be merged:

```lisp
(defun cancel-auto-save ()
  "cancel auto-save-buffers idle timer if found."
  (message "Try to cancel auto-save-buffers idle timer...")
  (let (timer-obj)
    (dolist (elt timer-idle-list timer-obj)
      (let* ((index-of-func 5)
             (find-func-name 'auto-save-buffers)
             (elt-func-name (aref elt index-of-func)))
        (if (eq find-func-name elt-func-name)
            (setq timer-obj elt))))
    (if (eq timer-obj nil)
        (message "Can not find auto-save-buffers idle timer, please checkout.")
      (cancel-timer timer-obj))
))
```

**Comment by redguardtoo** [comment]
what's the issue? You can still manually save the file `C-x C-s`.

**Comment by albert748** [comment]
not really an issue, but only add an toggle action to the auto-save-buffers idle timer.

most of time, I need check what changes I've done before actually save it to disk.

so I'd better to disable this auto save feature the time emacs start or toggle disable when emacs already running.

**Comment by redguardtoo** [comment]
cancel the timer make the auto-save useless, if you forgot to start the timer and your computer reset, you lose the change.

In your case, you'd better use git to track your files, so you can always `git diff` to review your change. Beside, git give you extra power like `git add -p` and `git reset -p`.

**Comment by albert748** [comment]
yep, but not all your files would be tracked by git,  in most cases, emacs's builtin save/backup feature is  useful enough

however, it's all about perspective, and up to you to use it or not.
