### ISSUE TITLE
Crayon Syntax Highlighter can not work with org2blog?

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#439]
Hello, I have seen the issues you post [here](https://github.com/punchagan/org2blog/issues/129). Do you have solved the problem about [Crayon Syntax Highlighter](https://github.com/aramk/crayon-syntax-highlighter)? It seems Crayon Syntax Highlighter can not work with org2blog out of box. 

The Crayon Syntax Highlighter checks tags like this:
`<pre>
...(my code)
</pre>`

But org2blog/wp outputs like this
```
[sourcecode]
...(my code)
[/sourcecode]
```
I tried edit the src of [ox-wp.el](https://github.com/punchagan/org2blog/blob/master/ox-wp.el)

```
(if (not sc)
        (org-html-src-block src-block contents info)
       ;;(format "[sourcecode language=\"%s\" title=\"%s\" %s]\n%s[/sourcecode]"
         (format "<pre class=\"lang:%s decode:true\" title =\"%s\"> %s\n%s</pre>" 
              (or (cdr (assoc lang langs-map)) lang "text")
              (or caption "")
              (or syntaxhl "")
              (org-export-format-code-default src-block info)))))
```

As show above, I replace

 `[sourcecode language=\"%s\" title=\"%s\" %s]\n%s[/sourcecode] `

with 

`<pre class=\"lang:%s decode:true\" title =\"%s\"> %s\n%s</pre>`.

It can help, but also introduce a new problem. If the code block has string like `<pre>` or `</pre>`, it will fail. 

So I want to escape some chars in the code block. For example, `<` is converted to `&lt;`, `>` is converted to `&gt;`. Can you give some advice? Or Is there another more elegant method to make Crayon work with org2blog/wp.

Thank you!

**Comment by redguardtoo** [comment]
Sorry, I can't help. You'd better contact the developer.
