### ISSUE TITLE
About c-eldoc-mode

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#441]
When I am programming a c source file in c-mode, it always indicates a little error in the minibuffer if my cursor stays at the code(no errors occured if my cursor was not on the code).

`eldoc error: (file error Searching for program 没有那个文件或目录 global`

If I commented out the `(require 'init-cc-mode)` in init.el, no error occured too.
Also， the c-eldoc-mode didn't work, that's to say, it didn't display the arguments of C functions in the minibuffer. Only when I type `M-x c-turn-on-eldoc-mode`, it can display the arguments of C functions in the minibuffer, and also the eldoc error I mentioned above disappeard.

**Comment by redguardtoo** [comment]
comment out line `(turn-on-eldoc-mode)` in init-misc.el

**Comment by ernest-dzf** [comment]
I have commented out line `turn-on-eldoc-mode` in init-misc.el, but it didn't work. The error still occured.

Only when I comment out those two lines，`(turn-on-eldoc-mode)` in init-misc.el and `(c-turn-on-eldoc-mode)` in init-cc-mode.el，error doesn‘t occur anymore.

**Comment by redguardtoo** [comment]
yes, but you don't have eldoc anymore.

**Comment by ernest-dzf** [comment]
so ,do you think what may causes the eldoc error? In fact, in spite of the error, I can still use the c eldoc mode on condition that  I manually type `M-x c-turn-on-eldoc-mode`, and in this situation the error disappeared.

**Comment by redguardtoo** [comment]
15da678 ggtags.el instead of c-eldoc-mode in eldoc-mode (Chen Bin)
