### ISSUE TITLE
在cygwin中使用emacs

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#442]
因为我平时还要进行嵌入式方面的开发，很多工具只有win下有，身边的同事也是windows的环境。但是我之前在linux下使用郭emacs。现在需要开发h5 node.js，作为初学者，希望这里有在cygwin下使用emacs-w32的小伙伴能给我一些建议和帮助

谢谢

**Comment by albert748** [comment]
如果确实只能用windows,建议使用msys2.

Cygwin下使用emacs有很多问题，使用中有大概率emacs卡慢，崩溃.



Thanks & Regards,
Albert (shengbo) Zhou
Global Delivery Centers
HPE Software Services
Mobile: +86 18696643030
Email: shengboz@hpe.com<mailto:shengboz@hpe.com>
Deliver Value through Expertise & Quality
[cid:image009.png@01D0EF72.1DC58AE0]

**Comment by redguardtoo** [comment]
用windows原生版本Emacs，命令行工具用cygwin，速度很快的，看我博客关于ivy，find-file-in-project的文章，windows下使用毫无问题

**Comment by danyuhao** [comment]
用原生windows , gtag, clang这些有问题吗
