### ISSUE TITLE
c-eldoc mode can not work automatically when opening a c source file

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#443]
When opening a c source file, the c-eldoc should work automatically, but it failed . I must type `M-x c-turn-on-eldoc-mode` manually, then the c-eldoc mode can work normally. 

I try to change the position of 
`(unless (or (derived-mode-p 'java-mode) (derived-mode-p 'groovy-mode))
                (my-c-mode-setup))` in init-cc-mode.el
and solved it.
As below.
````
(add-hook 'c-mode-common-hook
(lambda ()
            (unless (is-buffer-file-temp)
              ;; gtags (GNU global) stuff
              (setq gtags-suggested-key-mapping t)
              (my-common-cc-mode-setup)
              (ggtags-mode 1)
              ;; emacs 24.4+ will set up eldoc automatically.
              ;; so below code is NOT needed.
              (setq-local eldoc-documentation-function #'ggtags-eldoc-function)
               ;;以下两行原来是在前面的，移到了这里
               (unless (or (derived-mode-p 'java-mode) (derived-mode-p 'groovy-mode))
                (my-c-mode-setup))
              ))
````
I don't know if the situation is the same for you.

**Comment by redguardtoo** [comment]
It's because c-eldoc-mode fails to extract documentation and fallback to the default ggtags's eldoc which succeeded.
