### ISSUE TITLE
C++ flymake not work?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#444]
我有一段时间没有用emacs写过c++代码了，上一次用大概是半年前，各种配置都很好。

但最近在用的时候，发现flymake的语法检查没有工作，情况如下：
![untitled](https://cloud.githubusercontent.com/assets/11417632/15271674/f9258d2e-1a87-11e6-83db-bd89a6a2a3c3.png)
第16行的错误没有任何提示。用的是您最新的配置以及cpptuils-cmake中的example
另外minibuffer中的函数定义似乎也不见了，印象中半年前在光标移动到函数调用行的时候，就会有函数的定义。（像lisp语法一样）

注：尝试了cppcm-reload-all，没有任何变化。 直接执行flymake-compile会弹出编译错误窗口，但在cpp页面依然不会报错

**Comment by redguardtoo** [comment]
thanks, it's some regression bug of cpputils-cmake. please upgrade cpputils-cmake to v0.5.5

I've also add unit test to avoid such issues in the future.

**Comment by smallst** [comment]
it seems that flymake-cursor not work yet?
warning/error message not appear in minibuffer

**Comment by redguardtoo** [comment]
I will look into this.

**Comment by smallst** [comment]
oh , i find that flymake-cursor isn't installed.
after install flymake-cursor everything is ok.
