### ISSUE TITLE
git-gutter doesn't work normally in the latest commit.

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#445]
![new](https://cloud.githubusercontent.com/assets/16398130/15278880/07d2735e-1b51-11e6-9445-b0d9344e8911.png)
In the latest [commit,](https://github.com/redguardtoo/emacs.d/commit/614c7f2718c7617bea212305a7abf146d60d8de2) the git-gutter can't show whether the file has been changed. In the last commit, it works normally. 

I don't know if the situation is the same for you .

**Comment by redguardtoo** [comment]
thanks for reporting this. I have to revert. I will raise a issue to git-gutter user.
