### ISSUE TITLE
emacspeak 导致emacs快捷键失效

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#447]
今天突然想试试emacspeak，于是在（自认为）装好emacspeak之后，在emacs里运行emspk函数，听见了
“this is emacspeak” 之后，不管是evil的快捷键，还是M-x, C-x，都没有任何响应，minibuffer中显示back to top level.如下：
![screenshot_2016-05-17_11-41-57](https://cloud.githubusercontent.com/assets/11417632/15310665/e9ace4c0-1c24-11e6-81af-1cb555dc8279.png)

试图在google上搜索back to top level问题但没有找到答案……（可能是英文水平问题= =）
在X环境下还可以通过点击关闭按钮来关闭emacs，console下则没有任何退出的办法，是的，即使f10唤出菜单也没办法，将光标移动至quit就会出现back to top level，然后菜单就失去焦点。

不知道是否与我自己配置的emacspeak有关？
安装的是emacspeak 44
也配置了espeak

**Comment by redguardtoo** [comment]
interesting, I tried emacspeak several times and never succeeded. Sorry can't help.

**Comment by smallst** [comment]
ok, maybe next time i will try it again. Thank you!

**Comment by smallst** [comment]
结果我居然调好emacspeak了2333333
从github下源码编译后根据espeak的配置编译server/linux-espeak使server/espeak命令可正常运行后emacspeak就能用了，感觉还是非常有趣的功能

**Comment by redguardtoo** [comment]
写篇文章吧，我一直觉得语音编程的境界很高，但是高质量的文章几乎没看到过。

**Comment by smallst** [comment]
emacspeak 好像只有text-to-speach的功能，speach-to-text我还在试，有时间会写文章
