### ISSUE TITLE
buffer之间跳转

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#448]
例如,默认在Emacs中移动子窗口焦点不是很方便.需按”C-x O”多次.我找到了emacs插件switch-window,只要按”C-x O”一次,会有提示子窗口编号,接下来只要输入编号就可以了.但还有改善空间,我又找到了window-number.el,只要按”M-NUM”就可以了.

window-number.el已完美,但Alt键还是有点慢,我结合evil和evil-leader,可以按逗号和数字飞速切换子窗口了.

我git clone 你的emacs.d , 在切换buffer的时候，使用M+buffer的序号，是可以切换buffer的。但是 “使用逗号和数字”就没法切换。输入的逗号和数字，会显示在当前的buffer中

**Comment by redguardtoo** [comment]
in evil-normal-state

**Comment by vipzrx** [comment]
现在可以摸索出来了。ctrl+z 切换到vi模式，ctrl+o 进入正常模式，等待命令，可以识别逗号开头的命令

切换的过程中，只看到提示说进入到emacs模式，没有提示进入vi模式

**Comment by redguardtoo** [comment]
把vimtutor完成
