### ISSUE TITLE
emacs和外部程序共享粘贴板

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#449]
我记得之前是有个设置命令的，写在配置文件中。在外部程序复制之后，使用ctrl+y，就可以粘贴到emacs的buffer中了。

现在不能实现这样的操作，是因为：
1 你的配置文件中没有这样的设置吗？
2 因为我是在cygwin中、ssh到virtualbox中的debian虚拟机中使用字符界面emacs，是不是那样的命令，不支持这些环境？

**Comment by redguardtoo** [comment]
我不这样设置，没什么优点，如果我使用剪贴板内容，直接使用就可以了。为什么还要和kill-ring同步。参考我写的一系列文章和我开发的cliphist插件。

我的设置恰恰就是在任何环境下都支持剪贴板。

**Comment by vipzrx** [comment]
考虑到很多在linux下的工具，在cygwin中替代会有问题，而且出了问题涉及到windows、cygwin、linux，不好排查。 所以我现在是在windows上安装了虚拟机virtualbox，里面跑的是字符界面的dibian。vb用headless模式启动，mintty下ssh到虚拟机中的debian，使用字符界面的emacs。由于没有图形界面，就无法使用图形界面的粘贴板。 所以现在windows就和emacs无法复制粘贴文字。

而且 mintty有复制粘贴的快捷键ctrl+ins shift+ins，但是在debian中的emacs无法粘贴复制的内容

**Comment by vipzrx** [comment]
s/dibian/debian/

**Comment by redguardtoo** [comment]
http://blog.binchen.org/posts/copypaste-in-emacs.html

**Comment by vipzrx** [comment]
Remote clipboard

Use below command to ssh the Linux server. Then you can share the clipboard between the server and your local computer seamlessly. No furthe setup needed.

|ssh -X -C -c blowfish-cbc,arcfour $@
|

ssh -X 是在进行x11转发，这个还是需要安装x11的吧？


上面那个使用xsel的方案，是针对字符界面的emacs的吧？

xsel已经在你的emacs.d中设置好了，还是需要我自己设置下？

**Comment by vipzrx** [comment]
Insert below code into ~/.emacs. Use 'M-x yank-to-x-clipboard' to copy, 'M-x paste-from-xclipboard' to paste

使用xsel的方法，也是需要安装x11吗？

**Comment by redguardtoo** [comment]
yes
