### ISSUE TITLE
开启semantic-mode后，有些类型变量无法补全（如 string）

### ISSUE THREAD

**Issue by ernest-dzf** [redguardtoo/emacs.d#451]
`M-x semantic-mode`，开启semantic-mode后，有些类型变量无法补全，如（string，list<int>）；有些则可以，如自定义的类，c++11 的array类型
![1](https://cloud.githubusercontent.com/assets/16398130/15646344/b0ade76c-268f-11e6-8aa0-e2201c317221.png)

![2](https://cloud.githubusercontent.com/assets/16398130/15646367/d1babd5e-268f-11e6-98ae-55b886aeddc2.png)
第一张没有开启semantic-mode，第二张开启了semantic-mode。

**Comment by redguardtoo** [comment]
semantic is kind of obsolete now. Use other completion. See https://github.com/company-mode/company-mode/issues/525 for people's comment there.

For example, company-gtags is easy to setup and quick enough.
