### ISSUE TITLE
color-theme : Error during download request: Not Allowed

### ISSUE THREAD

**Issue by wps712** [redguardtoo/emacs.d#452]
Hi, appreciate your great job. There is a problem on the start up of emacs. It seems that the url "http://www.emacswiki.org/cgi-bin/wiki.pl?ColorTheme" can not be reached. Here is the debugging information. Thanks!

Debugger entered--Lisp error: (error "Error during download request: Not Allowed")
  signal(error ("Error during download request: Not Allowed"))
  error("Error during download request:%s" " Not Allowed")
  package-handle-response()
  package-download-tar(color-theme "20080305.34")
  package-download-transaction((color-theme))
  package-install(color-theme)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install pa$
  (if (package-installed-p package min-version) t (if (or (assoc package package-a$
  require-package(color-theme)

**Comment by redguardtoo** [comment]
works fine on my computer, could be network issue.
