### ISSUE TITLE
ess加载问题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#453]
这个问题不存在于redgurardtoo/emacs.d之中。只因我长期使用您的配置，又在工作中遇到ess插件的问题，故麻烦您帮助看看。

ess (http://ess.r-project.org/) 是一个emacs的插件，用于统计学软件的脚本程序编写。在安装和使用ess时都需要翻墙才能正常工作。特别在加载ess时，如果在内网就会卡死。我本人看不懂elisp代码。可否请您试用该插件，检查代码中哪里需要连接网络，使我可以注释掉，不再依赖翻墙才能正常加载该插件。

**Comment by redguardtoo** [comment]
installation is fine, but looks it depends on some program Splus which I don't know how to install. Sorry, can't help.

ess exists in melpa.org, If it's difficult to access melpa, you can go to https://emacs-china.org/ for help. As I know, they've built some mirror sites of melpa.

**Comment by yangdaweihit** [comment]
Splus is kind of statistics software as R, the latter is installed in my system. Anyway, thanks for your attention on my question. I'll look for answer in other ways.

**Comment by redguardtoo** [comment]
try search/ask at emacs.stackexchange.com,

https://www.google.com.au/search?q=ess+site%3Aemacs.stackexchange.com&ie=utf-8&oe=utf-8
