### ISSUE TITLE
how to run `git commit` in emacs?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#454]
i find log "280de32 - bye magit (11 months ago) " in your configuration, but not find new git commit command.
is there any way to commit git in emacs now?
or is it not recommanded to run `git commit` in emacs?

**Comment by redguardtoo** [comment]
`magit` is great. The reason I don't use magit is I'm already experienced cli git user. Besides, magit requires emacs 24.4+, but I need support 24.3..

You can install magit or use `M-x vc-next-action`.instead.

**Comment by smallst** [comment]
OK, thank you for response
