### ISSUE TITLE
慢，好慢

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#457]
你好，用这个最新的配置工作在evil模式的时候，感觉键盘移动特别的慢。
比如打开init.el，用hjkl移动浏览的时候，感觉比spacemacs的配置要慢很多，连续按住一个键比如'k'不放的时候明显卡顿。
尤其是打开c工程里的文件（gtag）的时候，慢的无法忍受，经常移动一个字符要卡3~5秒，这个情况应该怎么debug呢？？？
我是win7+cygwin64的环境，在suse 11里面也是这样

**Comment by redguardtoo** [comment]
`C-h v major-mode`

**Comment by danyuhao** [comment]
公司的文件，没法发，我看看能不能自己整个文件试试

**Comment by danyuhao** [comment]
有个明显得问题就是用了 hs-hide-all 之后，基本就卡住不动了

**Comment by danyuhao** [comment]
major-mode is a variable defined in `C source code'.
Its value is c-mode
Original value was fundamental-mode
Local in buffer mmx_process.c; global value is turn-on-evil-mode

  Automatically becomes buffer-local when set.

Documentation:
Symbol for current buffer's major mode.
The default value (normally `fundamental-mode') affects new buffers.
A value of nil means to use the current buffer's major mode, provided
it is not marked as "special".

When a mode is used by default, `find-file' switches to it before it
reads the contents into the buffer and before it finishes setting up
the buffer.  Thus, the mode and its hooks should not expect certain
variables such as `buffer-read-only' and `buffer-file-coding-system'
to be set up.

You can customize this variable.

[back]

**Comment by danyuhao** [comment]
关了flyspell-mode好像好点，flymake mode不知道怎么关

**Comment by danyuhao** [comment]
另外我要去掉 ggtags 的话，是不是init evil也得改
···
 1-*- mode: grep; default-directory: "~/.emacs.d/lisp/" -*-
 2Grep started at Sat Jun 18 14:32:10
 3
 4find . -type f -exec grep -nH -e ggtags {} +
 5./init-evil.el:261:        (ggtags-global-mode . emacs)
 6./init-evil.el:487:       "gt" 'ggtags-find-tag-dwim
 7./init-evil.el:488:       "gr" 'ggtags-find-reference
 8./init-elpa.el:262:(require-package 'ggtags)
 9./init-cc-mode.el:96:      (ggtags-mode 1)
10./init-cc-mode.el:99:      (setq-local eldoc-documentation-function #'ggtags-eldoc-function)
11
12Grep finished (matches found) at Sat Jun 18 14:32:10
···

**Comment by danyuhao** [comment]
卡顿问题的主要原因知道了，文件太大了，找了个2000行的文件试了下，很快

**Comment by redguardtoo** [comment]
- for gtags, all you need care is init-cc.mode.el
- comment out `(flymake-mode 1)` in init-mode.el
- there is no reason you need touch init-misc-lazy.el, Everything is already optimized.
- turn off linum-mode for c file, check `linum-mode-inhibit-modes-list` in init-linum-mode

Next time please report bug with more details at the beginning.

**Comment by danyuhao** [comment]
厉害！我在c模式中屏蔽了flymake-mode, 和linum-mode，现在在大文件中移动cursor非常顺畅了！
