### ISSUE TITLE
如何快速切换颜色主题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#459]
我个人很喜欢现在的暗色主题，但有时和别人一起看代码时，从侧面看屏幕就不是很清楚。我不得不注释掉`init.el`中的第`128`行后重启emacs。有没有方便的方式切换颜色主题，或增加一项这样的功能。

**Comment by redguardtoo** [comment]
There dozens 256-color color theme you can select, just `M-x color-them-` and wait for the hint.

Besides, Emacs by default provides about 100 16-color color themes, `M-x color-theme-select`,

To restore the original color theme, `M-x color-theme-molokai`

**Comment by yangdaweihit** [comment]
After looking around the color themes, I finally decide stay in `molokai` forever.

**Comment by redguardtoo** [comment]
UPDATE: I provide a `my-toggle-color-theme` which you can toggle between the molokai and bundled `deep-blue`
