### ISSUE TITLE
win7 + msys2： ffip提示找不到find命令

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#460]
一开始我装了cygwin， 然后ffip使用了cygwin64目录下的find，然后我看了下ffip搜索find目录的代码，发现在system-type是windows-nt的时候好像是会先搜索各个磁盘的find命令
`
(defun ffip--guess-gnu-find ()
  (let (rlt)
    (if (eq system-type 'windows-nt)
        (cond
         ;; cygwin
         ((setq rlt (ffip--guess-gnu-find-on-windows "c" ":\\\\cygwin64\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "d" ":\\\\cygwin64\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "e" ":\\\\cygwin64\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "c" ":\\\\cygwin\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "d" ":\\\\cygwin\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "e" ":\\\\cygwin\\\\bin\\\\find")))
         ;; msys2
         ((setq rlt (ffip--guess-gnu-find-on-windows "c" ":\\\\msys64\\\\usr\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "d" ":\\\\msys64\\\\usr\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "e" ":\\\\msys64\\\\usr\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "c" ":\\\\msys32\\\\usr\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "d" ":\\\\msys32\\\\usr\\\\bin\\\\find")))
         ((setq rlt (ffip--guess-gnu-find-on-windows "e" ":\\\\msys32\\\\usr\\\\bin\\\\find")))))
    (unless rlt (setq rlt "find"))
    rlt))
`
然后我就把cygwin删了，这次似乎能定位到msys64目录的，但是ffip提示
`bash: d:msys64userbinfind 未找到命令`

**Comment by redguardtoo** [comment]
Where is your `find` then?

**Comment by danyuhao** [comment]
D:\msys64\usr\bin\find

**Comment by redguardtoo** [comment]
The GTAGS should exist in the  parent or current directory of the file you are viewing

OR, set environment variable `GTAGSLIBPATH`, `man global` to get the details.


For ffip, looks my code is fine, but I double checked the your error message `d:msys64userbinfind`, r u sure it's `user`, not `usr`?

`M-x toggle-debug-on-error`, reproduce the issue, and send me the full error message.

**Comment by danyuhao** [comment]
Oh， it is `usr `,not `user` 
I restart emacs, and then enabled global Debug-on-Error by `M-x toggle-debug-on-error`,   
Then I entered  `M-x ffip`, it still prompt `D:msys64usrbinfind" 未找到命令` in status bar，
ant prompt “ file is write protected' sometimes

**Comment by redguardtoo** [comment]
`M-x eval-expression (ffip--guess-gnu-find)`, output?

`M-x eval-expression (executable-find (ffip--guess-gnu-find)`, output?

**Comment by danyuhao** [comment]
For Gtags：
我翻了下之前的issue， 发现我现在使用的emacs-32的gui模式，不知道跟这个有关系没有。
所以我就按照stackoverflow中的建议[How to run emacs in CLI mode under mintty in windows?](http://stackoverflow.com/questions/14465330/how-to-run-emacs-in-cli-mode-under-mintty-in-windows)安装了ComEmu，然后按照emacs -nw的方式启动进入了emacs的终端模式。
这时开启debug error on，让光标驻留在一个c文件中的函数名上，'ggtags-find-reference', 键入root目录之后，得到下面的错误信息：
 1Debugger entered--Lisp error: (error "`global' non-zero exit: global: GTAGSROOT must be an absolute path.")
 2  signal(error ("`global' non-zero exit: global: GTAGSROOT must be an absolute path."))
 3  error("`%s' non-zero exit: %s" "global" "global: GTAGSROOT must be an absolute path.")
 4  ggtags-process-string("global" "-pr")
 5  #[0 "\301\302^H!\303\304\305\"P!\207" [default-directory file-name-as-directory file-remote-p ggtags-process-string "global" "-pr"] 5 "\n\n(fn)"]()
 6  funcall(#[0 "\301\302^H!\303\304\305\"P!\207" [default-directory file-name-as-directory file-remote-p ggtags-process-string "global" "-pr"] 5 "\n\n(fn)"])
 7  ggtags-find-project()
 8  ggtags-create-tags("d:/msys64/home/y00329832/cmc/src/")
 9  call-interactively(ggtags-create-tags)
10  ggtags-ensure-project()
11  ggtags-read-tag(reference nil)
12  byte-code("\301\302^H\"C\207" [current-prefix-arg ggtags-read-tag reference] 3)
13  call-interactively(ggtags-find-reference nil nil)
14  command-execute(ggtags-find-reference)

**Comment by redguardtoo** [comment]
run `gtags` to create tagsl Run `global -v d whatever-func-definition` to find definition. Does that work?

Then in your ~/.emacs, insert `(setenv "GTAGSLIBPATH" "/your-project-dir-containing-gtags")`,

**Comment by danyuhao** [comment]
For Gtags：
global -vd  works for definitions, but `(setenv "GTAGSLIBPATH" "/your-project-dir-containing-gtags")` do not work when I insert it at the end of my init.el file  like this:
```
 '(window-numbering-face ((t (:foreground "DeepPink" :underline "DeepPink" :weight bold))) t))

(setenv "GTAGSLIBPATH" "d:/msys64/home/y00329832/cmc/src")
(setq gc-cons-threshold best-gc-cons-threshold)
;;; Local Variables:
;;; no-byte-compile: t
;;; End:
(put 'erase-buffer 'disabled nil)
```

**Comment by danyuhao** [comment]
For GTAGS
`global` `-vd` `whatever-func-definition` do work
`ggtags-find-reference` 的错误我发现可能是字符集设置的问题，当我把msys tty的locale设置成utf-8， 然后在emacs中把<menu>-<options>-<multilingual environment> 设置为utf8之后，之前的错误信息没有了，可是还是“File GTAGS not found”（已经打开了Debug-on-Error 开关），我现在怀疑这个问题是ggtags的某个bug。后面我会用helm（或者ivy？）- gtags试试。

For ffip：

**Comment by redguardtoo** [comment]
Try,
(setenv "GTAGSLIBPATH" "d:\\\\msys64\\\\home\\\\y00329832\\\\cmc\\\\src")

helm-gtags or counsel-gtags is great alternative.

BTW, could you star the https://github.com/syohex/emacs-counsel-gtags. The developer need more endorsement.

**Comment by danyuhao** [comment]
我又装上cygwin试了，没问题，只是cygwin底下使用emacs太慢了，尤其是编辑代码的时候，好像每键入一个字符，都会有一个wrote操作（保存文件），都会卡个1秒，相对来说msys2下用native emacs则快很多。

**Comment by redguardtoo** [comment]
Looks it's your global setup problem, see https://github.com/kosaki/gtags/blob/master/libutil/getdbpath.c , please unset the environment variable CTAGSROOT

I always assume you are using native windows.

**Comment by danyuhao** [comment]
是msys2的问题？我退出到msys的命令行模式，做了下面的测试
最开始的时候我没有设置环境变量GTAGSROOT，global程序是正常工作的
```
y00329832@MSYS
$ global -pr
/home/y00329832/cmc/src
y00329832@MSYS
$ export | grep GTAGSROOT
declare -x GTAGSROOT
···
然后我将GTAGSROOT绝对路径设置为windows下 盘符+冒号+’/'形式，复现了在emacs中的问题
···
y00329832@MSYS
$ export GTAGSROOT="d:/xx"
y00329832@MSYS
$ global -pr
global: GTAGSROOT must be an absolute path.
y00329832@MSYS
$ global -pr
global: GTAGSROOT must be an absolute path.
```
然后我将GTAGSROOT改成unix路径形式，global又可以正常使用了
```
y00329832@MSYS
$ export GTAGSROOT="/home/y00329832/cmc/src"
y00329832@MSYS
$ global -pr
/home/y00329832/cmc/src
y00329832@MSYS
$
```
 global的源码中，如果编译的时候加了w32的宏是会检查windows形式的绝对路径的，如下：
```
int
isabspath(const char *p)
{
	if (p[0] == '/')
		return 1;
#if defined(_WIN32) || defined(__DJGPP__)
	if (p[0] == '\\')
		return 1;
	if (isdrivechar(p[0]) && p[1] == ':' && (p[2] == '\\' || p[2] == '/'))
		return 1;
#endif
	return 0;
}

```
而我的global是在msys2 shell里面通过pacman安装的，说明这个global bin本身就是没有加w32编译宏的（PS：难道是我的系统是w64？？）
这里我还有一个疑问，global在msys2 shell中是不需要设置GTAGSROOT使用的，这样可以用于多套代码，而emacs-global需要设置GTAGSROOT这样一个全局环境变量，多套代码怎么办？

**Comment by redguardtoo** [comment]
When I use global in native Emacs, I don't setup any environment variables. So I ask you make sure *unset* GTAGSROOT.

I assume global and gtags use relative path to current TAGS files, so path doesn't matter.

I don't know how your compiled your global, its either recognize Windows path or Unix path, but could NOT know both. So make sure global use right format path.

Now let's sum up the minimum steps you need do,
- make sure you *unset* any environment variable related to gtags
- create and test global and gtags as we discussed.
- you either use ggtags.el (which bundled in my setup) or helm-gtags (which is not bundled), make sure you read the manual of the plugin you use
- create a minimum project 
- try to use either of the plugin
- Emacs version has nothing to do with this. Don't worry about it.

**Comment by danyuhao** [comment]
环境变量GTAGSROOT是启动emacs的时候自动设置的，好像正常的话没有这个变量，但是出问题的环境上我确实是没有设置GTAGS相关的环境变量，在用ggtags之前用getenv是得不到这个环境变量的，启动了ggtags之后就能getenv得到了

我现在用了helm-gtags，但是helm-gtags-dwim返回权限错误，我的helm-gtags那块初始化不对吗？？
返回错误如：
`apply: Setting current directory: permission denied, /home/y00329832/cmc/src/`
我的helm配置如下：
```
--- a/init.el
+++ b/init.el
@@ -69,6 +69,7 @@
   (require 'init-ibuffer)
   (require 'init-flymake)
   (require 'init-smex)
+  (require 'init-helm)
   (require 'init-ivy)
```
```
--- a/lisp/init-cc-mode.el
+++ b/lisp/init-cc-mode.el
@@ -93,7 +93,7 @@
                (not (string-match-p "GTAGS not found"
                                     (shell-command-to-string "global -p"))))
       (setq gtags-suggested-key-mapping t)
-      (ggtags-mode 1)
+      (helm-gtags-mode 1)
       ;; emacs 24.4+ will set up eldoc automatically.
```

**Comment by redguardtoo** [comment]
I don't know because I don't use helm, but @syohex is one of the best emacs lisp developers in the world and I'm using his other plugins a lot. So shouldn't be any issue. Please read the document and raise a issue on helm-gtags if you still got problem.

For example, at end of  helm-gtags README, there is sample configuration:
```lisp
;; customize
(custom-set-variables
 '(helm-gtags-path-style 'relative)
 '(helm-gtags-ignore-case t)
 '(helm-gtags-auto-update t))
```

In your case, you need use relative path. I guess.

**Comment by danyuhao** [comment]
我把所有的脚本都去掉，单独加载helm-gtags，得到一样的错误，应该是我安装msys2中有什么配置搞错了，我想ffip应该也是类似的原因，我还是先用suse的emacs吧，msys2以后慢慢试着

**Comment by redguardtoo** [comment]
Yes， Linux下积累的技能点在mac下也很好用的。坦率地说现在国外windows做开发的人越来越少了。我的客户不得不给我windows开发环境时会道歉。
