### ISSUE TITLE
md文件输出pdf文件

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#462]
是否有一个功能，使md文件转换输出pdf文件？

**Comment by redguardtoo** [comment]
I know somebody use `pandoc`, you need setup pandoc by yourself because I only use org-mode

**Comment by Bai-Yingjie** [comment]
https://github.com/mszep/pandoc_resume
like this?

**Comment by redguardtoo** [comment]
https://www.reddit.com/r/emacs/comments/4cbpph/markdown_pandoc_mode_pdf_export_looks_ugly/

**Comment by yangdaweihit** [comment]
看起来都很简单的样子，但却不会实现。:-(

**Comment by redguardtoo** [comment]
Then maybe you should use org-mode, export to odt, open with libreoffice and save as pdf

**Comment by yangdaweihit** [comment]
如果有必要，只好如此了。谢谢回复。
