### ISSUE TITLE
pager content be cutted under term mode

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#463]
As title.
1. try pager without config
   # emacs -q
   
   enter term mode
   # man systemctl
   
   without issue, full content shown.
2. try pager with config
   enter term mode
   # man systemctl
   
   totally 10 line be cutted compare to the one above.

any sugguestion?

**Comment by albert748** [comment]
any update?

**Comment by redguardtoo** [comment]
what's your os? more information needed.

**Comment by albert748** [comment]
Arch Linux, emacs 24.5.1 GTK+ 3.20.6

**Comment by redguardtoo** [comment]
try Emacs without GTK3, I heard that developers will drop GTK support because its buggy.

**Comment by albert748** [comment]
Have you tried it? I don't think it's GUI lib issue.

because when use emacs -q, the man page looks correct.

**Comment by redguardtoo** [comment]
what's your exact steps to enter term-mode?

**Comment by albert748** [comment]
M-x term-mode

**Comment by redguardtoo** [comment]
try to comment out line like `(require 'init-term-mode)` or `(require `init-xterm)` and try to bisect, to figure out the exact line causing the issue.
