### ISSUE TITLE
使用clang补全必须用cmake吗？？？

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#464]
我开发的是大型的嵌入式c工程，一般都是Makefile框架，没办法转成cmake。
我在工程输入结构体变量+.或->总是没有补全信息，这点好像不太正常，因为我记得spacemacs没有这个问题。
比如有一个结构体 `struct {int a, int b} foo,*pfoo;` 
我键入` foo. `或者 `pfoo->`的时候 ，总是没有补全信息，我感觉这是个基本功能啊，不知道为什么不好使。
另外就是`M-/`不知道是什么补全，补全的好像还能比clang补全的候选更加准确些

**Comment by redguardtoo** [comment]
那就得自己提供头文件和代码文件的路径了。C的话我觉得ctags+company-mode就足够了，那些高大上的没必要用。

**Comment by danyuhao** [comment]
我也想只用简单的啊： gtags+company-mode，不过还不怎么会配置。新手，呵呵。
我配置下代码文件的路径试试

**Comment by danyuhao** [comment]
我想用 gtags + company +flycheck， 这是不是要在你的配置里面关掉cpputils-cmake呢，还是说怎么直接配置一下？？

**Comment by danyuhao** [comment]
哦，你这里的cpputil-cmake是需要自己配置的？？？那是说company-clang我也要自己配置一下？？感觉光是init-comany.el好像不够

**Comment by redguardtoo** [comment]
first you need pick a backend for c, use either clang OR ctags OR gtags.

say you use clang, then please read http://tuhdo.github.io/c-ide.html , you just need setup `company-clang-arguments` as that document said, that's the easiest way maybe. Surely you need provide the location of header file.

if you prefer use ctags OR gtags, then just create tags, completion should work out of the box.

**Comment by danyuhao** [comment]
是我对自动补全的理解不对吗，我创建了如下文件
```
//#include "util.h"
#include <stdio.h>
typedef struct {int a; int b} TO_ST;
struct ttag{ int a1; int a2 } TTAG_ST;
int main（）
{
    // XXX_ST foo1;
    //any_st foo2;
    TO_ST too1;
    TTAG_ST absxxx;
    TO_ST tboo2;

    return 0;
}
```
我用的是company+semantic，然后我发现我输入结构体名字的时候比如`TO`，输入` 'M-x company-compete" ``可以自动补全成TO_ST`, 但是当我键入`too` 或者 `tb` 的时候没有自动补全提示信息，键入`too1.`也不会提示成员变量。
自动补全功能不能补全局部变量和结构体成员？？

**Comment by redguardtoo** [comment]
sorry, I don't use semantics, My opinion on semantics/cedet is it's legacy package which should not be used now. The major issue is it's too slow. 

I think company+ctags OR company+clang is good enough and easy to setup. For code completion, you need understand how to tweak `company-backends`, See http://emacs.stackexchange.com/questions/23999/php-completion-with-company-does-not-work-on-local-variables/24003#24003  

I admit company-mode need update documentation and I already submit my opinion to its developer.

**Comment by danyuhao** [comment]
额，我知道了，局部变量补全可以用 company-dabbrev, 跟company-clang放在一个group中就可以。
研究了很多帖子，我的company-clang还是不工作，我写了个测试程序，可以用clang编译通过运行
```
#include <stdio.h>
typedef struct mini_hope
{
    char  name[16];
    int   id;
}MIN_HOPE_ST;
int main()
{
    MIN_HOPE_ST term_hops;
    term_hops.id = 1;
    term_hops.name[0]='H';
    term_hops.name[1]='e';
    term_hops.name[2]='l';
    term_hops.name[3]='l';
    term_hops.name[4]='o';
    term_hops.name[5]='\0';
    printf("term[%d] is %s\r\n", term_hops.id, term_hops.name);
    return 0;
}
```
```
y00329832@siay6y003298321 ~/test
$ clang main.c -o ttest
y00329832@siay6y003298321 ~/test
$ ls
main.c  ttest.exe*
y00329832@siay6y003298321 ~/test
$./ttest.exe
term[1] is Hello
```
我的company-clang配置如下：
```
y00329832@siay6y003298321 ~/test
$ cat .dir-locals.el
((nil . ((company-clang-arguments . ("-I./")))))
```
然后我在main.c中键入`term_hops.``M-x company-clang` 状态栏提示Cannot complete at point
当时用的company backends配置如下：
```
File Edit Options Buffers Tools Help-Mode Help
company-backends is a variable defined in `company.el'.
Its value is (company-bbdb company-nxml company-css company-eclim company-clang company-xcode company-ropemacs company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)
```
当我退出emacs的时候，可以看到提示有激活的进程存在： `company-clang   run     *clang-output*  /dev/pty1    /usr/bin/clang -fsyntax-only$`，难道是我的clang被卡住了（cygwin-64）？？？

**Comment by danyuhao** [comment]
看来是cygwin + clang + emacs的原因，我最后用了irony+company，c可以精确自动补全，很好用

**Comment by redguardtoo** [comment]
@danyuhao maybe you can write an article about company clang irony since you are an expert now ;)

**Comment by danyuhao** [comment]
嗯 ， 我大概知道company-clang不能工作的原因了，company-clang需要正确的编译路径和标志，确保文件能被clang编译通过，还隐含编译依赖的头文件必须存在的这个条件，因为我的工程是从交叉编译服务器上down 下来的，所以缺少很多交叉编译的头文件，导致company-clang出错。这一点上irony做的比较好，提供了一个叫cdb的自动默认编译设置，没有包含任何头文件，定义任何标识也能用用，我正在试，不过在msys中有些问题。等我验证完了，我打算写一篇心得。多谢你的帮助和鼓励

**Comment by redguardtoo** [comment]
yes, you have to provide those flags. I wrote a tool cpputils-cmake which will find flags automatically, but requires cmake.
