### ISSUE TITLE
更新版本时保留原有配置

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#465]
由于个人的需要，在`init.el`中需要增加或修改一些配置。在最近的一次更新时，发现`init.el`做了修改，(可能由于我的误操作，记不清了)更新时提示`init.el`与最新版本有冲突，要求执行`commit`或`stash`命令。

我实际操作是：
```
git rest --hard
git pull
```
在完成更新后，又将`init.el`做了我需要的修改。请问对此情况有没有解决方案，如何方便地追踪你的更新且保留我的配置。(由于你的配置非常强大，且在issues中有求必应，使得我始终没有学习elisp的强烈欲望.....)

**Comment by redguardtoo** [comment]
You can place your setup in `~/.custom.el` to override my existing setup.

OR just `git pull`if you already commit your own change, `git stash; git pull;git stash apply` if your change is not committed yet. As I said in README, you need know some git at least.

**Comment by yangdaweihit** [comment]
还是`~/.custom.el`办法方便，这样`~/.emacs.d`就可以始终跟进你的版本了。谢谢。
