### ISSUE TITLE
use linum-mode, move cursor may block some time

### ISSUE THREAD

**Issue by seventhking** [redguardtoo/emacs.d#471]
When in a git project,is more often.
Is there some advices?

ah, one more, my project is a lua project which control by git.

**Comment by lipanXJ** [comment]
Disable linum-mode may be a way to solve this.

**Comment by seventhking** [comment]
@lipanXJ  But the line number seems to be useful when coding.

**Comment by selfname** [comment]
@seventhking I didn't get this problem when deal with git project.

**Comment by seventhking** [comment]
ah, one more, my project is a lua project which control by git.

**Comment by redguardtoo** [comment]
`M-x profiler-start`, move cursor for a while, then `M-x profiler-report`

**Comment by redguardtoo** [comment]
try disable evil-space related code in init-evil.el and see what happens.

**Comment by seventhking** [comment]
Hi, i combined your config with Steve Purcell's config, and i don't use evil. Then i found the condition which above i mentioned.
Then i tried spacemacs, prelude-emacs,Steve Purcell's emacs and yours, lastly, it behaves that in git project, making a lot of changes, then move cursor may block some time. When the project is not control by git, it works well.
I follow your profiler guide(test by purcell's emacs), get the result whick likes below:
mem report: 
     + smex                                                   74,059,883  24%
     + byte-code                                           39,682,617  13%
     + previous-line                                       37,886,886  12%
     + next-line                                               19,249,258   6%
     + profiler-report-write-profile                   15,164,332   4%
- redisplay_internal (C function)                         104,133,161  34%
 - eval                                                                 103,977,622  34%
  - if                                                                     103,977,622  34%
   - format                                                           103,961,246  34%
    - projectile-project-name                                103,961,246  34%
     - funcall                                                         103,953,058  34%
      - #<compiled 0x176841f>                             103,953,058  34%
       - projectile-project-root                                103,953,058  34%
        + file-truename                                              90,956,868  29%

cpu report:
- command-execute                                                 968  48%
 - call-interactively                                                   968  48%
  - apply                                                                   968  48%
   - ad-Advice-call-interactively                                966  48%
    - #<subr call-interactively>                                  940  46%
     + byte-code                                                        389  19%
     + smex                                                                205  10%
     + next-line                                                           198   9%
     + previous-line                                                      92   4%
     + mouse-drag-region                                            34   1%
     + profiler-report-toggle-entry                                15   0%
     + profiler-report-write-profile                                 6   0%
    + ido-ubiquitous-get-command-override                22   1%
- linum-update-current                                             505  25%
 - linum-update                                                        505  25%
  - mapc                                                                   500  24%
   - linum-update-window                                          496  24%
    - funcall                                                                  12   0%
       #<compiled 0xfde45b>                                         9   0%
    get-buffer-window-list                                              3   0%
- ...                                                                         376  18%
   Automatic GC                                                     375  18%


I'm just a beginner here, wish my report log to be able to help you. I also ask for Steve Purcell, and he let me do what you said.

**Comment by redguardtoo** [comment]
Suppose it's emacs's own git setup, see http://stackoverflow.com/questions/5748814/how-does-one-disable-vc-git-in-emacs , just `((setq vc-handled-backends ())`.

It's harder for beginner to mix the setup. You'd better stick to one setup for one year and report the issue that setup's author.

In your case, you need expand the report of next-line and previous-line.

**Comment by seventhking** [comment]
@redguardtoo  it's too shame to ask you for how to expand the tree of next-line and previous-line ...
Thanks a lot.

**Comment by redguardtoo** [comment]
press Enter on the plus sign to expand the tree

**Comment by seventhking** [comment]
maybe it looks like below:

     - next-line                                          842,944,830  69%
      - funcall                                            842,940,686  69%
       - #<compiled 0x109686d>               842,940,686  69%
        - line-move                                     842,940,686  69%
         - line-move-partial                         833,199,624  69%
          - pos-visible-in-window-p              468,091,348  38%
           - eval                                           467,967,947  38%
            - if                                               467,924,078  38%
             - format                                      467,874,950  38%
              - projectile-project-name           467,773,728  38%
               - funcall                                    467,746,235  38%
                - #<compiled 0x188007b>       467,746,235  38%
                 - projectile-project-root           467,746,235  38%
                  - file-truename                       415,761,475  34%
                   - file-truename                      363,718,439  30%
                    - file-truename                     311,726,107  25%
                     - file-truename                    259,455,400  21%
                      - file-truename                   207,521,344  17%
                       - file-truename                  155,595,168  12%
                        - file-truename                 103,697,976   8%
                           file-truename                 51,783,792   4%
                       file-symlink-p                              3,530   0%
                 projectile-default-project-name      24,564   0%
             file-remote-p                                      10,240   0%
          - posn-at-point                             234,448,050  19%
           - eval                                          234,448,050  19%
            - if                                              234,448,050  19%
             - format                                     234,423,486  19%
              - projectile-project-name          234,423,486  19%
               - funcall                                   234,390,734  19%
                - #<compiled 0x188007b>      234,390,734  19%
                 - projectile-project-root          234,390,734  19%
                  - file-truename                      208,439,294  17%
                   - file-truename                     182,470,998  15%
                    - file-truename                    156,279,822  12%
                     - file-truename                   130,260,514  10%
                      - file-truename                  104,268,922   8%
                       - file-truename                   78,305,834   6%
                        - file-truename                    52,398,178   4%
                           file-truename                   26,465,650   2%
                      file-symlink-p                            2,929   0%

**Comment by redguardtoo** [comment]
Latest report looks fine. next-line and previous-line does not take cost too much CPU resource.
If you just use git, you don't need these vc commands.

You could check indent-guide for further optimization.

Plugin with visual candy could always have unexpected impact on performance.

**Comment by seventhking** [comment]
Yes, i found indent-guide was a problem.
Thanks a lot.
