### ISSUE TITLE
 ido-ubiquitous seems cause a bug

### ISSUE THREAD

**Issue by lipanXJ** [redguardtoo/emacs.d#472]
I use emacs 24.5 in centos7(install just now),here is the emacs debug info

Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "ido-completin$
  require(ido-completing-read+)
  eval-buffer(#<buffer  *load*-857042> nil "/home/red/.emacs.d/site-lisp/ido-ubiquitous/ido-ubiquitous.el" n$
  load-with-code-conversion("/home/red/.emacs.d/site-lisp/ido-ubiquitous/ido-ubiquitous.el" "/home/red/.emac$
  require(ido-ubiquitous)
  eval-buffer(#<buffer  *load*-915541> nil "/home/red/.emacs.d/lisp/init-ido.el" nil t)  ; Reading at buffer$
  load-with-code-conversion("/home/red/.emacs.d/lisp/init-ido.el" "/home/red/.emacs.d/lisp/init-ido.el" nil $
  require(init-ido)
  (let ((file-name-handler-alist nil)) (require (quote init-modeline)) (require (quote cl-lib)) (require (qu$
  eval-buffer(#<buffer  *load*> nil "/home/red/.emacs.d/init.el" nil t)  ; Reading at buffer position 5866
  load-with-code-conversion("/home/red/.emacs.d/init.el" "/home/red/.emacs.d/init.el" t t)
  load("/home/red/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203$
  command-line()
  normal-top-level()

**Comment by lipanXJ** [comment]
After disable   ido-ubiquitous  in   .emacs.d/lisp/init.ido.el, everything goes well.

**Comment by redguardtoo** [comment]
`git reset --hard HEAD^`, then pull again, I forget commit another file

**Comment by lipanXJ** [comment]
OK,everything goes well.
