### ISSUE TITLE
如何在添加插件后查错

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#477]
直接拿别人的配置 想要添加一些已有的插件 发现启动出错 如何找出错误的所在地

**Comment by redguardtoo** [comment]
- finish official tutorial
- always use stable version of Emacs and plugin (as I know, the latest stable Emacs is 24.5)
- always use the official setup from plugin
- `M toggle-debug-on-error` and reproduce the issue
- send the bug report the plugin's developer

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
把问题发给开发者了 
不过对添加自定义的插件还是有些疑问
照搬purcell附加插件的方式做了如下改动：
1.在lisp文件夹下加入init-google-translate.el
```;; google-translate packages```
```(require-package 'google-translate)```
```(require-package 'google-translate-smooth-ui)```
```;; shotcut```
```(global-set-key "\C-ct" 'google-translate-smooth-translate)```
```;; translate en <-> cn```
```(setq google-translate-translation-directions-alist '(("en" . "cn") ("cn" . "en"))```
```(provide 'init-google-translate)```
2.在init.el中加入
```(require 'init-google-translate)```  

错误报告：
>Warning (initialization): An error occurred while loading `/Users/sb/.emacs.d/init.el':
>End of file during parsing: /Users/sb/.emacs.d/lisp/init-google-translate.el  
>To ensure normal operation, you should investigate and remove the  
>cause of the error in your initialization file.  Start Emacs with
>the `--debug-init' option to view a complete error backtrace.  

是不是应该把init-google-translate里面的内容直接写入init.el?

**Comment by redguardtoo** [comment]
`require-package ...)` should be placed in `init-elpa.el`

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
奇怪 移过去之后 所有的插件都加载不了
请问下 require-package和init-elpa.el有什么用

**Comment by redguardtoo** [comment]
自动下载未安装插件。初学者还是依样画葫芦比较好。

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
灰常感谢

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
又发现一个问题 以前按C－h直接弹出相关键位提示 现在要多按一下?才会出现 怎么查找相关的属性值进行设置

**Comment by redguardtoo** [comment]
it's `emacs-which-key` which works fine on my computer, whose setup you are using? Purcell's or mine?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Purell's 
what's the emacs-which-key belong?

**Comment by redguardtoo** [comment]
`eamcs-which-key` is plugin, Purcell may use different plugin.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
询问下本人看看
