### ISSUE TITLE
分屏

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#479]
一直想要把屏幕固定分成几小块 
比如多个buffer水平排列
而在一个buffer里面的操作 垂直进行扩展

尝试了下 按```C-x 3```后 水平是多出的几个buffer 
在按```C-x C-b```进行buffer切换 原先的水平的buffer又消失了

哪里需要设置吗

**Comment by redguardtoo** [comment]
I don't understand. What's your problem? details and exact steps. Besides, make sure you've already read official tutorial

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
* 1. use C-x 3 twice 
<img width="1277" alt="2016-08-03 1 30 35" src="https://cloud.githubusercontent.com/assets/16307328/17355142/08a74886-5981-11e6-9aa9-1a97d7571c73.png">
* 2. then use C-x C-b
<img width="1280" alt="2016-08-03 1 41 56" src="https://cloud.githubusercontent.com/assets/16307328/17355156/16ac9e54-5981-11e6-8c55-1f719ea3f5e7.png">

want to retain the original window step 1->2

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
always thanks for help

**Comment by redguardtoo** [comment]
After you select the buffer, you still get 3 column windows layout, right?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
reference this purcell/emacs.d#362
