### ISSUE TITLE
File mode specification error with #+SETUPFILE defined in org file settings

### ISSUE THREAD

**Issue by 0x4ec7** [redguardtoo/emacs.d#480]
When I open an org file with #+SETUPFILE defined in file header, emacs prompt:

File mode specification error: (void-variable ispell-alternate-dictionary)

and cannot do org-html-export-to-html, what can I do to make it right?

Thanks!

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, reproduce the issue and send me the full error message.

**Comment by 0x4ec7** [comment]
Debugger entered--Lisp error: (void-variable ispell-alternate-dictionary)
  (setq company-ispell-dictionary ispell-alternate-dictionary)
  (progn (make-local-variable (quote company-backends)) (if (member (quote company-ispell) company-backends) company-backends (setq company-backends (cons (quote company-ispell) company-backends))) (setq company-ispell-dictionary ispell-alternate-dictionary))
  (if (boundp (quote company-backends)) (progn (make-local-variable (quote company-backends)) (if (member (quote company-ispell) company-backends) company-backends (setq company-backends (cons (quote company-ispell) company-backends))) (setq company-ispell-dictionary isp$
  company-ispell-setup()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  #[(files templates) "\306^X\212\214~\210eb\210\307\310\311\306#\203\220^@\312 ^Y\313  !\314=\203\214^@\315\316    \"^Z\315\317    \"\320\232\203[^@\321\322\n\"\203\213^@\323\324\n\"^[\323\325\n\"\206>^@\326^\\327^K^M\"\211^^ \203Q^@^N \f\241\210\202W^@^K\fB^MB^U+\202\2$
  org-macro--collect-macros()
  org-macro-initialize-templates()
  org-export-as(html nil nil nil (:output-file "./websocket.html"))
  org-export-to-file(html "./websocket.html" nil nil nil nil nil)
  org-html-export-to-html()
  call-interactively(org-html-export-to-html record nil)
  command-execute(org-html-export-to-html record)
  (progn (setq prefix-arg current-prefix-arg) (setq this-command chosen-item) (setq real-this-command chosen-item) (command-execute chosen-item (quote record)))
  (unwind-protect (progn (setq prefix-arg current-prefix-arg) (setq this-command chosen-item) (setq real-this-command chosen-item) (command-execute chosen-item (quote record))) (smex-rank chosen-item) (smex-show-key-advice chosen-item) (run-at-time 0.01 nil (function (la$
  (if smex-custom-action (let ((action smex-custom-action)) (setq smex-custom-action nil) (funcall action chosen-item)) (unwind-protect (progn (setq prefix-arg current-prefix-arg) (setq this-command chosen-item) (setq real-this-command chosen-item) (command-execute chose$
  (let ((chosen-item (intern (smex-completing-read commands initial-input)))) (if smex-custom-action (let ((action smex-custom-action)) (setq smex-custom-action nil) (funcall action chosen-item)) (unwind-protect (progn (setq prefix-arg current-prefix-arg) (setq this-comm$
  smex-read-and-run(("toggle-debug-on-error" "capitalize-word" "org-html-export-to-html" "company-mode" "toggle-company-ispell" "org-version" "package-install" "delete-region" "mc/mark-all-symbols-like-this" "delete-backward-char" "org-html-export-as-html" "go-mode" "org$
  (if (smex-already-running) (smex-update-and-rerun) (and smex-auto-update (smex-detect-new-commands) (smex-update)) (smex-read-and-run smex-ido-cache))
  smex()
  call-interactively(smex nil nil)
  command-execute(smex)

**Comment by redguardtoo** [comment]
It's already resolved at 5110cd9

**Comment by 0x4ec7** [comment]
now it works, thanks a lot!
