### ISSUE TITLE
为什么不同时配置helm和ido

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#481]
看一年成为高手文章中说helm和ido可以同时使用 是在功能上可以互补吗
但是为什么在配置文件中只是配置了ido

**Comment by lipanXJ** [comment]
Because helm is slower than ido.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
如果想用helm上的一些扩展 有没有折中方案

**Comment by lipanXJ** [comment]
1- Installing helm and helm-extension by yourself.
2- Using spacemacs  https://github.com/syl20bnr/spacemacs  
     (If you using spacemacs,        http://emacs-china.org  will be helpful)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
虽然没有戳中要点 还是十分感谢

**Comment by redguardtoo** [comment]
I use ivy,  `git log`

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
只用git的log功能吗

**Comment by redguardtoo** [comment]
I use `ivy-mode` which replaces `helm`, I suggest you studying other people's setup at first. For example, read the log of my setup. Besides, you can read my blog and all my posts on reddit. I thoroughly explains why ivy is better than helm.
