### ISSUE TITLE
how use org-mode to open pdf in a special state

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#484]
such as I want type the link 
open the pdf in section 1

**Comment by redguardtoo** [comment]
that's decided by your pdf viewer. You also need know Emacs Lisp.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
is it a plugin or build in org?

**Comment by redguardtoo** [comment]
No plugin, you need write elisp by yourself and pick the right pdf software (adobe reader, for example).

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
try it
