### ISSUE TITLE
Cannot init configure correctly

### ISSUE THREAD

**Issue by deepythinker** [redguardtoo/emacs.d#485]
Hi, I'm a newer and I git your emacs.d today, and I didn't modify anything.When start emacs it shows error and I restart with --debug-init and it shows this: 
`Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "/home/allen/.emacs.d/elpa/company-0.9.0/company-autoloads")
  load("/home/allen/.emacs.d/elpa/company-0.9.0/company-autoloads" nil t)
  #[0 "\302\303\304\305\300\"\301\"\306\307#\207" [company "/home/allen/.emacs.d/elpa/company-0.9.0" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\303\304\305\300\"\301\"\306\307#\207" [company "/home/allen/.emacs.d/elpa/company-0.9.0" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"])
  package-activate-1([cl-struct-package-desc company (0 9 0) "Modular text completion framework" ((emacs (24 1)) (cl-lib (0 5))) nil nil "/home/allen/.emacs.d/elpa/company-0.9.0" ((:keywords "abbrev" "convenience" "matching") (:url . "http://company-mode.github.io/")) nil])
  package-activate(company (0 8 2))
  #[0 "\300\302H	>\204`
My enviroment is ubuntu 14.04 and emacs24.5.

**Comment by deepythinker** [comment]
Do you mean I just restart emacs when network fine and it will be OK?

**Comment by redguardtoo** [comment]
ye s

**Comment by deepythinker** [comment]
OK, thanks. It works now.
