### ISSUE TITLE
Could it work on a huge project?

### ISSUE THREAD

**Issue by deepythinker** [redguardtoo/emacs.d#487]
Hi, redguardtoo. Could your configure work on a huge project such as Android source code? I mean the C or C++ part. And what should I do? Thanks.

**Comment by redguardtoo** [comment]
Yes, search "How to be extremely efficient in Emacs", you will find what hotkeys I use.

You can also check `init-evil.el`, find the commands with prefix `counsel-`.

For C I use ctags, for c++ I use gnu global.

If you use ctags, my setup is the best in the world. 

If you use gnu global, you may need install emacs-helm-gtags  or emacs-counsel-gtags for code navigation.

Besides, I strongly recommend you reading "Master Emacs In One Year" again

**Comment by deepythinker** [comment]
Thank you and I'm sorry to bother you.  I really do read "Master Emacs In One Year" over and over again and maybe I'm not good at use internet resource and usually I can't find what I want quickly. I also read some issues even it has already closed. I knew learn emacs is a long-time work but sometimes I have to quickly find out some facilities to use.
And by the way, is there a menu list of your all plug-in with short brief or link to introduction?

**Comment by redguardtoo** [comment]
see http://blog.binchen.org/posts/how-to-be-extremely-efficient-in-emacs.html
check the first 20 commands. You also need finish official vim & emacs tutorial.

**Comment by deepythinker** [comment]
Thanks, I'll try this.
