### ISSUE TITLE
About ggtags...

### ISSUE THREAD

**Issue by AllenSue** [redguardtoo/emacs.d#488]
Hi, it's me again...
I use ,gt & ,gr to find definition of functions or symbols, and it seems cannot jump to the correct position.As I created database in the folder android/frameworks with command in shell "gtags -v", maybe it jump form a cpp file to a java file has a same name of a symbol, it's obviously not what I'm finding. And there might be over thousands references gtags gets, and oh my god...
How can I fix this?

**Comment by redguardtoo** [comment]
gt find definition, gr find reference.

you can also use `emacs-helm-gtags`, some programmer reported it's very good. The same developer is also developing `emacs-counsel-gtags`, which I will use instead `ggtags`, but he need some love, so star his project.

So if you really need this urgent feature urgently, `helm-gtags` is recommended.

The reason I don't like helm is it's not stable on low spec machine (2G memory) which I'm using right now. Other developers has no issue with helm.

**Comment by AllenSue** [comment]
Um...What should I do if I try to fix the wrong jump of ggtags? And what's the hot-key of jump back?

**Comment by redguardtoo** [comment]
`C-t`

**Comment by redguardtoo** [comment]
emacs-counsel-gtags or helm-gtags
