### ISSUE TITLE
How to open the most recently edited file with shortcut keys

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#489]
as title depicts. Please guide me. Thank you.

**Comment by yangdaweihit** [comment]
https://masteringemacs.org/article/find-files-faster-recent-files-package

I tried this way and put the code in `.custom.el`. It's the best way for my intention?

**Comment by redguardtoo** [comment]
Use ivy-mode.`M-x ivy-recentf`.

helm is also very popular http://emacs.stackexchange.com/questions/14079/how-to-see-recently-opened-files-in-helm

besides, in these days, my setup is not as conservative as these old guys, it's meaningless to save a few mega bytes disk space,
(setq recentf-max-saved-items 2048)

As a general rule, if you use any mature setup I suggested (Steve Purcell, Spacemacs, Bozhidar Batsov Prelude), consider that setup has all the latest essential information you need.

Please read my "Master Emacs In One Year" for details.

**Comment by yangdaweihit** [comment]
thanks for your suggestion.

**Comment by yangdaweihit** [comment]
thanks for your suggestion.
