### ISSUE TITLE
'avy' was not provided

### ISSUE THREAD

**Issue by hero007feng** [redguardtoo/emacs.d#490]
Warning (initialization): An error occurred while loading `/home/hero007feng/.emacs.d/init.el':

error: Required feature `avy' was not provided

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
I don't know why this problem occur when i reinstalled the emacs and git clone this respositiy again.
Thanks.

**Comment by redguardtoo** [comment]
It's your network problem, avy is required in init-elpa.el, you can either manually install avy or just restart Emacs
