### ISSUE TITLE
elpy配置

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#491]
在elpy文档中配置要求如下：
```
 (require 'package) 
 (add-to-list 'package-archives
              '("elpy" . "http://jorgenschaefer.github.io/packages/"))
 (package-initialize)
 (elpy-enable)
```
我在`.custom.el`或`init.el`中加入这几条语句后都未见elpy起作用，单独填加到`.emacs`中却起作用了。请教如何配置elpy适用于您的配置系统，感谢。

**Comment by yangdaweihit** [comment]
猜想您的配置中应该已经包含了这个插件，于是只在`.custom.el`中加入了最后一条语句，现在显示有自动补全了。
```
(elpy-enable)
```
还有哪些方面需要注意，请指导。感谢。

**Comment by redguardtoo** [comment]
nothing, it's simply because elpy change its API. 
Thanks for reporting the issue.
﻿

**Comment by yangdaweihit** [comment]
my duty to report issues as this project user.
