### ISSUE TITLE
从其他win窗口中复制文字到emacs中出现\XXXX的乱码

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#492]
![20160820_123206](https://cloud.githubusercontent.com/assets/5094958/17829009/5885c59a-66d2-11e6-9760-07248c76b2ed.png)

上面是正确的文字，以及在emacs中乱码。

找到了一个这方面的帖子，

Emacs复制粘贴乱码问题以及修改当前文件编码 - 诶露基基（LGG） - 博客园
http://www.cnblogs.com/ilfmonday/p/emacscoding.html

有点看不懂。

我使用emacs的环境也有点特殊，win7 x64中安装cygwin，里面安装emacs-w32 使用了老大的.emacs.d配置。

下面是emacs的报错

These default coding systems were tried to encode text
in the buffer `坚果云-install.txt':
  (utf-8-unix (36284 . 4194236) (36285 . 4194273) (36286 . 4194233)
  (36287 . 4194299) (36288 . 4194260) (36289 . 4194246))
However, each of them encountered characters it couldn't encode:
  utf-8-unix cannot encode these:            

Click on a character (or switch to this window by `M-x other-window'
and select the characters by RET) to jump to the place it appears,
where `C-u C-x =' will give information about it.

Select one of the safe coding systems listed below,
or cancel the writing with C-g and edit the buffer
   to remove or modify the problematic characters,
or specify any other coding system (and risk losing
   the problematic characters).

  raw-text no-conversion

我现在在从这些信息入手，查相关资料解决。希望了解这个问题的人，能给我些帮助，谢谢！

**Comment by vipzrx** [comment]
[坚果云-install.txt](https://github.com/redguardtoo/emacs.d/files/428135/-install.txt)
这是那个显示乱码的文档

**Comment by redguardtoo** [comment]
install `cygutils-extra` from cygwin, make sure `putclip` from that package is added to environment variable `PATH`, then `M-x paste-from-x-clipboard`. What's the result?

**Comment by redguardtoo** [comment]
try update from my latest setup, maybe it's Purcell's legacy code,
8798ebe remove init-locales.el, not useful since v24 (Chen Bin)

**Comment by vipzrx** [comment]
谢谢老大。git pull 你的最新的代码，可以复制中文，不乱码了
