### ISSUE TITLE
个性化配置

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#497]
上次了解到一些个性化配置可以放在`.custom.el`之中，这样可以避免编辑`init.el`文件，便于跟踪`redguardtoo/emacs.d`。然而与默认配置稍有不同的是，我喜欢`zenburn`配色主题，在`.custom.el`中添加了语句：
```
(load-theme `zenburn t)
```
但仅仅如此还不凑效，需要注释掉`init.el`中的语句：
```
  (if (or (display-graphic-p) (string-match-p "256color"(getenv "TERM"))) (require 'init-color-theme))
```

这样就实现了配色主题的更换。但这样一来每次pull的时候都会报错：文件已被修改，请提交变化或stash。我一般是做一次stash操作，这样感觉不大方便。

请问如何操作，能避免上述问题。

**Comment by redguardtoo** [comment]
commit your change locally, then `git pull -r https://redguardtoo@github.com/redguardtoo/emacs.d.git
 master`

**Comment by yangdaweihit** [comment]
rebase强！
