### ISSUE TITLE
M-x之后的待选项呈竖向排列

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#498]
今天更新配置后发现`M-x`之后的待选项已呈竖向排列，看起来更舒服。不知道这是什么模式，是哪个包的功能，烦劳解惑。

**Comment by redguardtoo** [comment]
`counsel-M-x`, I decided to use more from swiper/counsel/ivy from now on

**Comment by yangdaweihit** [comment]
惭愧，还是不懂。毕竟平时只用现成的。感谢您分享这么好的配置给大家。总能时不时感受到品质的提升。
