### ISSUE TITLE
how to improve the speed of code completion

### ISSUE THREAD

**Issue by Carter-Pro** [redguardtoo/emacs.d#499]
Recrntly, I'm learning a third c++ network library in Linux and using your config of emacs. Thanks for your contribution, the code completion helps me a lot.

But, I found the speed of code completion is very slow.  There always need 2~5s to get the completion.

I had put the third library in my `/usr/local/include`, and not using cmake in my project. I am wondering is there a way to speed up? 

I do not know how your config works, maybe i put the third labrary in my project and using cmake could better?

**Comment by redguardtoo** [comment]
suppose you already read my article `Emacs as C++ ide, easy way`.
It's just gnu global setup thing. See http://stackoverflow.com/questions/22675612/how-do-i-build-a-gnu-global-tags-file-with-files-not-in-the-root-directory 

So you can scan less files with gtags.

**Comment by Carter-Pro** [comment]
@redguardtoo 
Thanks, that's works!
