### ISSUE TITLE
Ctrl-2 set mark失效

### ISSUE THREAD

**Issue by wewchan** [redguardtoo/emacs.d#501]
你好，用了最新的update后，发现以前的Ctrl-2 set mark，按2扩展mark的功能没有了，能否告知这个功能是哪个包的功能？谢谢！

**Comment by redguardtoo** [comment]
what key bindings you press?

**Comment by redguardtoo** [comment]
That's deleted one year ago. `M-x er/expand` and `M-x er/contract-region`, it's from https://github.com/magnars/expand-region.el

**Comment by wewchan** [comment]
Thanks for your quick response!

**Comment by wewchan** [comment]
熟悉的习惯又回来了，谢谢
