### ISSUE TITLE
d(w|e) db do not working as expected when there are multiple cursors in normal-state

### ISSUE THREAD

**Issue by 0x4ec7** [redguardtoo/emacs.d#502]
Hi Bin,

1. (just as the title describes)

2. In emacs normal mode(without evil), subword-backward-kill is binded to "M-DEL" so we can delete a Camel-formed variable in a reasonable way, can we do the same thing in evil-mode?

THANKS!

**Comment by redguardtoo** [comment]
I'm still trying to figure out what's the best way to use multiple cursors.

I go to insert-mode and press `M-del`

**Comment by 0x4ec7** [comment]
Thanks anyway
