### ISSUE TITLE
Run stable version still need network

### ISSUE THREAD

**Issue by wuzixiao** [redguardtoo/emacs.d#503]
In stable version, we should comment line 112--123 to disable connect to melpa.

**Comment by redguardtoo** [comment]
can you show me the content of 112-123

**Comment by wuzixiao** [comment]
(if melpa-use-https-repo
    (setq package-archives
          '(;; uncomment below line if you need use GNU ELPA
            ;; ("gnu" . "https://elpa.gnu.org/packages/")
            ("melpa" . "https://melpa.org/packages/")
            ("melpa-stable" . "https://stable.melpa.org/packages/")))
  (setq package-archives
        '(;; uncomment below line if you need use GNU ELPA
          ;; ("gnu" . "http://elpa.gnu.org/packages/")
          ("melpa" . "http://melpa.org/packages/")
          ("melpa-stable" . "http://stable.melpa.org/packages/")))
  )

**Comment by redguardtoo** [comment]
looks OK to me.
After this snippet there is comment say you can use `~/myelap` instead
