### ISSUE TITLE
How to copy/paste content from terminal to system clipboard

### ISSUE THREAD

**Issue by PuppywantolearnJava** [redguardtoo/emacs.d#506]
System: Ubuntu 16.04, gnome-terminal
Problem: in emacs -nw, kill-ring doesn't put context into system-clipboard

Describe: 最近尝试直接在terminal 中使用emacs, 但是当使用C-w, M-w, C-k 等kill-ring 操作时， 内容并不会复制到系统的clipboard 上， 也就是没办法把emacs的内容，复制粘贴到比如浏览器，或者别的文档编辑其中，请问有没有插件，或是办法解决这个问题。
我在网上查了一下，好像说gnome-terminal 不支持xlib。

**Comment by redguardtoo** [comment]
http://blog.binchen.org/posts/the-reliable-way-to-access-system-clipboard-from-emacs.html 

Besides, in README I mentioned that my key bindings are recorded in in `init-evil.el`. Search "clipboard" there.

Read "following master" section from my "Master Emacs In One Year".

**Comment by smallst** [comment]
安装了xsel后使用陈斌的配置可以通过 ,aa  ,zz复制粘贴，可解决问题

**Comment by PuppywantolearnJava** [comment]
Thanks @redguardtoo @smallst ! Forgot to install xsel. Should read README more carefully!
