### ISSUE TITLE
取消auto-save了？

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#507]
在 commit a943782 之后，似乎自动保存的触发比以前更少了，将121行的` :type 'boolean` 补回去后，auto-save的触发和原来一致。请问这一行的作用是什么呢？

**Comment by redguardtoo** [comment]
不了解,这都是optional的,本来这个变量的目地就是要少触发auto-save.

**Comment by smallst** [comment]
嗯，从代码逻辑来说是这样，不过奇怪的是我在写一个perl代码时，没有 `:type 'boolean`的时候如果只是注释或取注一行（修改一个#)，等待一秒不会自动保存，而修改空行倒是会= = （嘛也可能是我电脑卡顿之类的问题，我自己再仔细研究一下吧。

**Comment by redguardtoo** [comment]
我测试下来一秒后都保存了. 如果用evil的话, mode-line的颜色不一定能及时反应,这个我叶没研究出来.
