### ISSUE TITLE
should i change yas-minor-mode to yas-global-mode?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#508]
recently when i edit source code in org-mode, i find `C-c ' (org-edit-special)` doesn't have snippets. then i find 
```emacs-lisp
(defun yasnippet-generic-setup-for-mode-hook ()
  (unless (is-buffer-file-temp)
    (yas-minor-mode 1)))
```
in `init-yasnippet.el`

For using yasnippet in `org-edit-special` and anthor situation where i use emacs as a external editor to edit some code(that only open temp file in emacs), should i use `yas-global-mode`?  is there any important reason for you to disable yassnipet in temp file?

Thanks.

**Comment by redguardtoo** [comment]
You can remove `(is-buffer-file-temp)`, but please see http://blog.binchen.org/posts/export-org-file-embedded-with-code-snippets.html at first

**Comment by smallst** [comment]
thanks for reply.

after read your blog, i don't understand `The issue is when exporting the org file, major mode for each language will be loaded to render the code snippet. ` clearly.
 i used think the snippets insert the template code into file when i press `tab`,  but the blog means when i export an org-mode file, all the code snippets would be rendered again?

**Comment by redguardtoo** [comment]
Snippet's own major mode will be loaded when exporting. So the heavy setup snippet's major mode could hang the exporting process.

But you have freedom to turn on yasnippet always in major mode hook.

**Comment by smallst** [comment]
OK, thank you very much!
