### ISSUE TITLE
how to enable auto-fill-mode for org file

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#510]
Every time creating an org file,  I have to enable auto-fill-mode with `C-c q`. How can I make it enabled automatically with opening or creating an org file?

**Comment by redguardtoo** [comment]
https://www.emacswiki.org/emacs/ModeHooks

**Comment by yangdaweihit** [comment]
operation as the link described works:
```
(add-hook 'org-mode-hook 'auto-fill-mode)
```
