### ISSUE TITLE
evil 问题整理

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#513]
如何查看evil内置文档

**Comment by redguardtoo** [comment]
The same way as you read inline document of other Emacs plugins.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
but when I use `C-h i`
can't find anything about evil

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
真的不行的话只能看着配置一个个查对应的功能了 
感谢

**Comment by redguardtoo** [comment]
`如果你不熟悉Vim,在命令行里运行 vimtutor 或者安装Emacs插件evil-tutor学习Vim基本命令.`, quoted from https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
请问下evil有没有类似vim寄存器计算的功能
:let i=1  -> qa  -> <C-r>=i -> :let i+=1 -> q
:let好像不能用
<C-r>=之后貌似不能加变量

**Comment by redguardtoo** [comment]
use elisp `M-x eval-expression`

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
vim的寄存器计算功能通过其内置的vimscript实现
evil则直接采用elisp编译表达式实现宏计算功能
`<C-r>=(setq foo 1) (setq foo (1+ foo))`
