### ISSUE TITLE
建议增加ess模式

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#514]
ess是一个统计学语言脚本编程插件。自己折腾了一阵，还是没有实现`自动补足`功能。可否请您花些时间将ess填加到您的配置中。

另，在使用`(require 'ess-site)`时如果不翻墙，会出现emacs卡死的现象。

<http://ess.r-project.org/index.php?Section=download>
<https://www.emacswiki.org/emacs/ESSAuto-complete>

**Comment by redguardtoo** [comment]
用company-ess， https://github.com/emacs-ess/ESS/issues/112

建议把我的“一年成为Emacs高手”再好好读一遍。

文章开宗明义要跟随高手，然后我申明我用company而不是auto-complete，对于EmacsWiki我的建议是作为了解主题值得一读，是否采用其内容”另当别论“

**Comment by yangdaweihit** [comment]
好吧。

**Comment by yangdaweihit** [comment]
(setq tramp-ssh-controlmaster-options nil)

>here is a bug in the version of TRAMP included with Emacs 24.5 that
causes Emacs to hang for at least 30 seconds -- on my system, about two
minutes -- when Emacs loads TRAMP.

The hang occurs when Emacs spawns ssh processes when initialising the
variable `tramp-ssh-controlmaster-options'.  If your ISP's DNS server
likes to hijack failed lookups to redirect the user to a branded search
engine, these ssh processes hang for a long time before timing out [1].
This bug affects all Emacs Lisp addons that load TRAMP as part of their
startup, of which Helm [2] and Magit [3] are prominent.

There are two workarounds for users: switch to DNS servers which don't
do this kind of hijacking (e.g. Google's public resolvers), or set
`tramp-ssh-controlmaster-options' to nil in your init file, before code
which causes TRAMP to be loaded is executed.


参考：
<https://github.com/emacs-ess/ESS/issues/348>
<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810640>

**Comment by yangdaweihit** [comment]
自动完成的功能是有的，但只有在启动R模式之后才能具有。
类似的提问也有过：<http://stackoverflow.com/questions/36109544/emacs-ess-autocomplete-working-in-iess-mode-but-not-in-scripts-how-to-get-it-wo>

怎么才能实现打开后缀为`.R`的文件时自动启动`R-mode`？
