### ISSUE TITLE
org mode 下, 如何关闭语法的高亮

### ISSUE THREAD

**Issue by PuppywantolearnJava** [redguardtoo/emacs.d#515]
redguardtoo 您好:

最近在使用org,做一些英文的笔记,并且越来越喜欢org-mode, 但是一直有个问题, 就是在一些should, 被动语态时会自动高亮, 会导致我阅读不太舒服.
选择font-lock-mode会导致所有高亮都消失, 有没有什么办法, 只是停止语法上的一些高亮, 但仍就保持org-mode 本身的高亮?

**Comment by redguardtoo** [comment]
comment out init-artbollocks-mode in init.el

**Comment by PuppywantolearnJava** [comment]
哦哦, 好的! 我再继续适应适应吧.
谢谢回复!
