### ISSUE TITLE
minior bug fix request

### ISSUE THREAD

**Issue by albert748** [redguardtoo/emacs.d#516]
Hi, dear:

Please refer:
https://github.com/leoliu/ggtags/issues/131

The code shall change from init-misc.el:

(defun compilation-finish-hide-buffer-on-success (buf str)
  "Could be reused by other major-mode after compilation."
  (if (string-match "exited abnormally" str)
      ;;there were errors
      (message "compilation errors, press C-x ` to visit")
    ;;no errors, make the compilation window go away in 0.5 seconds
    **(when (string-match "_compilation_" (or (buffer-name buf) ""))**
      (bury-buffer "_compilation_")
      (winner-undo)
      (message "NO COMPILATION ERRORS!"))))

**Comment by redguardtoo** [comment]
thanks

1103b49 minor issue (Chen Bin)
