### ISSUE TITLE
master branch init with failure of async-1.6.tar not found

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#517]
I was trying your latest master branch, but when I start emacs with that configuration, emacs complains for async-1.6.tar not found from melpa stable.

SHA1 of the latest commit on master branch is 1103b4.
Emacs version 24.5.1.

**Comment by redguardtoo** [comment]
http://stable.melpa.org/#/async 

It's there

**Comment by phye** [comment]
My fault. Seems like packages in .emacs.d/elpa folder was trying to depends on older async.  I didn't pull your configuration for a long time and a simple fetch and checkout redguardtoo/master won't work since .emacs.d/elpa is in the ignore list and was still refering older packages.
After I manually removed folder .emacs.d/elpa folder and restart emacs again, it's working normally. 

You can close the issue.

BTW, are there other way to refresh packages as removing the whole elpa folder and repull all packages takes quite long time?

**Comment by redguardtoo** [comment]
`M-x list-packages`, then press `U` and `x`

**Comment by phye** [comment]
Thank you for your share!
Tried on Arch and OS X, works like a charm 👍
