### ISSUE TITLE
swiper-the-thing stop working.

### ISSUE THREAD

**Issue by 0x4ec7** [redguardtoo/emacs.d#518]
Hi Bin,

swiper-the-thing(, s s)  stoped working after I upgraded all of my packages to the newest version(include unstable version),  it keeps telling "swiper--update-input-ivy: Wrong type argument: window-live-p, #<frame F2 0x103a68e68>". How to fix this issue?

Thanks.

**Comment by redguardtoo** [comment]
32a7cba use stable swiper (Chen Bin)

updated from my emacs.d, remove the unstable swiper package, restart emacs

**Comment by 0x4ec7** [comment]
I've linked this issue to abo-abo/swiper.

THX!
