### ISSUE TITLE
org表格操作问题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#519]
`C-S-left` fails to kill column. Do you meet this same problem?

**Comment by redguardtoo** [comment]
See http://orgmode.org/manual/Built_002din-table-editor.html

**Comment by yangdaweihit** [comment]
It's my type error that `M-S-<left>` cannot kill columns.

**Comment by redguardtoo** [comment]
works well on my Emacs 24.4.1, maybe it's your emacs or org version?

**Comment by yangdaweihit** [comment]
org-mode version 8.2.10 and Emacs 24.5.1

**Comment by redguardtoo** [comment]
Yeah, use other hotkeys, vim leader keys for example

**Comment by yangdaweihit** [comment]
it's due to openbox's hotkeys definition in `rc.xml`. The problem has been solved.
