### ISSUE TITLE
ubuntu 下启动emacs报错

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#520]
Debugger entered--Lisp error: (void-function cl-struct-define)
cl-struct-define(yas--template "A template for a snippet." cl-structure-object nil nil ((cl-tag-slot) (key) (content) (name) (condition) (expand-env) (load-file) (save-file) (keybinding) $
byte-code("\300\301\302\303#\210\304\305\306\307\310\211\311\312\313\303& \207" [function-put yas--define-snippets-2 side-effect-free t cl-struct-define yas--template "A template for $
require(yasnippet)
elpy-module-yasnippet(global-init)
apply(elpy-module-yasnippet global-init nil)
elpy-modules-run(global-init)
elpy-modules-global-init()
elpy-enable()
eval-buffer(#<buffer *load*-839254> nil "/home/y00329832/.emacs.d/lisp/init-python-mode.el" nil t) ; Reading at buffer position 226
load-with-code-conversion("/home/y00329832/.emacs.d/lisp/init-python-mode.el" "/home/y00329832/.emacs.d/lisp/init-python-mode.el" nil t)
require(init-python-mode)
(let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib)) (require (quote init-compat)) (require (quote init-utils)) (r$
eval-buffer(#<buffer *load*> nil "/home/y00329832/.emacs.d/init.el" nil t) ; Reading at buffer position 5770
load-with-code-conversion("/home/y00329832/.emacs.d/init.el" "/home/y00329832/.emacs.d/init.el" t t)
load("/home/y00329832/.emacs.d/init" t t)
#[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\21$
command-line()
normal-top-level()

**Comment by redguardtoo** [comment]
emacs version? os?

**Comment by danyuhao** [comment]
GNU Emacs 24.5.1 + Ubuntu 16.04.1 LTS

**Comment by danyuhao** [comment]
https://github.com/syl20bnr/spacemacs/issues/3129
问题已经解决：删除elpy下所有文件重新安装即可
原因是：
This is happening because the package(s) were compiled on Emacs 25.x and then attempted to be loaded on 24.5.1.
