### ISSUE TITLE
ido-find-file时键入Ctrl - d或者Ctrl - j 提示输入root密码

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#521]
想在查找文件(C - x  C-f)时进入某个目录，帮助上介绍是在minibuffer中按C - d或者 C-j，每次一按minibuffer就提示输入root密码
`Password for /sudo:root@127.0.0.1:`

**Comment by redguardtoo** [comment]
46cad5b only sudo edit physical file (Chen Bin)

**Comment by danyuhao** [comment]
ok
