### ISSUE TITLE
”winner-redo“ says “Previous command was not a 'winner-undo'” 

### ISSUE THREAD

**Issue by danyuhao** [redguardtoo/emacs.d#522]
When I typed ` , u u`(bind to winner-undo)， and then typed` , U U`(bind to winner-redo)
in the mini-buffer, it says
`Previous command was not a 'winner-undo'`
But When I disabled winner-mode and enable winner-mode again , `winner-redo` do work

**Comment by redguardtoo** [comment]
can't reproduce
