### ISSUE TITLE
evil模式下如何粘贴系统剪切版内容

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#523]
小白问题 不吝赐教

**Comment by redguardtoo** [comment]
"key bindings" section in README

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
三克油

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
> eval-buffer: Symbol’s function definition is void: nvmap

in init-evil.el why?

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
may add [this](http://emacsist.com/10842) in README

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the function of `paste-from-x-clipboard` and `copy-to-x-clipboard` is complicate
is also a function name act as M-w and C-y

**Comment by redguardtoo** [comment]
then `(setq save-interprogram-paste-before-kill t)` in `init-clipboard.el` if you don't want to use my command.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
这样设置在emacs模式下是可以
但是放到evil中 还是要通过调用无名寄存器来粘贴系统剪切版
最好是能够设置成 `init-evil.el` 那样   一个快捷键对应一个操作

**Comment by redguardtoo** [comment]
I use https://github.com/rolandwalker/simpleclip , check its README. If you find any issue, must be simpleclip bug.
