### ISSUE TITLE
mode-line chinese date format bug

### ISSUE THREAD

**Issue by Linxius** [redguardtoo/emacs.d#526]
emacs25 when set gnome-formats to chinese, Dec 11 become 日12月11.   

besides when use packages gitignore-mode in emacs25 the error "Failed to verify signature" raised so i setq package-check-signature to nil and it seems to be fixed.

**Comment by redguardtoo** [comment]
what's you mode-line setup? can you show me the code?

**Comment by Linxius** [comment]
I just cloned your emacs.d and haven't modify it yet.

**Comment by Linxius** [comment]
Maybe it's a bug of emacs itself

**Comment by redguardtoo** [comment]
your locale, os?

**Comment by Linxius** [comment]
debian/testing and locale zh_CN.UTF-8

it's "三 12月 14" now and before long it will turn into "Wed Dec 14" automatically

**Comment by redguardtoo** [comment]
In your ~/.bashrc,
```bash
export LC_COLLATE="zh_CN.UTF-8"
export LC_CTYPE="zh_CN.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="zh_CN.UTF-8"
export LC_NUMERIC="zh_CN.UTF-8"
export LC_TIME="zh_CN.UTF-8"
```
or you can change environment variable in your ~/.emacs, using `setenv` instead.

**Comment by Linxius** [comment]
it works, thanks.
