### ISSUE TITLE
Why "auctex-11.87 not available" appears when I try to install auctex?

### ISSUE THREAD

**Issue by Jacobi-Leo** [redguardtoo/emacs.d#527]
Emacs newbie, thanks a lot for answering this stupid question!

I'm a LaTeX user, so I need AUCTeX in my Emacs, but I failed to install it. As long as I open Emacs without configuration as $emacs -Q, AUCTeX becomes available. Could you please help me on this, thank you.

**Comment by redguardtoo** [comment]
You can switch to online repositories like http://elpa.gnu.org or http://melpa.org by modifying ~/.emacs.d/lisp/init-elpa.el.

I guess auctex only exist in elpa.gnu.org.

**Comment by Jacobi-Leo** [comment]
Thank you so much! I search the melpa.org and elpa.gnu.org, and find that
auctex only exist in elpa.gnu.org. After switching (setq package-archives
...), the problem is solved completely.
