### ISSUE TITLE
"Install w3m command in 'exec-path' or set 'w3m-command' variable correctly" and Target buffer ".notes" for file+headline should be in Org mode

### ISSUE THREAD

**Issue by whjfh** [redguardtoo/emacs.d#528]
------新手小白，不吝赐教~
一直在用您的配置，之前安装都正常，近次重装系统，再次配置emacs却出现以下两个问题。
1、M+x w3m，message显示"Install w3m command in 'exec-path' or set 'w3m-command' variable correctly"
2、在org-mode模式下使用org-capture，出现“Target buffer ".notes" for file+headline should be in Org mode”
困扰几天，google到的方法很多都尝试过，还是解决不了。

**Comment by redguardtoo** [comment]
1. read README, understand what's environment variable "PATH" and how to change PATH, then install w3m

2. http://orgmode.org/manual/Setting-up-capture.html#Setting-up-capture, mine setup is `(setq org-default-notes-file "~/org/gtd.org")` at ~/.custom.el, please note `.custom.el` is my personal setup which is not publicized. I don't use `org-capture`, so I have not touched related stuff. Could you `emacs -Q` and figure out what's the difference between your customization and original setup? maybe you changed `org-capture-templates`? The content of my `org-capture-tempates` is nil.

**Comment by whjfh** [comment]
非常感谢（Thank you very much）。现在解决了。刚重新过了遍README,发现之前自己遇到的一些问题有些README中已经提到过，尤其“Locked packages”部分。现在安装了w3m 。第二个问题也解决了，应该是没有设置org-default-notes-file 。真的非常感谢您~~

**Comment by liuchanghui1987** [comment]
我使用您截止2018.01.19的最新的配置，w3m依旧不工作
显示"Install w3m command in 'exec-path' or set 'w3m-command' variable correctly"
真的没看明白还需要什么特殊的设置。
@redguardtoo

**Comment by liuchanghui1987** [comment]
重新安装w3m时候就会有error，不确认是否和这些有关系
@redguardtoo 
Leaving directory `g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135'

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/bookmark-w3m.el at Fri Jan 19 21:54:16 2018
Entering directory `g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/'

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/mime-w3m.el at Fri Jan 19 21:54:16 2018
mime-w3m.el:47:11:Error: Cannot open load file: no such file or directory, calist

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-antenna.el at Fri Jan 19 21:54:17 2018
w3m-antenna.el:49:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-bookmark.el at Fri Jan 19 21:54:17 2018
w3m-bookmark.el:40:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-bug.el at Fri Jan 19 21:54:17 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-ccl.el at Fri Jan 19 21:54:17 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-cookie.el at Fri Jan 19 21:54:18 2018
w3m-cookie.el:45:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-dtree.el at Fri Jan 19 21:54:18 2018
w3m-dtree.el:35:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-ems.el at Fri Jan 19 21:54:18 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-favicon.el at Fri Jan 19 21:54:18 2018

In w3m-favicon-retrieve:
w3m-favicon.el:314:19:Warning: reference to free variable `w3m-message-silent'

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-fb.el at Fri Jan 19 21:54:19 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-filter.el at Fri Jan 19 21:54:19 2018
w3m-filter.el:40:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-form.el at Fri Jan 19 21:54:19 2018
w3m-form.el:44:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-hist.el at Fri Jan 19 21:54:19 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-image.el at Fri Jan 19 21:54:20 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-lnum.el at Fri Jan 19 21:54:20 2018
w3m-lnum.el:49:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-mail.el at Fri Jan 19 21:54:20 2018
w3m-mail.el:41:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-namazu.el at Fri Jan 19 21:54:20 2018
w3m-namazu.el:53:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-perldoc.el at Fri Jan 19 21:54:21 2018
w3m-perldoc.el:35:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-proc.el at Fri Jan 19 21:54:21 2018

In w3m-process-with-null-handler:
w3m-proc.el:325:15:Warning: function `gensym' from cl package called at
    runtime

In w3m-process-with-wait-handler:
w3m-proc.el:369:18:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:370:21:Warning: function `gensym' from cl package called at
    runtime

In w3m-process-do:
w3m-proc.el:445:30:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:447:21:Warning: function `gensym' from cl package called at
    runtime

In w3m-process-do-with-temp-buffer:
w3m-proc.el:467:30:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:469:17:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:470:20:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:471:19:Warning: function `gensym' from cl package called at
    runtime
w3m-proc.el:472:22:Warning: function `gensym' from cl package called at
    runtime

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-rss.el at Fri Jan 19 21:54:21 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-save.el at Fri Jan 19 21:54:22 2018
w3m-save.el:32:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-search.el at Fri Jan 19 21:54:22 2018
w3m-search.el:40:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-session.el at Fri Jan 19 21:54:22 2018

In end of data:
w3m-session.el:924:1:Warning: the function `seq-position' is not known to be
    defined.

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-symbol.el at Fri Jan 19 21:54:22 2018

Compiling file g:/important/gnu_emacs/Emacs-Version/emacs/emacs-cfg/.emacs.d/elpa/w3m-20180116.135/w3m-tabmenu.el at Fri Jan 19 21:54:23 2018
w3m-tabmenu.el:40:1:Error: Install w3m command in `exec-path' or set `w3m-command' variable correctly
w3m.el:Error: Creating pipe: too many open files

**Comment by redguardtoo** [comment]
` Install w3m command inexec-path' or set `w3m-command' variable correctly`

The easiest work around is to setup envrionment variable `PATH` on Windows.

**Comment by liuchanghui1987** [comment]
👌@chenbin
