### ISSUE TITLE
hydra 函数绑定的问题

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#530]
一直有这样一个疑问：
比如正常情况下发送一封邮件
需要切换 gnus buffer
在特殊情况下显然不方便
想要实现跨越 buffer 的函数绑定
能否指点一二

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
其实 hydra 快捷键的设定在于帮助记忆
绑定                    <leader + 任意键位>                                调出 hydra 快捷键索引
再绑定                <leader + 索引上对应的快捷键>              快速调用

**Comment by redguardtoo** [comment]
I just switch buffer, currently I'm using ido way, but ivy way may be better,

beside, the `, b b` go to recent buffer.
