### ISSUE TITLE
how to use evil's register and macro

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#531]
there are too many question I will interest in evil mode
how to give the cut and delete thing to `_register`
how to use macro in visual line mode

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
;; black hole delete ("_d)
(evil-define-operator evil-delete-without-register (beg end type yank-handler)
  (interactive "<R><y>")
  (evil-delete beg end type ?_ yank-handler))
(define-key evil-normal-state-map (kbd "D") 'evil-delete-without-register)
(define-key evil-visual-state-map (kbd "D") 'evil-delete-without-register)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
follow the [issue](https://bitbucket.org/lyro/evil/issues/468/how-delete-to-the-register-in-a-keymap)
it can be deleted any thing in black hole register in emacs way.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
something is know from issue
delete things use `_register`:

> (evil-define-operator evil-delete-without-register (beg end type yank-handler)
>  (interactive "<R><y>")
>  (evil-delete beg end type ?_ yank-handler))
(define-key evil-normal-state-map (kbd "D") 'evil-delete-without-register)
>(define-key evil-visual-state-map (kbd "D") 'evil-delete-without-register)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
>;; cut things use _register
(defun evil-paste-after-from-0 ()
  (interactive)
  (let ((evil-this-register ?0))
    (call-interactively 'evil-paste-after)))
>(define-key evil-visual-state-map "p" 'evil-paste-after-from-0)

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
it will be very graceful to see if can invoke macro directly in V mode

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
```
;; let system clipboard in evil paste-pop
(fset 'evil-visual-update-x-selection 'ignore)
```

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
```
;; carry out macro in visual-line
:'<,'>g/^/norm @q
```

**Comment by redguardtoo** [comment]
Not every feature of  vim is cloned. You can raise a issue on evil's web site.

**Comment by ninrod** [comment]
You can, but to no avail. Evil is unmanned and unmantained. Lyro, evil's creator, stop mantaining the package.

**Comment by ninrod** [comment]
for completeness, here is the new, migrated, and soon to be fully mantained repo of evil-mode package: https://github.com/emacs-evil/evil. You could open issues there.

**Comment by redguardtoo** [comment]
Thanks for the heads up. I know evil will live longer than my whole career life ;)

If the new evil team need new blood, I recommend @noctuid, I read his code and documentation. I got the impression he know the internals of evil

**Comment by ninrod** [comment]
@redguardtoo @noctuid is one of the best around. You may be interested in knowing that He's writing [targets.el](https://github.com/noctuid/targets.el). It is supposed to be a complete port of [wellle/targets.el](https://github.com/wellle/targets.vim) and some other plugins. I'm using it to great success already. Recommended.

**Comment by redguardtoo** [comment]
Haha, good to know.

**Comment by ninrod** [comment]
Oh, forgot to mention that I've wrote a little tutorial that features your elpa-mirror package. It's [here](https://github.com/ninrod/emacs-antiproxy#using-redguardtoos-elpa-mirror)

**Comment by redguardtoo** [comment]
Yes, I read your nice tutorial when you first published it. Good read 👍
