### ISSUE TITLE
how to highlight a paired parenthesis/bracket/brace while going through the code?

### ISSUE THREAD

**Issue by ozusawa** [redguardtoo/emacs.d#532]
Was a vim user and trying emacs now,
with the stable version, while going through the code
seems it cannot highlight its pair, when you come to a single parenthesis.
What can i do with this?

Thanks!

**Comment by redguardtoo** [comment]
I used to use smartparens which is pretty solid.

The only issue for me is smartparens could drag the performance a little a bit for files with 20000+ lines. That's the reason I gave up smarparens later.

**Comment by ozusawa** [comment]
Thanks, i'll try it
