### ISSUE TITLE
js2-mode-idle-reparse error?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#534]
it is not a common error but when i open a certen js file i get the following error and js2-mode cannot work properly
```
Error running timer ‘js2-mode-idle-reparse’: (error "No buffer available for node [cl-struct-js2-string-node 41 2 10 nil [cl-struct-js2-call-node 38 0 13 nil [cl-struct-js2-prop-get-node 33 0 18 nil [cl-struct-js2-call-node 38 0 20 nil [cl-struct-js2-prop-get-node 33 2166 27 nil nil 2186 #3 [cl-struct-js2-name-node 39 21 6 nil #4 zoomIn nil]] #2 nil 18 19] 2179 #1 [cl-struct-js2-name-node 39 14 4 nil #2 data nil]] [cl-struct-js2-name-node 39 0 1 nil #1 $ nil] (#0) 1 12] .sj-book]") [2 times]
```

the js file can be download at [turnjs](http://www.turnjs.com) ,  in `turnjs4/samples/steve-jobs/js/steve-jobs.js`

**Comment by redguardtoo** [comment]
I guess it's because https://github.com/mooz/js2-mode/issues/393 

I'm using patched js2 packages, so just upgrade js2-mode after `M-x list-packages`
