### ISSUE TITLE
evil's regex

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#535]
the rule of it is so strange
when type `:%s/, /,\r`
the `\r` will show `^M` in emacs.
<img width="179" alt="2016-12-29 9 25 04" src="https://cloud.githubusercontent.com/assets/16307328/21544818/654dd946-ce0d-11e6-984e-1d809d570574.png">
<img width="196" alt="2016-12-29 9 25 32" src="https://cloud.githubusercontent.com/assets/16307328/21544821/6c736484-ce0d-11e6-8621-5ca5badcfc6b.png">

**Comment by redguardtoo** [comment]
Nothing wrong. That's convention in most text editors.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
但是这个是换行符啊
没换行怎么搞

**Comment by redguardtoo** [comment]
`\n`
