### ISSUE TITLE
Trying to install ide-skel and tabbar for sqlplus

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#538]
I need help to understand how I can install sqlplus with additional packages (tabbar and ikd-skel) for making emacs into TOAD like Oracle SqlPlus client.

I inserted `sqlplus` in `init-elpa.el` under `defvar melpa-include-packages` and did `(require-package 'sqlplus)` towards the end. This installed sqlplus alright. I can start sqlplus mode with `M-x sqlplus`.

However I am trying to install ide-skel and tabbar (please see https://github.com/linuxnotes/emacs/tree/master/ide-skel which has all files and the wiki at https://www.emacswiki.org/emacs/SqlPlus#toc2 which mentions using sqlplus with ide-skel). I don't see ide-skel package on melpa (I could fine tabbar and install it). I used to simply copy the ide-skel.el file manually under site-lisp folder. But I guess that is not the clean way. Any hints?

**Comment by redguardtoo** [comment]
Well, if ide-skel doesn't provide melpa package, the cleanest way is to ask its developer to support melpa ;)

For now, you can place `ide-skel.el` under `site-lisp` (check other packages directory layout in site-lisp). Don't forget you need manually install ide-skel's dependencies.

The true spirit of Emacs is freedom. The way you are most comfortable with is always the cleanest way.

**Comment by amittendulkar** [comment]
Thanks for your tip.
