### ISSUE TITLE
melpa中安装package

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#539]
我使用package-list-package来安装package，为什么没有chinese-pyim-wbdict？这个包是在melpa中可以找到的啊。

**Comment by redguardtoo** [comment]
见README,默认只从melpa-stable安装插件.否则需要手动修改init-elpa.el,你也可以修改`~/.custom.el`,不过需要一定的elisp知识.

**Comment by lxeg0429** [comment]
能不能在init-elpa里面加个说明，说明要如何修改？其实只要把你那里面的stable字符去掉就可以了。但是能不能跟我说一下怎么在custom.el里面修改啊？

**Comment by redguardtoo** [comment]
没有读完elisp教程还是不要考虑`.custom.el`了.

以下引用自README,
I intentionally make packages from melpa-unstable uninstallable by default. You can modify variable melpa-include-packages in ~/.emacs.d/lisp/init-elpa.el to install packages from melpa-unstable

`melpa-include-packages`搜一下.

**Comment by lxeg0429** [comment]
刚才没看到你的配置里已经有解释了，很抱歉。谢谢你的回答。
