### ISSUE TITLE
<t> is undefined

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#540]
每次启动时，都会出现这么句话，是从哪里来的啊，我想注释掉，这个很影响工作效率。
另外，每次都会出现Failed to access ~/.emacs.d/history，这个是没有必要的吧，建议把这个message去掉，或者进行优化。

**Comment by redguardtoo** [comment]
084552e clean startup message (Chen Bin)
Don't know other message.

**Comment by lxeg0429** [comment]
在org-mode里面，把表格宽度进行限定后，按TAB会出现错误args out of range，要怎么修正啊？

**Comment by redguardtoo** [comment]
show me a sample. besides, emacs, os, org version?

**Comment by lxeg0429** [comment]
GNU Emacs 25.1.1, 64bit, Win7, org-mode version 8.2.10
下面这个表格会出现错误，如果第一个限定是<2>的话就不会报错

| 快捷键         | 说明         |
| <4>            | <6>          |
|----------------+--------------|
| M-LEFT/RIGHT   | 移动列       |
| M-UP/DOWN      | 移动行       |
| M-S-LEFT/RIGHT | 删除/插入列  |
| M-S-UP/DOWN    | 删除/插入行  |
| C-c -          | 添加水平分割线 |
| C-c RET        | 添加水平分割线并跳到下一行 |
| C-c ^          | 根据当前列排序，可以选择排序方式 |

**Comment by redguardtoo** [comment]
不能重现，你有使用等宽字体吗？建议到emacs china上问一下字体设置。

**Comment by lxeg0429** [comment]
我重新下载了你的配置，安装之后，上面的表格还是不能格式化。我原来的配置是有等宽字体的（安装了chinese-fonts-setup），GNU Emacs 25.1.1, Win7 64bit,  org version 8.2.10。

**Comment by redguardtoo** [comment]
read http://orgmode.org/manual/Column-width-and-alignment.html
You specify the 1st column 4 characters wide and second column 6 characters wide. org-mode just follow your instruction strictly. Maybe you should use 40 and 60 instead?

**Comment by lxeg0429** [comment]
把栏的宽度限定为<2>和<6>的时候就没有问题。
我也不知道哪里有问题，我用spacemacs试了一下，没有出现问题，先这样吧。谢谢你的回答！

**Comment by redguardtoo** [comment]
I guess it's because spacemacs use latest org-mode instead of built in org-mode.

My way works on any version of org-mode. The column width is just a **suggestion** to org-mode which will adjust the column ratio automatically.
