### ISSUE TITLE
Hit TAB or ENTER to expand function arguments

### ISSUE THREAD

**Issue by 0x4ec7** [redguardtoo/emacs.d#541]
Hi Bin,

Is there a function I can use to expand arguments when I finish a function and hit TAB or ENTER?

BR//Zhidong

**Comment by redguardtoo** [comment]
company-mode can do this in C++, check its documentation. Maybe you need learn how to use GNU Global.

**Comment by 0x4ec7** [comment]
GNU Global is a brand-new field for me, I will lean it if I have time.

When I type a self-defined function, the arguments table will be shown below.
<img width="580" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4551301/21889097/2fec0200-d902-11e6-9df4-a19f532d2118.png">
I think it's possible to put these arguments into my function parentheses automatically.

**Comment by redguardtoo** [comment]
You didn't mention what language you use. Elpy provides backend for company. I already installed elpy with minimum setup. You could read elpy documentation for more help. For C++, I recommend company+global.

**Comment by 0x4ec7** [comment]
It seems that company-jedi could do the trick.

Thanks
