### ISSUE TITLE
golang is popular now. gohelper would be very hapy if you support it.

### ISSUE THREAD

**Issue by jaydenhe** [redguardtoo/emacs.d#543]
golang is popular now. gohelper would been very hapy if you support it.

**Comment by redguardtoo** [comment]
Sorry, I can't support golang because I don't have any chance to use golang in Australia.

Check https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go for go setup. But I'll will repalce autocomplete with company
