### ISSUE TITLE
Copying emacs.d from Linux to Windows

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#544]
Due to network issues, I am stuck at using the stable.zip having all packages installed already on my Windows setup (myelpa). I am missing the latest enhancements done on the trunk. When will the next stable.zip rolled out?

Secondly, I do have emacs.d on Linux which is synced with trunk and has all necessary packages installed from network. Will simply copying the Linux emacs.d to Windows work or are there platform specific pieces involved?

**Comment by redguardtoo** [comment]
The stable.zip is released this morning, so you are already using the latest setup.

You Linux emacs.d should works out of box on Windows.

**Comment by amittendulkar** [comment]
Thanks. I will close the issue. Is there a page maintained for showing history of stable.zip releases? Or is there a way to figure out when stable.zip was released?
