### ISSUE TITLE
modeline配置

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#545]
你好，我觉得你的modeline的配置很好，参考了你的modeline里面的配置，设置之后，我的modeline里日期的显示是中文，你的是英文，我想问一下，我怎么才能把它设置成中文啊？谢谢！

**Comment by redguardtoo** [comment]
export LC_MESSAGES="en_US.UTF-8" in you ~/.bashrc or `（setenv LC_MESSAGES "en_US.UTF-8") in emacs setup.

**Comment by lxeg0429** [comment]
抱歉，我用的是windows，不大明白你的意思。 '(setenv LC_MESSAGES "en_US.UTF-8") in emacs setup 这是什么意思，直接在.emacs里面写上就行了吗？

**Comment by redguardtoo** [comment]
Yes.

**Comment by lxeg0429** [comment]
我试了好多次，都不起作用。我也不知道哪里有问题。

**Comment by redguardtoo** [comment]
try `(setenv LC_MESSAGES "en_US")` then.

**Comment by samsonwang** [comment]
I see information below during emacs startup:
"Symbol's value as variable is void: LC_MESSAGES"
Do I need any extra configs? (Win7 sp1)

**Comment by samsonwang** [comment]
I just did a quick search on "LC_MESSAGES".
I guess "LC_MESSAGES" is only supported on Linux?

**Comment by redguardtoo** [comment]
sorry, my typo, I updated answer.  It's part of standard which is supported since win2000.

**Comment by lxeg0429** [comment]
还是不管用，C-x C-e之后显示的信息没有问题，但是就是不起作用，重启也没效果。我用你的配置时，开始的时候是中文的，1s之后会自动变成英文的，我没找到在哪里设置的。

**Comment by redguardtoo** [comment]
What's the difference between your mode-line setup and mine then?
Mine is the default setup of original Emacs.

**Comment by lxeg0429** [comment]
我复制了你的mode-line，没有任何区别，里面没有关于day-and-date的配置。day-and-date是需要另外配置的，我在你的别的配置文件里找到了day-and-date的配置，但是没有关于语言的设置。

**Comment by redguardtoo** [comment]
Try original Emacs.

**Comment by lxeg0429** [comment]
init-misc.el 304行

**Comment by lxeg0429** [comment]
不加任何配置的emacs里面，mode-line上的日期显示是中文

**Comment by redguardtoo** [comment]
`(setq display-time-24hr-format t)` is the key

**Comment by lxeg0429** [comment]
这个只是说明要显示24小时制啊，我的里面有这个配置

**Comment by redguardtoo** [comment]
I don't know why, but I tested with my setup.

**Comment by lxeg0429** [comment]
是的，我试过了，没有效果，先这样吧，等以后知道了再设置吧，谢谢，辛苦你了。

**Comment by lxeg0429** [comment]
我对你的配置进行了逐个排查，最后确定init.el里面的init-python-mode起了关键作用，我对那个不熟，不知道为什么。

**Comment by redguardtoo** [comment]
`(setq system-time-locale "C")` in my `~/.custom.el`, modeline will update every second.

**Comment by samsonwang** [comment]
`(setq system-time-locale "C")` is very helpful!!
I put it in the config and it changed my modeline time display into English.
Thanks a lot! :+1:
