### ISSUE TITLE
你好, 请问如何在这套配置下面, 查看RSS订阅, 谢谢!

### ISSUE THREAD

**Issue by esongs** [redguardtoo/emacs.d#546]
如题

**Comment by redguardtoo** [comment]
You need install elfeed by yourself.

**Comment by esongs** [comment]
谢谢, 效果不错! 另外一个问题. elfeed的buffer默认是启动了evil模式的, 导致elfeed的快捷键不能用, 如何默认关闭elfeed-search buffer的evil模式? 谢谢!

**Comment by esongs** [comment]
oh, 不好意思, 春节, 几天没关闭, 这个issus关闭了. 您还可以回答吗?

**Comment by redguardtoo** [comment]
`C-h v major-mode`, then check init-evil.el, for example, search `eshell-mode`
