### ISSUE TITLE
你好,请教下emacs下处理邮件

### ISSUE THREAD

**Issue by esongs** [redguardtoo/emacs.d#547]
谢谢之前关于RSS Reader的问题的答复. 
再请教下, 在您的emacs.d配置中, 如何增加邮件收发的功能? 我主要的邮箱不是gmail的, 什么插件比较好用, 谢谢!

**Comment by redguardtoo** [comment]
check my guide, it works on any service supporting imap/pop3, not only gmail, as I mention in the the guide at the beginning.
