### ISSUE TITLE
w3m cannot retroeve URL error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#548]
sometimes when I use w3m to open https site
it returns "596 Service Not Found" error
for example the url: https://vimgolf.com/challenges/5462e3f41198b80002512673

**Comment by redguardtoo** [comment]
yes, I got error response even in my firefox. I don't think this is solvable in Emacs

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
it seems the page is too big to open
my emacs is already crush
wander if can open page partly
