### ISSUE TITLE
ubuntu下emacs 24.3.1安装 emacs.d报错

### ISSUE THREAD

**Issue by robin2003** [redguardtoo/emacs.d#549]
Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")
  signal(error ("Package `emacs-24.4' is unavailable"))
  error("Package `%s-%s' is unavailable" "emacs" "24.4")
  package-compute-transaction((magit) ((emacs (24 4)) (async (1 9)) (dash (2 13 0)) (with-editor (2 5 9)) (git-commit (2 10 0)) (magit-popup (2 10 0))))
  package-install(magit)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(magit (1 2 0) nil)
  eval-buffer(#<buffer  *load*-957672> nil "/home/robin/.emacs.d/init-elpa.el" nil t)  ; Reading at buffer position 5856
  load-with-code-conversion("/home/robin/.emacs.d/init-elpa.el" "/home/robin/.emacs.d/init-elpa.el" nil t)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/home/robin/.emacs.d/init.el" nil t)  ; Reading at buffer position 2731
  load-with-code-conversion("/home/robin/.emacs.d/init.el" "/home/robin/.emacs.d/init.el" t t)
  load("/home/robin/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by robin2003** [comment]
获取的stable以及v1.0 tag都有问题

**Comment by redguardtoo** [comment]
magit requires 24.4.

I don't use magit in my setup. If you check my git log, I discard because magit only support 24.4.

**Comment by robin2003** [comment]
dear redguardtoo,

i have upgrade my emacs version to 24.3.1, git tag based on stable, but still has the follow errors:

Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")
  signal(error ("Package `emacs-24.4' is unavailable"))
  error("Package `%s-%s' is unavailable" "emacs" "24.4")
  package-compute-transaction((request) ((emacs (24 4))))
  package-install(request)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(request)
  eval-buffer(#<buffer  *load*-448933> nil "/home/robin/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 5916
  load-with-code-conversion("/home/robin/.emacs.d/lisp/init-elpa.el" "/home/robin/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib)) (require (quote init-compat)) (require (quote init-site-lisp)) (require (quote init-utils)) (require (quote idle-require)) (require (quote init-elpa)) (require (quote init-exec-path)) (require (quote init-spelling)) (require (quote init-gui-frames)) (require (quote init-ido)) (require (quote init-dired)) (require (quote init-uniquify)) (require (quote init-ibuffer)) (require (quote init-ivy)) (require (quote init-hippie-expand)) (require (quote init-windows)) (require (quote init-sessions)) (require (quote init-git)) (require (quote init-crontab)) (require (quote init-markdown)) (require (quote init-erlang)) (require (quote init-javascript)) (require (quote init-org)) (require (quote init-css)) (require (quote init-python-mode)) (require (quote init-haskell)) (require (quote init-ruby-mode)) (require (quote init-lisp)) (require (quote init-elisp)) (require (quote init-yasnippet)) (require (quote init-cc-mode)) (require (quote init-gud)) (require (quote init-linum-mode)) (require (quote init-moz)) (require (quote init-gtags)) (require (quote init-clipboard)) (require (quote init-evil)) (require (quote init-multiple-cursors)) (require (quote init-sh)) (require (quote init-ctags)) (require (quote init-bbdb)) (require (quote init-gnus)) (require (quote init-lua-mode)) (require (quote init-workgroups2)) (require (quote init-term-mode)) (require (quote init-web-mode)) ...)
  eval-buffer(#<buffer  *load*> nil "/home/robin/.emacs.d/init.el" nil t)  ; Reading at buffer position 5734
  load-with-code-conversion("/home/robin/.emacs.d/init.el" "/home/robin/.emacs.d/init.el" t t)
  load("/home/robin/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by robin2003** [comment]
在lisp/init-elpa.el 中注释掉request安装，可以顺利安装成功

**Comment by redguardtoo** [comment]
thanks. I updated my setup. Now both myelpa and my emacs.d should work.

The package `request` just drop emacs 24.3 support recently.

**Comment by redguardtoo** [comment]
fixed: 2243c1e use old request (Chen Bin)
request v0.3.0 drops support for emacs 24.3, so we use request v0.2.0 instead
