### ISSUE TITLE
Python quit unexpectedly.

### ISSUE THREAD

**Issue by 0x4ec7** [redguardtoo/emacs.d#550]
Hi Bin,

I met a very strange problem, I think it is about elpy.
![image](https://cloud.githubusercontent.com/assets/4551301/22688407/1f879446-ed67-11e6-800b-cb615db0cae1.png)
If I don't workon any virtual environment, Python often quit unexpectedly.
It might related to this process:
`/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -W ignore -m elpy.__main__`

> ls -la $(which python)
> /usr/local/bin/python -> ../Cellar/python/2.7.13/bin/python
It's very odd that elpy is started by ../MacOS/Python instead of ../bin/python.

Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.13 (/usr/local/bin/python)
Interactive Python: python (/usr/local/bin/python)
Emacs.............: 25.1.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.16.0
Syntax checker....: flake8 (/usr/local/bin/flake8)

Thanks.

**Comment by redguardtoo** [comment]
Seem you did not setup environment variable PATH correctly. Is https://github.com/Valloric/YouCompleteMe/issues/611 related to this issue?

Besides, read my guide https://github.com/redguardtoo/mastering-emacs-in-one-year-guide at least once.

**Comment by 0x4ec7** [comment]
I digged deeper into this problem. It is likely related to brew installed python or importmagic.
This can be resolved by 
1. brew unlink python, which located at '/usr/local/bin/python', and use '/usr/bin/python' instead, but it is not what I wanted. 
2. pip uninstall importmagic.

https://github.com/Valloric/YouCompleteMe/issues/585
https://github.com/Valloric/YouCompleteMe/issues/18
https://github.com/jorgenschaefer/elpy/issues/938

**Comment by redguardtoo** [comment]
Have you tried `virtualenv`? I didn't use python but it's always better to setup isolated environment.

**Comment by 0x4ec7** [comment]
Yes, every project has its own virtual environment.
It works fine if I pyvenv-workon a specific virtual environment.
I just can't figure out the reason for this problem.

**Comment by redguardtoo** [comment]
If you setup all the environment variables I mentioned, there should be no problem.

**Comment by 0x4ec7** [comment]
I'll go on studying this problem.
Thanks a lot.
