### ISSUE TITLE
when use tramp based emacs.d on stable tag, it always promp sending password and hang....

### ISSUE THREAD

**Issue by robin2003** [redguardtoo/emacs.d#551]
dear redguardtoo,

i use emacs 24.3.1 installed your emacs.d, and i use c-x c-f /ssh:user@ip: enter remote server.
when i open a file, it always promp sending password, and then it hangs.

how to solve this problem.
wait for your help.

if you have better plugin that can replace tramp, please share with me for free.
thanks.

**Comment by redguardtoo** [comment]
http://stackoverflow.com/questions/7260/how-do-i-setup-public-key-authentication
