### ISSUE TITLE
请教steve purcell的emacs配置如何正确显示中文

### ISSUE THREAD

**Issue by limTeTE** [redguardtoo/emacs.d#552]
Emacs：24.5.1
系统：windows10（64bit）
Emacs新手，初次尝试使用purcell的emacs配置，不太清楚中文显示应该如何修改配置文件。
谢谢指导

**Comment by redguardtoo** [comment]
https://github.com/tumashu/chinese-fonts-setup 

or https://emacs-china.org/t/spacemacs/1003
