### ISSUE TITLE
能否在mode line增加当前buffer读取文件进度情况

### ISSUE THREAD

**Issue by robin2003** [redguardtoo/emacs.d#553]
有时候打开一个大文件时候，也不知道当前已经浏览到哪里了，能否在mode line上显示当前浏览进度，比如说浏览到5%，95%等~

**Comment by redguardtoo** [comment]
http://emacs-fu.blogspot.com.au/2011/08/customizing-mode-line.htm

search "progress", you can change `mode-line-format` in either `init-mode-line.el` or `~/.custom.el`

**Comment by robin2003** [comment]
好的，多谢~
