### ISSUE TITLE
如何改变当前文件编码

### ISSUE THREAD

**Issue by yangdawei** [redguardtoo/emacs.d#554]
请教如何改变当前文件编码。（按网上所说 C-x C-m f utf8-unix <RET>，调出的M-x模式，没有f选项。Emacs知识残缺严重，见笑了。）

**Comment by redguardtoo** [comment]
see http://ergoemacs.org/emacs/emacs_encoding_decoding_faq.html

**Comment by yangdawei** [comment]
学习了。谢谢。
