### ISSUE TITLE
C-x C-f package

### ISSUE THREAD

**Issue by lxeg0429** [redguardtoo/emacs.d#555]
你好！请问你的配置里面`C-x C-f` 的时候，输入文件名字会自动跳转到以前访问过的文件，这是怎么实现的啊？是什么package吗？

另外，你的配置挺好用的，但是开始的时候特别卡，只有配置了中文字体后才会流畅，建议加上这一项。(我的系统：`Window 7 64bit` )

**Comment by redguardtoo** [comment]
ido and other ido related packages, I don't details, it's copied from Purcell, maybe.

Check my readme for font setup. It has nothing to do with my setup. It's Emacs own issue

**Comment by lxeg0429** [comment]
ok, thank you!
