### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by yangdawei** [redguardtoo/emacs.d#556]
刚下拉了最新的版本后启时发现错误提示：
` File error: https://stable.melpa.org/packages/chinese-pyim-1.5.1.tar`

可能是因为国内连接不上stable.melpha.org，请教如何消除错误。

**Comment by redguardtoo** [comment]
Try access https://stable.melpa.org in your browser. If fine, then it's not net network problem.

If you are using windows version Emacs, check README.

Please note I remove not secure http connection a few days ago, as other distributions did ages ago.

**Comment by yangdawei** [comment]
访问 https://stable.melpa.org 是可以的。不知道问题出在哪里？ 我的系统是Debian stretch。

**Comment by yangdawei** [comment]
找到错误，在自定义部分`.custom.el`中出了问题，和您的配置无关。给您填麻烦了。
