### ISSUE TITLE
Recentf列表去除记录文件

### ISSUE THREAD

**Issue by yangdawei** [redguardtoo/emacs.d#557]
在Recentf列表中总是出现两个记录文件：`company-statistics-cache.el`和`recentf`，请问如何去除这两条文件。

在退出emacs时，回显区常显示`Buffer "company-statistics-cache.el" has a running process; kill it? (y or n)`，请问如何避免该显示。

**Comment by redguardtoo** [comment]
1. see `recentf-exclude` in init-misc.el
2. I don't know. Maybe you could raise an issue at company-mode site

**Comment by yangdawei** [comment]
https://github.com/company-mode/company-mode/issues/643

提了这个问题，回答这是由company-statistics引起的，看来作者不认为这是company-mode的问题。
