### ISSUE TITLE
magit conflict resolve issue

### ISSUE THREAD

**Issue by xueyouchao** [redguardtoo/emacs.d#559]
When I use magit to resolve conflict, press 'e' in magit-status buffer, bring up ediff compare window, but then I want to press a/b to resolve the conflict(http://dachary.org/?p=2893),
 I can not do it.  The conflict file is a markdown file, is it due to some mode overlapping with magit-ediff?
Attached screenshot below, when I press b in the small buffer, it gives me an error: Bad diff region number....
![2017-02-23-224622_1920x1095_scrot](https://cloud.githubusercontent.com/assets/281414/23289830/63005b44-fa1a-11e6-8ef4-700e37903516.png)

**Comment by redguardtoo** [comment]
I don't use magit. I guess evil key bindings are used. Check `init-evil.el`, the `grep-mode` setup may help

**Comment by xueyouchao** [comment]
Thank you, I will check that.
