### ISSUE TITLE
how to remove the highlight marks?

### ISSUE THREAD

**Issue by AmyAckerRoot** [redguardtoo/emacs.d#560]
Emacs: 25.1.1
System: Ubuntu 16.04.1
Configuration: redguardtoo/emacs.d

It seems only occurs in Org-mode.

It highlights them automatically.

![selection_001](https://cloud.githubusercontent.com/assets/19355221/23577431/0dfe9b6a-00fa-11e7-94df-6af7851844f9.png)

![selection_002](https://cloud.githubusercontent.com/assets/19355221/23577434/17c0c150-00fa-11e7-8535-b16e6688bab7.png)

![selection_003](https://cloud.githubusercontent.com/assets/19355221/23577451/2f6e36ca-00fa-11e7-95ec-cc73312e8156.png)

![selection_004](https://cloud.githubusercontent.com/assets/19355221/23577452/3391156a-00fa-11e7-80e3-60d6c7048e6f.png)

![selection_005](https://cloud.githubusercontent.com/assets/19355221/23577453/37078184-00fa-11e7-98b3-489f927f2349.png)

![selection_006](https://cloud.githubusercontent.com/assets/19355221/23577456/3c79eabc-00fa-11e7-987e-a917d54a7994.png)

**Comment by redguardtoo** [comment]
see #253

**Comment by AmyAckerRoot** [comment]
Thank you very much!
