### ISSUE TITLE
winner-undo winner-redo issue

### ISSUE THREAD

**Issue by xueyouchao** [redguardtoo/emacs.d#562]
I saw you defined C-x 4 u and C-x 4 U  for  winner-undo and winner-redo which is good.

However in the new version of emacs(after 22) , by default ‘C-c left’ and ‘C-c right’ are also used for these two according to: https://www.emacswiki.org/emacs/WinnerMode

It's annoying every time I try to press C-c to end a web server in emacs shell, it conflicts with C-c left and C-c right and I have to disable winner mode to do this.

How can I disable the C-c left and C-c right binding for winner-undo and winner-redo by default and still keep winner mode enabled?

**Comment by redguardtoo** [comment]
`(define-key winner-mode-map (kbd "C-c <right>") nil)`

**Comment by xueyouchao** [comment]
Thank you very much, problem solved.
