### ISSUE TITLE
ggtags模式工作有问题

### ISSUE THREAD

**Issue by lldustc** [redguardtoo/emacs.d#566]
最近的版本ggtags不能正常工作，去年早些时候的版本可以正常工作，不知道是不是修改了什么地方

**Comment by redguardtoo** [comment]
ggtags has not been updated for a long time. and I don't like it's architecture. The only reason I keep it is I'm still waiting https://github.com/syohex/emacs-counsel-gtags to mature. I strongly recommend you use counsel-gtags instead and give it a star.

**Comment by lldustc** [comment]
Thanks!!
