### ISSUE TITLE
emacs中使用ipconfig输出乱码

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#567]
babun中安装emacs-w32，使用大大的emacs配置。在emacs中 M-x term 调用了zsh

查看本机ip的时候，调用 $ ipconfig ,出现下面的乱码

![20170315_205238](https://cloud.githubusercontent.com/assets/5094958/23949327/d23619a2-09c1-11e7-9619-47bbef9f107a.png)

**Comment by redguardtoo** [comment]
set environment variable LC_MESSAGE to `en_US.UTF8`

**Comment by vipzrx** [comment]
![20170315_211449](https://cloud.githubusercontent.com/assets/5094958/23952482/8d1c50e2-09cc-11e7-9e49-8f970e0cde87.png)

babun中设置 .zshrc
C:\Users\kk\.babun\cygwin\home\kk\.zshrc

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_MESSAGE=en_US.UTF-8

使用windows下的命令，还是会出来乱码

**Comment by redguardtoo** [comment]
`LC_MESSAGES`, sorry, my typo, in my way, you only see English messages.

But maybe you prefer Chinese, see https://github.com/babun/babun/issues/582

**Comment by vipzrx** [comment]
谢谢！
你给出的链接中大致有两种
Add | iconv -f GBK -t UTF8 after the CMD command.

I add chcp 65001 into ~/.babunrc and the problem go away.

出现上面的乱码是因为babun不支持GBK的编码，我觉得第二种方法，让babun识别GBK的编码好一些。
您的意见呢？
I add chcp 65001 into ~/.babunrc and the problem go away.
这个在配置文件中具体怎么写呢？

**Comment by redguardtoo** [comment]
No opinion, I don't use babun.
