### ISSUE TITLE
rgrep 命令如何搜索 * 文件？

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#568]
你好，使用 ivy 后，rgrep 无法搜索 * 文件，而不希望搜索类似 *.js 文件。

**Comment by stevenswong** [comment]
minibuffer 显示这样：

1/1Search for "immutable" in files (default *.js):

输入 * ，自动选中 *.js

谢谢

**Comment by redguardtoo** [comment]
ivy 默认用空格代替任意字符，另外ivy使用regular expression，我没有做任何设置。

**Comment by stevenswong** [comment]
嗯，需要使用ivy的快捷键 C-M-j
原文：
[https://github.com/abo-abo/swiper/issues/250]
