### ISSUE TITLE
yank的快捷键被替换成了S-insertchar

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#569]
![20170320_201415](https://cloud.githubusercontent.com/assets/5094958/24099387/e09eb8e6-0da9-11e7-9829-a803f5271ee0.png)

使用你的配置，之前都是正常的：在windows中其他程序中，Ctrl + C，在emacs中C-y就可以将复制的内容粘贴到org模式的文本中。

也不知自己误按了什么键，yank的快捷键就成了S-insertchar。

在网上找到一篇文章

s-insertchar instead of c-y : orgmode
https://www.reddit.com/r/orgmode/comments/504oif/sinsertchar_instead_of_cy/

自己也看不懂，我还在理解。希望大大给个提示

**Comment by vipzrx** [comment]
![20170320_205214](https://cloud.githubusercontent.com/assets/5094958/24100432/30b97802-0daf-11e7-9419-6b023d094987.png)

 C-h k C-y 的输出如上图所示

**Comment by redguardtoo** [comment]
Not my setup.

**Comment by vipzrx** [comment]
我使用的是你的设置，我在你emacs.d的基础上只是修改elpa的源为清华的源，其他的都没有变

![20170320_212522](https://cloud.githubusercontent.com/assets/5094958/24101729/5e03925c-0db4-11e7-95be-d5c07001582a.png)

差异如下：
![20170320_213345](https://cloud.githubusercontent.com/assets/5094958/24101899/f91568ba-0db4-11e7-8e98-9112f92ed3bd.png)

其他的都没有改变

**Comment by redguardtoo** [comment]
If you are taking `yank`, if you are using evil-mode, then hotkey for yank is `p`, if you go back to emacs mode (you can press `C-z` in evil-mode), the original `C-y` is still there.

It's evil setup, not my setup.
