### ISSUE TITLE
my-grep 不能高亮匹配的关键字

### ISSUE THREAD

**Issue by stevenswong** [redguardtoo/emacs.d#570]
你好，我把 init-ivy.el 文件的 my-grep-cli 函数的 ag 删除 --nocolor 选项也不能高亮。

原来是这样的：
ag -s --nocolor --nogroup --silent
修改成这样的：
ag -S --nogroup --silent

求原因，谢谢

**Comment by redguardtoo** [comment]
It has nothing to do with ag. Basically you can do nothing about it unless you know Emacs Lisp.

I intended to keep my-grep UI minimum because my-grep is designed for high performance (I test with millions of matched results) or else I will use helm/ivy's own plugin.

**Comment by stevenswong** [comment]
ok, thanks
