### ISSUE TITLE
error: package 'async-' is unavailable 

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#571]
![20170321_201422](https://cloud.githubusercontent.com/assets/5094958/24146960/119c338c-0e73-11e7-85fd-3b3047439dca.png)

使用的是最新的配置
git clone https://github.com/redguardtoo/emacs.d.git
启动的时候，
{ ~ }  » https_proxy=127.0.0.1:1080 http_proxy=127.0.0.1:1080 emacs -nw --debug-init            ~

*scratch* ( 1,0) [Fundamental Ins]  ------------------------------------------------------------------------------------------
Debugger entered--Lisp error: (file-error "https://raw.githubusercontent.com/redguardtoo/js2-mode/release/archive-contents" "$
  signal(file-error ("https://raw.githubusercontent.com/redguardtoo/js2-mode/release/archive-contents" "Bad Request"))
  package--download-one-archive(("my-js2-mode" . "https://raw.githubusercontent.com/redguardtoo/js2-mode/release/") "archive-$
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (progn (package-refresh-contents) (require-package package min-version t))
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (r$
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-insta$
  require-package(async)
  eval-buffer(#<buffer  *load*-982269> nil "/home/kk/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 5049
  load-with-code-conversion("/home/kk/.emacs.d/lisp/init-elpa.el" "/home/kk/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib$
  eval-buffer(#<buffer  *load*> nil "/home/kk/.emacs.d/init.el" nil t)  ; Reading at buffer position 5779
  load-with-code-conversion("/home/kk/.emacs.d/init.el" "/home/kk/.emacs.d/init.el" t t)

在浏览器中访问这个文件，提示如下

![20170321_210601](https://cloud.githubusercontent.com/assets/5094958/24148554/4fa8632e-0e7a-11e7-8187-23dafb2dd0e2.png)

**Comment by redguardtoo** [comment]
Looks it's network problem, I can install js2-mode without issue.

Download https://github.com/redguardtoo/js2-mode/raw/release/js2-mode-100000002.tar then `M-x package-install-file`

**Comment by vipzrx** [comment]
1 下载了tar文件已经安装了
2 我还是不明白，你的配置
https://raw.githubusercontent.com/redguardtoo/js2-mode/release/archive-contents
这个是怎么找到的

![20170322_172649](https://cloud.githubusercontent.com/assets/5094958/24190989/3c8cc612-0f25-11e7-9eb6-7752823e0fb0.png)

这个页面里面只有tags，没有看到release，但是却可以看到
https://raw.githubusercontent.com/redguardtoo/js2-mode/release/archive-contents
的内容

**Comment by redguardtoo** [comment]
See README, "If you use Windows Emacs ...", basically it says you need use HTTPS download packages for security reason. That's kind of standard in the community. Every distribution switched to HTTPS ages ago.

**Comment by geometryolife** [comment]
> https://github.com/redguardtoo/js2-mode => 8 branches
> 
> See README, "If you use Windows Emacs ...", basically it says you need use HTTPS download packages for security reason. That's kind of standard in the community. Every distribution switched to HTTPS ages ago.

大神你好，为什么centos7也会出现error：包‘async-’不可用

**Comment by geometryolife** [comment]
> https://github.com/redguardtoo/js2-mode => 8 branches
> 
> See README, "If you use Windows Emacs ...", basically it says you need use HTTPS download packages for security reason. That's kind of standard in the community. Every distribution switched to HTTPS ages ago.



centos7出现这个报错，我尝试把https协议换成http，还是一样，换成清华源也一样，都一直无法安装。
Warning (initialization): An error occurred while loading ‘/home/Joe/.emacs.d/init.el’:

error: Package ‘async-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.


### 下面是执行 emacs --debug-init的:

Debugger entered--Lisp error: (error "Could not create connection to melpa.org:443")
  signal(error ("Could not create connection to melpa.org:443"))
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents" n$
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-cont$
  require-package(async)
  eval-buffer(#<buffer  *load*-232290> nil "/home/Joe/.emacs.d/lisp/init-elpa.el" nil t)  ; Re$
  load-with-code-conversion("/home/Joe/.emacs.d/lisp/init-elpa.el" "/home/Joe/.emacs.d/lisp/in$
  load("/home/Joe/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/$
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init (quote init-autoload)) (require-init (qu$
  eval-buffer(#<buffer  *load*> nil "/home/Joe/.emacs.d/init.el" nil t)  ; Reading at buffer p$
  load-with-code-conversion("/home/Joe/.emacs.d/init.el" "/home/Joe/.emacs.d/init.el" t t)
  load("/home/Joe/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x230f41>)()
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment]
都是网络问题。第一次安装时我给你选择可以切换到163的源。

**Comment by geometryolife** [comment]
> 都是网络问题。第一次安装时我给你选择可以临时切换到163的源。
> ![image](https://user-images.githubusercontent.com/184553/89894880-2e2c3480-dc1e-11ea-878d-806a1921a6c3.png)

Switch to faster package repositories in China temporarily?
You still need modify `package-archives' in "init-elpa.el" to PERMANENTLY use this ELPA mirror. (y or n)
第一次讯问这个的时候我选择y，然后就报 error: Package ‘async-’ is unavailable 这个错误

**Comment by geometryolife** [comment]
> 都是网络问题。第一次安装时我给你选择可以临时切换到163的源。
> ![image](https://user-images.githubusercontent.com/184553/89894880-2e2c3480-dc1e-11ea-878d-806a1921a6c3.png)

我把下面的源放到上面就报163无法连接
Debugger entered--Lisp error: (error "Could not create connection to mirrors.163.com:443")
  signal(error ("Could not create connection to mirrors.163.com:443"))
  package--download-one-archive(("melpa" . "https://mirrors.163.com/elpa/melpa/") "archive-con$
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-cont$
  require-package(async)
  eval-buffer(#<buffer  *load*-841835> nil "/home/Joe/.emacs.d/lisp/init-elpa.el" nil t)  ; Re$
  load-with-code-conversion("/home/Joe/.emacs.d/lisp/init-elpa.el" "/home/Joe/.emacs.d/lisp/in$
  load("/home/Joe/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/$
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init (quote init-autoload)) (require-init (qu$
  eval-buffer(#<buffer  *load*> nil "/home/Joe/.emacs.d/init.el" nil t)  ; Reading at buffer p$
  load-with-code-conversion("/home/Joe/.emacs.d/init.el" "/home/Joe/.emacs.d/init.el" t t)
  load("/home/Joe/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x230f41>)()
  command-line()
  normal-top-level()
![QQ截图20200811202627](https://user-images.githubusercontent.com/54882546/89897003-f5d22980-dc10-11ea-9e45-d99cfd51f02f.png)

**Comment by redguardtoo** [comment]
Close and restart emacs. If it does not work, delete `~/.emacs.d/elpa` and restart emacs.

**Comment by geometryolife** [comment]
> You can use either 163 or melpa.org as package repository.
> 
> If you got any network problem, restart emacs. Finally all the packages will be installed.
> 
> If it does not work, delete `~/.emacs.d/elpa` and restart emacs.
> 
> BTW, what's your Emacs version?

GNU Emacs 26.3
这个问题还是一样，我给你知乎发了私信，如果方便，你可以亲自看下我的服务器。

**Comment by redguardtoo** [comment]
把桌面已配置好的`.emacs.d`所有内容（包括~/.emacs.d/elpa内的所有的包）拷到服务器就行了。假设服务器和桌面版本的emacs都是emacs26。

这个问题还多人都碰到过，基本上都是网络问题。

我个人建议你还是先把桌面的emacs熟悉后再考虑服务器。     

https://github.com/redguardtoo/elpa-mirror 提供了解决方案。

**Comment by geometryolife** [comment]
> 把桌面已配置好的`.emacs.d`所有内容（包括~/.emacs.d/elpa内的所有的包）拷到服务器就行了。假设服务器和桌面版本的emacs都是emacs26。
> 
> 这个问题许多人都碰到过，基本上都是网络问题。
> 
> 我个人建议你还是先把桌面的emacs熟悉后再考虑服务器。
> 
> 实际上 https://github.com/redguardtoo/elpa-mirror 提供了一个通用的解决方案

感谢，按照你的方法，上传配置已经成功。
