### ISSUE TITLE
org-mode中使用firefox打开连接

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#572]
https://github.com/LdBeth/Emacs-for-Noobs/issues/2
问题已经在这里描述了

再重复下：

我使用你默认的emacs.d配置
设置的是使用w3m打开org-mode模式中的链接。我是在cygwin下使用emacs，想用firefox打开连接
我lisp代码不好，已经找到了相关的设置地方，不知道该怎么改：

(defadvice org-open-at-point (around org-open-at-point-choose-browser activate)
(let ((browse-url-browser-function
(cond
;; open with external browser
((equal (ad-get-arg 0) '(4)) 'browse-url-generic)
;; open with w3m
(t 'w3m-browse-url))))
ad-do-it))

firefox的安装路径在
C:\Program Files (x86)\Mozilla Firefox\firefox.exe

另外我希望双击org-mode中的链接，能够打开一个tab页面，现在firefox.exe是打开一个窗口

**Comment by vipzrx** [comment]
Command Line Options - Mozilla | MDN
https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options
上面的网站上，提到了firefox支持的命令行参数

相关的有两个

> 
> -new-instance
> 
> Open new instance, not a new window in running instance, which allows multiple copies of application to be open at a time.
> 
> firefox -new-instance -P "Another Profile"
> 
> Note: Not available for Windows, see bug 855899.
> -no-remote
> 
> Do not accept or send remote commands; implies -new-instance.
> 
> firefox -no-remote -P "Another Profile"
> 
> Note: Since Firefox 9, this does really mean what its name implies on all platforms, i.e. instances created with this parameter do not accept or send remote commands, see bug 650078. That means that such instances won't be re-used. Also when using this argument a new instance is created in any case.

其中提到在windows下不支持  -new-instance

855899 - -new-instance flag does not work
https://bugzilla.mozilla.org/show_bug.cgi?id=855899

但是在windows中从word之类的程序中双击链接，是可以在当前打开的firefox窗口中，新建一个tab打开链接的。

**Comment by redguardtoo** [comment]
I usually just copy the link to the clipboard, that works always.

**Comment by LdBeth** [comment]
Press <kbd>C-h v</kbd> you can qurey the value of `browse-url-browser-function`.
The default value should be `browse-url-default-browser`, which is:
```
("firefox" . browse-url-firefox)
 ("chromium-browser" . helm-browse-url-chromium)
 ("conkeror" . helm-browse-url-conkeror)
 ("uzbl-browser" . helm-browse-url-uzbl)
 ("kfmclient" . browse-url-kde)
 ("gnome-moz-remote" . browse-url-gnome-moz)
 ("mozilla" . browse-url-mozilla)
 ("galeon" . browse-url-galeon)
 ("netscape" . browse-url-netscape)
 ("xmosaic" . browse-url-mosaic)
 ("xterm" . browse-url-text-xterm)
 ("emacs" . eww-browse-url))
```
And the def of `browse-url-firefox` is:
```
(defun browse-url-firefox (url &optional new-window)
  "Ask the Firefox WWW browser to load URL.
Defaults to the URL around or before point.  Passes the strings
in the variable `browse-url-firefox-arguments' to Firefox.

Interactively, if the variable `browse-url-new-window-flag' is non-nil,
loads the document in a new Firefox window.  A non-nil prefix argument
reverses the effect of `browse-url-new-window-flag'.

If `browse-url-firefox-new-window-is-tab' is non-nil, then
whenever a document would otherwise be loaded in a new window, it
is loaded in a new tab in an existing window instead.

Non-interactively, this uses the optional second argument NEW-WINDOW
instead of `browse-url-new-window-flag'."
  (interactive (browse-url-interactive-arg "URL: "))
  (setq url (browse-url-encode-url url))
  (let* ((process-environment (browse-url-process-environment)))
    (apply 'start-process
           (concat "firefox " url) nil
           browse-url-firefox-program
           (append
            browse-url-firefox-arguments
            (if (browse-url-maybe-new-window new-window)
		(if browse-url-firefox-new-window-is-tab
		    '("-new-tab")
		  '("-new-window")))
            (list url)))))
```
To use this function under Windows, you might need to define `browse-url-firefox-program` to the path of your Firefox program.

I wish I've provide some help. 😃 

PS: I use mac at most time, so I know little about cygwin and I can't guarantee my solution works.

**Comment by redguardtoo** [comment]
Sorry, I totally forget what I did before. You can use `org-open-at-point` which will open the url with internal browser (w3m, in my case) or `C-u M-x org-open-at-point` which will open the external browser. The external browser is defined in `browse-url-generic-program`, see `init-emacs-w3m.el`.
