### ISSUE TITLE
the return and yank/paste indent in org mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/emacs.d#573]
recently, I get some trouble with org mode
### first
when keystroke `return` key isn't indent relative to above line
all of this in one step:
<pre><code>
*** headline|    ->    *** headline    ->    *** headline
                       |                         |
</code></pre>
### second
the code block I copy outside emacs, which is not auto-indent when yanking in org
yank code block:
<pre><code>
*** headline
{
    code block
}

v

*** headline
    {
      code block
    }
</code></pre>

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
I will be appreciate if give some lisp ideas

**Comment by redguardtoo** [comment]
my `enter` key is binding to `org-return` and it's fine on my computer, you must override your `enter` key binding.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
also can use `org-return-indent` is default bind to `C-j`
but have no idea for paste indent

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
someone has resolve it
but I think it should be more improved
<pre><code>
(defun yank-with-indent ()
  (interactive)
  (let ((indent
         (buffer-substring-no-properties (line-beginning-position) (line-end-position))))
    (message indent)
    (yank)
    (narrow-to-region (mark t) (point))
    (pop-to-mark-command)
    (replace-string "\n" (concat "\n" indent))
    (widen)))
</pre></code>
giving up write source code directly in org, I run `org-attach` to make a code file attachment like
