### ISSUE TITLE
chinese-pyim 半角符号的疑问

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#575]
我在使用 chinese-pyim 时因为您的配置遇到一些不太舒服的体验，所以来询问一下您的使用习惯

其实最大的问题就在于中英输入的切换，我觉得每次使用 `C-\`切换输入法不太舒服，所以使用了`pyim-english-input-switch-functions`, 在这几年里 chiense-pyim 的探针函数也有过几次变化，就目前来说是以光标前一个字符为中（全角）英（半角）字符来切换输入的语言，在配置中你设置了始终输入半角符号，这就使得每次输入符号后就需要调用`pyim-convert-code-at-point`，这样也很麻烦……所以我想把你的配置里对于标点的设置取消掉。

在此之前就想请教一下你平时都如何处理使用 chinese-pyim 时中英切换的问题，因为在你的配置里并没有设置自动切换的探针函数。如果有其他便捷的切换方式（如像其他输入法一样用shift切换这种）我就不需要更改配置了。

打扰了，谢谢！

**Comment by redguardtoo** [comment]
see `init-chinese-pyim.el`:
```lisp
;; use western punctuation (ban jiao fu hao)
(setq pyim-punctuation-dict nil)

````

**Comment by smallst** [comment]
哦大概是我表述得不太清楚……
我的问题是

当输入中文时需要临时插入英文的解决方案
如输入 `我使用 Archlinux 系统`

chinese-pyim 对于非拼音序列会自动将可组成的汉字上屏，无法连续输入 archlinux 再用 `enter` 使英文上屏。

**Comment by redguardtoo** [comment]
直接按enter不就行了，所有输入法都这样。
