### ISSUE TITLE
ubuntu14.04 launcher error

### ISSUE THREAD

**Issue by MonkJingfeng** [redguardtoo/emacs.d#576]
> Warning (initialization): An error occurred while loading `/home/luojiarui/.emacs.d/init.el':

> error: Package `emacs-24.4' is unavailable

my emacs version is 24.3.1

**Comment by redguardtoo** [comment]
`emacs --debug-init` then post full error message

**Comment by MonkJingfeng** [comment]
Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")
  signal(error ("Package `emacs-24.4' is unavailable"))
  error("Package `%s-%s' is unavailable" "emacs" "24.4")
  package-compute-transaction((gh gist) ((emacs (24 4)) (pcache (0 3 1)) (logito (0 1))))
  package-compute-transaction((gist) ((emacs (24 1)) (gh (0 9 2))))
  package-install(gist)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(gist)
  eval-buffer(#<buffer  *load*-682345> nil "/home/luojiarui/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 5524
  load-with-code-conversion("/home/luojiarui/.emacs.d/lisp/init-elpa.el" "/home/luojiarui/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib)) (require (quote init-compat)) (require (quote init-site-lisp)) (require (quote init-utils)) (require (quote idle-require)) (require (quote init-elpa)) (require (quote init-exec-path)) (require (quote init-spelling)) (require (quote init-gui-frames)) (require (quote init-ido)) (require (quote init-dired)) (require (quote init-uniquify)) (require (quote init-ibuffer)) (require (quote init-ivy)) (require (quote init-hippie-expand)) (require (quote init-windows)) (require (quote init-sessions)) (require (quote init-git)) (require (quote init-crontab)) (require (quote init-markdown)) (require (quote init-erlang)) (require (quote init-javascript)) (require (quote init-org)) (require (quote init-css)) (require (quote init-python-mode)) (require (quote init-haskell)) (require (quote init-ruby-mode)) (require (quote init-lisp)) (require (quote init-elisp)) (require (quote init-yasnippet)) (require (quote init-cc-mode)) (require (quote init-gud)) (require (quote init-linum-mode)) (require (quote init-moz)) (require (quote init-gtags)) (require (quote init-clipboard)) (require (quote init-evil)) (require (quote init-multiple-cursors)) (require (quote init-sh)) (require (quote init-ctags)) (require (quote init-bbdb)) (require (quote init-gnus)) (require (quote init-lua-mode)) (require (quote init-workgroups2)) (require (quote init-term-mode)) (require (quote init-web-mode)) ...)
  eval-buffer(#<buffer  *load*> nil "/home/luojiarui/.emacs.d/init.el" nil t)  ; Reading at buffer position 5779
  load-with-code-conversion("/home/luojiarui/.emacs.d/init.el" "/home/luojiarui/.emacs.d/init.el" t t)
  load("/home/luojiarui/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by redguardtoo** [comment]
fixed at 4574e25

gist use `gh` which is dependent on emacs 24.4 *recently*

**Comment by tchvsps** [comment]
i have the same error

**Comment by redguardtoo** [comment]
It's already fixed. Emacs 24.3 is OK with latest package upgrade

My setup use stable packages mostly. So it should support old Emacs for a longer time.

Package developer may stop supporting Emacs 24.3.
