### ISSUE TITLE
C-x C-f无法远程登录其他机器

### ISSUE THREAD

**Issue by HapCoderWei** [redguardtoo/emacs.d#577]
你好,我使用的你的emacs配置文件,很强大.但是我发现一个问题,我使用你的配置文件无法远程登录到其他机器了,我使用C-x C-f之后,目录默认设置为家目录下,我尝试删除路径之后自己输入/ssh:,但是在删除/home/之后我无法再输入任何东西了,只能C-g取消,请问我应该怎么办,谢谢

**Comment by redguardtoo** [comment]
`C-f` on more time, https://github.com/redguardtoo/emacs.d#open-file-with-ido

**Comment by HapCoderWei** [comment]
Ooo, find it,
Open file with Ido

If you press C-x C-f to open a file, Ido
<http://emacswiki.org/emacs/InteractivelyDoThings> will show the
suggestions.

Keep pressing C-f to ignore the suggestions.


Thanks a lot, and I will try it later.😀😀

2017-04-08 19:32 GMT+08:00 Chen Bin <notifications@github.com>:
