### ISSUE TITLE
auto complete function report fault in C++ mode 

### ISSUE THREAD

**Issue by zharmand** [redguardtoo/emacs.d#580]
Hello, under your .emacs.d configuration ,I'm trying to use auto complete function in C++ major mode at the following code:
```
void SUBJECT::add(OBSERVER* observer){
    list.//type "." character here (list is a std::list container object, which i want to invoke it's method)
```

Emacs report the following error：
**clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:11:10 -**

May you help me  to solve the error? It happened because of the clang command or some .el file?
My clang version：Ubuntu clang version 3.6.0-2ubuntu1
Thank you！

**Comment by redguardtoo** [comment]
I think it's `company-mode` setup issue.

Unless you use GNU Global (see my article http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html) plus `company-gtags`, `Company` tries to use clang to auto complete C++ code. That means you need set `company-clang-arguments`, see http://tuhdo.github.io/c-ide.html#sec-2 for some sample setup.

See https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html for GCC default C++ header search paths
