### ISSUE TITLE
Lisp nesting exceeds under OpenSuse 42.1

### ISSUE THREAD

**Issue by viscroad** [redguardtoo/emacs.d#581]
Hi Sir,

1. After start your emacs config under Opensue Leap 42.1, I got a "Lisp nesting exceeds `max-lisp-eval-depth`" message in minibuffer, so I can't use any commands,.

2. I tried to start in console without window, I got "error: Clipboard support not available", after emacs --debug-init, got the following message,

 signal(error ("Clipboard support not available"))
  error("Clipboard support not available")
  (condition-case nil (cond ((eq system-type (quote darwin)) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert str-val) (\
call-process-region ... ... "/usr/bin/pbcopy")) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) ((eq system-type (quote cygwin)) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save\
-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert str-val) (call-process-region ... ... "putclip")) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) ((memq system-typ\
e (quote (gnu gnu/linux gnu/kfreebsd))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert str-val) (call-process-region .\
.. ... "xsel" nil nil nil "--clipboard" "--input")) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) (t (error "Clipboard support not available"))) (error (error "Clipboard support not ava\
ilable")))
  (condition-case nil (cond ((fboundp (quote ns-set-pasteboard)) (ns-set-pasteboard str-val)) ((fboundp (quote w32-set-clipboard-data)) (w32-set-clipboard-data str-val) (setq simpleclip-contents str-va\
l)) ((fboundp (quote x-set-selection)) (x-set-selection (quote CLIPBOARD) str-val)) (t (error "Clipboard support not available"))) (error (condition-case nil (cond ((eq system-type (quote darwin)) (let\
 ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...)))) ((eq system-type (quote cygwin)) (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (u\
nwind-protect ... ...)))) ((memq system-type (quote (gnu gnu/linux gnu/kfreebsd))) (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...)))) (t (error "Clipboar\
d support not available"))) (error (error "Clipboard support not available")))))
  simpleclip-set-contents("testsimpleclip!")
  test-simpleclip()
  (setq simpleclip-works (test-simpleclip))
  eval-buffer(#<buffer  *load*-334856> nil "/home/.emacs.d/lisp/init-utils.el" nil t)  ; Reading at buffer position 6998
  load-with-code-conversion("/home/.emacs.d/lisp/init-utils.el" "/home/.emacs.d/lisp/init-utils.el" nil t)
  require(init-utils)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib)) (require (quote init-compat)) (require (quote init-site-lisp)) (require (\
quote init-utils)) (require (quote idle-require)) (require (quote init-elpa)) (require (quote init-exec-path)) (require (quote init-spelling)) (require (quote init-gui-frames)) (require (quote init-ido\
)) (require (quote init-dired)) (require (quote init-uniquify)) (require (quote init-ibuffer)) (require (quote init-ivy)) (require (quote init-hippie-expand)) (require (quote init-windows)) (require (q\
uote init-sessions)) (require (quote init-git)) (require (quote init-crontab)) (require (quote init-markdown)) (require (quote init-erlang)) (require (quote init-javascript)) (require (quote init-org))\
 (require (quote init-css)) (require (quote init-python-mode)) (require (quote init-haskell)) (require (quote init-ruby-mode)) (require (quote init-lisp)) (require (quote init-elisp)) (require (quote i\
nit-yasnippet)) (require (quote init-cc-mode)) (require (quote init-gud)) (require (quote init-linum-mode)) (require (quote init-moz)) (require (quote init-gtags)) (require (quote init-clipboard)) (req\
uire (quote init-evil)) (require (quote init-multiple-cursors)) (require (quote init-sh)) (require (quote init-ctags)) (require (quote init-bbdb)) (require (quote init-gnus)) (require (quote init-lua-m\
ode)) (require (quote init-workgroups2)) (require (quote init-term-mode)) (require (quote init-web-mode)) ...)
  eval-buffer(#<buffer  *load*> nil "/home/.emacs.d/init.el" nil t)  ; Reading at buffer position 5779
  load-with-code-conversion("/home/.emacs.d/init.el" "/home/.emacs.d/init.el" t t)
  load("/home/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\211#\210^K\322\
=\203a^@\324\325\326\307^H\327Q!\"\323^A\322\211#\210^K\322=\203`^@^A^S\210^K\203\243^@\330^K!\331\232\203\243^@\332^K!\211\333P\334^A!\203}^@\211\202\210^@\334^B!\203\207^@^A\202\210^@\314\262^B^A\203\
\241^@\335^B^K\"\203\237^@\336\337^C^K#\210\340\341!\210^A^S\266^B\f?\205\260^@\314^]\323\342\322\211#)\262^A\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init \
inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, pl\
ease use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "W\
arning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment]
Thanks, the quick fix is install `xsel` (recommended) or `xclip`. Or just update from my latest setup

ba755c3 xsel or xclip may be missing (Chen Bin)
