### ISSUE TITLE
How to reopen the title bar？

### ISSUE THREAD

**Issue by YuanPre** [redguardtoo/emacs.d#582]
In your configuration works, the title bar is disabled.But I like to enable the title bar.
However, I don't know how to modify your configuration to enable the title bar.
Would you like to help me? thank you !

**Comment by redguardtoo** [comment]
http://kb.mit.edu/confluence/display/istcontrib/Disabling+the+Emacs+menubar%2C+toolbar%2C+or+scrollbar

**Comment by YuanPre** [comment]
Thanks ，it works.

**Comment by fenguoerbian** [comment]
configuration in ~/emacs.d/lisp/init-gui-frames.el
` ;; NO tool bar                           `
` (if (fboundp 'tool-bar-mode)             `
`   (tool-bar-mode -1))                    `
` ;; no scroll bar                         `
` (if (fboundp 'set-scroll-bar-mode)       `
`   (set-scroll-bar-mode nil))             `
` ;; no menu bar                           `
` (if (fboundp 'menu-bar-mode)             `
`   (menu-bar-mode -1))                    `

Comment these lines you will get tool bar/scroll bar/menu bar back.
