### ISSUE TITLE
"emacs filename -nw" report errors

### ISSUE THREAD

**Issue by guyanf** [redguardtoo/emacs.d#583]
Hi all:
When I used "emacs filename -nw",report errors:

Warning (initialization): An error occurred while loading `/home/data/.emacs.d/init\
.el':

error: Clipboard support not available

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

When I used "emacs filename -nw --debug-init",
Debugger entered--Lisp error: (error "Clipboard support not available")
  signal(error ("Clipboard support not available"))
  error("Clipboard support not available")
  (condition-case nil (cond ((eq system-type (quote darwin)) (let ((temp-buffer (ge$
  (condition-case nil (cond ((fboundp (quote ns-set-pasteboard)) (ns-set-pasteboard$
  simpleclip-set-contents("testsimpleclip!")
  test-simpleclip()
  (setq simpleclip-works (test-simpleclip))
  eval-buffer(#<buffer  *load*-848362> nil "/home/data/.emacs.d/lisp/init-utils.el"$
  load-with-code-conversion("/home/data/.emacs.d/lisp/init-utils.el" "/home/data/.e$
  require(init-utils)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (qu$
  eval-buffer(#<buffer  *load*> nil "/home/data/.emacs.d/init.el" nil t)  ; Reading$
  load-with-code-conversion("/home/data/.emacs.d/init.el" "/home/data/.emacs.d/init$
  load("/home/data/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\20$
  command-line()
  normal-top-level()

But, when I used "emacs filename"
All is OK!
What can I do? 
Thanks!

**Comment by redguardtoo** [comment]
`emacs -nw filename`, please `man emacs` in console. You need learn some Linux basics.
