### ISSUE TITLE
what is the 'best practice' of using in non-cmake c++ project 

### ISSUE THREAD

**Issue by Stumble** [redguardtoo/emacs.d#584]
For the projects that are not using cmake, what is the best way to have features like auto-complete, flymake and flycheck?

**Comment by redguardtoo** [comment]
read manual and setup flycheck/company-mode/auto-complete

**Comment by Stumble** [comment]
Will rewriting the project built system with cmake be a good idea? (and add them all extra files to .gitignore)

For example:
Project:
./waf
./wscript
/build/*              // original targets
===========================
/cmake-build    //  cmake targets
./cmakelist.txt

**Comment by redguardtoo** [comment]
It's fine if it's your hobby project.

Or you can read my http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html

**Comment by Stumble** [comment]
When trying to dump obj from /usr/include, but i get an error:
cd /usr/include && MAKEOBJDIRPREFIX=~/obj gtags 
gtags: cannot make GTAGS.

Then I do 'sudo gtags' and 'sudo mv G* /home/..../obj'.

**Comment by redguardtoo** [comment]
Yes.

**Comment by Stumble** [comment]
After I set it up, I found that the header files complete is not working as before.

Before:
when I type `#include <boost/..>`, there will be a drop-down menu of possible header files

Now
When I type `#include <boost/..>`. Nothing showed up. 

Is there any way that I could manually call a function that should show the drop-down menu?

**Comment by redguardtoo** [comment]
That's from company-c-headers. you need setup `company-c-headers-path-system`.
