### ISSUE TITLE
file-error on  not found

### ISSUE THREAD

**Issue by yangdawei** [redguardtoo/emacs.d#585]
When I start `emacs --debug-init`，the errors show as follows, please help me.
> Debugger entered--Lisp error: (file-error "https://stable.melpa.org/packages/pcache-0.4.0.el" "Not found")
  signal(file-error ("https://stable.melpa.org/packages/pcache-0.4.0.el" "Not found"))
  url-insert-file-contents("https://stable.melpa.org/packages/pcache-0.4.0.el")
  package-install-from-archive([cl-struct-package-desc pcache (0 4 0) "persistent caching for Emacs." ((eieio (1 3))) single "melpa-stable" nil nil nil])
  mapc(package-install-from-archive ([cl-struct-package-desc pcache (0 4 0) "persistent caching for Emacs." ((eieio (1 3))) single "melpa-stable" nil nil nil] [cl-struct-package-desc gh (0 10 0) "A GitHub library for Emacs" ((emacs (24 4)) (pcache (0 3 1)) (logito (0 1))) tar "melpa-stable" nil nil nil] [cl-struct-package-desc gist (1 3 1) "Emacs integration for gist.github.com" ((emacs (24 1)) (gh (0 9 2))) single "melpa-stable" nil ((:url . "https://github.com/defunkt/gist.el") (:keywords "tools")) nil]))
  package-download-transaction(([cl-struct-package-desc pcache (0 4 0) "persistent caching for Emacs." ((eieio (1 3))) single "melpa-stable" nil nil nil] [cl-struct-package-desc gh (0 10 0) "A GitHub library for Emacs" ((emacs (24 4)) (pcache (0 3 1)) (logito (0 1))) tar "melpa-stable" nil nil nil] [cl-struct-package-desc gist (1 3 1) "Emacs integration for gist.github.com" ((emacs (24 1)) (gh (0 9 2))) single "melpa-stable" nil ((:url . "https://github.com/defunkt/gist.el") (:keywords "tools")) nil]))
  package-install(gist)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(gist)
  (if *emacs24old* nil (require-package (quote gist)))
  eval-buffer(#<buffer  *load*-546238> nil "/home/yangdawei/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 5720
  load-with-code-conversion("/home/yangdawei/.emacs.d/lisp/init-elpa.el" "/home/yangdawei/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  (let ((file-name-handler-alist nil)) (require (quote init-autoload)) (require (quote init-modeline)) (require (quote cl-lib)) (require (quote init-compat)) (require (quote init-site-lisp)) (require (quote init-utils)) (require (quote idle-require)) (require (quote init-elpa)) (require (quote init-exec-path)) (require (quote init-spelling)) (require (quote init-gui-frames)) (require (quote init-ido)) (require (quote init-dired)) (require (quote init-uniquify)) (require (quote init-ibuffer)) (require (quote init-ivy)) (require (quote init-hippie-expand)) (require (quote init-windows)) (require (quote init-sessions)) (require (quote init-git)) (require (quote init-crontab)) (require (quote init-markdown)) (require (quote init-erlang)) (require (quote init-javascript)) (require (quote init-org)) (require (quote init-css)) (require (quote init-python-mode)) (require (quote init-haskell)) (require (quote init-ruby-mode)) (require (quote init-lisp)) (require (quote init-elisp)) (require (quote init-yasnippet)) (require (quote init-cc-mode)) (require (quote init-gud)) (require (quote init-linum-mode)) (require (quote init-moz)) (require (quote init-gtags)) (require (quote init-clipboard)) (require (quote init-evil)) (require (quote init-multiple-cursors)) (require (quote init-sh)) (require (quote init-ctags)) (require (quote init-bbdb)) (require (quote init-gnus)) (require (quote init-lua-mode)) (require (quote init-workgroups2)) (require (quote init-term-mode)) (require (quote init-web-mode)) ...)
  eval-buffer(#<buffer  *load*> nil "/home/yangdawei/.emacs.d/init.el" nil t)  ; Reading at buffer position 5779
  load-with-code-conversion("/home/yangdawei/.emacs.d/init.el" "/home/yangdawei/.emacs.d/init.el" t t)
  load("/home/yangdawei/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by redguardtoo** [comment]
`M-x list-packages`, then restart emacs

**Comment by yangdawei** [comment]
the error disappeared....

**Comment by redguardtoo** [comment]
https://github.com/redguardtoo/emacs.d#cannot-download-elpa-packages
