### ISSUE TITLE
窗口布局和文件保留

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#586]
可否有这样一个功能：Emacs记住关闭前的窗口布局和相应的编辑文件，待下次启动时依旧保持上次的状态。

看了一下，可能需要利用`layout-restore`吧(<https://www.emacswiki.org/emacs/LayoutRestore>)
或者已经有解决方案(<https://www.gnu.org/savannah-checkouts/gnu/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html>)

**Comment by yangdaweihit** [comment]
试验了下，当在init文件中加入`(desktop-save-mode 1)`后，上次编辑的文件确实可以自动恢复。但还知道怎么同时将窗口布局与对应的文件恢复出来。

**Comment by redguardtoo** [comment]
See
```lisp
       "ss" 'wg-create-workgroup ; save windows layout
       "ll" 'my-wg-switch-workgroup ; load windows layout
```
in init-evil.el.

Asking Emacs to restore windows layout during startup is a bad idea because:
- It increase start up time (each buffer's major-mode need run major-mode-hook which could be very heavy because the user's own setup
- If major-mode-hook has some bug, Emacs can't start any more

**Comment by yangdaweihit** [comment]
感谢指导。
