### ISSUE TITLE
error with git

### ISSUE THREAD

**Issue by nowilike** [redguardtoo/emacs.d#587]
<img width="633" alt="wx20170530-175936 2x" src="https://cloud.githubusercontent.com/assets/15705415/26578298/d17ab7c6-4561-11e7-8584-342e93ba5781.png">

Dear expert,

This appears for a second when git starts emacs. And then things look OK. What's the problem and how to fix it?

Thank you in advance.

**Comment by redguardtoo** [comment]
`emacs --version`?

Then you need run `emacs -nw --debug-init` in shell and give the full error report.

**Comment by nowilike** [comment]
GNU Emacs 24.5.1
<img width="905" alt="wx20170531-083632 2x" src="https://cloud.githubusercontent.com/assets/15705415/26610870/c348a78c-45dc-11e7-95ac-cc2b85ed70c9.png">

**Comment by redguardtoo** [comment]
It's possibly network issue. `package-initialize`. Make sure your connections to https://stable.melpa.org and https://melpa.org are OK.

You may consider melpa mirror sites, like https://mirror.tuna.tsinghua.edu.cn/help/elpa/

**Comment by nowilike** [comment]
I tried https://stable.melpa.org and https://melpa.org with Chrome and looks OK.
I added 
(setq package-archives '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
                         ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
to init.el, but the same error still happened. 

It happens only when git called emacs. If i run emacs -nw from terminal, there are some "idle-require"s at the bottom but no error.

**Comment by redguardtoo** [comment]
https not http

**Comment by redguardtoo** [comment]
what do you mean `git called emacs`?

**Comment by nowilike** [comment]
I am using MacOS 10.12.4.
For git, I mean that i set emacs as the default editor of git.
[core]
	editor = emacs -nw

"git called emacs" means when i run something like "git commit --amend", git will open a temp file with emacs to edit the commit info, as you can see in the screen shots with a "git ci --amend" on the top.

Besides, I changed http to https
(setq package-archives '(("gnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
("melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
to init.el, but the same error still happened.

**Comment by redguardtoo** [comment]
You do know that OS X has Emacs v22 built in which doesn't have `package-xxxx` APIs, right?
Check my README on OS X part, you need a way to remove old version of Emacs.

Restore your `package-archives` setup.

**Comment by nowilike** [comment]
Sorry I miss that FAQ. 
I installed Emacs 24.5 but use an alias to open it. So i get GNU Emacs 24.5.1 with emacs --version.
But git use the one in /usr/bin/ I guess.
I do the $PATH things and it works.
Thank you and sorry for your time.
