### ISSUE TITLE
open c++ file very slow

### ISSUE THREAD

**Issue by Carter-Pro** [redguardtoo/emacs.d#588]
Hi, I have a big c++ project, and when I open a file, the speed is very slow.
Messages buffer info: "my-c-mode-setup called (buffer-file-name)=..." when I open a file.

The project is built with camke, and I'm learning it using gtags.
So, I want to know how to improve the speed of opening source code files.
Thanks very much!

**Comment by redguardtoo** [comment]
check `init-cc-mode.el` comment, comment out line as it instructed.

You can also comment ggtags setup in that file. ggtags is kind of outdated, now we should use `emacs-counsel-gtags` instead

**Comment by Carter-Pro** [comment]
Thanks! that works!
And I follow your suggestion that using `counsel-gtags`, but only `counsel-gtags-dwim`works, the function `counsel-gtags-find-definition` and `counsel-gtags-find-reference` can not give out the tags index. Do you have any idea about that?

**Comment by redguardtoo** [comment]
There is `counsel-gtags-find-reference` and `counsel-gtags-find-symbol`

ggtags has some timer issue which hasn't be resolved for a long time. I will remove ggtags soon.

**Comment by Carter-Pro** [comment]
@redguardtoo Thanks you very much!
