### ISSUE TITLE
emacs codec problems

### ISSUE THREAD

**Issue by samsonwang** [redguardtoo/emacs.d#589]
I have a file coding in GBK, and the file contains Chinese characters.
How can I turn this file into UTF-8 without content is garbled?

I tried this way:
C-x C-f => open the file
M-x => revert-buffer-with-coding-system => UTF-8
C-x C-s => save file

The result:
Though the codec is changed, but the content is garbled.

**Comment by redguardtoo** [comment]
see https://www.emacswiki.org/emacs/ChangingEncodings

**Comment by samsonwang** [comment]
Problem solved!!
Thanks a lot!!
