### ISSUE TITLE
使用了flycheck函数？

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#591]
在最新配置下打开 c/c++ 文件报错 `Error in post-command-hook (flyc/show-fly-error-at-point-pretty-soon): (error "Autoloading failed to define function flyc/show-fly-error-at-point-pretty-soon")`

你的配置一直是以 flymake 作为第一选择的，因此没有flycheck相关函数，但看起来这个报错是因为调用了flycheck，这是怎么回事呢？我取消了所有个人配置依然存在这个问题。

**Comment by smallst** [comment]
sorry, i checkout back and find it is not a bug in config files. but looks like some package update cause this.

**Comment by redguardtoo** [comment]
I upgrade elpa packages, none requires flycheck. I may use flycheck next year when I drop Emacs 24.3 support.

**Comment by smallst** [comment]
yes, flyc is the flymake-cursor , i install it by myself. remove it solve the problem.
