### ISSUE TITLE
Emacs 25.1.2 64-bit (Windows 7 64-bit): Rendering and find-replace works very slow to break very long xml line

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#592]
During my work I need to copy the xml response from the developer tools of Chrome and paste it in the Emacs for further analysis. The xml response is in a single line and the line is very long (consider 200K+ or even 500K characters).

I am doing the following operations (with the above `.emacs.d`),
- `C-y` to paste the content (initially I pasted the content in xml code block in an org file and later tried pasting in a brand new xml file)
- Note that the paste operation, syntax highlighting and getting the cursor active itself takes more than 30 seconds
- `C-a` and `M-x replace-regex` with pattern to replace as `>\s-*<` 
- Enter string to replace as `> C-q C-n C-n DEL <` (strangely the `C-q` inserts 2 newlines keeping the cursor on the top line, I was expecting `C-q C-j` to insert single newline)
- Note that even after waiting for 5 minutes the pattern replace isn't complete (pressing `C-g` kills the replace command and you see hardly 100 lines replaced)
- Repeat the above process with the above .emacs.d and notice that the replace completes within 5 seconds.
- Note that all of this is reproducible on Windows machine (I tried on couple of machines). I tried the same on my Linux laptop and it completed the replace within 5 seconds.

**Comment by redguardtoo** [comment]
`M-x tidy-buffer`, you need install `tidy`, it could be a package of Cygwin/MSYS2. Check README.

Emacs 25+ does have some performance issue, though.

**Comment by amittendulkar** [comment]
`M-x tidy-buffer` throws an error as `The system cannot find the path specified`.

Tidy exists on my system. Opening a command prompt and running `tidy --help` displays the tidy help.

**Comment by redguardtoo** [comment]
`(executable-find "tidy")`?

**Comment by amittendulkar** [comment]
The above expression is able to find tidy in "C:/Programs/emacs-24.3/bin/tidy.exe". Also the above path is in the PATH variable.

**Comment by redguardtoo** [comment]
I suggest you using Cygwin to install tidy and other cli, then add cygwin bin path to environment variable `PATH`
