### ISSUE TITLE
Do you have a plan to migrate to use-package?

### ISSUE THREAD

**Issue by ReimuXMX** [redguardtoo/emacs.d#593]
I found that use-package can simplify a lot of configuration.

This is just a small suggestion, if any offense please forgive.

**Comment by redguardtoo** [comment]
Maybe next year, when I drop emacs 24.3 support.

**Comment by ReimuXMX** [comment]
Thank you……I'm deciding whether to switch to use-package. So I would like to hear the views of the master

But **I** unilaterally think that this is not necessary.
I found that switching to use-package requires a lot of refactoring ... unless your template is based on use-package, or you are starting from scratch.

Sorry for my poor English.
