### ISSUE TITLE
How to change directory of stardict?

### ISSUE THREAD

**Issue by zhixing2017** [redguardtoo/emacs.d#594]
In the `README`, the dictionary for sdcv is pionted to `~/.stardict/dic`

Does this directory can be changed? How?

Thanks in advance.

**Comment by redguardtoo** [comment]
That's not setup by me. I just hint you where the stardict to search the dictionaries. READ startdic manual to figure out what other paths it searches.

**Comment by zhixing2017** [comment]
ok, I know.
I will try to figure it out.
Thanks.

**Comment by zhixing2017** [comment]
I did not find the manual.

Now I use the `--data-dir` to change the directory. It is simple.

**Comment by redguardtoo** [comment]
`man sdcv`

**Comment by zhixing2017** [comment]
I will try it later. Thank you.
