### ISSUE TITLE
No matches for tag "foo" when try to navigating source code

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#595]
Hi,
  I am new to this .emacs.d, now i have a trial problem:
navigating a c project ~/proj/ with such a simplified dir structure:

    main.cpp
    test/test.cpp
    GPATH
    GRTAGS
    GTAGS

After opening test/test.cpp with C-x C-f, I try to jump to a definition with C-],
but it tells me that `No matches for tag "foo"`.

How to fix this? thank.

P.S. I've read your [Emacs as C++ IDE, easy way](http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html), but I don't think I really get it:(

**Comment by redguardtoo** [comment]
`M-x counsel-gtags-dwim` or `,gt`

Read `README.org` then check `init-evil.el`

**Comment by whatacold** [comment]
Got it, thanks.
