### ISSUE TITLE
Maybe the FAQ about color theme tuning is a bit out-of-date?

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#596]
Hi,
  When I try to use a color theme other than molokai, I find that `init-color-theme.el` is not the same as in [FAQ](https://github.com/redguardtoo/emacs.d#color-theme), so I guess it is a bit out-of-date.

  I think that tuning color theme is a common need, it will be nice if you would update it.

  Thanks.

**Comment by redguardtoo** [comment]
thanks, I updated README.

**Comment by whatacold** [comment]
cool, thanks.
