### ISSUE TITLE
Evil can't work well.

### ISSUE THREAD

**Issue by memedayangyang** [redguardtoo/emacs.d#597]
Hey, brother,

Thanks for your emacs's configuration.

Here is a issue that when I open emacs .
Description:
1.Start emacs and into Evil mode.
2.Input 'I',into insert mode,just like vim
3.Type 'jkjkjkjk....' continuously
4.Exit the insert mode into the normal mode .

Why?

Looking forward to your update.

Yours,
Yang

**Comment by memedayangyang** [comment]
More,
condition:
Like this:
cd ~; git clone https://github.com/redguardtoo/emacs.d.git .emacs.

**Comment by guyanf** [comment]
Edit init.el
Add ';;' before "(require 'init-evil)"

About on the line 105 of init.el .



guyanf@163.com
 
From: zy-mcat
Date: 2017-07-26 15:20
To: redguardtoo/emacs.d
CC: Subscribed
Subject: [redguardtoo/emacs.d] Evil can't work well. (#597)
Hey, brother,
Thanks for your emacs's configuration.
Here is a issue that when I open emacs .
Description:
1.Start emacs and into Evil mode.
2.Input 'I',into insert mode,just like vim
3.Type 'jkjkjkjk....' continuously
4.Exit the insert mode into the normal mode .
Why?
Looking forward to your update.
Yours,
Yang

**Comment by memedayangyang** [comment]
Then?
If add that, I can't use the evil-mode...
Is there any other way?

Also: when I edit on the minibuffer , ｔｈｅ issue also exists.

**Comment by redguardtoo** [comment]
Search `evil-escape` in `init-evil.el`.

So when you want to escape certain mode (not just evil-insert-state), you can press `kj` to escape.

**Comment by memedayangyang** [comment]
Is this intentionally set up? Where can I change that?
I want to use evil-mode ,and wouldn't press kj to escape.
What should I do ?

**Comment by redguardtoo** [comment]
comment out the evil-escape.

**Comment by memedayangyang** [comment]
Thanks for your help, I already commented out the evil-escape as below:

;;(setq-default evil-escape-key-sequence "kj")

Is that right?

If so, I will close this issue.

**Comment by redguardtoo** [comment]
then `fd` is the escape key. It's the default setup of evil-escape.

**Comment by memedayangyang** [comment]
Okey...
I will change some configuration for myself.
Thanks for your support.
