### ISSUE TITLE
Customize -- Where can I configure for myself

### ISSUE THREAD

**Issue by memedayangyang** [redguardtoo/emacs.d#598]
Dear brother,

How do I configure custom content?

For example, which files? and where?

**Comment by memedayangyang** [comment]
And, how do I switch chinese input-method?
Thanks

**Comment by redguardtoo** [comment]
check README, usually `~/.custom.el`

See Chinese input method section. `C-h k toggle-input-method`

**Comment by memedayangyang** [comment]
Thanks very much.
I will check it .
