### ISSUE TITLE
my-grep results in a plain grep buffer

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#600]
Hi,
I have `git pull` the repo, but it still fails. And I try to log `cmd` variable in `my-grep-cli`, then my-grep `foo`, which gives me something like this: 

    cmd=grep -rsnE -P --exclude-dir='.git' --exclude-dir='.bzr' --exclude-dir='.svn' --exclude-dir='bower_components' --exclude-dir='node_modules' --exclude-dir='.sass-cache' --exclude-dir='.cache' --exclude-dir='test' --exclude-dir='tests' --exclude-dir='.metadata' --exclude-dir='logs' --exclude='*.log' --exclude='*.properties' --exclude='*.session' --exclude='*.swp' --exclude='TAGS' --exclude='tags' --exclude='GTAGS' --exclude='GPATH' --exclude='.bookmarks.el' --exclude='*.svg' --exclude='history' --exclude='#*#' --exclude='*.min.js' --exclude='*bundle*.js' --exclude='*vendor*.js' --exclude='*.min.css' --exclude='*~' "" *

My emacs version is 25.2.1, and there is no `ag` program on my Linux box.

**Comment by whatacold** [comment]
It works with ag installed.

**Comment by redguardtoo** [comment]
Thanks, I fixed it anyway.
9fa24c5 fixed my-grep typo (Chen Bin)

**Comment by whatacold** [comment]
I confirmed that it works with `grep` now, thanks.
