### ISSUE TITLE
Emacs display *ERROR*: Font `xft' is not defined

### ISSUE THREAD

**Issue by imcatsee** [redguardtoo/emacs.d#602]
Dear brother,

Everything was good before. Please help analyze how to solve this problem? thanks

**Comment by redguardtoo** [comment]
Don't know, maybe you set some unknown font.

**Comment by No42-Baili** [comment]
Have your try set font in Options—Set Default Font and then Save Options？

**Comment by imcatsee** [comment]
@No42-Baili
Yeah, I set my font to 'Terminus'.
But what's the problem?

**Comment by No42-Baili** [comment]
@imcatsee I‘m not sure what problem is now.
but can you provide your system version your emacs version and try set more font with/without redguardtoo’s configuration and paste the result?
this will help us locate what problem you have.

**Comment by redguardtoo** [comment]
I don't specify any font in my setup. If you want to setup Chinese font, see https://github.com/tumashu 

For generic font setup, see https://www.emacswiki.org/emacs/SetFonts

**Comment by imcatsee** [comment]
Dear all,
Yesterday, I canceled the configuration and found it was working properly. 
After that, I join the configuration again, it can run normally.

I think that xft is the font of the backend engine. Probably this service is not open, resulting in emacs can not recognize.

@redguardtoo No42-Baili
System:
Linux version 3.13.0-79-generic (buildd@lcy01-24) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016
Emacs:
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

PS:Emacs is my own compiled out.

**Comment by redguardtoo** [comment]
good to know.
