### ISSUE TITLE
term-interrupt-subjob not bound to C-c in multi-term terminal

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#604]
Hi,

Here is how I produce this:
1. Type `,trm` to open a new terminal window
2. Move point to that window, and run some long-run programs, say `sleep 60`
3. Try to terminate the command with `C-c`, but it fails.(`M-x term-interrupt-subjob` works.)

I notice that other elements in `term-bind-key-alist` like `term-send-up`, `swiper` and
successfully bound to their keys.

Version: GUI Emacs 25.2.1 on a Linux box.

**Comment by redguardtoo** [comment]
b596a354 fixed multi-term key bindings (Chen Bin)

**Comment by whatacold** [comment]
Thanks, it got fixed now.
