### ISSUE TITLE
Change the theme of M-x for clear text

### ISSUE THREAD

**Issue by imcatsee** [redguardtoo/emacs.d#605]
Dear brother,

To tell the truth, M-x text color display is ugly. Always can't see the contents of the text.

Is there any way to modify this highlight? Just like percull configuration.

Looking forward to your update.

**Comment by redguardtoo** [comment]
You can override color theme in `~/.custom.el`

**Comment by imcatsee** [comment]
Just like your README ?

If so , I will try it .

**Comment by redguardtoo** [comment]
Yes
