### ISSUE TITLE
注释字体颜色

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#606]
注释字体的颜色设置得过于暗淡，请教如何设置注释字体的颜色。

![screenshot_2017-08-29_10-36-37](https://user-images.githubusercontent.com/10682606/29802155-3014762e-8ca6-11e7-83f5-8c6495f959ca.png)

**Comment by redguardtoo** [comment]
select another theme, https://emacsthemes.com/charts/all-time.html

**Comment by yangdaweihit** [comment]
几乎所有的暗色主题中，注释都是这种灰。看来我该擦擦屏幕了。

**Comment by yangdaweihit** [comment]
```
(load-theme 'zenburn t)
(set-face-foreground 'font-lock-comment-face "snow4")
(set-face-foreground 'font-lock-comment-delimiter-face "snow4")
```

在原来`zenburn`颜色主题上小改了一下注释及注释标记符颜色。

**Comment by samsonwang** [comment]
其实，一个主题就是把一组更改界面样式lisp命令写在一个文件里（在emacs中通常是*.el的一个文件），你可以把那个文件找到，在这个主题文件上做自己的颜色调整，修改后自己手动加载该主题文件。可以参考我的实现方法：  [配置加载文件](https://github.com/samsonwang/emacs/blob/1506599d1f6ea67026f8553b068adb4ec8f7c8b9/.emacs.d/lisp/init-customization.el#L15)  和   [主题文件](https://github.com/samsonwang/emacs/blob/1506599d1f6ea67026f8553b068adb4ec8f7c8b9/.emacs.d/site-lisp/autumn-light-theme.el#L42)

**Comment by yangdaweihit** [comment]
感谢@samsonwang的提示，限于知识太少，暂时无法解决这个问题。

不过刚发现了一个识别颜色的网站：<http://www.color-hex.com/>
