### ISSUE TITLE
split window 功能建议

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#607]
现在配置的拆分窗口的快捷键很方便，比如：`, x 3`将窗口竖向分开。建议在执行这类命令时，在提示区跟上一个选项，即左右窗口的比例，如：`2:1`。每次默认值为上一次的设定值。

也许已经有这样的功能了，我还不知道。另外，使用了这么长时间您的配置，才知道看`README.org`，这里内容丰富，再次感谢陈先生的贡献。

**Comment by redguardtoo** [comment]
interesting idea, I will consider your proposal

**Comment by redguardtoo** [comment]
d41d986 split window with certain ratio (Chen Bin)
