### ISSUE TITLE
你这个插件配置占用好高

### ISSUE THREAD

**Issue by dhqdqk** [redguardtoo/emacs.d#608]
emacs内存使用搞到1.4GB了；
怎么瘦身。

**Comment by redguardtoo** [comment]
Too limited information. My setup is actually pretty slim. It will optimize according to hardware.

**Comment by dhqdqk** [comment]
;;(require 'init-erlang)
  (require 'init-javascript)
  (require 'init-org)
  (require 'init-css)
  (require 'init-python-mode)
  ;;(require 'init-haskell)
  ;;(require 'init-ruby-mode)
  (require 'init-lisp)
  (require 'init-elisp)
  (require 'init-yasnippet)
  ;; Use bookmark instead
  ;;(require 'init-cc-mode)
  (require 'init-gud)
  (require 'init-linum-mode)
  ;; (require 'init-gist)
  ;;(require 'init-moz)
  (require 'init-gtags)
  ;; init-evil dependent on init-clipboard
  ;;(require 'init-clipboard)
  ;; use evil mode (vi key binding)
  (require 'init-evil)
  (require 'init-multiple-cursors)
  (require 'init-sh)
  (require 'init-ctags)
  (require 'init-bbdb)
  (require 'init-gnus)
  ;;(require 'init-lua-mode)
  (require 'init-workgroups2)
  (require 'init-term-mode)
  (require 'init-web-mode)
  (require 'init-slime)
  (require 'init-company)
  ;;(require 'init-chinese-pyim) ;; cannot be idle-required
  ;; need statistics of keyfreq asap
  (require 'init-keyfreq)
  (require 'init-httpd)

禁用了若干个插件，内存占用76MB。或许上次是偶然问题。
