### ISSUE TITLE
GBK-encoded file loaded garbled

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#609]
Hi,

The buffer does not display Chinese when loading a GBK-encoded text file, for example:
1. load and edit `/tmp/utf8.txt` with some Chinese in UTF-8, say "你好，世界！"
2. iconv it to GBK: `iconv -f utf8 -t gbk /tmp/utf8.txt -o /tmp/gbk.txt`
3. load `/tmp/gbk.txt`, then the buffer will display garbled text.
4. if i `M-x revert-buffer-with-coding-system`, it displays it correctly.

So, how to let emacs display it with the right coding system after loading automatically? thanks.

**Comment by redguardtoo** [comment]
Did you try `emacs -nw -Q your.txt` in shell? Emacs version?

**Comment by whatacold** [comment]
also garbled with the shell command, and `M-x version` says `GNU Emacs 25.2.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.12) of 2017-05-02`.

and here is some env, which i think maybe helpful:

    ~ env | grep UTF   
    LANG=en_US.UTF-8
    GDM_LANG=en_US.UTF-8
    LC_CTYPE=en_US.UTF-8

**Comment by redguardtoo** [comment]
see https://github.com/hick/emacs-chinese
I didn't setup any encoding things.

**Comment by whatacold** [comment]
Close this issue, it seems that there is no setting like [fileencodings](http://edyfox.codecarver.org/html/vim_fileencodings_detection.html#hd004) as in Vim.

**Comment by redguardtoo** [comment]
you can always use Emacs lisp to set coding automatically for certain files.

**Comment by whatacold** [comment]
Hi,

Finally I figured out how to set it right :), at least for UTF-8 and GBK encoded files,
just prefer UTF-8 and GBK than any other coding systems like this:

    (prefer-coding-system 'gbk)
    (prefer-coding-system 'utf-8)

A section of Emacs manual, [22.6 Recognizing Coding Systems](https://www.gnu.org/software/emacs/manual/html_node/emacs/Recognize-Coding.html), says how it works:

> However, you can alter the coding system priority list in detail with the command M-x prefer-coding-system. This command reads the name of a coding system from the minibuffer, and adds it to the front of the priority list, so that it is preferred to all others. If you use this command several times, each use adds one element to the front of the priority list.

Thank you for your help.
