### ISSUE TITLE
The content move towards right, when open ".el" file

### ISSUE THREAD

**Issue by sagaidealsee** [redguardtoo/emacs.d#610]
Thx for sharing your config. files to us.

When I use your config. to use EMACS 26, everything goes well except when I try to open some ".el" (your config file)

could you help to modify it?

thanks a lot

**Comment by redguardtoo** [comment]
What error message you got when opening `*.el`?

`M-x toggle-debug-on-error` at first. Then open the el file and send me all the messages in "*Message*" and "*Backstrace*" buffer.

**Comment by redguardtoo** [comment]
`display-line-numbers conflict` with  `git-gutter` `linum-mode` setup. resolved.
