### ISSUE TITLE
How to navigate in a c project? 

### ISSUE THREAD

**Issue by asvcer** [redguardtoo/emacs.d#612]
Would you like to help? 
Which one you have used? gtags? ctags? ggtags? I used to use ggtags, but when I switched to your configuration, I can't figure out which one you have used? Do you have a tutorial about this? 
Thank you very much!

**Comment by redguardtoo** [comment]
Use my mctags. It's based on ctags. It's already built into my setup.

**Comment by asvcer** [comment]
Thank you, I will try it.
