### ISSUE TITLE
显示目录

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#613]
曾经发现配置里有个快捷键：可以弹出窗口，列出方档的目录。忘记了这个快捷键了，请提示一下。:-)

**Comment by redguardtoo** [comment]
`M-x neotree-project-dir`?

**Comment by yangdaweihit** [comment]
哦，是我描述得不到位了。不是显示的文件目录，是文档结构，如org或tex里面的标题目录。

**Comment by redguardtoo** [comment]
`,ii` or `M-x counsel-imenu`

**Comment by yangdaweihit** [comment]
是这个功能，不过我用的不是这个命令。感觉这个命令比我忘记的那个更好用一些。那个命令的结果是在当前buffer上方出现的新buffer。

**Comment by redguardtoo** [comment]
After start `counsel-imenu` you can press `C-c C-o` to export the candidates to a new buffer.

This feature is generic. It apply to most `counsel-xxx` commands.

**Comment by yangdaweihit** [comment]
好吧。学会这个命令还是很有收获的。
