### ISSUE TITLE
How about using the symbol at point as default keyword when do mctags-grep?

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#614]
Hi,
  Currently if I want to do this, I need to first select the symbol then do `,qq`. I think maybe it would be better if we just pick the symbol at point as the default keyword, it will be less typing.

**Comment by redguardtoo** [comment]
press `,xx` to select current word.

**Comment by whatacold** [comment]
Good to know this command and its extension, but I prefer to pick the symbol as default, personally, so i close this issue now.
thanks.

**Comment by redguardtoo** [comment]
It's pretty easy to write your own grep based on `mctags-grep`:
```lisp
(defun mctags-grep-symbol ()
  (interactive)
  (mctags-grep (thing-at-point 'symbol)))
```

**Comment by whatacold** [comment]
Yeah, I've tried to write one, but your version is simpler, thanks.

**Comment by redguardtoo** [comment]
Please note now `mctags` is rename to `counsel-etag` now to comply with MELPA requirement.

**Comment by whatacold** [comment]
Thanks for reminding me. I've just merged your upstream and it works really great. :)
