### ISSUE TITLE
typewritter-mode remark

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#615]
这是一个很好玩的功能，不过和真实的声音相比，只是在打字完成后发出声音。在输出英文时看不出来差别。但在中文输入时，就会发现声音是在文字录入后才发出的声音。不过问题不大，毕竟并不总是希望听到这样的声音。感谢陈老师总给大家提供好玩好用的功能。

**Comment by redguardtoo** [comment]
I will blog about this toy after my new pull request is accepted.

**Comment by yangdaweihit** [comment]
your pull request to where?

**Comment by redguardtoo** [comment]
https://github.com/tungd/typewriter-mode.el/pull/3

**Comment by yangdaweihit** [comment]
祝顺利！
