### ISSUE TITLE
通过emacs server快速启动的疑问

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#617]
如果在开机时自动执行`emacs --client`，则每次启动emacs通过`emacsclient -c`似乎可以实现快速启动。但每次启动时似乎没有调用`.custom.el`脚本。我不确定是否如此，如果是，请教如何解决这个问题。

**Comment by redguardtoo** [comment]
没试过，我目前正常启动只要一秒，开发插件需要经常重启emacs，所以client对我没什么用。
