### ISSUE TITLE
package-initialize is called repeatedly

### ISSUE THREAD

**Issue by ReimuXMX** [redguardtoo/emacs.d#619]
Hello

I noticed that you called the `(package-initialize)` twice. Once in `init.e`l, once in `init-elpa.el`.

Why did you do that? I know emacs25 will automatically add `(package-initialize)` in init.el. So why do not you comment out the `(package-initialize)` in init.el? Doing so can reduce the initialization time.

Thank you.

**Comment by redguardtoo** [comment]
Thanks. I fixed it.
6271f40 clean code (Chen Bin)

**Comment by ReimuXMX** [comment]
Thanks 
but`;; (package-initialize)` in init.el is good.
