### ISSUE TITLE
always stuck as connection to melpa

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#621]
when trying to `package-list-packages`, emacs always stuck as connection to melpa.  The `emacs China` melpa mirror(<https://elpa.emacs-china.org/>) might be better for Chinese user. Could you please teach me how to use this mirror instead of https address in `.emacs.d/lisp/init-elpa.el`, while I wish no modifying the files in `.emacs.d` that I could pull your latest version of emacs.d project.

**Comment by whatacold** [comment]
Hi,

You could put your custom settings in `~/.custom.el`, as Bin Chen said in [FAQ](https://github.com/redguardtoo/emacs.d#faq),
tune `package-archives` there.

Hope this help.

**Comment by redguardtoo** [comment]
You can always modify `init-elpa.el` while pulling from my setup. Usually git will resolve any conflicts automatically. Even there is conflict (that's almost impossible). You can use any git tool (sourcetree for example) to resolve conflicts easily.

I have not setup elpa in `~/.custom.el`, but surely you can have a try. Copy from Emacs-China's sample code is enough.

**Comment by yangdaweihit** [comment]
thanks for your response.

**Comment by whatacold** [comment]
Settings in `~/.custom.el` don't work in this case, sorry about that.
