### ISSUE TITLE
evil jump items problem in switch case statement in C

### ISSUE THREAD

**Issue by Mastize** [redguardtoo/emacs.d#623]
I find a problem when I use `%` to traverse through the switch case statements

If there is a `default` at the end of switch statement, `%` works fine. However, when no `default` at end, keeping press `%` will jump to the end of file, and you cannot jump back

**Comment by redguardtoo** [comment]
Which programming language, C/Java/Javascript?

**Comment by Mastize** [comment]
For now, I only test in C

```
switch(c) {
  case 'a': ...
  case 'b': ...
  case 'c': ...
}
```

In this case, if you put the cursor on the last `case` and press `%`, it jumps to the end of file. I want it jumps back to `switch`

```
switch(c) {
  case 'a': ...
  case 'b': ...
  default: ...
}
```

But if there is a `default` in the end, when you put the cursor on `default` and press `%`, it jumps back to `switch`, as I expected.

**Comment by redguardtoo** [comment]
Thanks, it's evil-matchit issue which I fixed now.

70c15eeb upgrade evil-matchit (Chen Bin)

**Comment by Mastize** [comment]
Great! Thank you so much
