### ISSUE TITLE
如何关闭自动补全符号？

### ISSUE THREAD

**Issue by FlashYDirOX** [redguardtoo/emacs.d#625]
我在c/c++的配置中看过了，并没有找到--

**Comment by redguardtoo** [comment]
`(setq-local company-backends nil)` in `my-common-cc-mode-setup`

**Comment by FlashYDirOX** [comment]
谢谢

**Comment by FlashYDirOX** [comment]
不好意思，由于刚刚从vim转emacs，再请问一下，能不能稍微详细一点？

**Comment by JiaHong-Lee** [comment]
@FlashYDirOX 
应该是在`init-cc-mode.el`文件里的`my-common-cc-mode-setup` function加入这行`(setq-local company-backends nil)`。 

(可使用`C-x` `C-f` `~/.emacs.d/lisp/init-cc-mode-el` `RET`找到`init-cc-mode.el`)

请看: https://github.com/redguardtoo/emacs.d/blob/70c15eeb34b89ff7abf1d92a542ccfe55ca2cee6/lisp/init-cc-mode.el#L17

**Comment by FlashYDirOX** [comment]
@JiaHong-Lee 
非常感谢

**Comment by FlashYDirOX** [comment]
@JiaHong-Lee 
好像并没有明显效果，是不是有一些小问题？

**Comment by redguardtoo** [comment]
At least it's working on my setup,
```diff
diff --git a/lisp/init-cc-mode.el b/lisp/init-cc-mode.el
index 0b308eeb..c026f1e2 100644
--- a/lisp/init-cc-mode.el
+++ b/lisp/init-cc-mode.el
@@ -15,6 +15,7 @@
   (add-to-list 'c-offsets-alist '(key . val)))
 
 (defun my-common-cc-mode-setup ()
+  (setq-local company-backends nil)
   "setup shared by all languages (java/groovy/c++ ...)"
   (setq c-basic-offset 4)
   ;; give me NO newline automatically after electric expressions are entered
```

**Comment by FlashYDirOX** [comment]
Thanks.
