### ISSUE TITLE
evil fold commands problem in c mode

### ISSUE THREAD

**Issue by Mastize** [redguardtoo/emacs.d#628]
I found that if I open a C file immediately after launching emacs (i.e. before idle-require finish), the evil fold commands like `zm` don't work. It prompts:

```
Folding is not supported for any of these major/minor modes
```

And I need to wait for idle-require to finish, then run `c-mode` command once to activate evil fold commands, or open C files after idle-require to finished. 

However, I noticed that org mode has no problem. If I open an org file immediately after I launch emacs, `zm` and `zr` commands work fine.

So, how can I make configuration to allow me to use fold function immediately, in c mode as well? Or at least don't need to type `c-mode` command to let it works.

**Comment by redguardtoo** [comment]
`init-hs-minor-mode.el`?

**Comment by Mastize** [comment]
That's it. Thank you!
