### ISSUE TITLE
evil-escape-key-sequence breaks pyim to input k* ascii sequences

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#629]
Hi,

I've noticed before that ascii chars were not correctly input in order when I use pyim
to input a k-leading sequences, such as `key` `keep` etc, when pyim was on:
Type `key` and hit ENTER, it will get me `ky` and `e` is waiting for other
input chars to form a Chinese word, rather than `key`.

Today I've found out that it is caused by `(setq-default evil-escape-key-sequence "kj")`
in [init-evil.el](https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-evil.el#L257),
but I don't know how to properly handle this, any ideas?

Thanks.

**Comment by redguardtoo** [comment]
d2b1e453 fixed evil-escape and pyim conflict (Chen Bin)

**Comment by whatacold** [comment]
Got it, thanks.
