### ISSUE TITLE
对org以外的所有文档设置统一的fill-column

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#631]
fill-column可以使文档看起来很整齐，便于阅读。但在写org时如果自动fill-column会影响格式化显示。所以我想让除了org以外的所有文档设置统一的fill-column值。如何设置呢？我现在的方式是这样的：
```
 (setq-default fill-column 72)
```

或者只对后缀为`.tex`的文档设置列填充。

**Comment by whatacold** [comment]
看这个是不是你想要的：

    (unless (eq 'org-mode major-mode)
      (setq-default fill-column 72))

**Comment by yangdaweihit** [comment]
好用的，谢谢！

**Comment by yangdaweihit** [comment]
好用的，谢谢！
