### ISSUE TITLE
error: Package `async-' is unavailble in docker Centos7

### ISSUE THREAD

**Issue by AizenHoyok** [redguardtoo/emacs.d#632]
Thanks for your help
when I run Emacs at Centos7, it started with the error:error: Package `async-' is unavailble,I think,the os is download from docker,so the centos7 missing some package,Can you tell me which one package I lost?

**Comment by peng051410** [comment]
me too!

![image](https://user-images.githubusercontent.com/5512326/34507908-369caa8a-f000-11e7-95a6-24cc72ee21cc.png)

**Comment by redguardtoo** [comment]
I've seen this issue so many times. Check you network setup and search `aysnc-` in issues history

**Comment by peng051410** [comment]
yes，it is my network problem！
