### ISSUE TITLE
Loading `company-statistics-cache.el` for a long time.

### ISSUE THREAD

**Issue by asvcer** [redguardtoo/emacs.d#634]
Dear Bin,

Today, I encountered a problem about loading `company-statistics-cache.el` file. When I started emacs, it got stuck in loading `company-statistics-cache.el` file for a few minutes. I checked this file and found this file too large. So, any suggestions about an elegant fix?

Yours,
Shuo

**Comment by redguardtoo** [comment]
You can request the original developer to add a cleanup command. The infrequently accessed candidates should be removed from cache file during cleanup
