### ISSUE TITLE
"Change Owner of <xxxx> to: "  is asked every time when click up/down array in dired mode

### ISSUE THREAD

**Issue by nshigit** [redguardtoo/emacs.d#635]
OS: DeepIn 15.5 64Bit
Emacs: 24.3.1 (emacs-nox) 
redguardtoo: 2.5/2.4

"Change Owner of <xxxx> to: "  is asked every time when click up/down array in dired mode

**Comment by nshigit** [comment]
Ctrl+n/p can be used to mv between item in dired-mode instead of Upp/Down keys..

**Comment by nshigit** [comment]
![_deepin-terminal_20180106081314](https://user-images.githubusercontent.com/8710627/34633906-49a26bb2-f2ba-11e7-8502-e9715bfb0990.png)

**Comment by nshigit** [comment]
The issue doesn't exist in LinuxMint.

**Comment by redguardtoo** [comment]
setup from `dired+.el`
