### ISSUE TITLE
"Change Owner of <xxxx> to: " is asked every time when click up/down array in dired mode 

### ISSUE THREAD

**Issue by nshigit** [redguardtoo/emacs.d#636]
OS: DeepIn 15.5 64Bit
Emacs: 24.3.1 (emacs-nox)
redguardtoo: 2.5/2.4

"Change Owner of to: " is asked every time when click up/down array in dired mode 
![_20180107094304](https://user-images.githubusercontent.com/8710627/34645697-4c998334-f38f-11e7-88aa-dea971589d3a.png) 

Ctrl+n/p can be used to mv between item in dired-mode instead of Up/Down keys..
Up/Down keys works with GUI emacs but doesn't work with 'emacs-nox' and 'emacs -nw'

**Comment by nshigit** [comment]
I test emacs 24.3 + redguard emacs.d 2.5 in LinuxMint 17, the same issue exists.

**Comment by redguardtoo** [comment]
`dired+` setup the keybinding not my setup

**Comment by nshigit** [comment]
I found the issue existing in windows'putty and macos terminal. 
If I start emacs with emacs-nox -Q, dired works correctly.
.

**Comment by redguardtoo** [comment]
Check your terminal (putty ...) setup.

**Comment by nshigit** [comment]
![snapshot](https://user-images.githubusercontent.com/8710627/34664885-fdfedcfa-f498-11e7-9917-6a45d4102d89.png)

**Comment by redguardtoo** [comment]
I'm not using putty. but a quick search leads me to https://superuser.com/questions/94436/how-to-configure-putty-so-that-home-end-pgup-pgdn-work-properly-in-bash

**Comment by nshigit** [comment]
It works after change the terminal type to 'linux'.
