### ISSUE TITLE
init-evil.el mm key define repeat

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#637]
I found ; m m in evil mode is trigger mpc-which-song，The definition above is covered.
In man page can realize lookup-doc-in-man with m definition in init.hydra.el

![image](https://user-images.githubusercontent.com/5512326/34718148-32127b20-f4fb-11e7-8f0b-20029915f3fc.png)

**Comment by redguardtoo** [comment]
Thanks. Fixed.
