### ISSUE TITLE
What is session-initialize?

### ISSUE THREAD

**Issue by ReimuXMX** [redguardtoo/emacs.d#638]
Hello:

I see it takes a lot of time. I read the document but did not understand what it was doing.

What is the difference between it and `desktop-save-mode`?
What will I lose if I disable it?

Thank you.

**Comment by redguardtoo** [comment]
“When you start Emacs, package Session restores various variables (e.g., input histories) from your last session. It also provides a menu containing recently changed/visited files and restores the places (e.g., point) of such a file when you revisit it.” from emacswiki

**Comment by ReimuXMX** [comment]
thanks.
