### ISSUE TITLE
Theme file not found when merge up do data config

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#640]
Hello:
    After merger lastest config, When i run emacs, i got a error:
`File error: Creating directory, No such file or directory, /Users/tomyli/.emacs.d/elpa/color-theme-20070910.1007/theme`
 But in my dir , i can't found 20070910.1007, only found color-theme-20080305.34
What shoud i do?

**Comment by redguardtoo** [comment]
update from my latest code, delete color-theme, start emacs

**Comment by peng051410** [comment]
It works for me, Thanks!
