### ISSUE TITLE
File error: Opening directory, No such file or directory, /home/fjc/.emacs.d/elpa/color-theme-20070910.1007/themes

### ISSUE THREAD

**Issue by programes** [redguardtoo/emacs.d#641]

**Comment by redguardtoo** [comment]
you need manually create that directory `themes`. I think it's that package's problem.

**Comment by cookieli** [comment]
i'm a newer and i can't understand the owner's comment,how can i do then step by step for just let it change  to its default

**Comment by redguardtoo** [comment]
Doesn't matter, Just update to the latest code. It's already fixed.
