### ISSUE TITLE
undo-tree-mode is conflicting with auto-save-mode

### ISSUE THREAD

**Issue by BrianYi** [redguardtoo/emacs.d#642]
1. Every time when I move the node from the undo-tree-visualizer, I can only move the node one step a time, and then the view has gone, I cannot take more actions.
2. Sometimes I cannot move the node to the very long before history, a message shows below as "Unrecognized entry".

**Comment by BrianYi** [comment]
![tim 20180226170252](https://user-images.githubusercontent.com/4556182/36661683-f6397a62-1b16-11e8-8f57-4689ecf1f731.png)
![tim 20180226170302](https://user-images.githubusercontent.com/4556182/36661684-f67a15ae-1b16-11e8-9e97-839bce626552.png)
Here is the pictures about question two, hope it will be helpful.

**Comment by redguardtoo** [comment]
I don't understand. why you think it conflicts with `auto-save`?

**Comment by BrianYi** [comment]
![4](https://user-images.githubusercontent.com/4556182/36665831-94940860-1b23-11e8-9801-350042556c17.png)
不知道为什么，会无法跳到很久以前的节点，这个图x是当前节点，当我想跳到根节点时，下面显示Unrecognized entry in undo list-tree-canary
想请教一下在你的代码下时怎么进行undo和redo的呢？

**Comment by redguardtoo** [comment]
See https://github.com/syl20bnr/spacemacs/issues/9903
Not sure it's my setup's problem.

I use git to backup my minor changes then use `git rebase -i`.

**Comment by BrianYi** [comment]
I've been using your setup for over a month, and it is dramatically increasing my working efficiency, very thxs : )
But I don't know how to use undo/redo in the current environment, noticed that you are using undo-tree for this, and I realized it is so powerful more than original emacs(no package undo-tree.el), here is the cite paragraph from the page [UndoTree](https://www.emacswiki.org/emacs/UndoTree)
> Instead of treating undo/redo as a linear sequence of changes, undo-tree-mode treats undo history as a branching tree of changes, similar to the way Vim handles it. 

I wonnder how do you undo/redo what you've written after you realized that you are making mistakes, are you the same as me, use undo-tree? cause I find no command has the effect of undo/redo in your blog [how-to-be-extremely-efficient-in-emacs](http://blog.binchen.org/posts/how-to-be-extremely-efficient-in-emacs.html)
thanks : )

**Comment by redguardtoo** [comment]
usually I just use evil's default undo/redo for small changes (4 or 5 lines).

Bigger change is always checked in as a minor git commit. I create/merge branch and use `git rebase -i` quite often. 

My shell work flow is optimized and is more efficient than Emacs. So not all of my work is finished in Emacs. See https://gist.github.com/redguardtoo?page=2 for my git and bash setup.

**Comment by BrianYi** [comment]
Thanks a lot. 👍

**Comment by BlacAmDK** [comment]
> See [syl20bnr/spacemacs#9903](https://github.com/syl20bnr/spacemacs/issues/9903)
> Not sure it's my setup's problem.
> 
> I use git to backup my minor changes then use `git rebase -i`.

Looks like they fixed this bug already, would you please repack the latest version of 
`undo-tree`?

[https://elpa.gnu.org/packages/undo-tree.html](url)
