### ISSUE TITLE
error: Package `let-alist-1.0.4' is unavailable

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#643]
启动中遇此错误，但搞不懂怎么解决。

参考：
<https://github.com/flycheck/flycheck/issues/551>

```
➜  ~ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by redguardtoo** [comment]
search `uncomment below line if you need use GNU ELPA` in `init-elpa.el`.

GNU ELPA is not very reliable (https://www.google.com.au/search?safe=strict&ei=qI-UWvGFBYuT8wXMkYKoDA&q=gnu+elpa+is+down+site%3Areddit.com&oq=gnu+elpa+is+down+site%3Areddit.com&gs_l=psy-ab.3...7443.20361.0.20584.31.25.4.0.0.0.303.4013.0j10j8j1.19.0....0...1.1.64.psy-ab..8.7.935...0i8i30k1j33i160k1.0.EgBoxGvXDTg).

So I avoid using packages in GNU ELPA.

**Comment by yangdaweihit** [comment]
谢谢，问题解决了。然后是不是重新注释掉这些源，保持和你的版本一致？

**Comment by redguardtoo** [comment]
不需要. pull的时候解决一下冲突就可以了(通常git会自动解决).

**Comment by yangdaweihit** [comment]
感谢回答。
