### ISSUE TITLE
cscope搜项目中的函数

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#644]
想用cscope做一个搜项目函数的插件，路子可行吗？有没有已造好的轮子？请老师给点评一下。

**Comment by redguardtoo** [comment]
I don't develop C++ for many years. So I'm not sure. The key point is whether cscope is still actively maintained and widely used. If not, don't waste time on a Emacs plugin based on cscope.

If you are fine with GNU Global, you could consider https://github.com/syohex/emacs-counsel-gtags

Check Emacs China and reddit, there are many other (or better) solutions.

**Comment by yangdaweihit** [comment]
感谢回复。
