### ISSUE TITLE
另存文件时遇到的问题

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#645]
当前目录有`15m.R`、`25m.R`，在将文件要名存为`5m.R`，`C-x C-w C-w `一输入`5m.R`时就强迫选择`15m.R`和`25m.R`，却不能人为定义为`5m.R`。请问这种情况应如何操作？

**Comment by redguardtoo** [comment]
press `C-f` again. It's from `ido`, I guess.

**Comment by yangdaweihit** [comment]
Thank you very much!
