### ISSUE TITLE
ace jump hot keys?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#647]
Previously I saw that you have some key mappings for AceJump but now all those key mappings have been removed.  And I now have to manually call them via ,xm -> ace-jump-char-mode -> <some char> to jump to some specific char. 

I am considering added the key mappings back, but before that would to know if you have any reason for removing them? 

Thanks.

**Comment by redguardtoo** [comment]
I used avy instead, have you read this article?
http://emacsredux.com/blog/2015/07/19/ace-jump-mode-is-dead-long-live-avy/

**Comment by phye** [comment]
Thanks dude!
Glad that I asked and didnot make those mappings :)
avy jump with pinyin is **fabulous!**
