### ISSUE TITLE
`M-x slime` compiling error with sbcl

### ISSUE THREAD

**Issue by whatacold** [redguardtoo/emacs.d#648]
Hi,

  `M-x slime` raises compiling error with sbcl backend, below is the output in `*inferior-lisp*` buffer:

    (progn (load "/home/whatacold/.emacs.d/site-lisp/slime-2013-04-05/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/tmp/slime.4957"))
    
    This is SBCL 1.3.18-1.fc26, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    * 
    ; loading #P"/home/whatacold/.emacs.d/site-lisp/slime-2013-04-05/swank-loader.lisp"
    
    ; file: /home/whatacold/workspace/github/emacs-conf/emacs.d/site-lisp/slime-2013-04-05/swank-sbcl.lisp
    ; in: DEFIMPLEMENTATION DESCRIBE-SYMBOL-FOR-EMACS
    ;     (SB-INT:INFO :SETF :INVERSE SYMBOL)
    ; 
    ; caught STYLE-WARNING:
    ;   (:SETF :INVERSE) is not a defined info type.
    
    ; in: DEFIMPLEMENTATION DESCRIBE-DEFINITION
    ;     (SB-INT:INFO :SETF :INVERSE SYMBOL)
    ; 
    ; caught STYLE-WARNING:
    ;   (:SETF :INVERSE) is not a defined info type.
    
    ; 
    ; caught ERROR:
    ;   READ error during COMPILE-FILE:
    ;   
    ;     Symbol "CODE-TRACE-TABLE-OFFSET-SLOT" not found in the SB-VM package.
    ;   
    ;       Line: 1502, Column: 70, File-Position: 59987
    ;   
    ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/whatacold/workspace/github/emacs-conf/emacs.d/site-lisp/slime-2013-04-05/swank-sbcl.lisp" {10027CF583}>
    ; 
    ; compilation unit aborted
    ;   caught 1 fatal ERROR condition
    ;   caught 1 ERROR condition
    ;   caught 2 STYLE-WARNING conditions
    ;; 
    ;; Error while compiling /home/whatacold/.emacs.d/site-lisp/slime-2013-04-05/swank-sbcl.lisp:
    ;;   COMPILE-FILE returned NIL.
    ;; Aborting.

  And If I install slime v2.20 from melpa-stable instead, it works fine.

**Comment by redguardtoo** [comment]
10acfb30 install latest slime (Chen Bin)

**Comment by whatacold** [comment]
thanks.
