### ISSUE TITLE
org文件是加载哪个文件夹的？

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#649]
您好，我想请教一下org文件是加载哪个文件夹下的，我现在想使用org-agenda视图，但是看到的不是我的org文件的视图！

**Comment by redguardtoo** [comment]
org-mode is part of Emacs. I place my org setup in `init-org.el`

**Comment by peng051410** [comment]
我看您的配置是agenda会加载当前文件和向上5层的org文件是吗？
`(setq org-refile-targets (quote ((nil :maxlevel . 5) (org-agenda-files :maxlevel . 5))))`

**Comment by redguardtoo** [comment]
This must be Steve Purcell's setup. To be honest, I don't know.

**Comment by peng051410** [comment]
But from your init-org.el configuration I did not see where the configuration read org files. Can you identify the location?

**Comment by redguardtoo** [comment]
They are not publicized in my setup because they are personal files.

Check org manual for how to setup. My setup is exactly same as the manual

**Comment by peng051410** [comment]
Thanks！
