### ISSUE TITLE
Org file agenda appears with unconfigured content.

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#650]
Hello:
I config 'org-agenda-files' in my .custom.el file，But when i go to the agenda view, i found some thing that not me configured.
![image](https://user-images.githubusercontent.com/5512326/37377294-06153332-2764-11e8-8686-1f319393e392.png)
Can you tell me what is this?

**Comment by redguardtoo** [comment]
Looks like some public holidays. https://emacs.stackexchange.com/questions/10965/easiest-way-to-customize-holidays-that-appear-in-org-agenda

**Comment by peng051410** [comment]
Got it!Thanks a lot！
