### ISSUE TITLE
vim的行内字母搜索“f”，重复搜索";"

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#654]
您好，vim的行内字母搜索“f”，重复搜索";"，以前用evil-space.el能实现这效果，现在有什么替代方法呢？

**Comment by redguardtoo** [comment]
I don't know. though looks useless to me since I've got `evil-avy`

**Comment by xxyyer** [comment]
谢谢您的回答，请教下在"+"前后加上空格的最佳方法是什么呢：

var foo = "method("+argument1+","+argument2+")";   
改成
var foo = "method(" + argument1 + "," + argument2 + ")";  

（以前我依赖 f ; 操作，现在我想用 / n 代替，想想还能宏。期待更好的实现方法。）

**Comment by redguardtoo** [comment]
I don't know  how to do it in pure Emacs Lisp way.

Usually I don't care coding style when typing. But before checking in code, I run `M-x js-beautify` which just called the shell cli tool `js-beautify` (https://github.com/beautify-web/js-beautify)
