### ISSUE TITLE
error: Package 'undo-tree-' is unavailablee

### ISSUE THREAD

**Issue by robotyx** [redguardtoo/emacs.d#657]
This problem occurs during installation。

signal(error ("Package ‘undo-tree-’ is unavailable"))
  error("Package `%s-%s' is unavailable" undo-tree "")
  package-compute-transaction(nil ((undo-tree)))
  package-install(undo-tree)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(undo-tree nil t)

**Comment by yangdaweihit** [comment]
我也遇到了同样的问题。

**Comment by redguardtoo** [comment]
`undo-tree` is removed from melpa.

295c189b undo-tree is missing on melpa (Chen Bin)

**Comment by yangdaweihit** [comment]
怎么处理一下呢？我重新克隆的项目，现在报这个错误。

**Comment by yangdaweihit** [comment]
更新了一下项目，但问题还没有得到解决。请陈老师再指导一下。
