### ISSUE TITLE
Any idea on pasting http link in org-insert-link in macOS?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#658]
Say that you find an article meaningful and want to refer to it from your org notes. You copied the link from chrome, `c-c c-l` to execute `org-insert-link`, however, you cannot simply paste the link in emacs prompt window. 

`cmd + v `simply does not work in emacsforosx, pasting via mouse buttons doesn't work either. Currently I can only paste that link in orgmode via `,zz`(`paste-from-x-clipboard`), then modify the description field interactively via `c-c c-l`. 

Wonder how do you paste link from chrome into emacs prompt line?

**Comment by redguardtoo** [comment]
check `(my-gclip)`, I prefer using yasnippet plus that api. Simply because I hate remember key bindings.
There are already a few example in `~/.emacs.d/snippets/`

**Comment by phye** [comment]
Thanks, I've mimic a new snippet from your `items-from-clipboard.yasnippet` and attach key l to the snippet. It works perfectly now!

However, I prefer to call your solution as a *workaroud*, as I am still unable to paste things from global clipboard to emacs prompt bar, not sure if you have any idea on this?

**Comment by redguardtoo** [comment]
Check `my-minibuffer-setup-hook` in `init-misc.el`

**Comment by phye** [comment]
Bravo!
Thanks buddy!
