### ISSUE TITLE
javascript程序，如何使用company补全库函数

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#659]
您好，我在写javascript程序，使用company补全，不知道怎么可以补全库函数呢？比如console.log这个函数没提示补全信息。谢谢！

**Comment by redguardtoo** [comment]
I don't need any library API info. I just  use `company-etags`.

At least in front end development. There is no reason we need look up API.

For example, in my setup, I have got tons of yasnippets snippets to input console.log

We can input `lo` or `lwf` then press `M-j` to complete with yansippets.

**Comment by xxyyer** [comment]
Thank you very much~!
