### ISSUE TITLE
ivy-wgrep-change-to-wgrep-mode 处理中文的问题

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#661]
您好，我发现了一个与中文有关的问题：

* 操作前的文件内容：
test.html:
```
<p>中文</p>
<p>english</p>
```

* 操作：
1、执行ounsel-grep，搜索p；
2、进入ivy-occur；
3、执行ivy-wgrep-change-to-wgrep-mode，把p修改为abc；
4、执行wgrep-finish-edit；

* 操作后的文件内容：
test.html:
```
<p>中文</p>
<abc>english</abc>
```

* 而正常的结果应该是：
test.html:
```
<abc>中文</abc>
<abc>english</abc>
```

请问有办法解决么？

**Comment by redguardtoo** [comment]
Can't reproduce the issue.

**Comment by xxyyer** [comment]
谢谢，
经过早上一番折腾，已经找到原因了。
您的配置的确重现不了，因为我在您的配置基础上在init.el文件中增加了
`(set-language-environment "Chinese-GB")`
把这句屏蔽然后重启emacs，就好了！！！

**Comment by redguardtoo** [comment]
现在基本都转到utf8了.
