### ISSUE TITLE
There was a slight problem during the installation but it was normal when used

### ISSUE THREAD

**Issue by robotyx** [redguardtoo/emacs.d#666]
Error (bytecomp): missing value for ‘smex-history’ at end of setq
Error (bytecomp): missing value for ‘smex-data’ at end of setq

Error (bytecomp): Cannot open load file: No such file or directory, calist
Error (bytecomp): Install w3m command in ‘exec-path’ or set ‘w3m-command’ variable correctly [4 times]
Warning (bytecomp): reference to free variable ‘w3m-message-silent’
Error (bytecomp): Install w3m command in ‘exec-path’ or set ‘w3m-command’ variable correctly [6 times]
Warning (bytecomp): function ‘gensym’ from cl package called at runtime [10 times]
Error (bytecomp): Install w3m command in ‘exec-path’ or set ‘w3m-command’ variable correctly [3 times]
Error (bytecomp): Cannot open load file: No such file or directory, un-define
Error (bytecomp): Install w3m command in ‘exec-path’ or set ‘w3m-command’ variable correctly

Warning (bytecomp): reference to free variable ‘defined-colors-as-structs’
Warning (bytecomp): assignment to free variable ‘defined-colors-as-structs’
Warning (bytecomp): reference to free variable ‘defined-colors-as-structs’
Warning (bytecomp): assignment to free variable ‘defined-colors-as-structs’
Warning (bytecomp): reference to free variable ‘defined-colors-as-structs’
Warning (bytecomp): assignment to free variable ‘defined-colors-as-st

**Comment by redguardtoo** [comment]
That's fine. Ignore them.

Many 3rd party packages are using some global variables in other packages directly without notifying compiler.

Emacs Lisp is pretty tolerant to this type of errors.
