### ISSUE TITLE
windows emacs25.1 编辑init.el文件的时候emacs会卡死

### ISSUE THREAD

**Issue by zhouyanrui** [redguardtoo/emacs.d#669]
编辑init.el的时候 emacs会卡死，.emacs.d文件夹中的.el文件都 一样的表现
如果改了文件名后缀 或者在其他目录新建的.el就不会有这种情况

**Comment by redguardtoo** [comment]
I can't reproduce the issue. run `M-x profiler-start` and `M-x profiler-report` to find the bottle neck

**Comment by redguardtoo** [comment]
`ido-find-file` is fine. It will search directorie. which might take a few seconds. Just measure adding line

**Comment by zhouyanrui** [comment]
只添加一行时候的记录是这样的
- ...                                                               5 100%
   Automatic GC                                                     5 100%

**Comment by redguardtoo** [comment]
Can you keep adding 50 lines?

**Comment by zhouyanrui** [comment]
添加50行 和添加一行的输出是一样的

**Comment by redguardtoo** [comment]
I did some test. the profiler output is different from yours.

Just double check, you are using exacly same setup as mine, right?
