### ISSUE TITLE
IRC in emacs

### ISSUE THREAD

**Issue by azzamsa** [redguardtoo/emacs.d#674]
Hi Redguardtoo.

Do you use emacs for IRC, or other client ?.
I don't find any irc config here.

Thanks lot.

**Comment by redguardtoo** [comment]
I don't use irc.

You can use `erc`.

**Comment by azzamsa** [comment]
> You can use erc.

Yes. I use `erc` already.

> I don't use irc.

Sorry for asking. So how you keep in touch with foo-hackers and bar-hackers ?
I am wondering :). I *think* some of them hang out in IRC.

**Comment by redguardtoo** [comment]
I spend most of my time on Github.
I do visit Emacs stackexhange and Planet Emacs frequently.

**Comment by azzamsa** [comment]
Thank you so much  Redguardtoo.

Thanks for your contribution to community :)
