### ISSUE TITLE
void-variable ivy-height-alist on Windows 10 (emacs 24.5 32-bit)

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#677]
Downloaded and unzipped latest master.zip, altered init-elpa.el to change melpa paths from https to http. Got following error after installing/compiling all packages,
`
Debugger entered--Lisp error: (void-variable ivy-height-alist)
  byte-code("\301\235\203...207" [ivy-height-alist (counsel-el . 7) nil] 2)
  require(counsel)
  eval-buffer(#<buffer  *load*-563291> nil "d:/Data/.emacs.d/lisp/init-ivy.el" nil t)  ; Reading at buffer position 19
  load-with-code-conversion("d:/Data/.emacs.d/lisp/init-ivy.el" "d:/Data/.emacs.d/lisp/init-ivy.el" nil nil)
  load("d:/Data/.emacs.d/lisp/init-ivy")
  (let ((file-name-handler-alist nil)) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-autoload)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-modeline)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-compat)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-utils)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-elpa)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-exec-path)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-spelling)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-gui-frames)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-ido)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-uniquify)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-ibuffer)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-git)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-ivy)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-hippie-expand)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-windows)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-markdown)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-erlang)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-javascript)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-org)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-css)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-python-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-haskell)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-ruby-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-lisp)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-elisp)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-yasnippet)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-cc-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-gud)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-linum-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-moz)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-gtags)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-clipboard)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-multiple-cursors)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-sh)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-ctags)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-bbdb)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-gnus)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-lua-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-workgroups2)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-term-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-web-mode)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-company)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-chinese)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-keyfreq)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-httpd)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-misc)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-emacs-w3m)))) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-hydra)))) ...)
  eval-buffer(#<buffer  *load*> nil "d:/Data/.emacs.d/init.el" nil t)  ; Reading at buffer position 7058
  load-with-code-conversion("d:/Data/.emacs.d/init.el" "d:/Data/.emacs.d/init.el" t t)
  load("d:/Data/.emacs.d/init" t t)
  #[0 "\205\262...207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
`

**Comment by redguardtoo** [comment]
counsel/ivy problem. Raise a issue there.

**Comment by abo-abo** [comment]
Seems like a MELPA hiccup to me. Similar issues happened before, when both `counsel.el` and `ivy.el` are upgraded in the repo, but the new `counsel` is available on MELPA before the new `ivy`. Or something like that.

Fixable with a reinstall.

**Comment by redguardtoo** [comment]
@abo-abo Thanks for the heads up.

**Comment by peng051410** [comment]
Reinstall works!

**Comment by amittendulkar** [comment]
Thanks, worked for me after re-getting the master.zip. Closing the issue.
