### ISSUE TITLE
how to kill the extra output line  while using M-x shell 

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#680]
i use your emacs.d config and just olny modify the elpa source. now when i use `M-x shell` in emacs , it will output an extra line , while it does not output in xfce4-terminal .

i want to disable output the extra line

in emacs use M-x shell :
```
kk@H3:~% cat 1dfasdfasdfasdfasdfasdfasdf
<sdfasdfasdfasdfasdf   <====== this line i want to kill 
cat: 1dfasdfasdfasdfasdfasdfasdf: No such file or directory
```

in xfce4-terminal:
```
kk@H3:~%  cat 1dfasdfasdfasdfasdfasdfasdf
cat: 1dfasdfasdfasdfasdfasdfasdf: No such file or directory    <=========no extra line
```

**Comment by redguardtoo** [comment]
maybe it's your terminal setup.

I tested in xterm and rxvt, same as Emacs shell

**Comment by vipzrx** [comment]
i use zsh .

**Comment by peng051410** [comment]
check you zsh theme!
