### ISSUE TITLE
error: Package ‘hl-sexp-’ is unavailable

### ISSUE THREAD

**Issue by A1saka** [redguardtoo/emacs.d#686]
启动时报错，导致很多设置无法保存

<img width="577" alt="screen shot 2018-05-11 at 11 17 18 am" src="https://user-images.githubusercontent.com/15502050/39904888-fd812cd6-550c-11e8-845d-74f1861285ec.png">

<img width="444" alt="screen shot 2018-05-11 at 11 19 32 am" src="https://user-images.githubusercontent.com/15502050/39904916-34b77e08-550d-11e8-8e97-a6711b7f2ac2.png">

**Comment by redguardtoo** [comment]
1aae4d32 hl-sexp is removed from melpa. anyway, not used (Chen Bin)
