### ISSUE TITLE
Org Refile abnormality of behavior

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#688]
I use Org for management. In the previous refile, I can correctly navigate to the existing org file in my system. However, after updating the configuration in the past few days, I can only navigate to the file name, as shown in the following figure:
![image](https://user-images.githubusercontent.com/5512326/39984988-813119f4-578f-11e8-9671-2f4e9f601d43.png)

The Personal in the diagram is in my mylife.org file, but I can't refile. Can you tell me how to deal with this?

**Comment by redguardtoo** [comment]
What's the command to org-navigate?

**Comment by peng051410** [comment]
c-c c-w

**Comment by redguardtoo** [comment]
Can you give me the command?

**Comment by peng051410** [comment]
I don't understand。

**Comment by peng051410** [comment]
I recorded a video and I have sent it to you on twitter.

**Comment by redguardtoo** [comment]
Can't find video. What's output of `C-h k C-c -C-w`?

**Comment by peng051410** [comment]
C-c C-w runs the command org-refile (found in org-mode-map), which is
an interactive compiled Lisp function in
‘~/.ihsec/personal/elpa/org-20180416/org.el’.

It is bound to C-c C-w, <menu-bar> <Org> <Edit Structure> <Refile
Subtree>.

**Comment by peng051410** [comment]
I sent a video again

**Comment by peng051410** [comment]
When I execute refile, I get the following error:
`error in evil-define-key: Symbol’s function definition is void: evil-org-define-eol-command [12 times]`

**Comment by peng051410** [comment]
Does this mistake have something to do with my problem?

**Comment by redguardtoo** [comment]
Yes

**Comment by peng051410** [comment]
I stopped evil-org, It still couldn't work.

**Comment by redguardtoo** [comment]
18ddd06d org-refile setup (Chen Bin)

**Comment by peng051410** [comment]
It works, Thanks!
