### ISSUE TITLE
error: Package `quack-' is unavailable

### ISSUE THREAD

**Issue by neidwdp** [redguardtoo/emacs.d#689]
Hi Chenbin,
你好， 我根据你的readme, 直接下载 emacs.d 没有做任何改动， 直接启动 emacs ， initial过程会报如下错误，加载package失败，导致启动失败。 我的系统是Debian， emacs 是25.3.
如果您方便，能查看一下吗？ 非常感谢

# **start emacs with --debug-init  report following message:**

Debugger entered--Lisp error: (error "Package `quack-' is unavailable")
  signal(error ("Package `quack-' is unavailable"))
  error("Package `%s-%s' is unavailable" quack "")
  package-compute-transaction(nil ((quack)))
  package-install(quack)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package$
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (p$
  require-package(quack nil t)
  (progn (package-refresh-contents) (require-package package min-version t))
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package$
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (p$
  require-package(quack)
  eval-buffer(#<buffer  *load*-324569> nil "/home/dongpingw/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 9248
  load-with-code-conversion("/home/dongpingw/.emacs.d/lisp/init-elpa.el" "/home/dongpingw/.emacs.d/lisp/init-elpa.el" nil nil)
  load("/home/dongpingw/.emacs.d/lisp/init-elpa")
  (let ((file-name-handler-alist nil)) (load (file-truename (format "~/.emacs.d/lisp/%s" (quote init-autoload)))) (load (file-truename (for$
  eval-buffer(#<buffer  *load*> nil "/home/dongpingw/.emacs.d/init.el" nil t)  ; Reading at buffer position 7055
  load-with-code-conversion("/home/dongpingw/.emacs.d/init.el" "/home/dongpingw/.emacs.d/init.el" t t)
  load("/home/dongpingw/.emacs.d/init" t t)

--------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------
# 
**Following is normal start report error:**

Warning (initialization): An error occurred while loading `/home/dongpingw/.emacs.d/init.el':

error: Package `quack-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

![image](https://user-images.githubusercontent.com/1858958/40167476-badffaa6-59f3-11e8-90ac-b1836dcb50fd.png)

**Comment by redguardtoo** [comment]
59946c23 quack is removed from melpa (Chen Bin)

**Comment by neidwdp** [comment]
commonts out the 'quack' and (require-package 'quack) in the .emac.d/lisp/init-elpa.el.  Emacs can normally start.  it for scheme language. if someone don't use the scheme language,  can following this modification.

**Comment by neidwdp** [comment]
quack has been removed from melpa, emacs can normally start in linux.
