### ISSUE TITLE
 how to enable to export to markdown

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#690]
** how to enable to export to markdown

i am always using org-mode, while sometimes i shoud to export org file into markdown file. 
in your emacs.d when i use "C-c C-e"  there is no  Markdown export .

https://orgmode.org/manual/Markdown-export.html

i should add the config 
（require 'ox-md）

i want to know where to put this config line

i add the line in /home/kk/.emacs.d/init.el

```
➜  lisp cat /home/kk/.emacs.d/init.el | grep -C 5 init-ox-md
  (require-init 'init-company)
  (require-init 'init-chinese) ;; cannot be idle-required
  ;; need statistics of keyfreq asap
  (require-init 'init-keyfreq)
  (require-init 'init-httpd)
  (require-init 'init-ox-md)
  ;; projectile costs 7% startup time

  ;; misc has some crucial tools I need immediately
  (require-init 'init-misc)


```
i creat the file /home/kk/.emacs.d/lisp/init-ox-md.el 
```
➜  lisp cat '/home/kk/.emacs.d/lisp/init-ox-md.el'
(require 'ox-md)


```

after doing the above , the export options still have no ox-md

**Comment by redguardtoo** [comment]
`(require 'ox-md)` in `~/.custom.el`

**Comment by vipzrx** [comment]
thx
