### ISSUE TITLE
bookmark is invalid when emacs turn off

### ISSUE THREAD

**Issue by neidwdp** [redguardtoo/emacs.d#694]
c-x r m set a book mark, it can work if emacs always turn on. 
if re-start emacs, all bookmark are gone.
the file ~/.emacs.d/bookmarks is always empty!
could you double check it?

**Comment by redguardtoo** [comment]
`M-x bookmark-save`

**Comment by neidwdp** [comment]
Thanks!   However, it seems that the bookmark will auto save for my previous emacs's config file.

**Comment by redguardtoo** [comment]
Don't know, I checked history of my setup. I have not touched bookmark save thing from the beginning. Maybe built in `boomark.el` has auto save?
