### ISSUE TITLE
Unable to prompt for sections/subsections during org-refile?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#695]
Previous with org-refile(`c-c c-w`), when entering TAB in the prompt window, certain sections will appear in the prompt window, so that you can *correctly* choose the right section/section to place the refiled content. 

However, after merging your latest config, I find the mechanism described above does not work any more.

**Comment by redguardtoo** [comment]
I use counsel/ivy instead of ido now.
`org-refile` still works, just take a little bit time to loading all the items for the first time.

**Comment by phye** [comment]
I'm sorry but I forgot to merge your latest commits. 
After merging your latest related commits, `org-refile` is working properly now. 
Thanks
