### ISSUE TITLE
how can i determine a bug in certain file?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#696]
recently i find a really strange thing that when i press C-s or some other keys (like press kkk...j) in a certain vue file the whole page will keep shift right.. look like this:
![screenshot_2018-05-30_16-09-39](https://user-images.githubusercontent.com/11417632/40707785-46a92b5e-6424-11e8-8ce5-cf1b9cbace4a.png)

i doesn't find this behavior in any other file, even i move this file to another place .I was stunned
this is my vue file(for upload i change the file type):
[GalleryDetails.txt](https://github.com/redguardtoo/emacs.d/files/2053045/GalleryDetails.txt)

**Comment by redguardtoo** [comment]
`C-h major-mode` at first.

In you case, it's `web-mode`. Try to reproduce issue and report it to `web-mode` author.

**Comment by smallst** [comment]
thanks. 
i roll back to an old commit and find there may be some touble with my system config.
