### ISSUE TITLE
Recent opened file in `C-x f`?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#698]
Previously in `ido-open-file`, recent opened file list will be searched so that you can open recently opened files much easier, even if the file has been removed from Emacs buffers.

With your latest config, i.e., replacing `ido-open-file` with `counsel-find-file`, there're no such behaviors and I do find it annoying. I have to manually invoke `recentf-open-files` by myself which is not that elegant really. 

Is it possible for you to bring the behavior mentioned above back? 

Thanks.

**Comment by redguardtoo** [comment]
`M-x my-counsel-recentf` is always there.

**Comment by phye** [comment]
Thanks for the explanation. I never tried `my-counsel-recentf` before, as `ido-find-file` helped me to achieve that already :) After my first trial, I find that I can close the issue now :)

It just works!

Thanks!

**Comment by redguardtoo** [comment]
`my-counsel-recent` is using API `ivy-read`, so it supports Chinese (每个字的汉语拼音首字母搜索)

**Comment by phye** [comment]
Got your hint.
I've been using your `evil-avy-goto-char-2` which supports quick navigation of Chinese words for quite a while and that's really handy. Thanks!
