### ISSUE TITLE
Weird behavior in editing long sql file

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#699]
Hi,
I was recently editing a relative long SQL file that spans longer than height of my screen and controlled by git, i.e., the SQL file has been previously added into git repo. 

Then I tried to edit the SQL file, which makes it dirty in git, then everytime I tried to navigate down/up half screen, or exit from insert mode, I can notice that Emacs is trying to indent the SQL file with one or more columns. Eventually the file becomes difficult to read. 

Attached the dummy SQL file. 

[sample.zip](https://github.com/redguardtoo/emacs.d/files/2071472/sample.zip)

Here's the steps to reproduce:

1) `mkdir dummy`
2) `git init`
3) `git add sample.sql`
4) `git commit -m "dummy commit"`
5) `emacs -nw sample.sql` 
6) Navigate around via `c-d` or `c-f`, or try to insert something.
7) Issue occurs

**Comment by redguardtoo** [comment]
can't reproduce, my major-mode is `sql-mode`. It's possibly your customization's problem.

If you grep `sql` in `~/.emacs.d/lisp/`, you will find I have not setup on sql at all.

Grep `prog-mode-hook` (`sql-mode` inherits from `prog-mode`), there is nothing special.

**Comment by phye** [comment]
I was actually reproducing the above scenario using your configurations...
Let me try to reproduce in another device at home.

**Comment by redguardtoo** [comment]
Run `emacs -Q` and repproduce issue.
Then try to bisect my `init-*.el`.

**Comment by phye** [comment]
After further investigation, I found that it is not sql only.

**Comment by phye** [comment]
After downgrading my emacs from 26.1 to 25.3, the issue disappears. 

Might be incompatible issue between emacs 26.1 and git, linum related modules...

I'll just stuck with emacs 25.3 first as I'm just too busy to bisect which module it is that is not compatible...

**Comment by redguardtoo** [comment]
Yes you'd better stick to 25.3.

**Comment by redguardtoo** [comment]
e230e80f emacs 26.1 display-line-numbers-mode setup (Chen Bin)

**Comment by phye** [comment]
Ah, you've managed to figure out the root cause! 
Just FYI, I've merged your latest commits and confirmed that the weird behavior in this issue is not there anymore. 

BTW, as a newbie not that familiar with ELisp and the various elpa packages, I am quite curious how do you find out the root cause? Are there any upstream bug reports, or you just reproduce the issue and figure the root cause via various debug techniques? Very curious on your debugging techniques or debugging steps :)

**Comment by redguardtoo** [comment]
Nothing magic. I just read code and guess. It's obviously related to git gutters.

Besides, the git gutter linum-mode workaround which caused the issue is started by me (see https://github.com/syohex/emacs-git-gutter/issues/48) ;)

**Comment by phye** [comment]
Thanks buddy. I'll switch to Emacs 26.1 from now on!
