### ISSUE TITLE
Org java source code indented more

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#700]
I indent java source code in org, like:
`public class Apple implements Cloneable {

    @Override
    protected Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
`
but when i run indent-region command, it become:
`public class Apple implements Cloneable {

    @Override
    protected Object clone() throws CloneNotSupportedException {
            return super.clone();
    }
}
`
It indented more 4 space!What should i do?

**Comment by redguardtoo** [comment]
`org-edit-special`, I don't run `indent-region` directly in org-mode

**Comment by peng051410** [comment]
I was doing indent-region operation when editing code after executing org-edit-special

**Comment by peng051410** [comment]
got it!
