### ISSUE TITLE
求助：为什么在windows10下用daemon模式的主题没有加载？

### ISSUE THREAD

**Issue by vrboxing** [redguardtoo/emacs.d#701]
在windows10下使用daemon模式，运行emacsclientw.exe发现主题没有加载，直接运行runemacs.exe主题不会出错，以前的版本不会这样。Emacs版本GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)

**Comment by redguardtoo** [comment]
sorry, I don't use deamon mode, So I can't help.

**Comment by vrboxing** [comment]
又可以了，应该是我设置有问题
