### ISSUE TITLE
`org-insert-link` automatically convert blank space into %20

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#704]
Hi,
This may not be an issue with your configurations, but I really could not find a good solution.

After upgrading to Emacs 26.1, when I run `org-insert-link` to insert the link stored via `org-store-link` which contains blank spaces and that I specify nothing in the prompt minibuf for the link description, those blank spaces will *automatically* be escaped to %20. 

I do not like this conversion, REALLY, as the special escaped characters looks really wired in org files. 
Do you have any idea on any options or any workaround to stop this conversion from happening?

**Comment by phye** [comment]
Kind reminder :)
Hope you're not leaving github...

**Comment by redguardtoo** [comment]
I don't know this `org-insert-link`, maybe it's because 26.1 upgrade `org-mode`?

Looks to me it's a feature instead of bug? A http link does need encode space character (and many other characters), right?

If you don't like this, surely you can advice `org-insert-link` and decode the text.

**Comment by phye** [comment]
Yes, http link should indeed encode space character and other characters, but here I'm actually referring to the description part. 

As you may know, an org link is listed as `[[link][description]]`. It's definitely fine to decode the *link* part, but the *description* part may better be more readable, as that's what will be shown in org files. 

I also suspect that this is due to the new embedded in orgmode in Emacs 26. But after scanning through the entire Release Notes of new orgmode, I didn't find any clue. 

Thanks for your wrapper script :+1: , but there're many other characters that are escaped as well :(

**Comment by redguardtoo** [comment]
https://stackoverflow.com/questions/611831/how-to-url-decode-a-string-in-emacs-lisp

**Comment by phye** [comment]
Thanks!
I would definitely give that a try.

**Comment by phye** [comment]
Unfortunately all the commands/functions listed in the stackover flow question above is rather old, none of them can be found in Emacs 26 and I also didn't find any stable packages which contain them.

Anyway, I'm now accustomed to edit the description field by hand. 

Thanks anyway.
