### ISSUE TITLE
Enter on directory opens a new buffer when `,xf`

### ISSUE THREAD

**Issue by Stumble** [redguardtoo/emacs.d#705]
previously, with ido, when I press enter on a matched directory in minibuffer, minibuffer cd into that directory. now it opens a new buffer in dired. How can I have the same behavior as before?

**Comment by redguardtoo** [comment]
Now I use `ivy` instead of `ido`. So UI may be different.

But for your question, looks the behavior is same. You press enter if your current path in filter input is directory (or maybe you have not updated from latest code?).

**Comment by Stumble** [comment]
Merged with `redguardtoo/emacs.d/master`, `, 
xf` is counsel-find-file, 
package-list-packages shows that all packages are update-to-date.

when I press on, it shows this
![selection_001](https://user-images.githubusercontent.com/3461891/42070030-83edf2c8-7b09-11e8-87b5-c05bfcf01e3a.png)

**Comment by redguardtoo** [comment]
It's dired, isn't it?

**Comment by Stumble** [comment]
yeah, it is. But how could I change it back to not use dired to open directory?

**Comment by redguardtoo** [comment]
There is nothing I can do, unless you go back to `ido-find-file`. But you need `(ivy-mode -1)` at first.

**Comment by whatacold** [comment]
> But how could I change it back to not use dired to open directory?

@Stumble press `/` instead of `ENTER`

**Comment by Stumble** [comment]
@whatacold Thanks for suggestion, It works! I wonder is there a way to change this behavior in `ivy` mode?

**Comment by whatacold** [comment]
This should work: https://github.com/abo-abo/swiper/issues/532 , also check [Do not open dired for directories when using counsel-find-file - Emacs Stack Exchange - emacs.stackexchange.com](https://emacs.stackexchange.com/questions/33701/do-not-open-dired-for-directories-when-using-counsel-find-file) with some explanations.
