### ISSUE TITLE
there is no react when emacs startup on FreeBSD11.2

### ISSUE THREAD

**Issue by gehancoder** [redguardtoo/emacs.d#706]
hi there is no react when Emacs startup on FreeBSD 11.2, and the version of Emacs is 26.1. Does this config file support FreeBSD OS? Thanks

**Comment by redguardtoo** [comment]
I don't have FreeBSD at hand. 

I need some days to install it on my machine.

**Comment by gehancoder** [comment]
Hi,

Thanks for your reply.

I am already have figured out the issue and this config works fine on FreeBSD machine.

I login in the machine with my username "ghan" which $HOME directory is "/usr/home/ghan" and switch to root account which $HOME is "/root" with "su" command in terminal, and then checked out .emacs.d to /root path, it had no react when start emacs.

Then I just moved the "init.el" file to "/usr/home/ghan" folder and keep other files still in "/root" folder, and it works fine and all config are vaild.


Best Regards,

Geng Han

________________________________

**Comment by redguardtoo** [comment]
Good to know. Thanks.
