### ISSUE TITLE
使用M-x ansi-term快捷键出错

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#710]
如题，OS为WIN7，emacs版本为26.1。错误信息是apply: Spawning child process: invalid argument

我搜索了该问题，stackoverflow上的[解释](https://stackoverflow.com/questions/20263012/m-x-term-with-emacs-on-ms-windows-error-spawning-child-process-invalid-argum)是：
`none of the terminal emulators in Emacs (term, ansi-term, multi-term) is supported under Windows`

但是我有按照你的README所推荐的那样在Windows下载Cygwin，也配置了环境变量。所以我觉得是我的使用方法出了点问题

我的问题有三个，分别是：
（1）README中Windows  section提到的“ Cygwin version of Emacs”是指在Cygwin中下载的emacs么？
（2）我在[issuse  446](https://github.com/redguardtoo/emacs.d/issues/466)中有注意到你提到 “windows原生版本结合Cygwin就是把`c:/cygwin64/bin'加到环境变量path里去就可以” `，我按照这句话添加了Cywin64/bin到我的环境变量里去，但是 `M-x ansi-term` 还是不能执行。  请问可否具体阐述一下“windows原生版本结合Cygwin”呢？
（3）请问对于Windows用户来说， `.emacs.d/init.el` 文件中的被你注释掉的：
`  ;; Windows configuration, assuming that cygwin is installed at "c:/cygwin"
  ;; (condition-case nil
  ;;     (when *win64*
  ;;       ;; (setq cygwin-mount-cygwin-bin-directory "c:/cygwin/bin")
  ;;       (setq cygwin-mount-cygwin-bin-directory "c:/cygwin64/bin")
  ;;       (require 'setup-cygwin)
  ;;       ;; better to set HOME env in GUI
  ;;       ;; (setenv "HOME" "c:/cygwin/home/someuser")
  ;;       )
  ;;   (error
  ;;    (message "setup-cygwin failed, continue anyway")
  ;;    ))`
需要还原么？

**Comment by redguardtoo** [comment]
1. Yes
2. ansi-term is not included. The original purpose is make `grep.exe` usable.
3. 不需要,下次我删了这段.

**Comment by Ynjxsjmh** [comment]
thx
