### ISSUE TITLE
请问如何将emacs外的文本复制到emacs内

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#712]
[issue 658](https://github.com/redguardtoo/emacs.d/issues/658)是类似的问题。
在里面你给出的最后的回答是`Check my-minibuffer-setup-hook in init-misc.el`，我看到的这部分的内容是：
```
(defun my-minibuffer-setup-hook ()
  (local-set-key (kbd "M-y") 'paste-from-x-clipboard)
  (local-set-key (kbd "C-k") 'kill-line)
  (setq gc-cons-threshold most-positive-fixnum))
```
我的理解是`M-y`可以达到我的目的，但是我尝试的时候`M-y`是打开`*Kill Ring*`

至于在issue 668中你提到的另一个方法：`check (my-gclip), I prefer using yasnippet plus that api.`，那个人的回复是`I've mimic a new snippet from your items-from-clipboard.yasnippet and attach key l to the snippet. It works perfectly now!` ，但是我看了下`items-from-clipboard.yasnippet`，感觉完全不知道该怎样做。

所以，怎样做才能做到将emacs外的文本复制到emacs内呢？

**Comment by redguardtoo** [comment]
`M-x paste-from-x-clipboard`

**Comment by Ynjxsjmh** [comment]
我试了 `M-x paste-from-x-clipboard 1` 到 `M-x paste-from-x-clipboard 4` ，但是均显示：
`M-x (match required) paste-from-x-clipboard `
不加参数的话显示`funcall: Wrong type argument: char-or-string-p, nil `

**Comment by redguardtoo** [comment]
Depending on OS. You might need install some cli tools. See http://blog.binchen.org/posts/copypaste-in-emacs.html

**Comment by Ynjxsjmh** [comment]
在安装Ditto之后，我使用`M-x paste-from-x-clipboard 1`等，还是提示`M-x (match required) paste-from-x-clipboard`。
我根据Ditto的使用文档里提到的全局热键`C-``是可以在Ditto的剪切板上看到我剪切的内容，并且在Emacs外是可以成功粘贴成功的，但是在Emacs里面就不行了。
上述情况是使用Windows下的原生Emacs

我又尝试了使用Cygwin安装的emacs-win32，然后使用`M-x paste-from-x-clipboard`，这次是可以复制了。

对于原生的Emacs有没有什么比较好的解决方案呢？

**Comment by redguardtoo** [comment]
Use `Ditto` to select content, Then see https://emacs.stackexchange.com/questions/30137/paste-windows-clipboard-with-shift-insert-but-not-by-yanking. 

`paste-from-x-clipboard` is for cli tool. It requires knowledge of Cygwin cli tool (for example, setup environment variable PATH),

**Comment by Ynjxsjmh** [comment]
我今天又试了一下，发现莫名其妙的使用 `C-y` 可以粘贴成功，但是我确定我昨天以及之前使用 `C-y` 是不能成功的，不然我也犯不着开个issue来问，所以我猜想是不是和安装Ditto的过程有关（我是通过exe方式安装的）

现在对这个关于 `如何将emacs外的文本复制到emacs内` 的issue做一个小结：
（1）对于原生版本的Emacs：
        ——Ditto处于关闭时：使用 `C-y` 粘贴，中英文均成功；  使用 `M-x paste-from-x-clipboard`粘贴， 显示 `funcall: Wrong type argument: char-or-string-p, nil`
        ——Ditto处于开启时：使用 `C-y` 粘贴，中英文均成功；  使用 `M-x paste-from-x-clipboard`粘贴， 显示 `funcall: Wrong type argument: char-or-string-p, nil`

（2）对于Cygwin下的Emacs：
       ——Ditto处于关闭时：使用 `C-y` 粘贴，中英文均成功；  使用 `M-x paste-from-x-clipboard`粘贴，中文乱码，英文成功。
       ——Ditto处于开启时：使用 `C-y` 粘贴，中英文均成功；  使用 `M-x paste-from-x-clipboard`粘贴，中文乱码，英文成功。

几点说明：
1. OS为WIN7
2. 原生版本的Emacs使用的是runemacs测试的，Cygwin下的Emacs使用的是emacs-w32测试的。版本号均为26.1
3. 是在下载Ditto之后进行测试的
4. cygwin binary directory has been added into environment variable PATH


最后谢谢你的帮助

**Comment by redguardtoo** [comment]
`C-y` surely works, at the beginning of `init-clipboard.el`,
```lisp
(setq x-select-enable-clipboard t
      x-select-enable-primary t)
```
See https://www.emacswiki.org/emacs/CopyAndPaste

I prefer `paste-from-xclipboard` because it works in every environment. But on native windows Emacs, you need know how to add cygwin binary directory into environment variable `PATH`. That's why README emphasizes the knowledge of *nix is very useful. But for now, forget `paste-from-xclipboard` since you are not familiar with CLI.
