### ISSUE TITLE
environment: windows 7 &  emacs 16.1

### ISSUE THREAD

**Issue by ytwas** [redguardtoo/emacs.d#713]
#this is information that come from "--debug-init"
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "c:/Users/ytw/AppData/Roaming/.emacs.d/elpa/w3m-20180405.520/w3m-autoloads")
  load("c:/Users/ytw/AppData/Roaming/.emacs.d/elpa/w3m-20180405.520/w3m-autoloads" nil t)
  package--activate-autoloads-and-load-path(#s(package-desc :name w3m :version (20180405 520) :summary "an Emacs interface to w3m" :reqs nil :kind nil :archive nil :dir "c:/Users/ytw/AppData/Roaming/.emacs.d/elpa/w3m-20180405.520" :extras ((:keywords "w3m" "www" "hypermedia")) :signed nil))
  package--load-files-for-activation(#s(package-desc :name w3m :version (20180405 520) :summary "an Emacs interface to w3m" :reqs nil :kind nil :archive nil :dir "c:/Users/ytw/AppData/Roaming/.emacs.d/elpa/w3m-20180405.520" :extras ((:keywords "w3m" "www" "hypermedia")) :signed nil) nil)
  package-activate-1(#s(package-desc :name w3m :version (20180405 520) :summary "an Emacs interface to w3m" :reqs nil :kind nil :archive nil :dir "c:/Users/ytw/AppData/Roaming/.emacs.d/elpa/w3m-20180405.520" :extras ((:keywords "w3m" "www" "hypermedia")) :signed nil) nil deps)
  package-activate(w3m)
  package-initialize()
  eval-buffer(#<buffer  *load*> nil "c:/Users/ytw/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 408
  load-with-code-conversion("c:/Users/ytw/AppData/Roaming/.emacs.d/init.el" "c:/Users/ytw/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/ytw/AppData/Roaming/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000be22d>)()
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment]
re-install `w3m`

**Comment by ytwas** [comment]
i met another problem when i open an '.cpp' file :
company backend 'company-clang' could not be initialized: company found no clang executable,
and i cannot found company-clang.
what should i do

**Comment by redguardtoo** [comment]
just ignore it. You don't need clang. See https://nilsdeppe.com/posts/emacs-c++-ide2
plus company-etags

**Comment by ytwas** [comment]
got it,
thanks a lot.
