### ISSUE TITLE
error in process filter: error: gnutls support needed!

### ISSUE THREAD

**Issue by SuJinpei** [redguardtoo/emacs.d#714]
Hi, I am a newbie to emacs.  I followed the installation guide.  But I get the error message as the title when I start emacs. My OS is Centos-7.2 and my emacs version is GNU Emacs 26.1. I also checked that the gnutls package was installed.
`$ rpm -ql gnutls
/usr/lib64/.libgnutls.so.28.43.0.hmac
/usr/lib64/.libgnutls.so.28.hmac
/usr/lib64/libgnutls.so.28
/usr/lib64/libgnutls.so.28.43.0
/usr/share/doc/gnutls-3.3.26
/usr/share/doc/gnutls-3.3.26/AUTHORS
/usr/share/doc/gnutls-3.3.26/COPYING
/usr/share/doc/gnutls-3.3.26/COPYING.LESSER
/usr/share/doc/gnutls-3.3.26/NEWS
/usr/share/doc/gnutls-3.3.26/README
/usr/share/doc/gnutls-3.3.26/THANKS
/usr/share/locale/cs/LC_MESSAGES/gnutls.mo
/usr/share/locale/de/LC_MESSAGES/gnutls.mo
/usr/share/locale/en@boldquot/LC_MESSAGES/gnutls.mo
/usr/share/locale/en@quot/LC_MESSAGES/gnutls.mo
/usr/share/locale/eo/LC_MESSAGES/gnutls.mo
/usr/share/locale/fi/LC_MESSAGES/gnutls.mo
/usr/share/locale/fr/LC_MESSAGES/gnutls.mo
/usr/share/locale/it/LC_MESSAGES/gnutls.mo
/usr/share/locale/ms/LC_MESSAGES/gnutls.mo
/usr/share/locale/nl/LC_MESSAGES/gnutls.mo
/usr/share/locale/pl/LC_MESSAGES/gnutls.mo
/usr/share/locale/sv/LC_MESSAGES/gnutls.mo
/usr/share/locale/uk/LC_MESSAGES/gnutls.mo
/usr/share/locale/vi/LC_MESSAGES/gnutls.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gnutls.mo`

any idea?  Thank you in advance.

**Comment by redguardtoo** [comment]
On Linux, you don't need any extra setup. `yum install emacs` is enough. Unless you compiled emacs by yourself?

**Comment by SuJinpei** [comment]
yes, I compiled the emacs by myself.

**Comment by SuJinpei** [comment]
after doing some google, I found that modifying lisp/init.el as below can escape this error.
```
-        ("melpa" . "https://melpa.org/packages/")
-        ("melpa-stable" . "https://stable.melpa.org/packages/")
+        ;; ("melpa" . "http://melpa.org/packages/")
+        ;; ("melpa-stable" . "http://stable.melpa.org/packages/")
```

**Comment by redguardtoo** [comment]
Yes, but it's not secure connection.

I suggest not compiling Emacs by yourself.
