### ISSUE TITLE
it takes a long time to open emacs

### ISSUE THREAD

**Issue by ytwas** [redguardtoo/emacs.d#715]
every time i open it, it always loading a lot of things,
i can only operate after the loading finished.
my environment: win7 & emacs 16.1

**Comment by ytwas** [comment]
i met another problem that i cannot use etags or gtags to navigate:

1. i have tried to use command "etags *.c",but the TAGS file created cannot open in emacs
2. i also tried to use "find . -name "*.[chCH]" -print | etags -", but the command cannot execute and it said"
 access denied -.
 cannot find file - -name
 cannot find file - -print"

**Comment by redguardtoo** [comment]
1. I tried etags, its TAG file does can be used by `counsel-etags` which is already built into this setup.

2. There is already unrelated `find.exe` in window. So you have to use full path of GNU Find.

**Comment by redguardtoo** [comment]
It only takes 1 or 2 seconds startup. But if it has to download third party packages it may take more time.

**Comment by ytwas** [comment]
so what can i do to solve this?
it always load file called "*.el" or idle-require.

**Comment by redguardtoo** [comment]
`idle-require` will loading optional setup when you are "idle".

**Comment by ytwas** [comment]
ok, thanks for your patience!!
and is there an introduction of your configuration?
i don't know what function i have in this configuration.
