### ISSUE TITLE
Error running timer ‘auto-save-buffers’: (user-error "Save not confirmed")

### ISSUE THREAD

**Issue by keyou** [redguardtoo/emacs.d#718]
When I exit Emacs, it says `xxx has changed since visited or saved.  Save anyway? (y or n)`, after press n, the bellow error appears, and it appears frequently. I can not exit Emacs.
```
Error running timer ‘auto-save-buffers’: (user-error "Save not confirmed")
```
(From a newbie.)

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, reproduce the issue, then show me full error message.

**Comment by keyou** [comment]
Can not reproduce the issue after several tries, I will show you when it does.

**Comment by redguardtoo** [comment]
`Cygwn` bug on fam conflicts with `auto-revert-buffer`, just my guess. I suppose I work arounded this issue.
