### ISSUE TITLE
Better electric-pair configurations?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#719]
Hi,
I'm not sure if you're aware of it or not, but I have to say that the default configurations for `electric-pair` mode is *NOT* that perfect.

Say that you want to add quotes to some word, with the default configuration of `electric-pair`, 

```sh
  <^>words to be quoted<$>
```
Entering `"` at `^` and `$` position above will result in ""，I just have to remove the *INCORRECTLY* paired quotes manually and that's really annoying...

Not sure if you're using electric-pair mode as well or you have any better configuration for this mode? I'm using emacs 26.1.

I've tried the following method, but it just solves the problem of inserting at `^` position, not in the `$`

https://www.reddit.com/r/emacs/comments/41i156/using_smartquotes_with_the_electric_pair_mode/

**Comment by redguardtoo** [comment]
e01b522e setup electric-pair (Chen Bin)

**Comment by phye** [comment]
Thanks.
I've merged your commit however it seems to remove electric pair function completely?

**Comment by redguardtoo** [comment]
see https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-misc.el#L221

Only disabled it at the end of word when input single or double quotes.

**Comment by phye** [comment]
Tried your latest setup and everything is working fine now!

Thanks.
