### ISSUE TITLE
How to use the find-file-in-project and the rg search?

### ISSUE THREAD

**Issue by zhixing2017** [redguardtoo/emacs.d#722]
when I use the find-file-in-project, the emacs crashed. I do not know why. 

I want to grep or rg the project. what is the command? counsel-rg? If I use the counsel-rg, the emacs don't work.

on Windows 7, emacs 26.1

**Comment by zhixing2017** [comment]
I use Git. And the emacs get stuck when I use the projectile and the rg. 

I cannot use the rg and the projectile. It is very strange.

**Comment by zhixing2017** [comment]
说错了，不是用的projectile, 就是用的你的原生配置，用的find-file-in-project, 还有一个ffip, 但是都会导致emacs卡死，不知道为什么。
我是用的git，应该是能自动识别的才对啊。

**Comment by redguardtoo** [comment]
Have you installed GNU Find? Install cygwin to its default location on any hard drive. `find.exe` will be automatically detected.
