### ISSUE TITLE
安装之后没反应

### ISSUE THREAD

**Issue by feibaliang** [redguardtoo/emacs.d#723]
我安装了配置，但是启动emacs后没什么反应，emacs没有安装什么包，请问我如何确定我是否成功安装了你的配置

**Comment by redguardtoo** [comment]
Search windows in README if you use windows.

Or else it should work out of box.

**Comment by feibaliang** [comment]
我用的是centos7

**Comment by slmoby** [comment]
你是用的命令行还是DM的界面呢？使用命令行的方式看看是否会有日志产生呢

**Comment by slmoby** [comment]
rpm -qa |grep emacs 尝试去看看你是否安装成功然后选择启动试试看呢

**Comment by feibaliang** [comment]
知道我的问题在哪里了，我的emacs 版本太低了，没看到错误信息。 用了 --debug-init 参数才看到

**Comment by slmoby** [comment]
使用CentOS7 这个发行版 本身包是有点老的 需要使用的话还是自己编译安装新的好了 : )

**Comment by redguardtoo** [comment]
Did you see `error: This config requires Emacs v24.4 or higher` when you start Emacs?

**Comment by feibaliang** [comment]
Didn't see the error until I use run emacs with --debug-init

**Comment by feibaliang** [comment]
我现在编译安装了26.1 ，出现这个错误 

> Error (bytecomp): Symbol’s value as variable is void: badger-colors-alist

这个影响正常使用吗

**Comment by redguardtoo** [comment]
I don't know, Run `emacs -nw --debug-init`. show me the full error message.

**Comment by feibaliang** [comment]
The error message just disappered after I tried sereral times, and now it works perfect for me.Thanks @slmoby @redguardtoo

**Comment by redguardtoo** [comment]
Could be thirty party package compile warning/error. You can safely ignore them.
