### ISSUE TITLE
Autocomplete file name/path?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#726]
If there're anything that I'm missing after switching from VIM to Emacs, autocompleted file names are among top of them.

Previously in VIM I'm using [neocomplete](https://github.com/Shougo/neocomplete.vim) which will automatically prompt file names if I enter some directory name, as is shown in the github page below.

![Image Of Autocomplete](https://camo.githubusercontent.com/5be2869c1af76a8b51b89ab6537f2de9ea37d22d/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f34313439352f3632323435342f66353139663662382d636634322d313165322d393231652d3665333464626131343861362e706e67)

I'm just wandering if there're such similar behaviors in your Emacs settings?

Thanks

**Comment by phye** [comment]
BTW, [neocomplete](https://github.com/Shougo/neocomplete.vim) is now replaced by [deocomplete](https://github.com/Shougo/deoplete.nvim) with async support.

**Comment by redguardtoo** [comment]
`company-file` from `company-mode` is already enabled. You don't need any extra setup.

**Comment by redguardtoo** [comment]
Don't know much about go. These days I'm only doing javascript.

**Comment by phye** [comment]
I was using go-autocomplete for quite a while and is now switching to company-go for better integration with company. 

Thanks for your hint and I just found another specific golang solution which has imports managements:

https://github.com/dominikh/go-mode.el
