### ISSUE TITLE
Remove the leading caret(^) in `M-x`?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#727]
I can't tell from which commit in your setup, every time I hit `M-x` to invoke commands, there's an annoying `^` in the prompt by default. As an Emacs newbie, I cannot tell the command prefix clearly and thus every time I have to remove the leading caret, then type some keywords to search for commands.

I know you should have your own consideration in introducing this leading caret, but I'm just wondering if there's an option if I only want fuzzy mode?

**Comment by redguardtoo** [comment]
`M-x space blah ....`

**Comment by phye** [comment]
Thanks!
