### ISSUE TITLE
org-mode 高亮错误

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#728]
在使用 org-mode 的过程中，我的高亮出现如下错误（此时光标是不闪烁的）：
![](https://emacs-china.org/uploads/default/original/2X/e/e667f6ec4b683aae0db3d1fe2dc919e19f33a73c.png)

如图，大纲 `4.2.2` 显示出错，最后一个 2 上出现一个紫色的框框，而且整句的颜色高亮也不对。

为此我在 Emacs China 上[提问](https://emacs-china.org/t/org-mode/7102)寻求大家的帮助，最后有人[给出解释](https://emacs-china.org/t/org-mode/7102/17?u=ynjxsjmh) 说是 `artbollocks-mode` 的问题。

但是，我换完主题的时候，org-mode 没有此问题，不过此时光标是闪烁的。由于个人不太喜欢闪烁的光标，因此我在 `~.emacs.d\init.el` 的最后一行加上了 `(blink-cursor-mode 0)` 来取消光标闪烁，但是取消这句后 org-mode 的高亮又不对了。

对这种情况有什么更好的方法来解决么？

我是在 Windows 下使用原生的 Emacs。

**Comment by ikaryshin** [comment]
文字的style在emacs中叫做face。你可以用M-x list-faces-display命令看看是哪些mode在影响字体的显示。然后不要require相应的包即可。
关于Text Face，可以看这个链接[https://www.gnu.org/software/emacs/manual/html_node/emacs/Faces.html](url)

**Comment by Ynjxsjmh** [comment]
谢谢，按照你的方法尝试发现是 `artbollocks-mode.el` 的问题，不 require 这个包后就没上述问题了。

**Comment by redguardtoo** [comment]
22a9fc89 remove artbollocks-mode (Chen Bin)
