### ISSUE TITLE
emacs启动慢

### ISSUE THREAD

**Issue by ytwas** [redguardtoo/emacs.d#729]
我的emacs启动很慢啊，感觉需要十几秒，有没有办法能够加快啊，
而且我在资源管理器里直接双击代码打开的话它居然是新开一个emacs打开的。。
感觉在emac里面找文件不太方便

**Comment by phye** [comment]
Try emacs-client

**Comment by redguardtoo** [comment]
I did some optimization. now faster

**Comment by zheng7fu2** [comment]
@redguardtoo 我在win7 和win10 下的Cygwin中安装emacs 26.1后使用您的配置文件，启动都要20多秒，没有出错信息，只是在 Message Buffer中有以下提示：

`` 1 No docstring slot for post-read-decode-hz
  2 No docstring slot for pre-write-encode-hz
  3 ad-handle-definition: ‘ispell-word’ got redefined
  4 Emacs startup time: 24 seconds.
  5 Loading /home/zheng/.emacs.d/.session...done
  6 Loading /home/zheng/.emacs.d/company-statistics-cache.el (source)...done
  7 [yas] Prepared just-in-time loading of snippets successfully.
  8 For information about GNU Emacs and the GNU system, type C-h C-a.

您看看是少装什么了吗？

**Comment by redguardtoo** [comment]
fixed, Latest cygwin `fam` and `auto-revert-mode` conflict

**Comment by ytwas** [comment]
我试了Emacs-client现在用起来很方便了
