### ISSUE TITLE
Symbol's value as variable is void: flymake-allowed-file-name-masks

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#731]
Emacs version: 25.2.2
git version: 18a0d6

When emacs launches, error shows:

```
Symbol's value as variable is void: flymake-allowed-file-name-masks
```

**Comment by jmikedupont2** [comment]
do you have a solution for this?

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/emacs.d#support-legacy-emacs-versions
