### ISSUE TITLE
How to save window layout?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#734]
Is it possible that I can save the window split layout and their corresponding buffers before I exit emacs and recover them when I restart emacs? I remembered there're Session in VIM, just wonder if there're similar solutions in Emacs.

**Comment by redguardtoo** [comment]
`init-evil.el`, search `windows layout`

**Comment by phye** [comment]
`spc s s` works like a charm!

Just one more question, if I have multiple work groups created by `wg-create-group`, how will I be able to recover one of the specific work group identified by certain work group name?

**Comment by redguardtoo** [comment]
`spc l l`

**Comment by phye** [comment]
Thanks!
The two commands above changed my workflow TREMENDEOUSLY!
