### ISSUE TITLE
python-mode 无显示

### ISSUE THREAD

**Issue by wangjunget** [redguardtoo/emacs.d#736]
打开python文件，无法进入python-mode
显示信息：File mode specification error: (error Loading file e:/Emacs26.1/.emacs.d/elpa/pyvenv-1.18/pyvenv.elc failed to provide feature ‘pyvenv’

**Comment by redguardtoo** [comment]
re-install `pyvenv`, it's used by `elpy`.

**Comment by wangjunget** [comment]
重新安装后可以了。之前看了下pyvenv.el文件，里面是空的，可能是刚开始安装时出问题了吧。
