### ISSUE TITLE
org-babel C 缩进错误

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#737]
我在 org-mode 的 c src block 中使用 `C-c '` 弹出的代码编辑区域里编辑时，无论是 TAB 缩进，还是换行时自动的缩进都是 8 个空格。但是在 .c 文件中缩进又都是 4 个空格。

请问怎么将 org-babel c 里的缩进改成 4 个空格呢？

**Comment by redguardtoo** [comment]
578cd237 call major-mode hook when buffer-file-name is nil (Chen Bin)

**Comment by Ynjxsjmh** [comment]
我在你的配置上也增加了一些其他的包，请问有没有一种便捷的方法 在保证与你的配置同步的同时 保留我原来的更改呢？

**Comment by redguardtoo** [comment]
You can override all my setup in `~/.custom.el`

**Comment by redguardtoo** [comment]
Or append you own setup in `lisp/init-*.el`, for example, at the end of `init-elpa.el`, add `(if (file-exists-p "~/my-init-elpa.el") (load-file "~/my-init-elpa.el"))`.

**Comment by Ynjxsjmh** [comment]
我按照 [How do I update a GitHub forked repository?](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) 上的最高赞回答来和你的配置保持最新后，发现我在 `~/lisp/` 下自己添加的 `init-elpa.el` 全部丢失了，但是 `~/elpa` 中我自己下载的包却还在。
![default](https://user-images.githubusercontent.com/40143136/48555488-5a693300-e91c-11e8-8133-e9670d68c6fa.png)

**Comment by redguardtoo** [comment]
`git pull https://redguardtoo@github.com/redguardtoo/emacs.d.git` is enough. It's over-engineering to create any branch in your case. If you file is under git control, you could not lose it. Maybe you need learn more git at first.

**Comment by Ynjxsjmh** [comment]
哈哈真的是一针见血，对 git 只熟悉 add 和 commit。我是按 README 里的 [easiest way](https://github.com/redguardtoo/emacs.d#install-stable-version-in-easiest-way-optional) 来安装的。我为了和你的配置保持一致做了如下工作：

1. git init 初始化我的 `~/.emacs.d`
2. git add 和 git commit 现有 repo 内的文件
3. git pull https://redguardtoo@github.com/redguardtoo/emacs.d.git 提示 `fatal: refusing to merge unrelated histories` 
4. 加上 `--allow-unrelated-histories` 再 pull 一遍，又出现很多很多 `Merge conflict`

我到 sof 上搜索的解决方法是手动解决这个 confict，但是文件太多了，手动改根本不太可能。昨天卡在这里一晚上。

今天早上看了推荐的那个 progit，感觉我是不是应该先 `git clone` 你的 repo 呢？


完整过程：
```
$ git reflog
510edff (HEAD -> master) HEAD@{0}: commit (initial): create repo

$ git pull https://redguardtoo@github.com/redguardtoo/emacs.d.git
warning: no common commits
remote: Enumerating objects: 28465, done.
...
From https://github.com/redguardtoo/emacs.d
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

$ git reflog
510edff4 (HEAD -> master) HEAD@{0}: commit (initial): create repo

$ git pull https://redguardtoo@github.com/redguardtoo/emacs.d.git --allow-unrelated-histories
From https://github.com/redguardtoo/emacs.d
 * branch              HEAD       -> FETCH_HEAD
Auto-merging snippets/scala-mode/with
CONFLICT (add/add): Merge conflict in snippets/scala-mode/with
...  many many merge confilct

(master|MERGING)
```

**Comment by redguardtoo** [comment]
Yes, you need `git clone` my emacs.d first. Then add your modification and commit. Then pull.

**Comment by Ynjxsjmh** [comment]
谢谢你耐心的解答 !
