### ISSUE TITLE
How to jump word precisely?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#739]
Consider the example below (i.e. camel case or underline separator):
```
 helloWorld  
^  # dw here
 hello_world
^  # dw here
```

I would like `dw` to remove 'hello' only in both cases, rather than deleting 'helloWorld' or 'hello_world' completely. Do you know how would I be able to configure this in emacs?

Thanks

**Comment by redguardtoo** [comment]
see https://www.reddit.com/r/emacs/comments/3ciddp/using_subwordmode_with_evilmode/

**Comment by phye** [comment]
I'm quite confident that previously the behavior I mentioned above works properly, but suddenly they're not working some other day.

I'm not sure if it's related to package upgrade or I merged your latest fixes, hence the question :)

Perhaps I have to refer to the last resort to bisect. Thanks anyway.

**Comment by redguardtoo** [comment]
OK, what's vim behaviour?

**Comment by phye** [comment]
I cannot tell that there're any standard here :(
Just tried my vim config, `dw` removes the whole camel case word as well. On the other hand, if I want to delete whole camel, I would normally try `dW`.

**Comment by redguardtoo** [comment]
05ddcd83 restore evil default word movement (Chen Bin)

**Comment by phye** [comment]
Thanks!
