### ISSUE TITLE
Find-file-in-project is very slow when I use mac and Freezes when I use windows

### ISSUE THREAD

**Issue by rayjun** [redguardtoo/emacs.d#743]

**Comment by redguardtoo** [comment]
How long it take to find file? How big is your project? What's result of `M-x eval-expression (ffip--executable-find)`. Have you installed GNU find or fd?

**Comment by rayjun** [comment]
On mac, it will take 5 Seconds,  around 10000 files(php+html)，the function output /usr/bin/find 。
It's still freezes on windows when I input execute this function. @redguardtoo

**Comment by redguardtoo** [comment]
On windows, you need install cygwin. So `ffip` could use Cygwin GNU Find.

**Comment by rayjun** [comment]
@redguardtoo  Thanks
