### ISSUE TITLE
configuration of Emacs in windows 7

### ISSUE THREAD

**Issue by lzg0015** [redguardtoo/emacs.d#745]
thank you for your emacs.d file and the installation instruction. I'm a new learner of Emacs and your tutorial helps me a lot. 
There are some questions, I think that may confuse and beat the new comers.
1. after I unzip the "emacs.d-master" file into ~/.emacs.d , I start Emacs 26.1 and there was an tip:  Contacting host: melpa.org:443 and stuck there. I think that might because of  I can't link to melpa.org in mainland of china, so I search on google and finally find a solution, that is to comment the source of GNU and uncomment the source of tsinghua and 163.com. 
As a new learner, this queastion really confused me a lot and I think for the other newcomers, the same. So please kindly add some tips about this for people like me. thank you very much.
2. If possible, could you wirte some instructions of how to use emacs in writing scientific papers, for instance, wirte a paper for a chemisty journal, and better in chinese. 
THANK YOU AND HOPE YOU HAPPY EVERY DAY.

**Comment by redguardtoo** [comment]
Thanks for the heads up.
See d0d09b6225ec
