### ISSUE TITLE
go-mode 删除了？

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#748]
一直使用您的配置，最近pull发现site-lisp\go-mode删除了，我对lisp不熟悉，只搜索到init.el有go-mode的一些信息，请问我现在怎么做才是合理的方法呢？

**Comment by redguardtoo** [comment]
It's better to install go-mode through melpa. I don't have chance to use `go`.

The easiest way is add your own setup into `~/.custom.el`.

**Comment by xxyyer** [comment]
OK，thank you~
