### ISSUE TITLE
c language syntax check does not work sometimes

### ISSUE THREAD

**Issue by chxin** [redguardtoo/emacs.d#749]
I am using your .emacs.d without any modifying for c and c++ language on Ubuntu 18.04.  
I find that only the main.c never shows the syntax error message when other .c or .h files of the same project show that. 
The other is that the prompt for function name and argument disappears once the function name has done. I am not sure whether it is your configuration for it but I have not found the place to reconfigure it because I would like to always show the function prompt when I type its arguments. Could you tell me how to realize it?

**Comment by redguardtoo** [comment]
Use GNU Global plus Emacs for code completion and code navigation.  See http://blog.binchen.org/posts/emacs-as-c-ide-easy-way.html (it's already part of my setup).

For real time syntax check. Don't spend too much time on it.
