### ISSUE TITLE
looking for a way to list buffers in kill-buffer in the latest commit

### ISSUE THREAD

**Issue by Kunderscore** [redguardtoo/emacs.d#751]
I have been using your stable emacs.d for a while now, it works great.
but after updating to the latest update, it works even better.
However, i noticed a few changes and don't know how to "revert" them.

In the stable release, c-x k will get you list of buffers. In latest release, emacs only prompt asking for the name of buffer to kill. 

Thanks in advance.

**Comment by redguardtoo** [comment]
I use original `counsel/ivy` with minimum setup. Looks it's counsel/ivy developer who removed this feature.

After reading its latest code, I found you can `C-x b` to list buffer and `C-c C-k` to delete a buffer.

**Comment by Kunderscore** [comment]
Thanks much appreciated!
