### ISSUE TITLE
请教如何更好地快速执行编译命令

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#752]
之前在用,oo执行编译，发现有两点不便的地方：
一是当前目录不在根目录（Makefile所在目录）时，执行编译命令make失败；
二是按完,oo后还需要按回车才执行编译。
请问有更好的操作方法吗？

_本人大概拼凑了几句代码，实现了一个还算能用的方法，在这里分享一下，望指点：
在.custom.el中增加以下内容，执行,oi用于记录编译所在目录和编译命令，之后在任意目录只需要执行,oo就能直接在记录的目录中执行记录的编译命令。_
```
(evil-define-command evil-cd-compile
  "Cd & compile."
  :keep-visual t
  :repeat nil
  :type exclusive
  (call-interactively 'cd "./")
  (call-interactively 'compile))

(nvmap :prefix ","
       "oi" 'evil-cd-compile
       "oo" 'recompile)

```

**Comment by redguardtoo** [comment]
`Enter` key is necessary. It's trivial compared to the actual compiling time. It also gives your a chance to not start compiling (maybe you realize there is typo in your code).

In you code, `(cd "./")` is enough. or maybe just change compile-command to `cd ./ && dosomething`.

**Comment by xxyyer** [comment]
`./ && dosomething`的确是个好主意，路径和命令放一起后能更好地管理和查看历史命令。谢谢！
