### ISSUE TITLE
Error setting org-babel-load-languages: (file-missing Cannot open load file No such file or directory ob-sh)

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#753]
I use org to manage my custom configuration file. When I modify the file, I execute tangle error. I found it on the Internet that ob-sh has been renamed to ob-shell after org8, but I can't find reference to ob-sh. Where can I locate the problem?

**Comment by redguardtoo** [comment]
steps to reproduce the issue?

**Comment by peng051410** [comment]
I have a function to reload my config:
`(defun config-reload ()
  "Reloads config.org at runtime"
  (interactive)
  (org-babel-load-file (expand-file-name "~/Nustore/orgs/config.org")))
(global-set-key (kbd "C-c r") 'config-reload)
`
My custom.el file content:
`(when (file-readable-p "~/Nustore/orgs/config.org")
  (org-babel-load-file (expand-file-name "~/Nustore/orgs/config.org")))`

When i run config-reload, the error appear.

**Comment by peng051410** [comment]
Here is the startup message:
`Loading /Users/tomyli/.custom.el (source)...
Loading /Users/tomyli/Nustore/orgs/config.el (source)...
Overriding package-menu--print-info with paradox--print-info
Overriding package-menu--print-info-simple with paradox--print-info
Overriding package-menu--generate with paradox--generate-menu
Overriding package-menu-mode with paradox-menu-mode
Deprecated date/weektree capture templates changed to ‘file+olp+datetree’.
Loading /Users/tomyli/Nustore/orgs/config.el (source)...done
Loaded /Users/tomyli/Nustore/orgs/config.el
Loading /Users/tomyli/.custom.el (source)...done
Error setting org-babel-load-languages: (file-missing Cannot open load file No such file or directory ob-sh)
Emacs startup time: 6 seconds.
Loading /Users/tomyli/.emacs.d/.session...done
Loading /Users/tomyli/.emacs.d/company-statistics-cache.el (source)...done
[yas] Prepared just-in-time loading of snippets successfully.
`

**Comment by peng051410** [comment]
I use set custom variable to solved it! thanks!
