### ISSUE TITLE
M-x can't use in emacs25.2.2 ubuntu18.04

### ISSUE THREAD

**Issue by cookieli** [redguardtoo/emacs.d#755]
it produce this:smex-load-save-file: Wrong number of arguments: setq, 1 [5 times]
i add (setq my-use-smex t) but it in init.el but it still doesn't work.I don't know how to fix ti

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, Send me the full output. Besides, double check smex and counsel version you are using.

**Comment by redguardtoo** [comment]
51022b9b use amx instead of smex (Chen Bin)
