### ISSUE TITLE
M-x auto-completion failed

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#757]
While using `M-x` and type some words like `des`, I will get the following result:

![default](https://user-images.githubusercontent.com/40143136/52390066-791d3700-2ad1-11e9-8c34-67d0c4e38683.png)

At this time, I want to use `TAB` to auto-complete the word `describe`, but I failed to do that. 

`M-x describe-key` helps me find out `M-x` has been bound to function `my-M-x`, but this function has no document.

Could you give me some advice on that?

**Comment by redguardtoo** [comment]
Please input `desc` (at least 4 characters). I just use ivy's default setup. You could ask ivy's developer.

**Comment by Ynjxsjmh** [comment]
Thank you, it works fine after inputting 4 characters.
