### ISSUE TITLE
It is complianing about can not find 

### ISSUE THREAD

**Issue by dadongshangu** [redguardtoo/emacs.d#758]
I am following the "optional"way to install the myelpa to ~/projs/myelpa and try the emacs. It complains like below:
-----------------
Warning (initialization): An error occurred while loading ‘/home/xmeng/.emacs.d/init.el’:

File is missing: Opening input file, No such file or directory, /home/xmeng/projs/myelpa/async-1.9.3.tar
----------------
And in the myelpa downloaded following your instruction, there's only async-1.9.2.tar. Just FYI.

Thanks,
Michael

**Comment by redguardtoo** [comment]
Then just use different way. When I'm testing stable setup. Emacs 26.1 is still not released.

**Comment by redguardtoo** [comment]
Check version `2.9`.
