### ISSUE TITLE
how to install other package ?

### ISSUE THREAD

**Issue by JackLovel** [redguardtoo/emacs.d#760]
## 问题
```
我尝试把 helm包 写到 init-elpa.init 中的 mepla-include-packages 函数里，
但是 重新开emacs ，发现helm包没有安装

我尝试过用 package install 去安装 但是没有 helm 包

请问一下如何正确的安装 包？
```

**Comment by redguardtoo** [comment]
See http://ergoemacs.org/emacs/emacs_package_system.html

Or https://melpa.org/#/getting-started

`M-x list-pacakges`

`helm` is there without any setup.

Please note `helm` is not the most solid pacakge in the world. So you need take the risk to install unstable version.

**Comment by JackLovel** [comment]
谢谢 ！！
