### ISSUE TITLE
Make hybrid mode like in Spacemacs

### ISSUE THREAD

**Issue by mrDSide** [redguardtoo/emacs.d#761]
Would be great have ability to edit text in insert mode with standart Emacs keybindings. At the moment need press 'C-z' everhy time and 'C-[' and 'ESC' doesn't works as expected (go back to Normal mode).

**Comment by redguardtoo** [comment]
It's as simple as comment out line containing `init-evil` in `init.el` and `git-pull -r` from my code.

**Comment by mrDSide** [comment]
``` elisp
(evil-define-state emacs
  "Emacs state that can be exited with the escape key."
  :tag " <EE> "
  :message "-- EMACS WITH ESCAPE --"
  :input-method t)

(setq evil-emacs-state-cursor '("Red" bar))

(defadvice evil-insert-state (around emacs-state-instead-of-insert-state activate)
  (evil-emacs-state))

(define-key evil-emacs-state-map (kbd "C-[") 'evil-normal-state)
```

Solved my question.

**Comment by redguardtoo** [comment]
Interesting. I 'm add this to my setup.
