### ISSUE TITLE
syntax highlighting inaccurate

### ISSUE THREAD

**Issue by yuziwen** [redguardtoo/emacs.d#762]
![Screenshot from 2019-04-06 17-39-19](https://user-images.githubusercontent.com/29099600/55667932-65097200-5895-11e9-890e-488c95021ef3.png)
I just began to learn emacs several days ago, but found the syntax highlighting worked not properly on many simple occasions(as the picture shows).  How can I get it right?
I use ubuntu18.04, emacs 26.1

**Comment by redguardtoo** [comment]
I fixed some minor issue.

Syntax warnings might still exist somewhere. Just ignore them.

**Comment by yuziwen** [comment]
By the way, in evil mode, sometimes after I press ESC, it takes about 0.5 second to exit insert mode. Besides, 'k' sometimes takes about 0.5 second to move the cursor up, as if it were a shortcut key prefix, and were waiting for another keystroke. How does that occur?

**Comment by redguardtoo** [comment]
Don't know esc. `k` delay might be `evil-escape-delay`.

I rarely press `esc`, btw. `evil-escape` is more efficient.
