### ISSUE TITLE
How to add my custom evil key bindings?

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#763]
https://github.com/redguardtoo/emacs.d/blob/b0cd5a25bf962f762b9998f35e522786bfa056ab/lisp/init-evil.el#L442

Every time sync your code, it will conflict with my modification. Can the request dynamically add some custom key configuration?

**Comment by redguardtoo** [comment]
`~/.custom.el`

**Comment by peng051410** [comment]
How to ? add-to-list?

**Comment by redguardtoo** [comment]
```
(eval-after-load "evil"
  '(progn
     (my-space-leader-def
       "ss" 'pwd
       "ll" 'pwd
       "pp" 'pwd)))
```

**Comment by peng051410** [comment]
Copy, Thanks a lot.
