### ISSUE TITLE
evil-mode conflict with artist mode?

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#764]
Not sure if you're familiar with artist mode, but when I enabled it per 
[youtube](https://www.youtube.com/watch?reload=9&v=cIuX87Xo8Fc), evil mode seems to disallow painting. I have to manually turn off evil mode and draw something.

**Comment by phye** [comment]
Before draw anything, hitting `c-z` to switch back to emacs mode will do the trick.

**Comment by sethidden** [comment]
https://stackoverflow.com/questions/46513910/emacs-evil-mode-binding-mouse-event

Evil binds mouse drag to something. Perhaps visual mode selection? You just need to unbind it to avoid the <kbd>c-z</kbd> trick
