### ISSUE TITLE
Line wrap in markdown mode

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#765]
When using Emacs to handle markdown file, I find that Emacs treats the markdown file as one-line-per-paragraph style in `markdown mode`. If I switch to `text mode`, Emacs wraps a line that reaches the window width as what I expected.

I searched a lot in Google, but it seems I couldn't find similar problems. Finally I found a hint in [markdown-mode](https://github.com/jrblevin/markdown-mode#github-flavored-markdown-gfm) saying that
> to correspond to hard line breaks--then you may want to enable `visual-line-mode` for line wrapping in buffers

If I enable visual line mode in markdown file, the one-line-per-paragraph style disappears. And that's what I want.

My question is have you faced the one-line-per-paragraph problem using Emacs to handle markdown file? Could you please give me some advice to solve it?

**Comment by redguardtoo** [comment]
I need input table inside  markdown.

See https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-markdown.el#L23

You can always press `C-c C-v` to toggle the flag.

**Comment by Ynjxsjmh** [comment]
That's it, thanks a lot!

**Comment by Ynjxsjmh** [comment]
PS. `C-c C-v` runs the command `hydra-toggle/body` defined in `init-hydra.el` and in the current version it's changed to `C-c C-h`.
