### ISSUE TITLE
打开latex文件编译后卡死

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#767]
打开latex文件后编译，再退出时就卡死了。如果不使用配置则不会卡死。请教怎么回事。
补充：发现问题出现在

OS: Debian testing buster
Emacs: 26.1
注：没有做其它修改，使用的是克隆下来的配置版本。

**Comment by yangdaweihit** [comment]
Debugger entered--Lisp error: (quit)
  sleep-for(0.1)
  (if (and (not done) mustsave) (sleep-for 0.1) (setq done t))
  (while (not done) (if (keyfreq-file-is-unlocked) (progn (keyfreq-file-claim-lock) (if (eq (keyfreq-file-owner) (emacs-pid)) (unwind-protect (progn (keyfreq-table-load table) (let (... ...) (unwind-protect ... ...))) (clrhash table) (setq done t) (keyfreq-file-release-lock))))) (if (and (not done) mustsave) (sleep-for 0.1) (setq done t)))
  (let (done) (while (not done) (if (keyfreq-file-is-unlocked) (progn (keyfreq-file-claim-lock) (if (eq (keyfreq-file-owner) (emacs-pid)) (unwind-protect (progn (keyfreq-table-load table) (let ... ...)) (clrhash table) (setq done t) (keyfreq-file-release-lock))))) (if (and (not done) mustsave) (sleep-for 0.1) (setq done t))))
  (if (> (hash-table-count table) 0) (let (done) (while (not done) (if (keyfreq-file-is-unlocked) (progn (keyfreq-file-claim-lock) (if (eq (keyfreq-file-owner) (emacs-pid)) (unwind-protect (progn ... ...) (clrhash table) (setq done t) (keyfreq-file-release-lock))))) (if (and (not done) mustsave) (sleep-for 0.1) (setq done t)))))
  keyfreq-table-save(#<hash-table equal 11/128 0x1c55059> t)
  keyfreq-mustsave--do()
  kill-emacs()
  save-buffers-kill-emacs(nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)

**Comment by yangdaweihit** [comment]
关掉tex文件buffer后可以正常关闭emacs。

**Comment by redguardtoo** [comment]
Raise a issue at `keyfreq`.

In `keyfreq-table-save`, `(eq (keyfreq-file-owner) (emacs-pid))` is always `t`, so the the loop will never ends.

**Comment by yangdaweihit** [comment]
注释后解决了，非常感谢。

**Comment by redguardtoo** [comment]
Could you give me details how to compile latex? I need reproduce the issue.
