### ISSUE TITLE
evil mode在某些文档中不是初始状态

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#768]
有些文档初始没有设置为evil mode，因为已经习惯了快捷键，打开文档时经常误操作。如果设置，使得所有文档初始设置都是evil mode，还是我的无意设置使然。请指教。

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-evil.el#L249

**Comment by yangdaweihit** [comment]
谢谢。
