### ISSUE TITLE
realgud与evilmode

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#775]
如何让realgud调用的调试器启动时，在源代码窗口中自动关闭evilmode，在退出调试时，又自动打开evilmode呢？

**Comment by redguardtoo** [comment]
search `evil-set-initial-state` in `init-evil.el`

**Comment by yangdaweihit** [comment]
看了下，实在不懂。

**Comment by yangdaweihit** [comment]
(evil-set-initial-state 'python-mode 'emacs)

确实可以实现设想的功能。但替换为`realgud-mode`就不能禁用evil-mode。请问这个方式只能主模式有效？
