### ISSUE TITLE
How to switch cursors between windows？

### ISSUE THREAD

**Issue by JackLovel** [redguardtoo/emacs.d#779]
## 问题：
![ pic](https://raw.githubusercontent.com/JackLovel/excuise-/master/img_store/switch_window_cursosr.png)
```
光标如何从左边的命令行窗口切换到右边窗口，
之前我都是用鼠标进行切换的，因为命令行的窗口 不能执行像( , x 2) 、（,  x  3）之类的快捷键
请问有什么好方法，进行快速切换，比如快捷键 
```

**Comment by redguardtoo** [comment]
`C-x o`.

**Comment by JackLovel** [comment]
谢谢！！

**Comment by Ynjxsjmh** [comment]
Looking at your screenshot, I think you have installed [window-numbering.el](https://github.com/nschum/window-numbering.el), so you can use `M window-number` like `M-1` to switch to specific window. For more methods, you can have a look at redguardtoo's article [Emacs中的完美多窗口操作](https://blog.csdn.net/redguardtoo/article/details/7768233).
