### ISSUE TITLE
R(rename ) does not work  in dired

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#780]
![image](https://user-images.githubusercontent.com/5094958/59662547-c330ca80-91df-11e9-886e-2b0f0170d437.png)

**Comment by redguardtoo** [comment]
Exact steps to reproduct the issue and Emacs, OS details.

**Comment by vipzrx** [comment]
>kk@H7 ~/bin/tg % uname -a
Linux H7 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

   emacs --version
GNU Emacs 27.0.50

M-x dired 
use m to mark a file 111 then i type r to rename the file . the minibuffer output the message shown on the picture above

**Comment by vipzrx** [comment]
i use debian stable (the currunt name is strtech) , i use apt install emacs .the emacs version is too old . how can i use a recent emacs version ?

**Comment by vipzrx** [comment]
emacs -q not load your eamcs.d config , it works!

**Comment by redguardtoo** [comment]
Output of `emacs --version`?

**Comment by redguardtoo** [comment]
725eb918 remove dired+ which conflicts with emacs27. stripe-buffer is removed (Chen Bin)

**Comment by vipzrx** [comment]
% emacs --version
GNU Emacs 27.0.50

**Comment by vipzrx** [comment]
i =git merge= your latest commit . how can i make emacs using your latest code . shoud i run emacs init just like first time to use your code .

**Comment by redguardtoo** [comment]
`git pull https://github.com/redguardtoo/emacs.d.git`
