### ISSUE TITLE
w3m use pac  proxy to visit google

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#781]
i want to use w3m in emacs , how to set up proxy to decide which url should use proxy
http://blog.binchen.org/posts/toggle-http-proxy-in-emacs-w3m.html i finde your code. but i do not how to use it .

in china ,when to use google to search infomation , the proxy is needed . may you add the feather to proxy according the url ?

**Comment by redguardtoo** [comment]
w3m does not support PAC.

I gave up on pac setup one month ago because the Google Chrome dropped support for PAC.

Maybe you can use some proxy relay software? Let me know if you find such software.
