### ISSUE TITLE
[Multiwindow] It will open file in another window  while jumping to symbol

### ISSUE THREAD

**Issue by bernarcio** [redguardtoo/emacs.d#782]
**Symptom:**
Window vertically split, upper as A, and lower as B,
Source code in window A, if using (, g t) to jump to the symbol, it will display in window B, and if jumping again, everything will only happen in window B, unless you open other file in window A.

So the question is, how to prevent it from jumping to another window? Because that window is supposed to be used for note-taking, or something like that.

Thanks a lot!

**Comment by redguardtoo** [comment]
I can't reproduce the issue. `,gt` corresponds to `counsel-gtags-dwim` from https://github.com/syohex/emacs-counsel-gtags 

Report bug to its author.

**Comment by bernarcio** [comment]
tks, will close it
