### ISSUE TITLE
[gtags] counsel-gtags-find-symbol does not work

### ISSUE THREAD

**Issue by bernarcio** [redguardtoo/emacs.d#783]
Using (, g r) to find a symbol, it only pops up a list beginning from A, but cannot actually find the symbol.
and the command counsel-gtags-find-reference cannot work either: (match required)

but using global in eshell-command can find the symbol/reference.1

**Comment by redguardtoo** [comment]
Use `counsel-gtags-find-reference` instead.  It looks it's counsel-gtags issue. Report to its original developer.

**Comment by bernarcio** [comment]
counsel-gtags-find-reference cannot work either at my end(stable version)

**Comment by bernarcio** [comment]
close it and report to original developer
thanks!

**Comment by redguardtoo** [comment]
Make sure you have installed `GNU Global` and executable `gtags` is added into environment variable `PATH`. When creating tags file first time, select `native`.
