### ISSUE TITLE
error: Package ‘amx-’ is unavailable

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#784]
Warning (initialization): An error occurred while loading ‘c:/Users/kk/AppData/Roaming/.emacs.d/init.el’:

error: Package ‘amx-’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

This is GNU Emacs 26.2 (build 1, x86_64-w64-mingw32)
 of 2019-04-13
Copyright (C) 2019 Free Software Foundation, Inc.

**Comment by vipzrx** [comment]
win7 x64 chinese 旗舰版本

**Comment by redguardtoo** [comment]
The melpa is shutdown, maybe?
