### ISSUE TITLE
Line wrap problem when adding space between Chinese and English in Org mode

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#785]
There is a discussion on emacs-china [中英文混排时候的自动折行？](https://emacs-china.org/t/topic/2616).

And `Chunyang Xu` reported [a bug](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29364). 

Some examples given in his bug report:

```
For example, here is some Chinese text:

文字文字 English 文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字。

in Emacs, turn on Word Wrap via M-x visual-line-mode and adjust window
width (e.g., 87), Emacs displays it as:

---------------------------------------------------------------------------------------
文字文字 English
文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字。
---------------------------------------------------------------------------------------

but it should display:

---------------------------------------------------------------------------------------
文字文字 English 文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文
字文字文字文字文字。
---------------------------------------------------------------------------------------
```

His explanation is on <https://emacs-china.org/t/topic/2616/12> :

> Visual Line Mode / Word Wrap 不支持中文（CJK），中文和英文（Latin）的断行规则不同。 

> Emacs 的断行规则里预设了「空格处断行」，没考虑过 CJK 的情况。所以这可以当作一个 Bug，TODO 需要有人提交一个 Bug Report。

Do you have some good solution for that?

**Comment by redguardtoo** [comment]
Seems it's better to solve the issue in C instead of Lisp because Lisp is too slow.
