### ISSUE TITLE
"Not Connected" issue with slime-mode

### ISSUE THREAD

**Issue by gehancoder** [redguardtoo/emacs.d#786]
Hi, i just updated the repository yesterday night on my Deepin OS which install in virtual box. And when I tried out SLIME, but it is not working. When I do C-c C-c, I get an error message that says "Not connected.". The slime has been installed. Please help to figure out. Thanks.

I will update the repository later on Ubuntu OS and confirm this issue.

**Comment by redguardtoo** [comment]
e7b17cd0 slime setup (Chen Bin)

**Comment by gehancoder** [comment]
thanks, it works.
