### ISSUE TITLE
my-gclip和my-pclip函数内容是否有些问题？

### ISSUE THREAD

**Issue by LOVEXUE** [redguardtoo/emacs.d#791]
`(and win64-clip-program (memq system-type '(gnu gnu/linux gnu/kfreebsd)))`
及
`(and (memq system-type '(gnu gnu/linux gnu/kfreebsd)) powershell-program)`

`win64-clip-grogram`和`powershell-program`分别为win下的clip.exe和powershell.exe程序

在(gnu gnu/linux gnu/kfrebsd)下应该不存在？

**Comment by redguardtoo** [comment]
WSL emacs with GUI.

Windows GUI emacs could access clipboard API directly.

**Comment by LOVEXUE** [comment]
thx;
