### ISSUE TITLE
Aspell 0.60.8 will have better typo corrections.

### ISSUE THREAD

**Issue by kevina** [redguardtoo/emacs.d#795]
I found your blog post and also noticed this line in the README.

> I recommend aspell for programmers. Non-programmers find hunspell is better on typo correction

and thought you would like to know that I tweaked the scoring of suggestions so that typos will get a lower score and thus appear first.  It was merged in https://github.com/GNUAspell/aspell/pull/559 and will appear in Aspell 0.60.8.  You can try it out now with the latest snapshot available at http://aspell.net.

**Comment by redguardtoo** [comment]
sure. thank you. I will definitely try it.
