### ISSUE TITLE
start emacs26.3 error

### ISSUE THREAD

**Issue by ghost** [redguardtoo/emacs.d#798]
Debugger entered--Lisp error: (error "Need package ‘let-alist-1.0.6’, but only 1.0.5 is available")
  signal(error ("Need package ‘let-alist-1.0.6’, but only 1.0.5 is available"))
  error("Need package `%s-%s', but only %s is available" let-alist "1.0.6" "1.0.5")
  package-compute-transaction((#s(package-desc :name package-lint :version (20191010 2146) :summary "A linting library for elisp package authors" :reqs ((cl-lib (0 5)) (emacs (24 1)) (let-alist (1 0 6))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "7780c3f95db6626d0ec04b71c1950bcad70da29a") (:keywords "lisp") (:authors ("Steve Purcell" . "steve@sanityinc.com") ("Fanael Linithien" . "fanael4@gmail.com")) (:maintainer "Steve Purcell" . "steve@sanityinc.com") (:url . "https://github.com/purcell/package-lint")) :signed nil)) ((cl-lib (0 5)) (emacs (24 1)) (let-alist (1 0 6))) (#s(package-desc :name package-lint :version (20191010 2146) :summary "A linting library for elisp package authors" :reqs ((cl-lib (0 5)) (emacs (24 1)) (let-alist (1 0 6))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "7780c3f95db6626d0ec04b71c1950bcad70da29a") (:keywords "lisp") (:authors ("Steve Purcell" . "steve@sanityinc.com") ("Fanael Linithien" . "fanael4@gmail.com")) (:maintainer "Steve Purcell" . "steve@sanityinc.com") (:url . "https://github.com/purcell/package-lint")) :signed nil)))
  package-compute-transaction(nil ((package-lint)))
  package-install(package-lint)
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(package-lint)

**Comment by lkzz** [comment]
me too

**Comment by redguardtoo** [comment]
9ddd122e ugprade let-alist (Chen Bin)

**Comment by gdperson** [comment]
this error still have from china

**Comment by redguardtoo** [comment]
fixed

**Comment by edipofederle** [comment]
Still here. Just clone the repo.

**Comment by redguardtoo** [comment]
f4df861e remove package-lint which has dependency on let-alist 1.0.6 (Chen Bin)
