### ISSUE TITLE
My-git-log-trace-definition line number error

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#799]
When selecting the last few lines of a file ending with a blank line(\n), run my-git-log-trace-definition(, g l), will get error like this:

> fatal: file /path/to/file has only 233 lines

Actual run command is:

> git log -L200,234:/path/to/file

It seems that Emacs counts the blank line at the end of the file.

**Comment by redguardtoo** [comment]
c75f876f fix git log trace definition (Chen Bin)

**Comment by BlacAmDK** [comment]
When use "V" to select only one line, this function use whole line as git funcname. I made some minor changes to fix this.
