### ISSUE TITLE
comint-password-prompt-regexp error

### ISSUE THREAD

**Issue by BrianLv** [redguardtoo/emacs.d#801]
An error occurred Symbol's value as variable is void: comint-password-prompt-regexp

**Comment by redguardtoo** [comment]
step to reproduce the issue?

**Comment by redguardtoo** [comment]
f0f7196c optimize comint configuration (Chen Bin)

Usually it's not a problem. When you start REPL, `comint` is always loaded. if it's not loaded, the original setup just define a free variable. 

Anyway, it doesn't hurt to do some optimization.

**Comment by BrianLv** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Thanks
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                brian.lv
                            
                    
                        
                            
                                    brian.lv@outlook.com
                            
                        
                
            
        
        
    
    
 
    

    On 11/27/2019 14:36，Chen Bin<notifications@github.com> wrote： 


f0f7196 optimize comint configuration (Chen Bin)
Usually it's not a problem. When you start REPL, comint is always loaded. if it's not loaded, the original setup just define a free variable.
Anyway, it doesn't hurt to do some optimization.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
