### ISSUE TITLE
Failed to create tags file.

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#802]
I was using your setup recently. It is a good new experience to use emacs. However, recently I found I suddenly could not use the `counsel-etags-scan-code`, it returns a error messge

>>  Failed to create tags file.

I was playing with spacemacs just before that and tried the spacemacs' gtags layer. So I installed gnu global, add the environment variable `GTAGSLABEL` and used the configure file `gtags.conf` provided with the source code of gnu global.

After that I found I could not use `counsel-etags-sacn-code` when I switch back to your setup. I thought I messed something up maybe on the os level. I reinstalled my linux system. By the way, I am using windows subsystem for linux(WSL). I reinstalled emacs 26.3 and universal ctags from source code. However I could not use that command. It still returns the same error message.

I looked at the source code, but I know nothing about elisp or any kind of lisp. I tried to switch to debug mode and print out  some additional message but they do not seemed helpful. I will post them here.

I am using WSL ubuntu, emacs 26.3, and universal ctags.

Here is all the information I could gathered:
[temp.txt](https://github.com/redguardtoo/emacs.d/files/3887166/temp.txt)

Could you tell me how could I figure out actually what went wrong? Thanks.

By the way the ctags is visible in the PATH.

>> Universal Ctags 0.0.0(8b7c636d), Copyright (C) 2015 Universal Ctags Team
>> Universal Ctags is derived from Exuberant Ctags.
>> Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
>>   Compiled: Nov 25 2019, 08:54:03
>>   URL: https://ctags.io/
>>   Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc

**Comment by drcxd** [comment]
I tried to run the command output when debug is turned on. It seems that the command failed because I did not have a `.ctags` file in my home directory. I created a empty one and then the command succeeded. This confused me. Because I run this command well and I did not have a .ctags file before. Do you have any idea if there is something going wrong?

**Comment by redguardtoo** [comment]
OK, it's counsel-etags issue. I will try to fix it

**Comment by redguardtoo** [comment]
c8eeabfc ~/.ctags might be missing (Chen Bin)

**Comment by drcxd** [comment]
This fixed the problem, thank you.
