### ISSUE TITLE
Error enabling Flyspell mode: (stringp nil)

### ISSUE THREAD

**Issue by include-yy** [redguardtoo/emacs.d#804]
My OS is win10.
When I open Emacs, it always display a message :

Starting new Ispell process nil with default dictionary...
Error enabling Flyspell mode:
(stringp nil)

This is GNU Emacs 26.3 (build 1, x86_64-w64-mingw32)

**Comment by redguardtoo** [comment]
6e31002a wucuo-start will not start flyspell-mode automatically (Chen Bin)

**Comment by include-yy** [comment]
It works, thanks a lot!
