### ISSUE TITLE
how to remove the margin in the top

### ISSUE THREAD

**Issue by blurhead** [redguardtoo/emacs.d#805]
when emacs is open, there is always margin between the top of window and the screen edge, where can i set the margin

**Comment by redguardtoo** [comment]
can you show me the screenshot? besides, what's your environment?

**Comment by blurhead** [comment]
ubuntu 18.04 using kde 
![Screenshot_20191225_155904](https://user-images.githubusercontent.com/26830473/71438166-97167900-272f-11ea-8801-d2c5beeef582.png)

**Comment by redguardtoo** [comment]
It has nothing to do with the setup. It's Emacs own problem or windows manager's problem. I use i3 and there is bottom tool bar, so there is always margin at bottom. The only solution is make Emacs full screen.

**Comment by blurhead** [comment]
I fix it using kde's windows manager, hope it will help someone else
