### ISSUE TITLE
Regarding configuring other packages

### ISSUE THREAD

**Issue by li012589** [redguardtoo/emacs.d#806]
Hi, thanks for the amazing configs.

I have some questions about configuring other packages from MELPA. I didn't see docs describing it in your repo, so I thought I might just ask.

In my understanding, to configure a package based on your config files, one has to add a `(require-package 'PKGNAME)` and add it to `melpa-include-packages` in file `\lisp\init-elpa.el`. Then create an `init-` file at folder `\lisp` and require this file at `init.el`. And for short-keys, add them to `\lisp\init-evil.el`. Am I doing it right?

**Comment by redguardtoo** [comment]
I updated README.

**Comment by li012589** [comment]
Thanks!
