### ISSUE TITLE
Error when start-up, seems related to the theme

### ISSUE THREAD

**Issue by JMwill** [redguardtoo/emacs.d#809]
![image](https://user-images.githubusercontent.com/11496449/73165973-dcafd280-412f-11ea-906f-0e3e83ed65e4.png)
Cannot open Emacs after pull master.
I am not familiar with the lisp, please help me!

**Comment by redguardtoo** [comment]
Sorry, fixed. `git reset --hard HEAD^^`, then pull again.

**Comment by JMwill** [comment]
Perfect! Everything works well, Thanks for your help.
