### ISSUE TITLE
输入middle dot

### ISSUE THREAD

**Issue by yangdaweihit** [redguardtoo/emacs.d#810]
今天在Emacs中工作时需要输入middel dot，即` · `，查了一下，按照[How to insert the Interpunct character in ubuntu?](https://askubuntu.com/questions/236974/how-to-insert-the-interpunct-character-in-ubuntu)上的方式没有实现，但在终端中却可以实现。
可否请您帮我研究一下，如何能够在您的配置下实现这个符号的输入。感谢在先。

**Comment by redguardtoo** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/184553/73800500-0a220d80-480d-11ea-994f-f562820bafec.png">

Or just use yasnippet.

**Comment by yangdaweihit** [comment]
感谢
