### ISSUE TITLE
关于配置python

### ISSUE THREAD

**Issue by xiaojidan** [redguardtoo/emacs.d#814]
我是Mac上安装的，emacs界面上只有Emacs这个选项，其他都没有，和您那边也是一样的吗？我是直接拉的您的emacs.d文件
并且运行（c-c p）python代码后出现这个错误 

<img width="744" alt="截屏2020-03-01下午8 24 12" src="https://user-images.githubusercontent.com/3738833/75625658-34dc6780-5bfb-11ea-800c-9e43707e2466.png">

<img width="744" alt="截屏2020-03-01下午8 24 12" src="https://user-images.githubusercontent.com/3738833/75625632-fb0b6100-5bfa-11ea-8d51-864e3d867800.png">

**Comment by redguardtoo** [comment]
`C-h k` 然后按 `C-c p` 我想知道对应的command是什么。

menubar, toolbar都被我关掉了。
![image](https://user-images.githubusercontent.com/184553/75638348-947c5680-5c7f-11ea-8d7c-d1aac7a85371.png)

想成为高手的话，menubar和toolbar都必须不用，要养成这个习惯。替代方法就是直接输入并执行文本文件操作命令。甚至除了我列出的重要命令外，其他次要命令的快捷键都不应该用。

建议从开头的VSCode一章开始读起，仔细体会其含义，我教程没那么简单的。不要直接从Emacs一章开始。很多重要的技术可放在Emacs一章或放在VSCode一章，我一般都放在VSCode，因为可以照顾大多数人。

**Comment by xiaojidan** [comment]
好的 好的 谢谢您。 我了解了
