### ISSUE TITLE
failed to start iedit-mode

### ISSUE THREAD

**Issue by Eason0210** [redguardtoo/emacs.d#819]
@redguardtoo , when I  Space-s e  to start iedit-mode, it failed with the error as below,

`command-execute: Wrong type argument: commandp, evil-iedit-state/iedit-mode `
I found that the iedit-mode alone worked well, may be there is something wrong in the evil-iedit-state package.

```
(defun evil-iedit-state/iedit-mode (&optional arg)
  "Start `iedit-mode'."
  (interactive "P")
  (if (fboundp 'ahs-clear) (ahs-clear))
  (iedit-mode arg)
  (evil-iedit-state))
```

emacs 26.3
windows 10 pro

**Comment by redguardtoo** [comment]
9d865597 make evil-iedit-state builtin (Chen Bin) 
I re-bind its command to `<SPC>rr` because its should be used more frequently.

**Comment by Eason0210** [comment]
Now it work well, thanks for your quick help.
