### ISSUE TITLE
How to use copy/paste to system clipboard without evil-mode?

### ISSUE THREAD

**Issue by zwpdbh** [redguardtoo/emacs.d#824]
The init-clipboard.el is tightly coupled with evil-mode. 
Could we use emacs default key-bindings to do copy/paste to system clipboard?

**Comment by redguardtoo** [comment]
Yes, you could define your own key bindings but Emacs does not have default key binding for system clipboard.

Besides, `init-clipboard.el` is not coupled with evil-mode, its code could run without evil mode.
