### ISSUE TITLE
26.3 startup error in windows10

### ISSUE THREAD

**Issue by xiaotingHuang** [redguardtoo/emacs.d#825]
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`https?:" nil nil)
  package-install-from-archive(#s(package-desc :name nadvice :version (0 3) :summary "Forward compatibility for Emacs-24.4's nadvice" :reqs nil :kind single :archive "gnu" :dir nil :extras ((:url . "http://elpa.gnu.org/packages/nadvice.html") (:authors ("Stefan Monnier" . "monnier@iro.umontreal.ca")) (:maintainer "Stefan Monnier" . "monnier@iro.umontreal.ca")) :signed nil))
  mapc(package-install-from-archive (#s(package-desc :name nadvice :version (0 3) :summary "Forward compatibility for Emacs-24.4's nadvice" :reqs nil :kind single :archive "gnu" :dir nil :extras ((:url . "http://elpa.gnu.org/packages/nadvice.html") (:authors ("Stefan Monnier" . "monnier@iro.umontreal.ca")) (:maintainer "Stefan Monnier" . "monnier@iro.umontreal.ca")) :signed nil) #s(package-desc :name async :version (1 9 3) :summary "Asynchronous processing in Emacs" :reqs ((cl-lib (0 5)) (nadvice (0 3))) :kind tar :archive "gnu" :dir nil :extras ((:url . "https://github.com/jwiegley/emacs-async") (:maintainer "John Wiegley" . "jwiegley@gmail.com") (:authors ("John Wiegley" . "jwiegley@gmail.com")) (:keywords "async")) :signed nil)))
  package-download-transaction((#s(package-desc :name nadvice :version (0 3) :summary "Forward compatibility for Emacs-24.4's nadvice" :reqs nil :kind single :archive "gnu" :dir nil :extras ((:url . "http://elpa.gnu.org/packages/nadvice.html") (:authors ("Stefan Monnier" . "monnier@iro.umontreal.ca")) (:maintainer "Stefan Monnier" . "monnier@iro.umontreal.ca")) :signed nil) #s(package-desc :name async :version (1 9 3) :summary "Asynchronous processing in Emacs" :reqs ((cl-lib (0 5)) (nadvice (0 3))) :kind tar :archive "gnu" :dir nil :extras ((:url . "https://github.com/jwiegley/emacs-async") (:maintainer "John Wiegley" . "jwiegley@gmail.com") (:authors ("John Wiegley" . "jwiegley@gmail.com")) (:keywords "async")) :signed nil)))
  package-install(async)
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(async)
  eval-buffer(#<buffer  *load*-680298> nil "c:/Users/Administrator/AppData/Roaming/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 7567
  load-with-code-conversion("c:/Users/Administrator/AppData/Roaming/.emacs.d/lisp/init-elpa.el" "c:/Users/Administrator/AppData/Roaming/.emacs.d/lisp/init-elpa.el" t t)
  load("c:/Users/Administrator/AppData/Roaming/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "~/.emacs.d/lisp/%s" pkg)) t t))
  (if (or (not maybe-disabled) (not (boundp (quote startup-now)))) (progn (load (file-truename (format "~/.emacs.d/lisp/%s" pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init (quote init-autoload)) (require-init (quote init-modeline)) (require-init (quote init-utils)) (require-init (quote init-file-type)) (require-init (quote init-elpa)) (require-init (quote init-exec-path) t) (require-init (quote init-spelling) t) (require-init (quote init-gui-frames) t) (require-init (quote init-uniquify) t) (require-init (quote init-ibuffer) t) (require-init (quote init-ivy)) (require-init (quote init-hippie-expand)) (require-init (quote init-windows)) (require-init (quote init-markdown) t) (require-init (quote init-javascript) t) (require-init (quote init-org) t) (require-init (quote init-css) t) (require-init (quote init-python) t) (require-init (quote init-lisp) t) (require-init (quote init-elisp) t) (require-init (quote init-yasnippet) t) (require-init (quote init-cc-mode) t) (require-init (quote init-gud) t) (require-init (quote init-linum-mode)) (require-init (quote init-git) t) (require-init (quote init-gtags) t) (require-init (quote init-clipboard)) (require-init (quote init-ctags) t) (require-init (quote init-bbdb) t) (require-init (quote init-gnus) t) (require-init (quote init-lua-mode) t) (require-init (quote init-workgroups2) t) (require-init (quote init-term-mode) t) (require-init (quote init-web-mode) t) (require-init (quote init-company) t) (require-init (quote init-chinese) t) (require-init (quote init-keyfreq) t) (require-init (quote init-httpd) t) (require-init (quote init-theme) t) (require-init (quote init-essential)) (require-init (quote init-misc) t) (require-init (quote init-emacs-w3m) t) (require-init (quote init-shackle) t) (require-init (quote init-dired) t) (require-init (quote init-writting) t) (require-init (quote init-hydra)) (require-init (quote init-evil)) (require-init (quote init-ediff)) ...)
  eval-buffer(#<buffer  *load*> nil "c:/Users/Administrator/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 6609
  load-with-code-conversion("c:/Users/Administrator/AppData/Roaming/.emacs.d/init.el" "c:/Users/Administrator/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/Administrator/AppData/Roaming/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000baab9>)()
  command-line()
  normal-top-level()

**Comment by xiaotingHuang** [comment]
now I have used stable-version, it's ok thank u

**Comment by redguardtoo** [comment]
I tested with my latest setup. can't reproduce the issue. Maybe it's you install some package dependent on  `nadvice`. I don't use nadvice directly or in-directly.

**Comment by xiaotingHuang** [comment]
thank u





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Bin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 上午7:55
收件人:&nbsp;"redguardtoo/emacs.d"<emacs.d@noreply.github.com&gt;;
抄送:&nbsp;"Da Vinci"<21443415@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [redguardtoo/emacs.d] 26.3 startup error in windows10 (#825)





 
I tested with my latest setup. can't reproduce the issue. Maybe it's you install some package dependent on  nadvice. I don't use nadvice directly or in-directly.
