### ISSUE TITLE
couldn't find counsel-etags-find-ctags

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#828]
In README, you say

> Run `M-x counsel-etags-find-ctags` from `counsel-etags` to navigate code. 

However [searching `counsel-etags-find-ctags` in your counsel-etags](https://github.com/redguardtoo/counsel-etags/search?q=counsel-etags-find-ctags&unscoped_q=counsel-etags-find-ctags), nothing is matched.

**Comment by redguardtoo** [comment]
https://github.com/redguardtoo/counsel-etags#usage
