### ISSUE TITLE
File mode error when opening .tex file

### ISSUE THREAD

**Issue by fenguoerbian** [redguardtoo/emacs.d#829]
OS: Ubuntu 18.04
Emacs: 25.2
Emacs.d: git version, commit 83fa2b

When opening a .tex file, emacs reports an error
```
File mode specification  error:(void-variable comint-terminfo-terminal)
```

With the help of `--debug-init`I think it roots from the call `native-complete-setup-bash` in `list/init-term-mode.el`.

This `comint-terminfo-terminal` seems to be introduced in Emacs 26 and defaults to "dumb" for backward compatibility. Since I'm using Emacs 25.2, I add
```
(setq comint-terminfo-terminal "dumb")
```
before the `native-complete-setup-bash` call. Then the problem seems to be solved.

**Comment by redguardtoo** [comment]
b431b8cc compatible with emacs25 (Chen Bin)

**Comment by fenguoerbian** [comment]
Thanks~
