### ISSUE TITLE
how to control backup files(*~ and *.orig) when using ediff mergetool?

### ISSUE THREAD

**Issue by john-Ly** [redguardtoo/emacs.d#832]
http://blog.binchen.org/posts/emacs-is-the-best-merge-tool-for-git.html
thank for that amaing tool.

I checked that:
1. autosave files (\~num~) will store in ~/.backup
2. *.orig, introduced by git, can be turned off in .gitconfig files or [manually clean](https://stackoverflow.com/questions/1251681/git-mergetool-generates-unwanted-orig-files)

but, i have no idea about *~ files(like vim's backup files, may be evil)
can you share the better way to deal with these backup files? thx~

**Comment by redguardtoo** [comment]
279542a2 git merge tool could produce lots of backup files (Chen Bin)

**Comment by john-Ly** [comment]
backup files gone. It's great.

Now, another trouble:
when git pull the latest commit, emacs will suck at connecting elpa.org, so i switch to tag 3.1(It works) and cherry-pick that commit.
But i am ok with tag 3.1 and will not sycn eagerly.

os: manjaro
emacs: 26.3
my .custom.el file:
```
(setq package-archives
      '(("localelpa" . "~/.emacs.d/localelpa/")
        ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
        ("melpa-stable" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa-stable/")
        ))

git branch -v
* master  b234456d [ahead 1, behind 15] git merge tool could produce lots of backup files
```

**Comment by redguardtoo** [comment]
Start emacs at least once, it will install flymake-shellchek automatically. Then you can keep using emacs as normal
