### ISSUE TITLE
Flymake-shellcheck with Emacs 25

### ISSUE THREAD

**Issue by fenguoerbian** [redguardtoo/emacs.d#833]
[Flymake-shellcheck in elpa requires Emacs 26.](https://github.com/federicotdn/flymake-shellcheck) Is there a work-around for Emacs 25?

**Comment by redguardtoo** [comment]
b60db469 flymake-shellcheck requires emacs 26 (Chen Bin)

You need ask the original author to support emacs 25

**Comment by fenguoerbian** [comment]
Thanks~
