### ISSUE TITLE
[feature request] evil escape with IME

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [redguardtoo/emacs.d#834]
Hi,

Just a thought. Would be convenient to have evil-escape on while IME is active.
Saves `c-\` keystroke before `kj`.

Any possibilities?

Thanks

**Comment by redguardtoo** [comment]
You need contact IME authors first. At minimum they need have provide,
- a hook after intercepting keyboard input
- inside hook, user could quit ime and switch evil state

See `evil-escape-pre-command-hook` in evil-escape for details

**Comment by Inc0ns1st3nt** [comment]
Thanks for the comments. Will look into `pyim` instead.
