### ISSUE TITLE
No more buttons to interact with

### ISSUE THREAD

**Issue by Chuxclub** [redguardtoo/emacs.d#835]
Hi!

First I'd like to thank you for this setup of emacs which I find very useful. I've also installed Smex which is an awesome addition. There's just one thing I wanted to know: is the fact that all the buttons have been removed normal? Let me show you with this picture:

My Emacs:
![Screenshot from 2020-04-27 12-46-56](https://user-images.githubusercontent.com/37174180/80365512-0213c000-8888-11ea-950f-50ac6de1ccbe.png)

Default Emacs: 
![teaser](https://user-images.githubusercontent.com/37174180/80365585-21aae880-8888-11ea-9663-e77437b42b04.png)

As you can see at the top of the default Emacs window there are a bunch of buttons which are now missing in my Emacs.

Note: I'm on Ubuntu 20.04LTS, I use Emacs 26.3.

If this is a bug and you need more information I'll be glad to give them to you. If this is a normal behaviour, well I'll get used to it (I barely used them anyway).

Thank you very much for your time and attention!

Best regards

**Comment by redguardtoo** [comment]
You could add below code into `~/.custom.el` to restore toolbar and menubar,
```lisp
(tool-bar-mode 1)
(menu-bar-mode 1)
```
Actually you can override any existing setup in `~/.custom.el`.

**Comment by Chuxclub** [comment]
Thank you very much for your answer and your awesome setup. I'm actually really getting the hang of it.

Best regards!
