### ISSUE TITLE
Add support to Chemacs?

### ISSUE THREAD

**Issue by lyq0930** [redguardtoo/emacs.d#836]
Hi, I'm wondering if it's possible to add support to https://github.com/plexus/chemacs, so that I could download your config and try it without losing my current setup.

It's currently complaining about
```
-Lisp error: (void-function my-add-subdirs-to-load-path)
  (my-add-subdirs-to-load-path "~/.emacs.d/site-lisp/")
```
with my Chemacs setting:
```
(("redguardtoo" . ((user-emacs-directory . "~/.redguardtoo-emacs.d"))))
```

Not sure if it's because my Chemacs setting is incorrectly or something else.

**Comment by redguardtoo** [comment]
884fb7a3 use user-emacs-directory instead of ~/.emacs.d (Chen Bin)

**Comment by lyq0930** [comment]
Thanks @redguardtoo , confirmed it worked perfectly.
