### ISSUE TITLE
[help] swiper skips replacing matches if replacement is an empty string on 'y'

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [redguardtoo/emacs.d#838]
## Issue
I had tried at an issue at swiper https://github.com/abo-abo/swiper/issues/2566 already.

### Their response
> I just tested that it still works. Please try to reproduce with make plain.

## My questions:
Previously I was able replace matches with empty string, effectively deleting them, but not anymore.

Is there any configuration that comes to your mind to tweak this behavior?

emacs version: 26.3

**Comment by redguardtoo** [comment]
I need exact steps to reproduce the issue.

**Comment by Inc0ns1st3nt** [comment]
Apology for the inconvenience, if you refer the steps how I encounter the issue, it is as follows:

1. `C-s` to get `swiper` up
2. enter text to match
3. `M-q` to activate `swiper-query-replace`
4. press enter to enter empty string for replacement
5. Now press `y` to replace the string with replacement

While listing the steps, I figured the query replace stage have some interesting placeholder text: 
> \,(concat \&)

Which evaluates to the search string entered in step 2. And if `\,(concat)` is entered as replacement, the matches can be replace by empty string. How can the placeholder text be configured?

**Comment by redguardtoo** [comment]
I'm using stable version swiper `0.13.0`. You could upgrade to unstable verison of swiper, see `init-elpa.el`. 
`,(concat \&)` is hint from swiper that you could input elisp code to do the replace.

I don't use this feature from swiper. Instead, I use evil.  Select a text or just move cursor in the word, then press `,rb`.

**Comment by Inc0ns1st3nt** [comment]
That is a very handy shortcut. Tho using swiper to replace might be slower compare to using evil, I do prefer how it would give an overview to all matches, and control over which to replace and not.
But thanks, I should know where to look into.
