### ISSUE TITLE
Error message about auto save and ispell

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#841]
I have not installed aspell or hunspell. But there always some error message pops up about them.

The first one is `Error running timer 'auto-save-buffers': (wrong-type-argument stringp nil)`.

The second is 

```
Starting new Ispell process nil with default dictionary..
ispell-check-version: Wrong type argument: stringp, nil
```
They pop up usually after save/auto save. Is there any way fix them or at least suppress them?

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/83829550-744caf80-a726-11ea-827a-7099334653ab.png)

Can't reproduce the issue. 

Please `M-x toggle-debug-on-error` and reproduce the issue. Send me the error message.

**Comment by drcxd** [comment]
[err.txt](https://github.com/redguardtoo/emacs.d/files/4742378/err.txt)

**Comment by redguardtoo** [comment]
Try the latest version, btw, what's the value of `ispell-program-name`?

**Comment by drcxd** [comment]
The value of `ispell-program-name` is `nil`. After I update to the latest version, the issue is gone.
