### ISSUE TITLE
[feature request] allow setting line number to relative

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [redguardtoo/emacs.d#842]
in your init-linum-mode.el
```
(defun display-line-numbers-mode-hook-setup ()
    (setq display-line-numbers (if (or (memq major-mode linum-mode-inhibit-modes-list)
                                       ;; don't show line number for certain file extensions
                                       (should-use-minimum-resource))
                                   nil
                                 t)))
```
this function governs the display-line-numbers, and overrides this crucial variable to `t` or `nil`.
Which prevents it to be set to `'relative` to enable relative line numbers.

My idea would be, if possible, add a variable accessible by both the users and the function, and be used in place of the `t`.  

Also, because ur `defun` is inside a `cond`, my suggestion is to use `labels` instead to create a local binding, since `defun` defines a global function, this is true for commonlisp, I am not too sure for elisp. However, i do think using `labels` for local function bindings is a better style.

**Comment by Inc0ns1st3nt** [comment]
actually, it seems that in customize, setting both `display-line-numbers` & `display-line-numbers-type` to relative does take effects

**Comment by redguardtoo** [comment]
Yes, all the set up could be overrode in `~/.custom.el`. I'll have a look at this relative line number thing, though. Never use it before.
