### ISSUE TITLE
ispell-phaf: No matching entry for hunspelldict in ‘ispell-hunspell-dict-paths-alist’.

### ISSUE THREAD

**Issue by moxuetianya** [redguardtoo/emacs.d#843]
当我修改为使用hunspell纠错是，会报错；
操作信息如题目描述：
         ispell-phaf: No matching entry for hunspelldict in ‘ispell-hunspell-dict-paths-alist’.

修改了my-force-to-use-hunspell t； 显示错误
index 12efb4b..79a8e7e 100644
--- a/lisp/init-spelling.el
+++ b/lisp/init-spelling.el
@@ -128,7 +128,8 @@ Please note RUN-TOGETHER makes aspell less capable.  So it should be used in `pr
 ;; hunspell searches a dictionary named "en_US" in the path specified by
 ;; `$DICPATH' by default.

-(defvar my-force-to-use-hunspell nil
+(defvar my-force-to-use-hunspell t
   "Force to use hunspell.  If nil, try to detect aspell&hunspell.")

**Comment by redguardtoo** [comment]
Thanks. I updated code,

In your `~/.custom.el`, you could add below code,
```
(setq my-force-to-use-hunspell t)
(my-configure-ispell-parameters)
```

**Comment by moxuetianya** [comment]
更新配置后，在~/.custom.el 配置hunspell后，company有这个样的错误提示
`Company-Ispell: lookup-words error: No plain word-list found at systemdefault locations.  Customize ‘ispell-alternate-dictionary’ to set yours.`
还需要添加其他文件吗？

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/emacs.d/blob/82924e453ee8b1f826db671a5b364069208d0178/lisp/init-company.el#L99 

My emacs  works perfect.

You know `ispell-alternate-dictionary` is "*plain word-list* dictionary for spelling help", right?

**Comment by moxuetianya** [comment]
好的，以前没用过ispell，现在可以了
