### ISSUE TITLE
C语言的tab缩进总是2

### ISSUE THREAD

**Issue by zqyzsj** [redguardtoo/emacs.d#846]
我在lisp/init-cc-mode.el中sh设置tab为8，但是没有起作用，我的配置如下。请问如何配置能够设置tab=8，并缩进为tab。
  (setq tab-width 8)
  (setq indent-tabs-mode t)
  (setq c-basic-offset 8)

**Comment by redguardtoo** [comment]
315495ee set c-basic-offset out of mode hook (Chen Bin)

In `~/.custom.el`, use `(setq-default whatever-var whatever-val)`.

**Comment by TEE-OS** [comment]
不论是放在.custom.el还是lisp/init-elpa.el，都不工作。

**Comment by redguardtoo** [comment]
It's better to delete `~/.emacs`

**Comment by TEE-OS** [comment]
But it does not work if I set it in init.el.

**Comment by redguardtoo** [comment]
It works on my computer:
![image](https://user-images.githubusercontent.com/184553/85488293-672e2c80-b611-11ea-957d-b2ff77558d04.png)

I've grepped my `.emacs.d`, no tab related code is found. Maybe it's your own configuration.

Please double check my README.

**Comment by Mastize** [comment]
I have exactly the same problem with @TEE-OS  on stable version, setq-default solve the problem after I update to newest version
