### ISSUE TITLE
How to add tide mode to config

### ISSUE THREAD

**Issue by karta0807913** [redguardtoo/emacs.d#849]
greetings, I want to write typescript with tide server with this configure into `lisp/init-javascript.el`.
I am using GNU Emacs 28.0.50, and the latest commit 5f8d28a

```lisp
(defun setup-tide-mode ()
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  ;; company is an optional dependency. You have to
  ;; install it separately via package-install
  ;; `M-x package-install [ret] company`
  (company-mode +1))

(add-hook 'before-save-hook 'tide-format-before-save) ;; mark this line to get weird result
(add-hook 'typescript-mode-hook #'setup-tide-mode)
```

I get a wrong result when I command, remove or move it `(add-hook 'before-save-hook 'tide-format-before-save)` into the function, I will get this behavior.
It will not automatically show the recommendation for the second file and after(it's work fine in the first file).
![wrong](https://i.imgur.com/o00Vs2j.gif)

This is the result I expected.
![expect](https://i.imgur.com/XJ1cqEa.gif)

I saw the source, I can't find any special with this function.
Is this a bug or the conflict of the config.
```lisp
;;;###autoload
(defun tide-format-before-save ()
  "Before save hook to format the buffer before each save."
  (interactive)
  (when (bound-and-true-p tide-mode)
    (tide-format)))

;;;###autoload
(defun tide-format ()
  "Format the current region or buffer."
  (interactive)
  (if (use-region-p)
      (tide-format-region (region-beginning) (region-end))
    (tide-format-region (point-min) (point-max))))
```

I am confuse, can you enlighten me?
Thank you.

**Comment by redguardtoo** [comment]
As README said, you could place all you set up into `~/.custom.el`, it  will overrides my original configuration.

Here is my minimum code in `~/.custome.el`, it just works.
```lisp
(defun setup-tide-mode ()
  (tide-setup)
  (tide-hl-identifier-mode 1))
;; formats the buffer before saving
(add-hook 'before-save-hook 'tide-format-before-save)
(add-hook 'typescript-mode-hook #'setup-tide-mode)
```
Maybe you forgot to create `tsconfig.json` in project root? See README of `tide-mode`.

Here is my `tsconfig.json`,
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true
  },
  "files": [
    "hello.ts"
  ]
}
```

Screencast:

![Uploading demo.gif…]()

company and eldoc is already set up in my configuration. But I use flymake instead of flycheck. If you use flycheck, please comment out line `(require-init 'init-flymake t)` in `init.el`.

**Comment by karta0807913** [comment]
thanks for answer,
I tried to add config in ~/.custome.el, but I still got the same behavior.
It will not automatically show the recommendation for the second file and after(it's work fine in the first file).

this is my code, and I have `tsconfig.json` on root of my project.

```lisp
(defun setup-tide-mode ()
(tide-setup)
(tide-hl-identifier-mode 1))

(add-hook 'typescript-mode-hook #'setup-tide-mode)
```

**Comment by redguardtoo** [comment]
Maybe you you could set up a sample project?

**Comment by karta0807913** [comment]
Hi, I created a project over [here](https://github.com/karta0807913/test_typescript_project)

I open emacs using this command `emacs -nw src/index.ts`

custom.el
```lisp
(defun setup-tide-mode ()
  (tide-setup)
  (flycheck-mode 1)
  (tide-hl-identifier-mode 1))

;; mark this, company-tide will not show in "C-h v company-backends"
;; (add-hook 'before-save-hook 'tide-format-before-save)
(add-hook 'typescript-mode-hook #'setup-tide-mode)
```
I can't found the company-tide when I open another file

first file
![first file](https://i.imgur.com/4XX185W.gif)

second file and after
![after first file](https://i.imgur.com/52lQbnw.gif)

**Comment by redguardtoo** [comment]
```lisp
(defun setup-tide-mode ()
  (when (and (boundp 'company-backends)
             company-backends
             (not (memq 'company-tide company-backends)))
    (cl-pushnew 'company-tide company-backends))
  (tide-setup)
  (tide-hl-identifier-mode 1))
(add-hook 'typescript-mode-hook #'setup-tide-mode)
```

**Comment by karta0807913** [comment]
thank you, but I want to know the cause of this behavior.
It's the configuration conflict or just a bug.

**Comment by redguardtoo** [comment]
I just read code of tide and guess. You need understand  `company-backends` is buffer local variable. So it's better to set it up in mode hook.
