### ISSUE TITLE
让eim支持模糊拼音

### ISSUE THREAD

**Issue by redguardtoo** [redguardtoo/emacs.d#85]

**Comment by redguardtoo** [comment]
- search `eim-bisearch-word` in eim-py.el.

**Comment by redguardtoo** [comment]
` grep '^[a-z]*ing-[a-z]*in ' ~/.eim/py.txt  | wc -l`: 52
`grep '^[a-z]*in-[a-z]*ing ' ~/.eim/py.txt | wc -l`: 63

**Comment by redguardtoo** [comment]
use pyim instead, also check 56c5ec2 for better algorithm

**Comment by redguardtoo** [comment]
that's actually pretty easy， all we need is just hack pyim-get-choices

**Comment by russellfei** [comment]
我一直觉得直接用系统层面上的输入法也可以
有个 RIME，完全可以自行hack

**Comment by redguardtoo** [comment]
what's rime?

**Comment by russellfei** [comment]
a not so famous input method developed by [lotem](https://github.com/lotem)

Well, I just use this across all my platforms, free from malicious sxxgou IME.
