### ISSUE TITLE
looks like we still need melpa ivy/counsel/swiper

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#851]
i'm not very sure where cause the problem, but when i start a new emacs configuration on WSL2 windows and use your config files, almost (because i didn't check every command) every counsel command give me this error:
`ivy-configure: Keyword argument :parent not one of (:initial-input :height :occur :update-fn :unwind-fn :index-fn :\ sort-fn :format-fn :display-transformer-fn :more-chars :grep-p :exit-codes)`

but when i install melpa ivy & swiper , no error shows again. i see abo-abo says [maybe this error shows when ivy version too old](https://github.com/abo-abo/swiper/issues/2249).

**Comment by redguardtoo** [comment]
I prefer packages on http://stable.melpa.org 

The advantage is of stable-melpa-first policy is my configuration is very robust. It rarely breaks after full package upgrading.

The disadvantage is the stable packages are a bit outdated. So if any package you are using are dependent on new version of ivy. You might get this error.

See https://github.com/redguardtoo/emacs.d#checklist if you prefer unstable version of ivy/counsel/swiper.

I'm serious about my claim "this is a fast and robust Emacs setup". The cost of "fast and robust" is you need manually specify the unstable packages to install.
