### ISSUE TITLE
how to avoid yas-insert-snippet or complete when use TAB in org-mode to unfold/fold headline?

### ISSUE THREAD

**Issue by fpGHwd** [redguardtoo/emacs.d#852]
I have a headline `* emacs` in a org file, when the cursor is between ‘e’ and ‘m’, and I want to unfold this headline and browse its content and then stroke `tab`. But the buffer insert content like 
`* #+begin_example
   #+end_examplemacs
`
It seems the `tab` stroke triggered a yas-insert-snippet or some completion. How can I avoid this situation?

**Comment by redguardtoo** [comment]
49460c69 org-mode might conflict with yasnippet-minor-mode (Chen Bin)

**Comment by fpGHwd** [comment]
thanks, it works properly now :+1:
