### ISSUE TITLE
每次加载或者保存文件的时候都会卡顿5秒左右

### ISSUE THREAD

**Issue by t6ui** [redguardtoo/emacs.d#857]
使用如下函数：
(defun profiled-save-buffer ()
    ""
  (interactive)
  (profiler-start 'cpu)
  (save-buffer)
  (profiler-report)
  (profiler-stop)
  (select-window (previous-window)))

生成save buffer的性能报告：

- ...                                                              89 100%
 - flyspell-external-point-words                                   73  82%
  - flyspell-word                                                  73  82%
   - wucuo-generic-check-word-predicate                            73  82%
    - let*                                                         73  82%
     - cond                                                        73  82%
      - let*                                                       73  82%
       - setq                                                      73  82%
        - wucuo-check-camel-case-word-predicate                    73  82%
         - if                                                      73  82%
          - string-match-p                                         73  82%
           - wucuo-spell-checker-to-string                         73  82%
            - let*                                                 73  82%
             - let                                                 73  82%
              - save-current-buffer                                73  82%
               - unwind-protect                                    73  82%
                  progn                                            73  82%
 - flyspell-check-region-doublons                                  15  16%
  - flyspell-word                                                  15  16%
   - wucuo-generic-check-word-predicate                            15  16%
    - let*                                                         15  16%
     - cond                                                        15  16%
      - let*                                                       15  16%
       - setq                                                      15  16%
        - wucuo-check-camel-case-word-predicate                    15  16%
         - if                                                      15  16%
          - string-match-p                                         15  16%
           - wucuo-spell-checker-to-string                         15  16%
            + let*                                                 15  16%
 - funcall-interactively                                            1   1%
  - profiled-save-buffer                                            1   1%
   - save-buffer                                                    1   1%
    - basic-save-buffer                                             1   1%
     - run-hooks                                                    1   1%
      - lazyflymake-check-buffer                                    1   1%
       - cond                                                       1   1%
        - if                                                        1   1%
         - progn                                                    1   1%
          - lazyflymake-start-buffer-checking-process                  1   1%
           - cond                                                   1   1%
            - flymake-start                                         1   1%
             - run-hook-wrapped                                     1   1%
              - #<compiled 0x243a36d>                               1   1%
               - flymake--run-backend                               1   1%
                  elisp-flymake-byte-compile                        1   1%
   Automatic GC                                                     0   0%

调用如下函数，在保存文件的时候不卡了
(setq after-save-hook nil)
我该如何解决保存文件卡顿的问题。（因为启用了自动保存功能，所以只要编辑几乎就一直卡，卡顿的时候Ctrl+g无法使用）

加载文件不知道是什么原因，也是一样，首次加载一个几行代码的lisp文件需要5秒左右时间。

**Comment by redguardtoo** [comment]
Check lazyflymake and wucuo set up.

**Comment by t6ui** [comment]
There is no effect by setting variable 'wucuo-update-interval' and 'lazyflymake-update-interval'.

I have to remove hook both of 'wucuo-start' and 'lazyflymake-start'.

And loading every file from disk is still slow, a small size file can spend 2 to 4 seconds, I don't know how to debug this.

**Comment by t6ui** [comment]
电脑配置：Windows 10， 12G RAM
虽然非常卡顿，但是wucuo-mode 和 lazyflymake-mode都是可以使用的，如果打开这两个模式可以成功检查语法错误和拼写错误。

还有一个问题请教下：
flymake-allowed-file-name-mask的值如下：
Value:
(("\\.\\(?:c\\(?:pp\\|xx\\|\\+\\+\\)?\\|CC\\)\\'" flymake-proc-simple-make-init nil flymake-proc-real-file-name-considering-includes)
 ("\\.xml\\'" flymake-proc-xml-init)
 ("\\.html?\\'" flymake-proc-xml-init)
 ("\\.cs\\'" flymake-proc-simple-make-init)
 ("\\.php[345]?\\'" flymake-proc-php-init)
 ("\\.h\\'" flymake-proc-master-make-header-init flymake-proc-master-cleanup)
 ("\\.java\\'" flymake-proc-simple-make-java-init flymake-proc-simple-java-cleanup)
 ("[0-9]+\\.tex\\'" flymake-proc-master-tex-init flymake-proc-master-cleanup)
 ("\\.tex\\'" flymake-proc-simple-tex-init)
 ("\\.idl\\'" flymake-proc-simple-make-init))

这里头没有el后缀的正则表达式，为什么在lisp文件中也可以进行语法检查。

**Comment by redguardtoo** [comment]
Emacs 26 has already set up the lint functions. Maybe gives me a sample file. Any extra packages you are using? lsp-mode? flycheck?

**Comment by t6ui** [comment]
刚开始使用这个仓，还没有什么配置。
我的custom.el就是下面这样

;; evil-matchit 2.3.0 is required
(setq my-use-m-for-matchit t)

;; avoid bug in find-file-in-project.el
(if (eq system-type 'windows-nt)
     (setq ffip-find-executable "d:\\\\cygwin64\\\\bin\\\\find"))

(defun profiled-save-buffer ()
    "Profile save buffer."
  (interactive)
  (profiler-start 'cpu)
  (save-buffer)
  (profiler-report)
  (profiler-stop)
  (select-window (previous-window)))

(with-eval-after-load 'wucuo
  (setq wucuo-update-interval 300))
(with-eval-after-load 'lazy-flymake
   (set lazyflymake-update-interval 300))

**Comment by redguardtoo** [comment]
I tested the GUI Emacs on Windows. It opens el file in 1 second.
Cygwin Emacs is a bit slower, need 2 or 3 seconds.  My PC is bought 7 years ago.

**Comment by t6ui** [comment]
1.在移除对应Mode之前：
after-save-hook值是(wucuo-spell-check-buffer lazyflymake-check-buffer t)

2.编写如下函数，执行打开init.el文件完成大约花2-3S时间，在Windows Emacs上操作的。
(defun profiled-open-file ()
    "Profile save buffer."
  (interactive)
  (profiler-start 'cpu)
  (find-file "~/.emacs.d/init.el")
  (profiler-report)
  (profiler-stop)
  (select-window (previous-window)))


cpu测试报告如下：

- ...                                                              12 100%
 - progn                                                           12 100%
  - let*                                                           12 100%
   - if                                                            12 100%
    - if                                                           11  91%
     - and                                                         11  91%
      - git-gutter:in-repository-p                                 11  91%
       - cond                                                      11  91%
        - let*                                                     11  91%
         - while                                                   11  91%
          - and                                                    11  91%
           - progn                                                 11  91%
            - if                                                   11  91%
             - git-gutter:vcs-check-function                       11  91%
              - cond                                               11  91%
               - git-gutter:in-git-repository-p                     9  75%
                - if                                                9  75%
                 - progn                                            9  75%
                  - let                                             9  75%
                   - save-current-buffer                            9  75%
                    - unwind-protect                                9  75%
                     - progn                                        9  75%
                      - if                                          9  75%
                       - =                                          9  75%
                        - git-gutter:execute-command                  9  75%
                         - apply                                    9  75%
                          - process-file                            9  75%
                             apply                                  9  75%
               - git-gutter:in-repository-common-p                  2  16%
                - and                                               2  16%
                 - executable-find                                  2  16%
                    locate-file                                     2  16%
    - progn                                                         1   8%
     - git-gutter:start-diff-process                                1   8%
      - cond                                                        1   8%
       - let                                                        1   8%
        - git-gutter:start-diff-process1                            1   8%
         - cond                                                     1   8%
          - git-gutter:start-git-diff-process                       1   8%
           - let                                                    1   8%
            - apply                                                 1   8%
             - start-file-process                                   1   8%
              - apply                                               1   8%
               - start-process                                      1   8%
                  apply                                             1   8%
   Automatic GC                                                     0   0%

**Comment by t6ui** [comment]
(defmacro measure-time  (name &rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (let ((dt (float-time (time-since time))))
       (if (>= dt 0.1)
           (message "%.06f in %s" dt ,name)))))

(defun profiled-open-file ()
    "Profile save buffer."
  (interactive)
  (profiler-start 'cpu)
  (measure-time "open file" (find-file "~/.emacs.d/init.el"))
  (profiler-report)
  (profiler-stop)
  (select-window (previous-window)))

花了11秒：

CPU profiler started
11.697751 in open file
CPU profiler stopped

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/87559293-73337880-c6fd-11ea-9568-e30d36d3338a.png)

I can't reproduce the issue.

**Comment by t6ui** [comment]
The slow loading of file is unlike the problem of a certain plugin.
I removed git-gutter and it still took a long time.

![image](https://user-images.githubusercontent.com/17449509/87618533-b1a45400-c74c-11ea-9ea0-9b3167b72b1b.png)

**Comment by t6ui** [comment]
This is an attempt on spacemacs:

![image](https://user-images.githubusercontent.com/17449509/87619091-ebc22580-c74d-11ea-96a4-31e4e0fd8c9c.png)

**Comment by t6ui** [comment]
Emacs -Q启动的话，打开init.el文件也花了8S多的时间..

Cygwin Emacs 速度更慢...

**Comment by t6ui** [comment]
打开一个18M左右的日志文件秒开。
只要打开有语法渲染的文件都很慢。

**Comment by redguardtoo** [comment]
你机器什么配置？ `emacs -Q` 我的配置就不会被载入了。如果是我的配置的话，瓶颈可能在git-gutter。因为需要diff当前代码。

**Comment by redguardtoo** [comment]
```lisp
(defun profile-open-file ()
  (interactive)
  (profiler-start 'cpu)
  (find-file "/home/user1/your-file-path")
  (profiler-report)
  (profiler-stop))
```
Run `M-x profile-open-file`.

**Comment by t6ui** [comment]
Win10 64位 i7-4790 CPU 12G RAM
待我回家用自己的笔记本测试下。

**Comment by redguardtoo** [comment]
我电脑7年前买的i3, Windows 7下打开init.el秒开。我之前的Windows 10也用过，电脑配置比你差多了，都是秒开。

**Comment by redguardtoo** [comment]
你要么到emacs-china.org上看看以前的帖子，中文字体设置可能会影响emacs性能。我不用中文，所以没有这个问题。

**Comment by t6ui** [comment]
你好，我重新验证了，和字体没有关系... 

和文件是不是在版本控制目录中有关系，如果文件在版本控制中，速度就很慢，同一个文件从版本控制中拷贝出来，速度就是秒开...

使用Emacs -Q也是一样的情况。

似乎git库体量越大，打开git库中的文件就越快。

**Comment by t6ui** [comment]
更正
似乎git库体量越大，打开git库中的文件就越慢。。

**Comment by redguardtoo** [comment]
我已调查过了. git-gutter的锅。见  https://github.com/redguardtoo/emacs.d/issues/858#issuecomment-659336012 

对我来说git-gutter是我工作流中最核心的插件。所以只能忍了。如果你不用git-gutter，可以把它关掉。我认为自己的的git-gutter设置和官方设置没什么区别，不过你可以试一下是否是我的问题。

另外`init-git.el`的开头注释你可以看一下。虽然是针对网络文件系统的优化。不过也应该适用于其他文件IO较慢的系统

**Comment by t6ui** [comment]
打开/保存同一个文件操作：
在个人电脑上不卡...
而在公司电脑上很卡... 

Emacs配置和Emacs版本都是一样的。。。
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

目前公司电脑只能关闭flymake/wucuo功能才能使用（忽略加载慢的情况）..

**Comment by redguardtoo** [comment]
公司电脑可能在文件读写上有额外的监控.所以慢. lazyflymake和wucuo设计的目的就是提供用户优化性能的机会,可以把检查的间隔调大. 象flyspell-mode和flymake-mode那样要么用要么不用对低性能电脑来说只能不用.

**Comment by t6ui** [comment]
好的，谢谢。
