### ISSUE TITLE
Slow Windows machines: Screen freezes frequently with "Blocking call to accept-process-output with quit inhibited" message

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#858]
I am facing lot of slowness of Emacs on relatively slow Windows machines (4GB RAM, 3.2GHz Duel Processor with Windows7).

I am using Cygwin64 and Emacs 26.3,

I see a lot of below messages while trying to type text in say an org file,
`Blocking call to accept-process-output with quit inhibited!! [2 times]`

Any tips?

**Comment by amittendulkar** [comment]
When I press `i` to insert text (evil mode), the Emacs gets hung for some time and the above mentioned message appears in the mini-buffer.

When I start typing something, after typing 2-3 characters, the same message repeats by hanging Emacs for every few seconds (not sure whether it is a result of auto-save), making it impossible to work.

**Comment by redguardtoo** [comment]
What's your `major-mode`? What programming language you are using? What extra packages you have installed?

Besides, if you insert below code into `~/.custom.el`, is situation improved?
```lisp
(with-eval-after-load 'wucuo
  (setq wucuo-update-interval 300))
(with-eval-after-load 'lazy-flymake
   (set lazyflymake-update-interval 300))
```

**Comment by amittendulkar** [comment]
The situation is greatly improved after adding the above code in `~/.custom.el`. Editing is now smooth.

I was editing a simple org file (org major-mode) and was facing lot of issues while typing in the file. At least while typing Emacs is not getting hung.

There are other set of issues I am facing (not sure whether I should add new issue to track them),
- Emacs takes more than 60 seconds to startup (~10 seconds with bare default .emacs file it creates
- Opening any new file takes 20-30 seconds (I tried with a python file while org file is already open)

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/87611358-3aba8b80-c74b-11ea-9069-bf9979a590c8.png)
See the `elpy-enable` which is takes most start up time. You could comment out that line. elpy is the python IDE. It's optional for python development.

I only use ctags based solution for code completion and code navigation. So I rarely use elpy..

**Comment by amittendulkar** [comment]
Thanks. Python file is now opening within 5 seconds. How do I get the CPU profile report like above? This way I will be able to comment out unnecessary parts in other major modes (e.g. org file taking ~60 seconds to open as well).

**Comment by redguardtoo** [comment]
Insert below code into `~/.custom.el`,
```lisp
(defun profile-open-file ()
  (interactive)
  (profiler-start 'cpu)
  (find-file "/home/user1/your-file-path")
  (profiler-report)
  (profiler-stop))
```
Run `M-x profile-open-file`.

**Comment by amittendulkar** [comment]
Somehow, the above function didn't produce output. So I manually executed commands. Here is the analysis,
![image](https://user-images.githubusercontent.com/18111340/87642149-c392f080-c766-11ea-877e-49f75c702fb8.png)

**Comment by amittendulkar** [comment]
Ok, here is the output after calling above function,
![image](https://user-images.githubusercontent.com/18111340/87649222-b7f6f800-c76d-11ea-93e0-77f219ea7e2b.png)

**Comment by redguardtoo** [comment]
That's the first time you load org file. So the whole org library need be loaded.  As you can see,  `org-load-modules-maybe` is the org's own function which takes the most resource.

Try to open the second org file, it's much faster. This time the bottle neck is `git-gutter-mode`.

Surely you can remove git-gutter mode. But git gutter mode is critical to my workflow.

![image](https://user-images.githubusercontent.com/184553/87663094-9f570400-c7a6-11ea-84dd-9b8242d9806f.png)

**Comment by amittendulkar** [comment]
Thanks. I found that the second org file opened pretty quickly for me,
![image](https://user-images.githubusercontent.com/18111340/87848380-80b75100-c8fd-11ea-9dba-b89dea84e149.png)

I haven't yet pulled in your above change. For now closing the issue.
