### ISSUE TITLE
eval the (expand-file-name "~") won't expand to absolute path

### ISSUE THREAD

**Issue by nusgnaf** [redguardtoo/emacs.d#859]
**Setup**: 
  - Ubuntu 20.04
  - Emacs: 26.3

It's a pleasure to use your setup, until I debug a third-party package and trace down to a simple s-exp
`(expand-file-name "~")`
would produce the error message:
`Debugge entered--Lisp error: (void-variable ~)
`
while move back to vanilla setup would correctly expand to "/home/myname".
So, this is my first week using emacs, and dig into such a complex setup is beyond my capability. Hope it provides enough info.

**Comment by redguardtoo** [comment]
I need more information. What package you are using? What's exact steps to reproduce the issue?

**Comment by nusgnaf** [comment]
Hi, I am using [neuron-mode](https://github.com/felko/neuron-mode)
While utilizing `C-c C-z` to create new Zettelkasten note, the error arise
`Command "neuron --zettelkasten-dir \~/zettelkasten/ query --uri z\:zettels" exited with code 1: neuron: user error (Zettelkasten directory ~/zettelkasten/ \
does not exist.)`
I check the source code of neuron-model.el, trace to [this](https://github.com/felko/neuron-mode/blob/0f61ca2fc63f14a04cec0e29b541feaba6a8d3ee/neuron-mode.el#L52)
It seems that `(expand-file-name "~/zettelkasten")` doesn't generate absolute directory path correctly, instead, it assembles such a command
`neuron --zettelkasten-dir \~/zettelkasten/ query --uri z\:zettels`
unfortunately neuron cannot working with relative directory path, leads to error.

**Comment by nusgnaf** [comment]
I reduce the case to the `C-x C-e` the one-liner
`(expand-file-name "~")`
which indeed cannot expand to the full home path.

**Comment by redguardtoo** [comment]
In you setup,
`(setq neuron-default-zettelkasten-directory "/home/user1/zettelkasten")`
