### ISSUE TITLE
Use “m” key for “evil-matchit”

### ISSUE THREAD

**Issue by t6ui** [redguardtoo/emacs.d#860]
Hello, I put the statement below in the custom.el, but it has no effect.

```
;; evil-matchit 2.3.0 is required
(setq my-use-m-for-matchit t)
```

**Comment by redguardtoo** [comment]
I stop supporting this feature. In evil/vim, `m` key is used for setting mark. I tested about a week and found out this is not good practice.

**Comment by t6ui** [comment]
Thanks, got it.

**Comment by Zilong-Li** [comment]
maybe you should remove this from README so that people won't get misled.

**Comment by redguardtoo** [comment]
620bfdf3 clean README (Chen Bin)
