### ISSUE TITLE
workgroup没有自动保存功能

### ISSUE THREAD

**Issue by t6ui** [redguardtoo/emacs.d#861]
wg-emacs-exit-save-behavior的值是'save

布局的改变没有在emacs关闭的场景中被保存....

**Comment by t6ui** [comment]
workgroup没有被安装，关闭此issue。

**Comment by redguardtoo** [comment]
自动保存没什么用。直接手动保存就行了。另外我用的是workgroups2

**Comment by t6ui** [comment]
谢谢陈兄，用其他工具没有主动保存布局的习惯，不过看你的教程已经有意识到你的用意了。
