### ISSUE TITLE
Can't redo stuff in Gnus compose buffer

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#862]
When I am typing email in Gnus using evil mode, I accidentally undid one change using `u` (in non-edit mode).

When I tried redo (`C-r`), it said "no further redo information". Pressing undo (`u`) undid earlier changes but redo didn't work.

I switched to Emacs editing mode (`C-z`) and started pressing `C-/` hoping to re-walk the tree and eventually redo what I undid. However, this further undid my edits.

Am I missing something here? The `C-r` keymap looks correct as it is printing redo related message. Any tips are appreciated.

**Comment by amittendulkar** [comment]
I noticed that the `Date` field at the top of compose buffer keeps automatically updating after every minute. When it updates, it seems to be erasing the redo tree as well. Any workaround to revive the redo tree?

**Comment by redguardtoo** [comment]
can't reproduce the issue. But `undo-tree` (which is used by `evil`) is known to be buggy.
So I replace it with `undo-fu`

4f2c3863 2020-07-19 use undo-fu to replace undo-tree (Chen Bin)

**Comment by amittendulkar** [comment]
I pulled the latest code and the issue still exists. After careful observation, here is what I think is happening.

Every few seconds, the `Date` field above the `--text follows this line--` is updated with the latest timestamp.

Type few sentences (say 4 sentences) in your compose buffer. While you are typing the `Date` field keeps updating in-between. Press `ESC` and then `u` to undo the last typed (4th) sentence. Note that the undo tree will also undo the changes in the `Date` field if any (after typing 4th sentence so you might have to press `u` 2 or more times to remove 4th sentence). Now, wait few seconds after undo, and let the `Date` field get updated with the latest timestamp.

Now, press `C-r` and you see a `Redo without undo step (C-g to ignore)` message. I suspect that the automatic update of the timestamp is breaking the redo tree.

What I don't understand is that the Emacs undo-redo tree is never overwritten. You can reach to the last (or any) edited change using the same undo key (`C-/`) which is also redo. Whether I stay in evil-mode or start from scratch from plain Emacs editing mode (using `C-z`) I never get my 4th sentence back (instead without getting the 4th sentence as redo, it continues to erase the 3rd, 2nd, 1st sentences as well).

**Comment by amittendulkar** [comment]
I tried all of the above using bare bone Emacs (moved away `~/.emacs.d`) and found that the above issue is not reproducible. I didn't see the `Date` field inserted in the compose buffer. 

I undid the 4th sentence using `C-/`. After cursor movement, pressing `C-/` again brought the 4th sentence back (redo worked successfully).

**Comment by redguardtoo** [comment]
Can you show me the screenshot of your gnus? Why I don't have `Date` field?

**Comment by amittendulkar** [comment]
Here is a screenshot
![Screenshot from 2020-07-20 11-17-00](https://user-images.githubusercontent.com/18111340/87904061-1e845a80-ca7b-11ea-9354-582490272c5e.png)

**Comment by amittendulkar** [comment]
Spent some more time on this after a long time. If I don't use your `.emacs.d`, (but use the evil mode) the date field appears if I press `:w RET` in the message mode (I guess it will appear after pressing `C-x C-s` in non-evil mode).

Do you have any code in your `.gnus.el` to switch off auto-save buffer while composing a message in Gnus?

**Comment by redguardtoo** [comment]
a475f7ca Donot auto-save in message-mode (Chen Bin)

**Comment by amittendulkar** [comment]
Thanks working properly now.
