### ISSUE TITLE
company cannot work

### ISSUE THREAD

**Issue by zhanyi22333** [redguardtoo/emacs.d#864]
I followed your course and try to write the first part of company-mytags.But I found my code doesn't work.Emacs will report "wrong-type-argument hash-table-p nil" when I type something and no popup for completion.
I renamed my .custom.el, try again and fail. I also try company-files ,it doesn't work too.Then I switched to spacemacs and **it works**.
## environment details:
GNU Emacs 27.0.50
ubuntu 19.10
## Here is my code:
(defun company-mytags-candidates (arg)
  (message "arg=%s" arg)
  '("hello1"
    "hello2"))
(defun company-mytags-prefix ()
  (company-grab-symbol)
  )

(defun company-mytags (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'company-mytags))
    (prefix (company-mytags-prefix))
    (candidates (company-mytags-candidates arg))
    ))

(provide 'company-mytags)
(setq company-backends '(company-mytags company-files ))
## Here is information from Backtrace for my code :
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("hello2" nil)
  company-statistics-score-calc-heavy("hello2")
  #f(compiled-function (cand1 cand2) #<bytecode 0x18eb181>)("hello2" "hello1")
  sort(("hello1") #f(compiled-function (cand1 cand2) #<bytecode 0x18eb181>))
  company-sort-by-statistics(("hello1"))
  company--transform-candidates(("hello1"))
  company--postprocess-candidates(("hello1" "hello2"))
  company-calculate-candidates(#("thi" 0 3 (fontified t)) nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer company-mytags.el> #<window 6 on company-mytags.el> 291 507)
  apply(company-idle-begin (#<buffer company-mytags.el> #<window 6 on company-mytags.el> 291 507))
  timer-event-handler([t 24343 51289 970124 nil company-idle-begin (#<buffer company-mytags.el> #<window 6 on company-mytags.el> 291 507) nil 563000])
## here is information from Backtrace for company-files when I type (setq one "~/proj") :  
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("~/project/elisp/" nil)
  company-statistics-score-calc-heavy("~/project/elisp/")
  #f(compiled-function (cand1 cand2) #<bytecode 0x1859405>)("~/project/elisp/" "~/project/")
  sort(("~/project/") #f(compiled-function (cand1 cand2) #<bytecode 0x1859405>))
  company-sort-by-statistics(("~/project/"))
  company--transform-candidates(("~/project/"))
  company--postprocess-candidates(("~/project/" "~/project/elisp/"))
  company-calculate-candidates("~/proj" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer company-mytags.el> #<window 3 on company-mytags.el> 438 522)
  apply(company-idle-begin (#<buffer company-mytags.el> #<window 3 on company-mytags.el> 438 522))
  timer-event-handler([t 24343 52515 547926 nil company-idle-begin (#<buffer company-mytags.el> #<window 3 on company-mytags.el> 438 522) nil 475000])

**Comment by redguardtoo** [comment]
What's  value of `company-backends`?

**Comment by zhanyi22333** [comment]
(company-statistics-mode) is not removed.
After I run M-x company-statistics-mode and disable it,company-mode works well.
Why company-statistics-mode makes company-mode cannot work?Should I do anything else for company-statistics-mode?

**Comment by redguardtoo** [comment]
I don't have this problem. As you can see in my video tutorial, I wrote the `company-mytags` from the scratch.

It's always enabled in my workflow. I double checked my set up. Can't find any problem.

**Comment by zhanyi22333** [comment]
Ok.Thank you.
