### ISSUE TITLE
In Multi-term buffer C-x C-f, find-file always in the same directory where the term buffer is created

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#865]
Once you use multi-term and create a term buffer, then no matter which directory you are in in the term buffer, when using C-x C-f to open files, it always starts looking files in the directory where you first created this term buffer. Is there anyway to start looking for files in the current directory the term buffer is in?

**Comment by Inc0ns1st3nt** [comment]
Here is what I found on [stackoverflow](https://stackoverflow.com/questions/20729884/ansi-term-wont-find-file-under-current-directory), their approach is to track the current directory in term.

I recommend you to check out `term-command-hook`
