### ISSUE TITLE
putty 组合键没有用

### ISSUE THREAD

**Issue by bensonlew** [redguardtoo/emacs.d#867]
我用putty 登录到终端发现有的组合键不可以用 C-=   C-;    C-,
但是 C-], C-[, C-_ C-正常字母键 是可以用的
请问有什么办法可以排查么？

**Comment by redguardtoo** [comment]
It's not Emacs problem. See https://stackoverflow.com/questions/24309580/emacs-key-bindings-change-in-terminal-emulator 

But my configuration does provide a workaround by using Vim key bindings.

`general.el`, hydra, counsel-M-x also helps.

So key bindings is a solved problem for me.
