### ISSUE TITLE
What are the last symbols on the modeline?

### ISSUE THREAD

**Issue by srustamo** [redguardtoo/emacs.d#868]
What is 1.60 on the screenshot of the modeline?
<img width="606" alt="Screenshot 2020-08-19 at 19 57 51" src="https://user-images.githubusercontent.com/749813/90651917-0577f080-e257-11ea-9c84-3022e27fbe65.png">

**Comment by dalu98** [comment]
通过<kbd>C-h f</kbd>`display-time`可以看到相关信息，其实就是过去一分钟内的系统负载。

可以通过`(setq display-time-default-load-average nil)`关掉

**Comment by srustamo** [comment]
谢谢
