### ISSUE TITLE
Evil mode macro conflicts with shortcut key 'fg'

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#870]
### Reproduction steps

1. record a macro to insert "format" (qaiformat`Esc`q)
2. run the macro (`@a`)

### Expected behavior

"format" should be inserted after point 

### Actual behavior

"frmat" is inserted

---

It seems that the shortcut key below conflict:

https://github.com/redguardtoo/emacs.d/blob/009dc1fb58bf5891b6091f8612ff87c8fe6f5524/lisp/init-evil.el#L927

**Comment by redguardtoo** [comment]
eb0a08ee make evil macro recording work (Chen Bin)
