### ISSUE TITLE
Strange Font Changes

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#871]
After pull the latest code, when editing a c++ source code file, I found some identifiers are highlighted but not following the regular syntax highlighting rule. I don't know which package is doing this. I tried disable flyspell and flymake, both don't work.

**Comment by redguardtoo** [comment]
Could you give me more details? My C++ set up has not changed for ages.

**Comment by drcxd** [comment]
There is a buffer called `*Flymake log*` with these content:

```
Warning [flymake *scratch*]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Error [flymake-proc main.cpp]: NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake-proc main.cpp]: deleted file /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main_flymake.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because (wrong-type-argument stringp t)
Error [flymake-proc main.cpp]: NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake-proc main.cpp]: deleted file /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main_flymake.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because (wrong-type-argument stringp t)
Error [flymake-proc main.cpp]: NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because NOMK: No buildfile (Makefile) found for /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main.cpp
Warning [flymake-proc main.cpp]: deleted file /mnt/d/workplace/LearnOpenGL/LearnOpenGL/main_flymake.cpp
Warning [flymake main.cpp]: Disabling backend flymake-proc-legacy-flymake because (wrong-type-argument stringp t)
```

**Comment by redguardtoo** [comment]
Flymake warnings could be ignored. See `(add-hook 'prog-mode-hook #'lazyflymake-start)` in `init-flymake.el`. You can comment out that line. `lazyflymake` is light weight alternative of `flymake-mode`. 

I'm not sure flymake has anything to do with font rendering. Could you give me a sample file and screenshot? What's your major mode?
`

**Comment by drcxd** [comment]
screen shot link [https://drive.google.com/file/d/1SMgA-Blsk4QEwlB60EK2kr9r87OIXa5K/view?usp=sharing](url)
sample code file link [https://drive.google.com/file/d/1TeEIbxv4CRf9PU4AeT54U8dbN9J_cjEQ/view?usp=sharing](url)
my major mode is c++-mode,

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/emacs.d#spell-check-camel-case-code 

The package wucuo spell check the camel case code. 

You can customize wucuo to ignore code with certain font faces.

**Comment by drcxd** [comment]
Actually I don't want spell check in programming buffers. How could I turn off that? It seems it is activated once you installed any spell check software?

**Comment by redguardtoo** [comment]
comment out the line containing `wucuo-start`, see README. and make sure `flyspell-mode` is not enabled.

**Comment by drcxd** [comment]
I tried modify the code in `init-spelling.el` but it still automatically enable the spell-checking.

Here is the code snippets.

```

;; (defun text-mode-hook-setup ()
;;   ;; Turn off RUN-TOGETHER option when spell check text-mode
;;   (setq-local ispell-extra-args (my-detect-ispell-args))
;;   (my-ensure 'wucuo)
;;   (wucuo-start))
;; (add-hook 'text-mode-hook 'text-mode-hook-setup)

```

**Comment by redguardtoo** [comment]
grep `(wucuo-start)`, it's called in `text-mode-hook` and `prog-mode-hook`.
