### ISSUE TITLE
load-theme in '.custom.el' does not respect 'Custom Safe Themes' values in Customize

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [redguardtoo/emacs.d#872]
##  Issue brief 
I usualy load my themes of choice in `.custom.el`
And it always asks me for 
> Loading a theme can run lisp code. Really load
> Treat this theme as safe in future sessions?

Even though I am sure that `custom-safe-themes` contains my theme's hash.
I was lead to believe that `load-theme` doesn't check `custom-safe-themes`, because loading the theme after emacs has started up would load the theme just fine without those prompts.

## source code 
Digging into `init.el`, it seems `.custom.el` is indeed loaded before `custom-file`. Would fixing this be as simple as swapping their load order?
Or should I use a different way to load my theme?

## importance of fixing this issue
My fellow emacs friend, uses some other config, and has an `emacs-init-time` of `0.7secs`, while mine is `3.4secs`. Fixing this issue, will chop down my turtle reaction of answering the `load-theme` prompt and bring my `emacs-init-time` down to a good 1.4secs.

**Comment by redguardtoo** [comment]
5a5bbd7c load ~/.custom.el after custom-set-variables.el is loaded (Chen Bin)

I use `(load-theme 'my-theme t)`.

**Comment by Inc0ns1st3nt** [comment]
Ohhh, I didn't realize there are optional "flags" that can be passed in to `load-theme`.
