### ISSUE TITLE
Autoload gmail2bbdb-import-file twice

### ISSUE THREAD

**Issue by Ynjxsjmh** [redguardtoo/emacs.d#875]
https://github.com/redguardtoo/emacs.d/blob/91ac31c9695ee1b665403bfd481edf03b2802e2d/lisp/init-autoload.el#L10-L13

` (autoload 'gmail2bbdb-import-file "gmail2bbdb" "" t) ` is written twice. Does this have some special meaning?

**Comment by redguardtoo** [comment]
198f26cf clean code (Chen Bin)
