### ISSUE TITLE
[improve] replace "git-gutter" with "diff-hl"

### ISSUE THREAD

**Issue by KiteAB** [redguardtoo/emacs.d#876]
as the title

## reason

[diff-hl](https://github.com/dgutov/diff-hl) is fast, customizable, in maintenance and dont take up 2 much space on de left or right

**Comment by redguardtoo** [comment]
No sure. I did check diff-hl before. It's a good package but I've already written some code for git-gutter (See https://blog.binchen.org/posts/enhance-emacs-git-gutter-with-ivy-mode/). I got no performance issue on git-gutter yet.

**Comment by KiteAB** [comment]
> No sure. I did check diff-hl before. It's a good package but I've already written some code for git-gutter (See https://blog.binchen.org/posts/enhance-emacs-git-gutter-with-ivy-mode/). I got no performance issue on git-gutter yet.

i hope i can use better git-gutter lol
