### ISSUE TITLE
void-function package-installed-p

### ISSUE THREAD

**Issue by vipzrx** [redguardtoo/emacs.d#878]
git clone

first time to init 

Debugger entered--Lisp error: (void-function package-installed-p)
  (package-installed-p package min-version)
  (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-contents) (require-package package min-version t)))
  require-package(async)
  eval-buffer(#<buffer  *load*-108863> nil "c:/msys64/home/kk/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 7204
  load-with-code-conversion("c:/msys64/home/kk/.emacs.d/lisp/init-elpa.el" "c:/msys64/home/kk/.emacs.d/lisp/init-elpa.el" t t)
  load("c:/msys64/home/kk/.emacs.d/lisp/init-elpa" t t)
  (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))
  (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))
  require-init(init-elpa)
  (let* ((file-name-handler-alist nil)) (require-init 'init-autoload) (require-init 'init-modeline) (require-init 'init-utils) (require-init 'init-file-type) (require-init 'init-elpa) (require-init 'init-exec-path t) (require-init 'init-spelling t) (require-init 'init-uniquify t) (require-init 'init-ibuffer t) (require-init 'init-ivy) (require-init 'init-hippie-expand) (require-init 'init-windows) (require-init 'init-markdown t) (require-init 'init-javascript t) (require-init 'init-org t) (require-init 'init-css t) (require-init 'init-python t) (require-init 'init-lisp t) (require-init 'init-elisp t) (require-init 'init-yasnippet t) (require-init 'init-cc-mode t) (require-init 'init-linum-mode) (require-init 'init-git t) (require-init 'init-gtags t) (require-init 'init-clipboard) (require-init 'init-ctags t) (require-init 'init-bbdb t) (require-init 'init-gnus t) (require-init 'init-lua-mode t) (require-init 'init-workgroups2 t) (require-init 'init-term-mode t) (require-init 'init-web-mode t) (require-init 'init-company t) (require-init 'init-chinese t) (require-init 'init-keyfreq t) (require-init 'init-httpd t) (require-init 'init-theme) (require-init 'init-essential) (require-init 'init-misc t) (require-init 'init-emacs-w3m t) (require-init 'init-shackle t) (require-init 'init-dired t) (require-init 'init-writting t) (require-init 'init-hydra) (require-init 'init-evil) (require-init 'init-ediff) (setq load-path (cdr load-path)) (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)) ...)
  eval-buffer(#<buffer  *load*> nil "c:/msys64/home/kk/.emacs.d/init.el" nil t)  ; Reading at buffer position 6159
  load-with-code-conversion("c:/msys64/home/kk/.emacs.d/init.el" "c:/msys64/home/kk/.emacs.d/init.el" t t)
  load("c:/msys64/home/kk/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1dd4359>) #f(compiled-function () #<bytecode 0x1dd436d>) t)
  command-line()
  normal-top-level()

**Comment by redguardtoo** [comment]
emacs version?

**Comment by vipzrx** [comment]
works ! thx
