### ISSUE TITLE
Multiple key binding function errors

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#881]
1.  `;;`
Wrong type argument: commandp, ace-pinyin-jump-char-2

1.  `C-x C-b`
Args out of range: #<buffer *Ibuffer*>, 1, 5

**Comment by redguardtoo** [comment]
e6d7501c fix ace-pinyin (Chen Bin)
73e12602 remove obsolete ibuffer format (Chen Bin)

**Comment by BlacAmDK** [comment]
First one still not work
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ace-pinyin")                                                                                                     
   #<subr autoload-do-load>((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2 nil)                                                                                                                           
   apply(#<subr autoload-do-load> ((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2))                                                                                                                       
   autoload-do-load((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2)                                                                                                                                       
   command-execute(ace-pinyin-jump-char-2) 
```

**Comment by BlacAmDK** [comment]
> First one still not work
> 
> ```
> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ace-pinyin")                                                                                                     
>    #<subr autoload-do-load>((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2 nil)                                                                                                                           
>    apply(#<subr autoload-do-load> ((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2))                                                                                                                       
>    autoload-do-load((autoload "ace-pinyin" "" t nil) ace-pinyin-jump-char-2)                                                                                                                                       
>    command-execute(ace-pinyin-jump-char-2) 
> ```

After install ace-pinyin 0.2.5(melpa-stable), problem solved.

**Comment by redguardtoo** [comment]
f500bb6d 2020-10-28 use ace-pinyin source package (Chen Bin)
