### ISSUE TITLE
improper auto completion in shell

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#882]
In the shell buffer, which is created by `M-x shell`, the auto completion is really cool. However, there is an issue.

For example, when I am typing `g++ -` in the shell, the auto completion flush the shell buffer with the completing option. For a compiler which has numerous options, this is some kind of disaster since it will take a long time to print all the options in the buffer which usually triggers improper behavior of the shell buffer. Is there anyway other than setting the waiting time of the auto completion?

**Comment by redguardtoo** [comment]
66dc682d optimise company-idle-delay (Chen Bin)

You can also set up in `~/.custom.el`,
```lisp
;; two seconds idle
(add-hook 'shell-mode-hook (lambda () (setq-local company-idle-delay 2)))
```

**Comment by drcxd** [comment]
Though this works, I think the real problem is that the completion options are too many to displayed in the shell buffer or the drop down menu. Is there a way to set a threshold and when the completion options are more than this threshold then it doesn't show these options until the scope is narrow enough to provide real meaningful options?

Anyway, thanks for the prompt fix.

**Comment by redguardtoo** [comment]
company-mode does not have performance issue. The problem is backend `company-native-complete`. You could raise an issue at https://github.com/CeleritasCelery/emacs-native-shell-complete
