### ISSUE TITLE
ace-window not working after migrating to Emacs 27.1

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#883]
I recently download and compile the source code of emacs 27.1. After that I clear the `.emacs.d` directory and pull the git repository again to reinstall your setup. 
After the first launch of emacs, it downloads and compiles the packages required. Then I could use ace-window to switch between windows. However, once I exit emacs and launch it again, ace-window is not working properly. Every time I invoke `ace-window` by `, x o`, there is an error message in the mini buffer
```
Cannot open load file: No such file or directory, ace-window
```
I checked `~/.emacs.d/elpa/` and there is a directory named `ace-window-20200606.1259`
I comment all the code in `~/.custom.el`.

Edit:
I could manually evaluate the `ace-window.el` and after that the function `ace-window` is available.

Also, when I launch emacs, there is an error message after emacs starts up:
```
Package cl is deprecated
```

**Comment by redguardtoo** [comment]
Thanks. There is a bug in `init.el`, now it's fixed.

d00da5c6 fixed load-path problem (Chen Bin)

Some 3rd packages are still using cl so you can see the warning. You could ignore it.
