### ISSUE TITLE
ivy switch buffer prompt issue

### ISSUE THREAD

**Issue by Mastize** [redguardtoo/emacs.d#884]
say I already open a file named test_xx_xx.cc, when I press `, x b` (ivy switch buffer) and type `test cc`, emacs cannot prompt test_xx_xx.cc 

but `, r r` or `j` in ibuffer mode doesn't have same issue

my os is linux, emacs runs in -nw mode

**Comment by redguardtoo** [comment]
could you give more details? I can't reproduce the issue.

**Comment by Mastize** [comment]
sure, for example I already open test_aaa.cc, and want to switch to that 

now if I am in ibuffer mode, I could press `j` and type `test cc`, it can prompt test_aaa.cc

![Screenshot_2020-11-10_09-09-15](https://user-images.githubusercontent.com/17522169/98615051-c082c800-2334-11eb-87c5-246636280544.png)

but if I am not in ibuffer, and `, x b` to switch buffer, it doesn't work. 

![Screenshot_2020-11-10_09-10-04](https://user-images.githubusercontent.com/17522169/98615171-ec05b280-2334-11eb-999a-2dec32a53ef9.png)

I expect ivy switch buffer could also prompt test_aaa.cc

**Comment by Mastize** [comment]
PS: I found `, x b` could prompt correctly if I type `test c` (i.e. only one 'c' letter)

![Screenshot_2020-11-10_09-29-06](https://user-images.githubusercontent.com/17522169/98616258-6800fa00-2337-11eb-8ca8-eec7b5140ac0.png)

**Comment by redguardtoo** [comment]
779a0503 fixed regexp in buffer search (Chen Bin)

**Comment by Mastize** [comment]
thanks!
