### ISSUE TITLE
请教引入evil后快捷键上的一致性问题

### ISSUE THREAD

**Issue by Gaeric** [redguardtoo/emacs.d#885]
使用evil后，在需要进行文本操作的buffer，完全使用evil的快捷键，这时hjkl是移动指令，
但是在dired或org-agenda等模式的buffer中，evil不启用，这时移动指令是n/p等，
在日常使用的时候经常会在dired、org-agenda和需要文本操作的buffer间切换，这样非常容易混淆指令，比如我偶尔会在org-agenda中按下kj，然后就触发了org-capture。

我看您的配置中并没有使用evil-collect之类配置其它模式快捷键的包，请问您是如何处理这个问题的呢？

**Comment by redguardtoo** [comment]
dired我使用emacs的`C-n`, `C-p`。和evil不冲突。我在evil的insert state本来也用emacs的快捷键移动。

其他快捷键用得很少。偶尔用到也是以 `M-x command`形式使用，如我一年的emacs按键统计数据证明的，常用的操作就几十个而已。不常用的根本不值得去记快捷键。最多重新分配快捷键，安排到统一的`C-c C-y`开头的hydra。

另外见 https://emacs-china.org/t/topic/7687/40?u=redguardtoo ， mode-line的背景色也提醒了我当前状态,

emacs原生，
![image](https://user-images.githubusercontent.com/184553/98744164-584fe700-2405-11eb-977c-ebfca4624a62.png)

evil normal state，
![image](https://user-images.githubusercontent.com/184553/98744205-6a318a00-2405-11eb-9384-9c6fd159949c.png)

evil insert state,
![image](https://user-images.githubusercontent.com/184553/98744233-787fa600-2405-11eb-8fc4-850cc8677088.png)

evil normal state but buffer modified,
![image](https://user-images.githubusercontent.com/184553/98744276-8b927600-2405-11eb-8b7a-d5c821cfd920.png)

**Comment by Gaeric** [comment]
主要问题其实是容易在emacs原生模式中按下j/k键触发其它操作；
关键在于没有直观的提示我处于什么模式下；modeline对我而言可能并不适用，我得找个其它提醒自己的方法；
谢谢您的回答，很有启发。

**Comment by Gaeric** [comment]
解决方式：使用beacon-mode，为beacon-before-blink-hook添加hook，根据evil模式设置beacon-color值，
