### ISSUE TITLE
my-swiper can not search Chinese pinyin

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#886]
# Reproduction steps
1. use `M-x my-swiper` open swiper
2. type `:` to search Chinese pinyin
3. it will show error
`[Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)]`

**Comment by redguardtoo** [comment]
bc266376 fixed pinyin search in swiper (Chen Bin)

**Comment by BlacAmDK** [comment]
thanks.
