### ISSUE TITLE
workgroup strange behaviour

### ISSUE THREAD

**Issue by Mastize** [redguardtoo/emacs.d#887]
Hi, I found workgroup's behaviour very confused to me, looks like it just doesn't work on my side. Sorry I am not sure if I am misunderstanding workgroup, but I expect it is something similar to `C-x r w` and `C-x r j`

Reproduce steps:
1. open file A and use `SPC s s` to save as wg0, now if I use `SPC l l` to load wg0, emacs shows file A, no problem
2. then I open file B, use `SPC s s` save as wg1
3. now use `SPC l l` return to wg0, emacs shows file A, but I expect file B. Btw wg1 also shows file B.

Any tips? Thanks

emacs version: 27.1
os: 18.04.1-Ubuntu
emacs runs in -nw mode

**Comment by redguardtoo** [comment]
just my understanding because I'm only the maintainer , but not the original developer.

workgroups2 saves/loads the windows/frame layout. So you need split window at least once.

I usually split window to 2x2 layout and save.

**Comment by Mastize** [comment]
I tried with split layout, but still same problem

it seems `SPC s s` overwrite the last created wg config of my saved wg configs

so it works after creating two or more wgs, if I don't care that my wg0 config gets lost 

though I don't know if this is expected behaviour
