### ISSUE TITLE
my-evil-delete-hack break evil-surround function

### ISSUE THREAD

**Issue by BlacAmDK** [redguardtoo/emacs.d#888]
# Reproduction steps
1. input some text in buffer, switch to evil normal mode, and put cursor at *
`"this is *the test string"`
2. press `ds"` to delete surrounds double quote(")
3. it will also delete the text between the first double quote and the cursor
`the test string`

after I disable the code below, evil-surround works well.
https://github.com/redguardtoo/emacs.d/blob/4f857bf493ce19e30815ec264b91b5cda6e1da24/lisp/init-evil.el#L741-L750

**Comment by redguardtoo** [comment]
feeefdce respect evil-delete (Chen Bin)
