### ISSUE TITLE
About the system encoding set.

### ISSUE THREAD

**Issue by aaa1999** [redguardtoo/emacs.d#889]
Hello,Bin Chen.I'm using your configuration on emacs.But when I git clone your .emacs.d to my ~/ . Then I run my emacs 26.1 on win10.But something unexpected happened.After downloading many packages,the emacs let me choose one of the system encoding (mine is gbk..).I choose the utf-8,but it cannot work!It seems that something is wrong about the chinese encoding set using your configuration.You know,ever I configured my emacs on win10,it worked well. Today I used yours,then I cannot solve it.Could you please help me out?Thank you very much!

---A very strong wanted learner for emacs.

**Comment by aaa1999** [comment]
rest: I tried to choose another system encoding,it still cannot work.I want to knwo why.Thank you for spending time .

**Comment by redguardtoo** [comment]
more details and  screenshot?

My set up has not specify and encoding actually.

**Comment by aaa1999** [comment]
![image](https://user-images.githubusercontent.com/49224989/100231877-92bb9700-2f62-11eb-9934-e7ace125c52e.png)

**Comment by aaa1999** [comment]
This is the screenShot.Yet,it is an error.

**Comment by aaa1999** [comment]
Thank you for your response whatever.

**Comment by redguardtoo** [comment]
8195b884 set session encoding (Chen Bin)

Delete ~/.emacs.d/.session and restart.

**Comment by aaa1999** [comment]
> [8195b88](https://github.com/redguardtoo/emacs.d/commit/8195b88495086587ad36d5e6ef8fb9e165ca7013) set session encoding (Chen Bin)
> 
> Delete ~/.emacs.d/.session and restart.

I used everything to find the .session file.But,it seems that the file is not exists at all in .emacs.d dir.

**Comment by aaa1999** [comment]
That sounds wired.

**Comment by redguardtoo** [comment]
> > [8195b88](https://github.com/redguardtoo/emacs.d/commit/8195b88495086587ad36d5e6ef8fb9e165ca7013) set session encoding (Chen Bin)
> > Delete ~/.emacs.d/.session and restart.
> 
> I used everything to find the .session file.But,it seems that the file is not exists at all in .emacs.d dir.

The file in the second sub-window in your screenshot.

**Comment by aaa1999** [comment]
The file is not exists after I closed the emacs .I don't know why.

**Comment by redguardtoo** [comment]
https://www.emacswiki.org/emacs/EmacsSession

**Comment by aaa1999** [comment]
ok,thank you.I am ready to read it to solve this.

**Comment by redguardtoo** [comment]
You need do nothing because the problem should already be solved. But `session.el` is very powerful and worth to study.

**Comment by aaa1999** [comment]
Yeah, I see.Thank you.I will try it again until it is can work out normally.
