### ISSUE TITLE
A typo in init-elpa.el line 14

### ISSUE THREAD

**Issue by Passky** [redguardtoo/emacs.d#891]
First,
Let's take a look at release log,
[Release log of emacs27](https://www.gnu.org/software/emacs/news/NEWS.27.1)
the variable name is `package-quickstart`,not `package-quick-start`.

Second,
` (setq package-enable-at-startup nil)` shall be moved to early-init.el.

If we follow that, adding codes below 
```
(setq package-enable-at-startup nil) 
```
into early-init.el will lead to error like this
```
Symbol's function definition is void: package-installed-p
```

My hack is
```
(if (file-readable-p  `path-to-package-quickstart.el`)
(define a void `require-package` function)
(define the origin `require-package' function)
```
and this improves startup performance a lot.

**Comment by redguardtoo** [comment]
package-enable-at-startup
