### ISSUE TITLE
Flyspell marking "f" prefixed strings in python code

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#892]
For `f` prefixed strings I am always getting the first word marked as incorrect. How to avoid this?

![image](https://user-images.githubusercontent.com/18111340/101162996-1f4c1080-3659-11eb-802c-6b9da133e1fb.png)

Also I am not getting any auto-correct options. When I select `flyspell-correct-word`, I get _flyspell-correct-word must be bound to an event with parameters_.

**Comment by redguardtoo** [comment]
Thanks for heads up. It's basically the backend's problem. I suppose you use aspell as backend.

Run `echo "f'helle world'" | aspell pipe --lang en` in shell ,
![image](https://user-images.githubusercontent.com/184553/101233043-db651400-3709-11eb-86ba-f726f53b13f4.png)

Aspell regards `f'hello` as a complete word. See http://aspell.net/0.61/man-html/Words-With-Symbols-in-Them.html#Words-With-Symbols-in-Them 

The best solution is to report the bug to aspell developers and ask them to provide a solution.

The good news is the spell check plugin `wucuo` (https://github.com/redguardtoo/wucuo, it is developed and use by me) does provide some easy workaround,

You can set `wucuo-extra-predicate` to tell wucuo to ignore this kind of typo.

**Comment by redguardtoo** [comment]
Above is just a quick workaround. I will give a better solution in wucuo.

**Comment by amittendulkar** [comment]
Another issue I found is that the spell check is enabled inside the curly brackets (python variables or expressions).

![image](https://user-images.githubusercontent.com/18111340/101321821-02e3ea00-388c-11eb-8e71-ea77c1a0753e.png)

I think the expressions should be ignored.

![image](https://user-images.githubusercontent.com/18111340/101322023-50f8ed80-388c-11eb-9931-24db7c88d3ae.png)

Is this something handled in `wucuo`. Is this something eligible to be tracked as a new issue (here and in aspell)?

**Comment by redguardtoo** [comment]
wucuo can't analyze python code. It just uses font face at point to decide if the typo should be ignored.

But you can always customize wucuo or flyspell.

In this case, I will simply create my personal plain text dictionary which includes words `sys` and `exc`. See https://github.com/redguardtoo/wucuo for details.

**Comment by amittendulkar** [comment]
Thanks for the tips. I am afraid, I am trailing off from the original issue, but the `electric-pair-mode` (I believe this is what you are using) doesn't seem to work properly if in python I am prefixing the string with `f`. For e.g. pressing `"` will give me `""`. However, pressing `f` followed by `"`, won't give me `f""`.

**Comment by redguardtoo** [comment]
I don't know much about `electric-pair`. But maybe you can try `electric-pair-inhibit-predicate`?

**Comment by redguardtoo** [comment]
2e8b1841 optimise electric-pair (Chen Bin)

**Comment by amittendulkar** [comment]
I pulled latest code and restarted Emacs. However, I am not getting the expected result. Secondly, the electric-pair has stopped working for the regular case too. For e.g. typing `print(` gives me `print(<point here>)`. After that typing `"` or `'` doesn't give me paired single or double quote (I end up with `print(")` instead of `print("")`).

**Comment by redguardtoo** [comment]
35b3187d fixed a bug (Chen Bin)

**Comment by amittendulkar** [comment]
Thanks, working properly now. 

Since the original issue reported is fixed with a temporary workaround, I will keep this issue open for now.

**Comment by redguardtoo** [comment]
3e96eee7 2020-12-07 upgrade wucuo (Chen Bin) 

This commit should fix the issue, even without aspell's fix.

**Comment by amittendulkar** [comment]
Closing the issue as the issue is no longer visible after the above fix.
