### ISSUE TITLE
Magit Status Information Missing

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#893]
I notice there is an update about magit and its purpose is to reduce the responding time.

True, before this update, magit is really slow especially when working on large project.

However, after the update, in the magit status buffer, there is only information about untracked files, modified files, etc., but no information related to remote repository. I have to say these information is really helpful. Are there any way to check these information easily? Are them removed to increase magit responding speed? If so, could I customize the status buffer and redisplay these information?

**Comment by redguardtoo** [comment]
See `my-prefer-lightweight-magit`. You can set it to false in `~/.custom.el` or add your own Magit setup there.
