### ISSUE TITLE
Electric pair not handling single quote completion overwrite gracefully

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#894]
If I am typing `'` (single quote), then I get `''` (2 single quotes) due to electric pair mode. 

However, if I mistakenly type another single quote at the state `'<point here>'`, I get `'''` (3 single quotes) instead of `''` (2 single quotes). The expectation is that the inadvertently typed single quote should be handled gracefully and overwrite the paired single quote.

The paired double quote is overwritten but not paired single quote.

**Comment by redguardtoo** [comment]
I think python also uses triple quotes.I don't want to be to radical  on this.

But you can freedom to override or re-use my code in `~/.custom.el` or elsewhere.

```lisp
(with-eval-after-load 'elec-pair
  (setq electric-pair-inhibit-predicate
        (lambda (char)
          ;; insert your code here
           my-electric-pair-inhibit char))))
```

**Comment by amittendulkar** [comment]
My issue is that the behavior is not consistent for single and double quotes.

Typing double quotes 3 times gives me six double quotes in this fashion: `"""<point here>"""`. And typing it twice gives me `""<point here>`.

Typing single quote 3 times again gives me six single quotes: `'''<point here>'''`. However, typing it twice gives me `''<point here>'`. 

Similarly, the DEL will symmetrically delete the double quotes. For e.g. `"""<point>"""` and hitting `DEL` (backspace) gives me `""<point>""` and one more `DEL` gives me `"<point>"`.

For single quote however the transition is from `'''<point>'''` to `''<point>'''` to `'<point>'''` and finally to `<point>''`. So returning to original state requires extra `DEL`.

Does this make sense? Otherwise, I will close the issue.

**Comment by redguardtoo** [comment]
If you start Emacs with `emacs -Q hello.py` and `M-x electric-pair-mode`, you still have this 6 quote problem.

See `elec-pair.el.gz` line 547~554,

![image](https://user-images.githubusercontent.com/184553/101706601-919b7580-3add-11eb-8834-a2004e483f8a.png)

`electric-pair-inhibit-predicate` is not called. So I'm not sure if `electric-pair-inhibit-predicate` could help in this scenario. 

The easiest solution is to raise a issue to its developer.

**Comment by amittendulkar** [comment]
Thanks for the explanation and tips. I will close this issue and reference it once I report the issue to the developer.
