### ISSUE TITLE
Typewriter Sound Does Not Work Under WSL + Pulse Audio

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#896]
I am using emacs in Windows Subsystem for Linux (WSL) and to pass the sound in Linux through Windows, I also use Pulse Audio. This setup works for emms but it does not work for the typewriter sound. 
It works also for local video/audio files and online streaming media. 
The system alert could also be passed through, e.g. when scroll to the beginning of the buffer and keep scrolling up, the alert generated by the system.
Thus I am wondering why only the typewriter sound could not be passed through?

**Comment by redguardtoo** [comment]
See  `twm/play-command`

**Comment by drcxd** [comment]
Why use `aplay` here rather than `mplayer`? What's the advantage of using `aplay`?

**Comment by redguardtoo** [comment]
d38b4acb typewriter-mode supports pulseaudio (Chen Bin)
Maybe pulseaudio command `paplay` exists.
