### ISSUE TITLE
vscode-dark-plus color theme issue

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#897]
Recently I find that when using the vscode-dark-plus color theme, the name of directories output by `ls` and key stroke hints for hydra commands are rendered in a dark blue color which is really hard to distinguish on the dark background.

I remember this is not the case weeks before, since I have been always using this color theme.

I am not sure if this is the color theme issue, so I ask first here.

By the way, is there any light color theme recommendation?

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/102866430-5c9f0380-448b-11eb-9dde-b65f1062adcb.png)

My looks pretty normal. 

I can't recommend any theme. Now I use `M-x random-healthy-color-theme`

**Comment by drcxd** [comment]
This is what I got:

![sample](https://user-images.githubusercontent.com/24535087/102906815-29d11d00-4443-11eb-88cd-2d6043f8b133.png)

Any idea where to start? I believe this happened after someday I updated my software packages and the emacs setup.

**Comment by redguardtoo** [comment]
I use true color terminal. Check README on terminal setup. If you use GUI Emacs, report the bug to theme's developer.

**Comment by drcxd** [comment]
I removed the directory `~/.emacs.d` and reinstall your setup, then the color returns to normal.
