### ISSUE TITLE
Python代码自动完成问题

### ISSUE THREAD

**Issue by chenyidao110** [redguardtoo/emacs.d#898]
**问题描述：**
    git clone你最新的配置，启动emacs后，elpy提示创建虚拟环境，确认后等待，minibuffer中提示"done"之后完成，编辑python文件，不会自动完成，没有代码提示，

**环境信息：**
 Elpy Configuration
  2
  3 Emacs.............: 27.1
  4 Elpy..............: 1.35.0
  5 Virtualenv........: None
  6 Interactive Python: python 3.9.1 (/usr/bin/python)
  7 RPC virtualenv....: rpc-venv (/home/xiaobai/.emacs.d/elpy/rpc-venv)
  8  Python...........: python 3.9.1 (/home/xiaobai/.emacs.d/elpy/rpc-venv/bin/python)
  9  Jedi.............: 0.18.0
 10  Rope.............: 0.18.0
 11  Autopep8.........: 1.5.4
 12  Yapf.............: 0.30.0
 13  Black............: 20.8b1
 14 Syntax checker....: Not found (flake8)
 15
 16 Warnings
 17
 18 You have not activated a virtual env. It is not mandatory but often a
 19 good idea to work inside a virtual env. You can use `M-x
 20 pyvenv-activate` or `M-x pyvenv-workon` to activate one.
 21
 22 The configured syntax checker (flake8) could not be found. Elpy uses
 23 this program to provide syntax checks of your code. You can either
 24 install it, or select another one using `elpy-syntax-check-command`.
 25
 26 [Install flake8]
 27
 28 Options
 29
 30 Square brackets indicate buttons; type RET or click mouse-1 on a
 31 button to invoke its action.  Invoke [+] to expand a group, and [-] to
 32 collapse an expanded group.  Invoke the [Group], [Face], and [Option]
 33 buttons below to edit that item in another window.
 34
 35 [+]-- [Group] Elpy
 36 [+]-- [Group] Python
 37 [+]-- [Group] Virtual Environments (Pyvenv)
 38 [+]-- [Group] Completion (Company)
 39 [+]-- [Group] Call Signatures (ElDoc)
 40 [+]-- [Group] Inline Errors (Flymake)
 41 [+]-- [Group] Code folding (hideshow)
 42 [ ]-- [Group] Snippets (YASnippet)

M+x执行elpy-compayny-backend，提示Cannot complete at point

**Comment by redguardtoo** [comment]
That's elpy problem. As I tested, company elpy backend does work. The problem is elpy rpc sever. My latest code enabled elpy backend error report flag. 

0082621d elpy backend error report is enabled by default (Chen Bin)

Reproduce the error and send the report to elpy developers,

**Comment by chenyidao110** [comment]
> That's elpy problem. As I tested, company elpy backend does work. The problem is elpy rpc sever. My latest code enabled elpy backend error report flag.
> 
> [0082621](https://github.com/redguardtoo/emacs.d/commit/0082621d1d196a6d720a7d741b4f10d8eed9aeb1) elpy backend error report is enabled by default (Chen Bin)
> 
> Reproduce the error and send the report to elpy developers,

On debian sid, generates more elpy error message. I have reported to elpy. Thank you!

**Comment by redguardtoo** [comment]
Looks Jedi 0.18.0 has changed its API. So I upgraded unstable version of elpy and solved this problem.

11e3ffc1 use latest elpy (Chen Bin)

**Comment by chenyidao110** [comment]
> 
> 
> Looks Jedi 0.18.0 has changed its API. So I upgraded unstable version of elpy and solved this problem.
> 
> [11e3ffc](https://github.com/redguardtoo/emacs.d/commit/11e3ffc1c073f6a0bd9bd59feed38d5adc218230) use latest elpy (Chen Bin)
> 
> See also https://github.com/redguardtoo/emacs.d#python-environment for python setup

follow your update, generate new issue:
Error Message

__init__() got an unexpected keyword argument 'source'

Configuration

Emacs.............: 27.1
Elpy..............: 1.35.0
Virtualenv........: rpc-venv (/home/test/.emacs.d/elpy/rpc-venv)
Interactive Python: python 3.9.1 (/home/test/.emacs.d/elpy/rpc-venv/bin/python)
RPC virtualenv....: rpc-venv (/home/test/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.9.1 (/home/test/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.18.0
 Rope.............: 0.18.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/home/test/.emacs.d/elpy/rpc-venv/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/test/.emacs.d/elpa/elpy-1.35.0/elpy/jedibackend.py", line 368, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

**Comment by redguardtoo** [comment]
upgrade elpy, jedi changed its API, so only unstable elpy works.

**Comment by chenyidao110** [comment]
> 
> 
> upgrade elpy, jedi changed its API, so only unstable elpy works.

How to upgrade elpy if using your emacs configuration

**Comment by redguardtoo** [comment]
`M-x list-packages` then press `U x`, see https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Menu.html

Or run `rm -rf ~/.emacs.d/elpa/elpy*` in shell and restart Emacs.
