### ISSUE TITLE
Racket-mode installation error

### ISSUE THREAD

**Issue by paprikaw** [redguardtoo/emacs.d#900]
I use `M-x package-install` to install racket-mode and got the error:

> Need package ‘pos-tip-20191127.1028 but only 0.4.6 is available

I realize this dependency is a package in the site-lisp, how can I get racket-mode working with a locked package? 

Thanks in advance!

**Comment by redguardtoo** [comment]
site-lisp is independent of package manager. In this case, it's because this emacs setup prefer stable version of package.
