### ISSUE TITLE
Difference between Find File and Swith Buffer

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#901]
I noticed that when executing `counsel-find-file` to create a new file and, at the same time, a new buffer, the buffer is well initialized: corresponding major and minor modes are enabled depends on the name of the file (and thus, the name of the buffer).

However, when executing `ivy-switch-buffer` to a new named buffer, the buffer is not well initialized: only the `Fundamental` mode is enabled?

Could you explain why it is configured like this? What's the essential difference between creating a buffer by creating a new file and directly creating a new named buffer? I sometimes would create a temporary buffer and do not plan to write to disk. If the created buffer is well initialized according to the buffer name, it would spare me a lot of chores.

**Comment by redguardtoo** [comment]
buffer is where user edit/read text. buffer could bind a file or a shell or anything (for example, save a buffer will save the buffer's text into narrowed region of another buffer).

I've not set up anything related to file or buffer. It's just how Emacs works.

You need finish the Emacs built in tutorial to understand “buffer”.

If you know Chinese, you could study my online tutorial “how to code faster". It teaches everything on coding faster.

https://www.udemy.com/course/how-to-code-faster-zh/

https://www.udemy.com/course/how-to-code-faster-zh/
