### ISSUE TITLE
Adding to auto-mode-alist in .custom.el does not work 

### ISSUE THREAD

**Issue by paprikaw** [redguardtoo/emacs.d#902]
### How I reproduce this problem:
I'd like to open the .rtk file with racket-mode so I add two lines to .custom.el:
``` lisp
(require 'racket-mode)
(add-to-list 'auto-mode-alist '("\\.rkt\\'" . racket-mode))
```
But it didn't work. Every time I was trying to open a `.rkt` file, it will use lisp as the default mode. And then I was trying to put these two lines to  `.emacs.d/.init.el`, it still didn't work.

### Which version am I using?
I use the clean version emacs of 9470513.

**Comment by paprikaw** [comment]
I think I found the answer from [here](https://github.com/syl20bnr/spacemacs/issues/3919#issuecomment-741605960), `add-to-list` only add element which doesn't exist in the list, but `("\\.rkt\\'" . racket-mode)` has existed in the list so 
`(add-to-list 'auto-mode-alist '("\\.rkt\\'" . racket-mode)) `can't add racket-mode entry to the `auto-mode-alist.`

**Comment by redguardtoo** [comment]
The racket code might inherit from old setup. I don't write racket any time. Thanks for the fix.

322dc810 clean code (Chen Bin)

**Comment by paprikaw** [comment]
Thanks a lot!
