### ISSUE TITLE
how to solve no permission problem on windows OS

### ISSUE THREAD

**Issue by robin2003** [redguardtoo/emacs.d#906]
when I want to make a link to the specific emacs config with follow command in elisp
`mklink /D "C:\Users\test\AppData\Roaming\.emacs.d"  "C:\Users\test\AppData\Roaming\emacs.d"
`
but **no permission** has been got when execute this command, 
so  is there some workaround  method on this no permission problem in elisp on windows platform?

**Comment by redguardtoo** [comment]
Set environment variable HOME instead.

**Comment by robin2003** [comment]
how does elisp get the administrator permision on windows OS?

**Comment by redguardtoo** [comment]
I don't know. I will mv `.emacs.d` into a directory where I have permission. Then set HOME directory.

**Comment by robin2003** [comment]
> I don't know. I will move `.emacs.d` into a directory where I have permission. Then set HOME environment variable.

ok, thanks a lot
