### ISSUE TITLE
can i use js-beautify with eslint ?

### ISSUE THREAD

**Issue by smallst** [redguardtoo/emacs.d#912]
some of my projects uses a strange eslint configuration for syntax. so emacs always get a wrong format. i remember you are a js programmer, too, so i'd like to know if you deal with eslint already. Thanks

**Comment by redguardtoo** [comment]
See http://blog.binchen.org/posts/easy-indentation-setup-in-emacs-for-web-development.html 
The indentation is set up in major mode. I don't have extra set up javascript. js2-mode has builtin parser which report some js syntax error. You can use flymake or flycheck to report extra syntax error in js.

**Comment by smallst** [comment]
okay, thanks!
