### ISSUE TITLE
chinese-calendar 报错

### ISSUE THREAD

**Issue by zheng7fu2** [redguardtoo/emacs.d#913]
let*: Symbol’s value as variable is void: calendar-font-lock-keywords
无法打开 中文日历

win10 Emacs27.1 全新clone的.emacs.d

**Comment by zheng7fu2** [comment]
查看了一下 cal-china-x  https://github.com/xwl/cal-china-x/commit/2a8d6de93ccb892660fdb5e397196fd8f42df152
Version: 2.5 更新到了 Version: 2.6b Remove usage of obsolete var calendar-font-lock-keywords.

site-lisp/cal-china-x 是2.5版本，报给大神更新。

**Comment by redguardtoo** [comment]
e61944c6 upgrade cal-china-x (Chen Bin)
