### ISSUE TITLE
Debugger entered--Lisp error: (void-variable <!DOCTYPE) when using PDB-mode.el

### ISSUE THREAD

**Issue by FPF-64** [redguardtoo/emacs.d#914]
Debugger entered--Lisp error: (void-variable <!DOCTYPE)
  eval-buffer(#<buffer  *load*-570842> nil "~/.emacs.d/plugins/pdb-mode/pdb-mode.el" nil t)  ; Reading at buffer position 16
  load-with-code-conversion("~/.emacs.d/plugins/pdb-mode/pdb-mode.el" "~/.emacs.d/plugins/pdb-mode/pdb-mode.el" nil nil)
  load("~/.emacs.d/plugins/pdb-mode/pdb-mode.el" nil nil t)
  load-file("~/.emacs.d/plugins/pdb-mode/pdb-mode.el")
  eval-buffer(#<buffer  *load*> nil "~/.emacs" nil t)  ; Reading at buffer position 1090
  load-with-code-conversion("~/.emacs" "/home/ferron/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1e0f4d>)()
  command-line()
  normal-top-level()

I am not sure what is wrong in the install the error message seems very common The pluggin use to work fine on emacs25 .
Thanks for your help

**Comment by redguardtoo** [comment]
re-download `pdb-mode.el`

**Comment by FPF-64** [comment]
Hi 
I did so the plug-in loads and works partially  I have to say that the plug-in stop working moving from ubuntu 18.04 to 20.04

**Comment by redguardtoo** [comment]
Check the code of plugin. It seems to be html file instead of emacs lisp file.
