### ISSUE TITLE
error: Need package ‘esxml-0.3.6’, but only 0.3.5 is available

### ISSUE THREAD

**Issue by Zilong-Li** [redguardtoo/emacs.d#916]
something wrong when require nov

**Comment by redguardtoo** [comment]
https://stable.melpa.org/#/esxml 0.3.6 is not released yet. You could use unstable version though.

Most packages from MELPA are invisible but packages from MELPA Stable are visible. You can modify variable melpa-include-packages in lisp/init-elpa.el to install unstable packages. Please choose stable packages if possible. Even advanced users often under-estimate the risk of unstable packages

**Comment by Zilong-Li** [comment]
Thanks for warning of unstable version. But I don't use these packages. I just cloned your repo and it didn't install everything successfully even though I tried `git reset --hard stable`. This is the error. 

I have to comment `(require-package 'nov)` out in `init-elpa.el` manually. This is annoying.

**Comment by redguardtoo** [comment]
2a5477e4 use latest esxml and kv (Chen Bin)

**Comment by Zilong-Li** [comment]
yeah, that's what I was guessing. glad you keep this updated
