### ISSUE TITLE
添加新包时报错

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#919]
最近在学习您的配置 遇到了如下问题：
我想添加  ivy-rich
![image](https://user-images.githubusercontent.com/60682638/113132768-7a7dc080-9251-11eb-83d5-f801d35efd4b.png)
<img width="1074" alt="WeChat109594a835c845d5704077f838856951" src="https://user-images.githubusercontent.com/60682638/113132895-a13bf700-9251-11eb-93ab-24316c096339.png">

启动的时候报错了 

Symbol's value as variable is void: ivy--display-transformers-list

不知道哪里出了问题  麻烦指点一下 感谢

**Comment by redguardtoo** [comment]
from README,
```
t packages from MELPA are invisible but packages from MELPA Stable are visible. You can modify variable melpa-include-packages in lisp/init-elpa.el to install unstable packages. Please choose stable packages if possible. Even advanced users often under-estimate the risk of unstable packages
```

Obviously `ivy-rich` requires unstable version of `ivy`.

**Comment by donneyluck** [comment]
嗯 readme中写的很详细了  我在仔细看几遍 感谢

**Comment by donneyluck** [comment]
![image](https://user-images.githubusercontent.com/60682638/113239201-d93c4c00-92dc-11eb-995f-aa61295bb5d4.png)
我在melp stable  也看到了ivy-rich   
ivy 和 ivy-rich 的 stable版 不匹配吗？

**Comment by redguardtoo** [comment]
stable 版本刚上线的吧
