### ISSUE TITLE
关于切换wg后find-file

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#920]
因为不用projectile
所以我把proj1 保存为一个wg proj2保存为另一个wg 这样可以方便我在多个项目中切换

问题是： 当我切换了wg后 ，i p
find file in project 还是在搜索老的目录

想请问下您的工作方法习惯 或者 解决方案

**Comment by redguardtoo** [comment]
什么是wg？ 找文件对应命令是什么？

**Comment by donneyluck** [comment]
> 什么是wg？ 找文件对应命令是什么？

wg就是 workgroup2
找文件的命令是 find file in project
又测试了一下 好像没有问题

想了解 类似projcetile中 find file in other project 您是怎么做的

**Comment by redguardtoo** [comment]
workgroups2 就是保存和载入窗口layout。

ffip默认就是从当前目录的向父目录搜索.git或.svn 
第一个找到的目录就是根目录。不需手动切换project

**Comment by donneyluck** [comment]
明白了 wg2即可当作proj的入口
ffip直接会在当前项目下搜索

还有个问题：
 如何在当前项目下 搜索项目外 或者 其他项目的文件呢

**Comment by redguardtoo** [comment]
编辑器没有项目这个概念。就是打开的当前文件告诉我项目根目录在哪里。我一般不需要考虑项目外文件的概念。因为很少用到。万一用到就手动打开一个文件。

一般程序员的思路是第一步打开最近工作的项目，然后第二步打开最近编辑的文件。我把第一步优化掉了，只要打开最近的文件就可以了。代价就是第三方目录的文件就不包含在项目里了，得用其他方法找文件。这个代价按照我使用数据统计是可以接受的。

建议看我的知乎专栏“如何提高编程速度”，我说“提高编程速度”不是开玩笑的。

**Comment by donneyluck** [comment]
就是喜欢您对编程速度的追求 和 工作流的优化 percol也是从您博客中学到的 了解了 感谢解答
