### ISSUE TITLE
refresh package list without restarting emacs

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#921]
When I need to install some new package from melpa, normally I'll add the package name into `melpa-include-packages` and restart emacs to make this update in effect. How can I make this change become effective without restarting emacs? 

![image](https://user-images.githubusercontent.com/3255399/114021943-d674c480-98a3-11eb-9abf-f63e42476b26.png)

Seems I cannot call `my-package--add-to-archive-contents-hack` directly (just have no idea on what args to be passed into this function.

**Comment by redguardtoo** [comment]
You can remove the advice `my-package--add-to-archive-contents-hack`.

**Comment by redguardtoo** [comment]
`melpa-inlucde-packages` is just a variable you can modify any time.

The key is when `package--add-to-archive-content` is called. You can check the code and find all its callers.  For example, `package-initialize` is calling it indirectly.

**Comment by phye** [comment]
Thanks for the hint!
