### ISSUE TITLE
关于 evil 其他模块中的使用

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#922]
斌哥 打扰了  在学习配置的过程中 

问题1：
我想在ivy-minibufer 和 compelte 补全中  使用 c-j c-k 取代 c-n c-p
尝试hack了一下没有成功   不知道是改哪个map

问题：
如何像doom一样 可以在全局使用 evil的操作方式 j k 移动  
比如 在magit中  每个插件都单独设置感觉不是很合理

**Comment by redguardtoo** [comment]
To be honest, I don't know much about ivy/evil key bindings.

For the first question, you need read ivy's code, I think it's defined in `ivy-minibuffer-map`

For the second question, I usually use original key bindings of plugins. As I said in http://blog.binchen.org/posts/how-to-be-extremely-efficient-in-emacs.html , I only customise key bindings of top 20~30 commands .

**Comment by donneyluck** [comment]
明白  还是按照自己日常的 keyfreq 设定快捷键  其他插件用原生按键  感谢回复
