### ISSUE TITLE
orgtbl-ctrl-c-ctrl-c: Wrong type argument: commandp, (keymap 

### ISSUE THREAD

**Issue by ArvinShaffer** [redguardtoo/emacs.d#924]
when i edit *.md files, i use C-c C-c have the bug, i dont know why, and can't find the solver in the issues. the error is as the following
`orgtbl-ctrl-c-ctrl-c: Wrong type argument: commandp, (keymap #^[nil nil keymap 
#^^[3 0 nil nil nil nil nil nil nil nil nil ...] nil nil nil nil nil nil nil nil ...] nil nil nil nil nil nil nil nil ...] nil nil nil nil nil ...] #("Command: markdown, preview, open, export, export & preview, check refs, unused refs, C-h = more" 9 10 (face markdown-bold-face) 19 20 (face markdown-bold-face) 28 29 (face markdown-bold-face) 34 35 (face markdown-bold-face) 54 55 (face markdown-bold-face) 60 61 (face markdown-bold-face) 72 73 (face markdown-bold-face)))
user-error: Minibuffer window is not activeError during redisplay: (eval undecided-unix) signaled (void-variable undecided-unix)
Error during redisplay: (eval undecided-unix) signaled (void-variable undecided-unix) [2 times]
`

**Comment by ArvinShaffer** [comment]
> Is your major mode `markdown-mode`? What's markdown-mode version? I test 2.4 and `C-c C-c` is prefix key set by markdown mode.

Yes, my major mode is markdown,  and the version is 2.4, what i need to do, update the markdown-mode version?

**Comment by redguardtoo** [comment]
```lisp
(with-eval-after-load 'org-table
  (define-key orgtbl-mode-map (kbd "C-c C-c") nil))
```
