### ISSUE TITLE
自动保存怎么关闭？

### ISSUE THREAD

**Issue by nesteiner** [redguardtoo/emacs.d#925]
我本来用`tide`写`typescript`，写着写着，一个自动保存把我的文件搞成这样，连高亮都没有了  
肿么一回事啊  
![2021-05-08 00-12-02 的屏幕截图](https://user-images.githubusercontent.com/46296608/117478714-15c12e80-af92-11eb-9662-abd77a7f6e06.png)

**Comment by nesteiner** [comment]
在**Message**窗口里找到的日志  
> Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
Tide mode enabled in current buffer
Use +,-,0 for further adjustment
Mark set
Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
Undo!
Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
Undo! [3 times]
Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
Undo!


突然发现`auto-save-mode`没有开，那这个自动`worte`的功能是哪来的啊

**Comment by donneyluck** [comment]
> 在**Message**窗口里找到的日志
> 
> > Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
> > Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
> > Tide mode enabled in current buffer
> > Use +,-,0 for further adjustment
> > Mark set
> > Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
> > Undo!
> > Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
> > Undo! [3 times]
> > Wrote /home/steiner/workspace/Nexus/Vue/demo/src/components/switcher-ts.vue
> > Undo!
> 
> 突然发现`auto-save-mode`没有开，那这个自动`worte`的功能是哪来的啊

site-lisp 下面的 auto-save.el  自己hack一下吧

**Comment by Tinker-S** [comment]
请教下想设置auto-save-idle的值，给不同的major-modes设置上不同的值，这个能做到吗

**Comment by redguardtoo** [comment]
@Tinker-S ， you can advice `auto-save-buffers`. Define a global variable which save the timestamp of last saving per major mode. Then inside `auto-save-buffer`, check current buffer's info and compare current time with the timestamp saved in the global variable.
