### ISSUE TITLE
如何进行代码移动

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#926]
类似move-region 没有在您的代码中看到

如果进行选中区域的 上下左右移动  这个在写代码的时候也会用到

**Comment by redguardtoo** [comment]
I don't know. I use vim key bindings. kill lines and yank lines.

**Comment by donneyluck** [comment]
kill lines and yank lines
可以完成上下移动
左右该如何处理呢 
比如 选中3行 整体右移

**Comment by redguardtoo** [comment]
kill/yank selection region in EVIL. Not exactly same thing, though.

**Comment by Tinker-S** [comment]
evil-shift-left / evil-shift-right? Maybe that's what you need.
