### ISSUE TITLE
在搜索结果中c-n c-p移动有明显卡顿

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#927]
整个配置使用起来 够轻量 够快 但是发现点问题
my-counsel-git-grep 搜索后 在候选列表中 C-n C-p 上下移动 会有很明显的卡顿 
不知道什么问题

**Comment by redguardtoo** [comment]
It's just a wrapper of `counsel-git-grep`.  You can  raise a issue to counsel/ivy project.

I use `cousel-etags-grep` which is more light weight.

**Comment by donneyluck** [comment]
我用counsel-rg做了测试 在doom中很流畅

在您的配置中依然有卡顿

**Comment by donneyluck** [comment]
![image](https://user-images.githubusercontent.com/60682638/118452974-45f29500-b729-11eb-81ad-41f0f79f59ed.png)
找到问题了
设置为0后 不再卡顿

**Comment by redguardtoo** [comment]
Use `(setq ivy-dynamic-exhibit-delay-ms (if (or *unix* *is-a-mac*) 10 250))`
