### ISSUE TITLE
emacs contacting host: network mirror while startup every tiime!

### ISSUE THREAD

**Issue by chenyidao110** [redguardtoo/emacs.d#929]
system: windows 10 21h1,wsl2 debian sid
emacs: GNU Emacs 28.0.50, git commit id: 2003a407c8bdf79dabe4f782039706d91c4fd9c5
emacs git id: 1f3d035193edba639a127f0119d4bbde5b147f93
install step:
 1. git clone https://github.com/redguardtoo/emacs.d.git .emacs.d
 2. modify init-elpa.el for use tsinghua mirror,than start emacs, wait until automatic install packages
 3. enter "emacs" in cmd to start, mini buffer show messages: "emacs contacting host: xxxx"
 4. buffer show contacting message every time while emacs startup
 
It has no effective to use, I want to know it's new feture or bug?

**Comment by redguardtoo** [comment]
I don't have this message. Maybe it's some package you installed.

grep `~/.emacs.d/elpa` to locate that package.

![image](https://user-images.githubusercontent.com/184553/120088635-fd2dd980-c135-11eb-8417-1122b54e2112.png)

**Comment by chenyidao110** [comment]
> 
> 
> I don't have this message. Maybe it's some package you installed.
> 
> grep `~/.emacs.d/elpa` to locate that package.
> 
> ![image](https://user-images.githubusercontent.com/184553/120088635-fd2dd980-c135-11eb-8417-1122b54e2112.png)

I just modify init-elpa.el for quick mirror, not install addtional package.
![emacs](https://user-images.githubusercontent.com/14362421/120088703-f26b4880-c125-11eb-9d05-fdb64441e298.gif)

**Comment by redguardtoo** [comment]
Looks OK to me.
So what's actual host?

**Comment by redguardtoo** [comment]
Did you comment melpa part before  uncomment tsinghua elpa in `init-elpa.el`?

![image](https://user-images.githubusercontent.com/184553/120092444-278f8f00-c156-11eb-9fee-71809768c90f.png)

**Comment by chenyidao110** [comment]
![emacs_source](https://user-images.githubusercontent.com/14362421/120092885-d927c380-c148-11eb-9610-7c5e69def58a.png)
![init-elpa](https://user-images.githubusercontent.com/14362421/120092886-d9c05a00-c148-11eb-98aa-7f6912cd2af1.png)

**Comment by redguardtoo** [comment]
looks ok to me. 
I'm not sure you can find the root cause on Windows. But on Linux there is a way to investigate.

You can use cli program `strace` to find which package is sending url request.

**Comment by chenyidao110** [comment]
After update, comment all the mirrors to avoid this issue
