### ISSUE TITLE
OpenBSD 6.9  Emacs 27.2 on startup hangs for 2 hours

### ISSUE THREAD

**Issue by vladp** [redguardtoo/emacs.d#930]
Hello,
I am trying to use the setup on a vanilla OpenBSD 6.9 with Emacs 27.2 (which comes standard in OpenBSD 6.9 prebuilt binary packages).

At the first startup it starated downloading files from melpa -- which is fine.
Then it started compiling the packages.

It seems to have finished that step, now it is doing something else. utilizing 2 of the Virtual CPUs I allocated to OpenBSD (I am running it on VirtualBox 6.x)

It has been going for some time (over 2 hours). It does not seem like there is an infinite loop (because it if it would be the case, it would be utilizing just one CPU at a time, but I am observing that it is using 2 CPUs at a time).

See attached screen shot.

Would really appreciate if you could recommend what steps I could take to troubleshoot the issue.

![emacs-openbsd-69-error1](https://user-images.githubusercontent.com/94890/120118569-3fb8db80-c161-11eb-9cd7-ea950e760ddf.png)

**Comment by redguardtoo** [comment]
Interesting. Does this problem happens only on OpenBSD or other OS? What's the the content of *Message* buffer?

**Comment by vladp** [comment]
Thanks for checking in this issue.  I have tried today on NetBSD 9.2/amd64 (Emacs 27.1) and the problem did not manifest there.
The initial run is still very slow (over an hour at least), but it finished and after that the startup time is over a second, but not by much.

What I started doing now is using TMUX to run emacs the first time.
That's because I cannot keep a remote session on my *BSD machines open for several hours.
But with TMUX I can let it run even after my remote session breaks off.

I do not know why the first run is so slow, it seems to be just getting emacs packages and compiling them.
May be it would be better to get all the packages at once and then compile, not sure.
My internet connection is reasonably fast, and I have been doing melpa package refreshes quite often on my other emacs configs.

When I was doing the initial install on OpenBSD , I had to restart it many times, over the course of 24 hours -- as the download-package-compile cycle was very very slow.

I am planning to redo my test on OpenBSD again, and do the initial startup in TMUX session, just like I am doing in NetBSD.
I have also now enabled softupdates on the OpenBSD filesystem to speed up operations. So this and in combination with TMUX, may be OpenBSD will finish the first run sooner. I will report back with my observations, when done.

**Comment by vladp** [comment]
I have re-done the OpenBSD 6.9 test.  And I could not reproduce same behavior as I reported
So will close the issue.

In this test, before running emacs on the newly downloaded  .emacs.d repo, I tuned OpenBSD (as compared to no-changes Install that I had done before), and then I ran emacs first time in TMUX session, so that it can complete without interuptions.

My tuning included enabling soft updates and noatime in /etc/fstab and some /etc/sysctl.conf changes.
With that and then running first time emacs in TMUX session, emacs core dumped once, I restarted and the the downloads/compilations  initiated by .emacs.d -- had completed.

Then I just went and disabled the 'evil' mode in the init file,  It is working now.


I use emacs server mode (by placing the below script into /home/<myhome>/bin folder).
So now the startup times really fast (on both OpenBSD and NetBSD)
```

#!/bin/sh                                                                                     
                                                                                              
usr=$(whoami)                                                                                 
emacs_daemon1="emacs --daemon"                                                                
cmd1="ps auxww | grep \"$usr.*$emacs_daemon1\" | grep -v grep"                                
#echo "$cmd"                                                                                  
is_running=$(eval "$cmd1")                                                                    
if [ -z "$is_running" ]                                                                       
then                                                                                          
    echo "Starting emacs daemon"                                                              
    eval "$emacs_daemon1"                                                                     
    if [ $? -ne 0 ]                                                                           
    then                                                                                      
        echo "$0: Cannot start $emacs_daemon1" >&2                                            
        exit                                                                                  
    fi                                                                                        
fi                                                                                            
emacsclient -a "" -t "$@"                                                                     
exit $?                                                                                       
```

**Comment by redguardtoo** [comment]
I also noticed that "package-initialize" was called multiple times when no package has been installed yet.  Once all packages are installed, the problem should be gone.
