### ISSUE TITLE
Slow to open C++ headers

### ISSUE THREAD

**Issue by phye** [redguardtoo/emacs.d#931]
Reproduce Procedure:

1. git clone some C++ repo, eg `git clone https://github.com/apache/incubator-brpc.git` brpc
2. `cd brpc`
3. `emacs -nw bthread/bthread.h`, it usually takes several seconds before the file will be opened, you can try to open other headers as well.

My findings:
1. trying to `toggle-debug-on-quit` and I can just find that emacs is in `redisplay_internal`
2. Each time a header file is opened, I can see that a pip3 process is fired, however I just cannot find where the root call is

**Comment by redguardtoo** [comment]
I don't have this problem.

See https://github.com/redguardtoo/emacs.d#hardcore-debug-technique

**Comment by phye** [comment]
That's quite strange. Emacs 27.2 is OK, but 26.2 is not. Will use strace to figure out why.
