### ISSUE TITLE
 <no-record> is undefined

### ISSUE THREAD

**Issue by jizai** [redguardtoo/emacs.d#932]
When typing some using pyim in evil insert mode, the minibuffer show this massage "\<no-record\> is undefined". How to solve this problem? 
emacs version : 26.3
.eamcs.d : the lastest of this repo

**Comment by jizai** [comment]
已解决，详情[点这里](https://github.com/tumashu/pyim/issues/402)

**Comment by redguardtoo** [comment]
5c0f5702 use stable pyim (Chen Bin)
