### ISSUE TITLE
Error: Need package 'transient-0.3.6', but only 0.3.5 is available

### ISSUE THREAD

**Issue by quarkquartet** [redguardtoo/emacs.d#933]
Hi,

I'm using this emacs config. But I meet this error while starting emacs:
`error: Need package ‘transient-0.3.6’, but only 0.3.5 is available`

My OS system is MacOS catalina. I'm using melpa outside China (choose "No" for the start up question).

Reproduce: simply git clone this directory to `~/.emacs.d`, start emacs (latest setup). After installation, I finally have this.

**Comment by redguardtoo** [comment]
magit developer fogot to tag his own package `transient`. I pinged him on twitter. 
![image](https://user-images.githubusercontent.com/184553/124271466-d4f42900-db80-11eb-98b4-cd0455f3fd2f.png)

Download unstable version from https://melpa.org/packages/transient-20210701.1116.tar and run `M-x package-install-file`.

**Comment by redguardtoo** [comment]
Ok. It's fixed. Wait a few hours for melpa.
