### ISSUE TITLE
TAG file and tag file 

### ISSUE THREAD

**Issue by jizai** [redguardtoo/emacs.d#935]
When i use 'citre' which generated a tag file in project root path, there are some additional contents in **my-imenu-or-list-tag-in-current-file**'s result. How to solve this problem? (On the other word, I don't want this commamd to read tags file.)
![图片](https://user-images.githubusercontent.com/12199375/124596332-ba79c280-de94-11eb-8e38-0ebc77cc8eb8.png)

**Comment by redguardtoo** [comment]
You can just use `my-counsel-imeu` or `counsel-imeu` instead.

**Comment by jizai** [comment]
Thank for you  enthusiastic answers！ Citre changed the imenu setup and I commented those codes, then it works very well!
