### ISSUE TITLE
关于使用er/expand-region的问题， 使用v扩展之后，想使用c进行修改会有问题；

### ISSUE THREAD

**Issue by moxuetianya** [redguardtoo/emacs.d#936]
1、这是触发了er/expand-region后；
![image](https://user-images.githubusercontent.com/16444334/125081772-f57c3000-e0f8-11eb-8b1f-682995c1a6eb.png)
2、这个使用想进行修改， 使用c后会变成这样；
![image](https://user-images.githubusercontent.com/16444334/125081941-2fe5cd00-e0f9-11eb-9182-738e0766c5f0.png)

ps：问题：使用vvc会出问题（evil nomal state状态：期望选中一个区域然后修改）；
使用,xxx（3个x，最右一个x是触发的expand扩展word）进行扩展遇到同样的问题；

**Comment by moxuetianya** [comment]
使用vvc会出问题（evil nomal state状态：**期望选中一个区域然后修**改）；

**Comment by redguardtoo** [comment]
a6cf2547 fixed typo in expand contract hotkey (Chen Bin)

**Comment by moxuetianya** [comment]
可以了，👍🏻
