### ISSUE TITLE
sudo zypper in emacs, 25.3 version error can‘t load init.el

### ISSUE THREAD

**Issue by Oferiston** [redguardtoo/emacs.d#938]
emacs version should at least be 26.1. how to fix it.

**Comment by redguardtoo** [comment]
25.3 is not supported any more. Check https://github.com/redguardtoo/emacs.d#support-legacy-emacs-versions if you want to use old version of Emacs.

**Comment by Oferiston** [comment]
besides download other versions, does other solutions exist?

**Comment by redguardtoo** [comment]
You can comment out the lines I highlighted. But I highly recommend emacs 26. Its line number rendering is re-written in C. Huge performance boost.
