### ISSUE TITLE
counsel-etags-find-tag-at-point打开文件强制转换了软链接

### ISSUE THREAD

**Issue by mortimerzhu** [redguardtoo/emacs.d#941]
设置了find-file-visit-truename nil(或者vc-follow-symlinks nil)后，counsel-find-file打开带有软链接的文件，显示出来的文件路径是带有软链接的，我想要保持这个风格，但是counsel-etags-find-tag-at-point在查询到tag后打开的文件路径就是不带软链接的文件路径了（文件的真实路径），有没有什么配置可以让counsel-etags-find-tag-at-point不进行软链接的强制转换？

**Comment by redguardtoo** [comment]
Could you give me more details? Better with an example.

**Comment by mortimerzhu** [comment]
Here are the steps:
1. cd ~/code; git clone git@github.com:cesanta/frozen.git
2. cd ~/project; ln -s ~/code/frozen .
3. cd frozen
4. add (setq find-file-visit-truename nil) in ~/.custom.el
4. TERM=xterm-256color emacs -nw
5. ,xf  then choose unit_test.c
6. go to line 122, move cursor to json_walk, then C+] to go to definition, it will open file frozen.c, but run ,xf again, it shows now is under directory ~/code/frozen, not ~/project/frozen. Also, org-store-link also will show the link is ~/code/frozen

I use symbolic link to manager code and project, and write org mode note in each project directory, so I want when C+] open a new file, it keeps symbolic link.

**Comment by redguardtoo** [comment]
b8d47e5 donot use file-truename (Chen Bin)

**Comment by mortimerzhu** [comment]
confirmed
