### ISSUE TITLE
my-counsel-git-grep 不能搜索中文

### ISSUE THREAD

**Issue by xxyyer** [redguardtoo/emacs.d#943]
这个问题已经折腾我好几个日夜了，甚至查看elisp代码，能力有限，还是未能解决，请指教：

windows的emacs下使用 ,gg 搜索中文无效，但是用cmd命令行这样是可以的：

git --no-pager grep --full-name -n --no-color -i -I -e "测试搜索中文"
test.txt:3:测试搜索中文

请问怎么解决呢？

（我现在工作需要用到windows，不方便切换到Linux。）

**Comment by redguardtoo** [comment]
https://cdsp-scpo.github.io/wpss-doc/nc/windows-activation-utf8/
