### ISSUE TITLE
git-gutter Fails in Windows

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#946]
I am currently using Emacs in Windows on a project managed by Subversion.

The Emacs binary is downloaded from the GNU website. Emacs has access to the `svn` or `svn.exe` command.

Emacs commands like `vc-diff`, `vc-annotate` and `vc-dir` works well.  However, `git-gutter` could not display those marks on the side bar. `git-gutter` mode is enabled and there is no related error messages in the `*Messages*` buffer.

Any suggestions?

**Comment by redguardtoo** [comment]
`git-svn`?

**Comment by drcxd** [comment]
Well, I could try that. However, I was using Emacs in WSL and working on the same project. In WSL, git-gutter works well. In the README of git-gutter, it also mentioned that svn is supported.

There is also another quick question, though not related to this issue particularly. In Linux, if a file is modified outside Emacs, Emacs will automatically reflect that modification. Thanks to your configuration. However, in Windows, this feature just disappears. Emacs would not reflect changes from outside, it would even not ask me to revert the buffer if I try to modify the same file, which is already staled, in Emacs. Is it possible to fix this problem?

**Comment by redguardtoo** [comment]
Check comment in `init-misc.el`,

```
(unless (or *cygwin* *win64*)
  ;; Takes ages to start Emacs.
  ;; Got error `Socket /tmp/fam-cb/fam- has wrong permissions` in Cygwin ONLY!
  ;; reproduced with Emacs 26.1 and Cygwin upgraded at 2019-02-26
  ;;
  ;; Although win64 is fine. It still slows down generic performance.
  ;; @see https://stackoverflow.com/questions/3589535/why-reload-notification-slow-in-emacs-when-files-are-modified-externally
  ;; So no auto-revert-mode on Windows/Cygwin
  (setq global-auto-revert-non-file-buffers t
        auto-revert-verbose nil)
  (my-run-with-idle-timer 4 #'global-auto-revert-mode))
```

You can comment out my setup.

**Comment by drcxd** [comment]
To clarify, I am using a Windows native Emacs with Windows native svn. All `vc-*` commands works well, I could diff, annotate, and even commit using these commands in Emacs. Since I am using a native Windows toolchain, I suppose it's not because of access to executable or path convention.

The wired thing is when I am using Linux Emacs with Linux svn in WSL, git-gutter works well. I could also diff and annotate but I can't commit using `vc-*` commands. It is a problem of permission. WSL Linux processes could not write to Windows svn repository database.

> Maybe you can take over this project?

I am not sure which one you are talking about?

**Comment by redguardtoo** [comment]
I don't know much about wsl.  My workflow is using native Windows Emacs and Cygwin cli tools (svn/git/p4/find/grep....). I never has any file permission issue.

I mean it's a good opportunity to take over the https://github.com/emacsorphanage/git-gutter.

**Comment by drcxd** [comment]
Yes, you just reminded me that I could try MSYS2 svn. 

> I mean it's a good opportunity to take over https://github.com/emacsorphanage/git-gutter.

I'd love to, but I know nothing about Emacs lisp. Just to make sure we are on the same page, by "taking over", you mean I could make a fork of that repository and contribute to it, right? I have never contributed to the open source world, shame.

**Comment by redguardtoo** [comment]
Ok, I'll have a look. Could you show me the minimum steps to reproduce the issue? I've not touched svn for ages.

**Comment by drcxd** [comment]
Since this is a really specific issue, I do not expect you to spend any time on it. I could try other similar tools like diff-hl, maybe that will work.

If you are really interested in this problem, it is kind of troublesome to reproduce it. 

First, you have to install a Windows Subversion, the one with graphics interface and make sure you check the option to install the command line client tool, although you may want to use Cygwin or MSYS2 svn command line tool. Then just create a new repository and commit something to it. After that just launch a Windows version Emacs with your default setup and edit that file. 

I can't help with the detail of setting up a subversion repository or server, since I have never set up a subversion repository myself. I am working on a proprietary software and the repository is setup by my coworkers.

Again, this is a very specialized issue, and I just intended to see if you already know how to deal with it. You may actually could not reproduce it since I am working in a really specific environment. I think someday I will learn Emacs lisp and then I could debug on it myself.

Thanks.
