### ISSUE TITLE
Wucuo Spell Checking Fail in Windows When Provided with User Dictionary

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#947]
I am using aspell and wucuo in Windows.  I installed apsell and its dictionary in MSYS2, the package names are `msys/aspell 0.60.8-1` and `msys/aspell6-en` respectively. 

It works well with the default settings. However, after I execute the command `wucuo-create-aspell-personal-dictionary`, I get an error message saying "Can't check region" when I execute the command `wucuo-spell-check-visible-region`. If I delete the personal dictionary file, it works again.

To reproduce this problem, just install a Windows native Emacs, pull your default setup, and install MSYS2 with those packages I mentioned above and make sure Emacs has access to aspell executable in MSYS2 directory.

**Comment by drcxd** [comment]
Not sure why I can't reproduce this problem today. Today when I tried to save a buffer, I found wucuo is emitting addtional error message. It complains about the line-breaking character in the personal dictionary file. After I changed the file's coding system to `utf-8-unix`, wucuo could work well with the personal dictionary.

**Comment by redguardtoo** [comment]
Thanks. I updated wucuo doc.
