### ISSUE TITLE
Default key binding in *vc-diff* buffer

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#948]
Currently, if I open a *vc-diff* buffer by executing command `vc-diff` or pressing "=" in a *vc-dir* buffer, it is in a evil key mapping state. However, *vc-diff* has useful key mapping configs which is available in Emacs state, such as `q` to close the diff buffer, `n` to move to next hunk, etc.. Each time I open a *vc-diff* buffer, I have to use `C-z` to enable Emacs state.

I think it is preferred to open this *vc-diff* buffer which is in Emacs state by default. Could you change this particular behavior?

Sorry for the improper choice of terms, I am not quite familiar with the key binding things.

**Comment by redguardtoo** [comment]
87a05795 can customize evil state per major mode (Chen Bin)

**Comment by drcxd** [comment]
Thanks
