### ISSUE TITLE
关于evil 复制粘贴 和 clipboard复制粘贴的疑问

### ISSUE THREAD

**Issue by donneyluck** [redguardtoo/emacs.d#955]
问题1:  为什么需要两套复制粘贴   是否能够互通 （evil 复制的时候 也复制到clipboard 这样是不是方便点）
问题2： 使用场景是什么 想学习一下  
问题3:  GUI下evil-yank复制的内容 不能覆盖另一个选中区域  终端下没问题
感谢解答

**Comment by redguardtoo** [comment]
我的工作流需要经常拷贝文本。clipboard等于多了一个拷贝文本的手段。网上流行的或者默认的方法是kill-ring和clipboard互通，我刻意不这样做当然是因为我的效率更高。例如从一行的两个地方拷贝文本到另一行的两个地方

我的知乎专栏和我的教程都强调速度是第一位的，所以如果我的采用了没有采用流行方案，原因当然是我追求文本文件操作的效率。

GUI的问题是EVIL的bug，我已提交PR https://github.com/emacs-evil/evil/pull/1536

我的emacs.d已修复这个问题。

**Comment by donneyluck** [comment]
学到了 确实有这种需要  需要多个拷贝的时候多一种手段 就可以提高效率 
感谢解答
