### ISSUE TITLE
关于低配机器安装失败的问题

### ISSUE THREAD

**Issue by mn-nm** [redguardtoo/emacs.d#957]
系统是manjaro linux ，emacs-nox 27.2，4g内存，安装过程中emacs内存占用越来越大，超过2.5g，然后系统卡死，不知有无办法解决（除了买新机
已排查过，不是网络问题

**Comment by redguardtoo** [comment]
`emacs --debug-init`具体什么信息？ 可能有些插件对于内存有不合理要求。我可以把这些插件排除掉。我常用的插件消耗内存都不大。

**Comment by BlacAmDK** [comment]
> `emacs --debug-init`具体什么信息？ 可能有些插件对于内存有不合理要求。我可以把这些插件排除掉。我常用的插件消耗内存都不大。

是在第一次全新安装的时候下载并编译包会占用大量内存, 我也遇到过这种问题

**Comment by redguardtoo** [comment]
aa06b4db use less memory on low spec machine (Chen Bin)
