### ISSUE TITLE
Company Issues under LSP-mode

### ISSUE THREAD

**Issue by drcxd** [redguardtoo/emacs.d#958]
I am using LSP with company. 

The reason that I am not using tag based completion and navigation system is that I am mainly working on a Unreal Engine 4 project. UE4 use a lot of macros to mark the C++ code and before the compilation, its build tool parse the source code and then generate some code based on these macros, to implement its own reflection system. Those macros make tag based system works improperly. The tag system simply ignore the macro-modified members. What's more, UE4 is a huge project that the generated tag file is so large that it makes looking for a particular tag a really slow task.

LSP is quite practical solution and it applies a general method to solve the completion, navigation and even refactoring problems. However, I found that your setup does not work well with lsp-mode. 

First, in the README file, you suggest ` (setq lsp-enable-completion-at-point nil)`. This turns off the code completion feature provided by lsp, which is one of the most important feature provided with it.
Second, for some particular language, in my case, they are c++ and lua, even if I turn on the completion, it works improperly. For example, in C++, if I am typing `int`, then the completion list pop up and it may contains something like
```
int16
int32
int64_t
...
```
Now if I type `6`, the program just complete with the sixth option, rather than input `6`. This happens also in lua-mode, also, with lsp-mode enabled. However, in python-mode, under such situation, `6` will be considered as input rather than choosing the sixth completion option.

I tried doom eamcs and under its configuration, c++-mode with lsp-mode enabled, the completion works properly.

Maybe you are not an user of lsp-mode, but it has been evolved quite much and enabled Emacs a lot. Could you consider update your setup against lsp-mode and optimize these behaviors?

**Comment by redguardtoo** [comment]
dd7908ea company setup and doc (Chen Bin)

**Comment by drcxd** [comment]
Thanks for your quick response, but I still have a little question. Given the following code:
```
void myfunc31();
void myfunc32();
void myfunc33();
void myf|
```
`|` denotes the location of the cursor, now company would prompt something like:
```
myfunc31
myfunc32
myfunc33
```
Now, I think if I press TAB, company should auto complete to the latest common character in the options. However, this is not the case in lsp-mode. Could you explain why the completion behaves differently inside or outside lsp-mode?

**Comment by redguardtoo** [comment]
I think you need ask the developer who implemented the company backend (lip-mode?) for help.

**Comment by drcxd** [comment]
Sure, thank you.
