### ISSUE TITLE
error ("Package ‘emacs-27.1’ is unavailable")

### ISSUE THREAD

**Issue by geometryolife** [redguardtoo/emacs.d#959]
`emacs —version`: GNU Emacs 26.3

`emacs —debug-init`:

Debugger entered--Lisp error: (error "Package ‘emacs-27.1’ is unavailable")                                                                                             signal(error ("Package ‘emacs-27.1’ is unavailable"))                                                                                                                 error("Package `%s-%s' is unavailable" emacs "27.1")                                                                                                                  package-compute-transaction((#s(package-desc :name modus-themes :version (20211117 1517) :summary "Highly accessible themes (WCAG AAA)" :reqs ((emacs (27 1))) :ki  nd tar :archive "melpa" :dir nil :extras ((:commit . "1ac72499c930435bb86fa9c2205e4c4b6c2699bc") (:authors ("Protesilaos Stavrou" . "info@protesilaos.com")) (:maint  ainer "Protesilaos Stavrou" . "info@protesilaos.com") (:keywords "faces" "theme" "accessibility") (:url . "https://gitlab.com/protesilaos/modus-themes")) :signed ni  l)) ((emacs (27 1))) (#s(package-desc :name modus-themes :version (20211117 1517) :summary "Highly accessible themes (WCAG AAA)" :reqs ((emacs (27 1))) :kind tar :a  rchive "melpa" :dir nil :extras ((:commit . "1ac72499c930435bb86fa9c2205e4c4b6c2699bc") (:authors ("Protesilaos Stavrou" . "info@protesilaos.com")) (:maintainer "Pr  otesilaos Stavrou" . "info@protesilaos.com") (:keywords "faces" "theme" "accessibility") (:url . "https://gitlab.com/protesilaos/modus-themes")) :signed nil)))         package-compute-transaction(nil ((modus-themes)))
 package-install(modus-themes)                                                                                                                                         (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-conte  nts) (require-package package min-version t)))                                                                                                                          require-package(modus-themes nil t)                                                                                                                                   (cond ((package-installed-p package min-version) t) ((or (assoc package package-archive-contents) no-refresh) (package-install package)) (t (package-refresh-conte  nts) (require-package package min-version t)))                                                                                                                          require-package(modus-themes)                                                                                                                                         (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--)))                                                            (while --dolist-tail-- (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-tail--))))                                    (let ((--dolist-tail-- popular-themes)) (while --dolist-tail-- (let ((theme (car --dolist-tail--))) (require-package theme) (setq --dolist-tail-- (cdr --dolist-ta  il--)))))                                                                                                                                                               my-install-popular-themes((afternoon-theme alect-themes ample-theme ample-zen-theme anti-zenburn-theme apropospriate-theme atom-dark-theme atom-one-dark-theme bad  wolf-theme base16-theme birds-of-paradise-plus-theme bubbleberry-theme busybee-theme cherry-blossom-theme clues-theme color-theme-sanityinc-solarized color-theme-sa  nityinc-tomorrow cyberpunk-theme dakrone-theme darkburn-theme darkmine-theme darkokai-theme darktooth-theme django-theme doom-themes dracula-theme espresso-theme ex  otica-theme eziam-theme fantom-theme farmhouse-theme flatland-theme flatui-theme gandalf-theme gotham-theme grandshell-theme gruber-darker-theme gruvbox-theme hc-ze  nburn-theme hemisu-theme heroku-theme inkpot-theme ir-black-theme jazz-theme jbeans-theme kaolin-themes leuven-theme light-soap-theme lush-theme madhat2r-theme ...)  )                                                                                                                                                                       (if my-disable-idle-timer nil (my-install-popular-themes (quote (afternoon-theme alect-themes ample-theme ample-zen-theme anti-zenburn-theme apropospriate-theme a  tom-dark-theme atom-one-dark-theme badwolf-theme base16-theme birds-of-paradise-plus-theme bubbleberry-theme busybee-theme cherry-blossom-theme clues-theme color-th  eme-sanityinc-solarized color-theme-sanityinc-tomorrow cyberpunk-theme dakrone-theme darkburn-theme darkmine-theme darkokai-theme darktooth-theme django-theme doom-  themes dracula-theme espresso-theme exotica-theme eziam-theme fantom-theme farmhouse-theme flatland-theme flatui-theme gandalf-theme gotham-theme grandshell-theme g  ruber-darker-theme gruvbox-theme hc-zenburn-theme hemisu-theme heroku-theme inkpot-theme ir-black-theme jazz-theme jbeans-theme kaolin-themes leuven-theme light-soa  p-theme lush-theme madhat2r-theme ...))))                                                                                                                               eval-buffer(#<buffer  *load*-574644> nil "/home/ubuntu/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 15854                                         load-with-code-conversion("/home/ubuntu/.emacs.d/lisp/init-elpa.el" "/home/ubuntu/.emacs.d/lisp/init-elpa.el" t t)                                                    load("/home/ubuntu/.emacs.d/lisp/init-elpa" t t)                                                                                                                      (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t))                                                                                                   (if (or (not maybe-disabled) (not (my-vc-merge-p))) (progn (load (file-truename (format "%s/%s" my-lisp-dir pkg)) t t)))                                              require-init(init-elpa)                                                                                                                                               (let* ((file-name-handler-alist nil)) (require-init (quote init-autoload)) (require-init (quote init-modeline)) (require-init (quote init-utils)) (require-init (q  uote init-file-type)) (require-init (quote init-elpa)) (if my-disable-idle-timer (progn (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir)))) (r  equire-init (quote init-spelling) t) (require-init (quote init-ibuffer) t) (require-init (quote init-ivy)) (require-init (quote init-windows)) (require-init (quote   init-javascript) t) (require-init (quote init-org) t) (require-init (quote init-python) t) (require-init (quote init-lisp) t) (require-init (quote init-yasnippet) t  ) (require-init (quote init-cc-mode) t) (require-init (quote init-linum-mode)) (require-init (quote init-git)) (require-init (quote init-gtags) t) (require-init (qu  ote init-clipboard)) (require-init (quote init-ctags) t) (require-init (quote init-bbdb) t) (require-init (quote init-gnus) t) (require-init (quote init-lua-mode) t  ) (require-init (quote init-workgroups2) t) (require-init (quote init-term-mode) t) (require-init (quote init-web-mode) t) (require-init (quote init-company) t) (re  quire-init (quote init-chinese) t) (require-init (quote init-keyfreq) t) (require-init (quote init-httpd) t) (require-init (quote init-theme)) (require-init (quote   init-essential)) (require-init (quote init-misc) t) (require-init (quote init-emacs-w3m) t) (require-init (quote init-shackle) t) (require-init (quote init-dired) t  ) (require-init (quote init-writting) t) (require-init (quote init-hydra)) (require-init (quote init-evil)) (require-init (quote init-ediff)) (if my-disable-idle-ti  mer nil (my-add-subdirs-to-load-path (file-name-as-directory my-site-lisp-dir))) (require-init (quote init-flymake) t) (if (my-vc-merge-p) nil (setq custom-file (ex  pand-file-name (concat my-emacs-d "custom-set-variables.el"))) (if (file-exists-p custom-file) (load custom-file t t)) (load (expand-file-name "~/.custom.el") t nil  )))                                                                                                                                                                     eval-buffer(#<buffer  *load*> nil "/home/ubuntu/.emacs.d/init.el" nil t)  ; Reading at buffer position 6100                                                           load-with-code-conversion("/home/ubuntu/.emacs.d/init.el" "/home/ubuntu/.emacs.d/init.el" t t)                                                                        load("/home/ubuntu/.emacs.d/init" t t)                                                                                                                                #f(compiled-function () #<bytecode 0x1e0f4d>)()                                                                                                                       command-line()                                                                                                                                                        normal-top-level()

**Comment by redguardtoo** [comment]
fixed

**Comment by geometryolife** [comment]
> * [aa2e65e](https://github.com/redguardtoo/emacs.d/commit/aa2e65ea79a6befff6ee63c7c3764d73d1c5fea6) 2021-11-18 modus-themes requires emacs27 (Chen Bin)

Thank you！
