### ISSUE TITLE
Globally replaces related shortcuts

### ISSUE THREAD

**Issue by geometryolife** [redguardtoo/emacs.d#960]
![EA119AB6-23C6-4ED6-8030-5778D282879D](https://user-images.githubusercontent.com/54882546/142759117-c79e573c-fbfd-4b96-b956-fffe7ace3900.jpeg)

如图所示，我想知道在选中了一个词后，如何快速地调出左下角的正则，我不想用手一个个输入，在你的教程有演示操作，但是却没提到这个操作的快捷键。我想知道。

**Comment by redguardtoo** [comment]
`M-x my-rename-thing-at-point`，快捷键见`init-evil.el`。该命令是几个命令的封装，实际调用了`evilmr-replace-in-defun`。 该命令来自我多年前开发的插件`evil-mark-replace`。开发这个插件时我水平一般，后来也没有加什么功能。实际上counsel/ivy要比它强大得多。建议不要浪费时间在我的早期插件上。我的教程推荐的counsel/ivy才是主流和正道。

**Comment by geometryolife** [comment]
> `M-x my-rename-thing-at-point`，快捷键见`init-evil.el`。是几个命令的封装。可能是调用了`evilmr-replace-in-defun`。 命令`evilmr-replace-in-defun`来自我多年前开发的插件`evil-mark-replace`。开发这个插件时我水平一般，后来也没有加什么功能。实际上counsel/ivy要比它强大得多。建议不要浪费时间在我的早期插件上。我的教程推荐的counsel/ivy才是主流和正道。

谢谢明白了。

**Comment by t6ui** [comment]
> `M-x my-rename-thing-at-point`，快捷键见`init-evil.el`。是几个命令的封装。可能是调用了`evilmr-replace-in-defun`。 命令`evilmr-replace-in-defun`来自我多年前开发的插件`evil-mark-replace`。开发这个插件时我水平一般，后来也没有加什么功能。实际上counsel/ivy要比它强大得多。建议不要浪费时间在我的早期插件上。我的教程推荐的counsel/ivy才是主流和正道。

@redguardtoo 陈兄，这个场景下用,rb不是很方便吗？需要用其他什么命令代替这个操作吗？

**Comment by redguardtoo** [comment]
> > `M-x my-rename-thing-at-point`，快捷键见`init-evil.el`。是几个命令的封装。可能是调用了`evilmr-replace-in-defun`。 命令`evilmr-replace-in-defun`来自我多年前开发的插件`evil-mark-replace`。开发这个插件时我水平一般，后来也没有加什么功能。实际上counsel/ivy要比它强大得多。建议不要浪费时间在我的早期插件上。我的教程推荐的counsel/ivy才是主流和正道。
> 
> @redguardtoo 陈兄，这个场景下用,rb不是很方便吗？需要用其他什么命令代替这个操作吗？

swiper的命令(比如自动输出到一个occur buffer里)拿来改改比这强大得多. 一样是正则表达式替换, swiper基于ivy的UI界面更灵活,功能更多.

我主要是现在懒得弄了.

**Comment by t6ui** [comment]
@redguardtoo 了解了。谢谢陈兄！

**Comment by Stumble** [comment]
@redguardtoo 请问目前您最推荐的find and replace的方法是？我发现在master branch上的evilmr有一些问题，例如在匹配区域的开始，会多出一个`'`符号。您上面提到的使用counsel/ivy的组合，可以发一些相关资料了链接吗？看了一下ivy，swiper的文档，还是没有太理解如何使用它来完成find and replace的过程。
![image](https://github.com/redguardtoo/emacs.d/assets/3461891/f94229f1-5b9c-4f5b-87ed-0dc23c43bf21)

**Comment by redguardtoo** [comment]
见 https://sam217pa.github.io/2016/09/11/nuclear-power-editing-via-ivy-and-ag/ 虽然写的是多文件查找替换,但文件也适用.

`M-x swiper`后 `C-c C-o`
