### ISSUE TITLE
wrong-type-argument commandp hydra-git/body

### ISSUE THREAD

**Issue by peng051410** [redguardtoo/emacs.d#965]
When run 

> space g g

Got an error:
```
Debugger entered--Lisp error: (wrong-type-argument commandp hydra-git/body)
  call-interactively(hydra-git/body nil nil)
  command-execute(hydra-git/body)
```

Emacs version: GNU Emacs 27.2 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H1615)) of 2022-02-14

**Comment by redguardtoo** [comment]
a83cf47b fixed hydra setup (Chen Bin)

**Comment by peng051410** [comment]
Everything is ok!
