### ISSUE TITLE
display-linum-mode

### ISSUE THREAD

**Issue by Zexin-Li** [redguardtoo/emacs.d#968]
陈斌大佬，问一下，我的版本是27.2，fork了你的配置，想开启相对行号设置，在`init-linum-mode.el`添加了如下代码，效果如图，突出显示当前行生效了，但相对行号没有生效，是我用命令行emacs问题吗？我在Windows Emacs 27.2 GUI（简单配置，开启行号、相对行号、突出显示当前行）下是有效果的
![image](https://user-images.githubusercontent.com/53425340/158052499-f696941b-75be-4f4c-9487-472167d4a6f0.png)

**Comment by guoqinglei** [comment]
相对行号，有这个需求吗？

**Comment by Zexin-Li** [comment]
现在没有了，甚至把行号都关了
