### ISSUE TITLE
怎么将eaf整合到作者的配置中去？

### ISSUE THREAD

**Issue by PandaZhym** [redguardtoo/emacs.d#969]
最近接触到emacs-application-framework -> https://github.com/emacs-eaf
真的太棒了，对于pdf，上网的功能真的太棒了。其他功能还没有尝试，但是这两个功能真的好棒。
所以想问问大家，是不是可以将eaf整合到作者的配置中来？

**Comment by redguardtoo** [comment]
就按照eaf的README安装就行了。我的配置并无任何魔改。
