### ISSUE TITLE
wg-open-workgroup,wg-create-workgroup工作不正常

### ISSUE THREAD

**Issue by hhcwyx** [redguardtoo/emacs.d#970]
运行这两个命令的时候，mini-buffer显示：end  file during parsing.
查看 ~/.emacs_workgroups 文件，文件是空的。
原来工作正常，当更新到陈老师最新配置后，出现了这个问题。

我又git pull了一下，更新到最新的版本。下面是现象：
将 ~/.emacs_workgroups文件删除后，分了三个window，每个window显示不同文件的内容，此时运行wg-create-workgroups命令，minibuffer内显示命令创建了wg，正常。但是关闭emacs，后重新打开，使用wg-open-workgroups命令加载workgroups，在minibuffer内也有提示刚刚创建的workgroups,但是，选中后，就是加载不了，minibuffe里显示：Attempt to set a constant symbol:nil  。

**Comment by redguardtoo** [comment]
882ccbc9 upgrade workgroups2 (Chen Bin)
If the emacs.d still does not work, show me a minimum example to reproduce the issue.

**Comment by hhcwyx** [comment]
更新后，问题解决了，谢谢陈老师
