### ISSUE TITLE
dired does not show file attributes 

### ISSUE THREAD

**Issue by TooChaos** [redguardtoo/emacs.d#971]
OS: ubuntu 20.04

emacs --version
GNU Emacs 27.1

emacs.d
a15c73db7157d570daa8c814d84aacf15f07614c

I found the dired does not show file attribute by default and by providing "flag" '-l' using C-u prefix. Instead it shows as if there is no "flag" supplied to 'ls'.  However when running emacs -Q, it does show attributes by default and work as expected with C-u prefix.

Would you please help?

Thank you!

**Comment by redguardtoo** [comment]
comment out `(dired-hide-details-mode 1)` in `init-dired.el`

**Comment by TooChaos** [comment]
Cool! I didn't know dired has this feature! Thank you!
