### ISSUE TITLE
how to open the url website in the org file with external program such as default internet explorer instead of using w3m ?

### ISSUE THREAD

**Issue by guoqinglei** [redguardtoo/emacs.d#972]
I have tried to modify the settings of the variable browse-url-generic-program to the default internet explorer of OS, but it does not work.

**Comment by redguardtoo** [comment]
`C-u C-c C-o` That's Emacs builtin feature.

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/163399778-0913ba25-09d9-49f4-9eed-599393becbe9.png)

**Comment by guoqinglei** [comment]
> Try `C-u C-c C-o`

 Thanks.

it works when i put the mouse to the position of url and press C-u C-c C-o. 

But if  I click the mouse on the link , it's still opened with e3w. How to solve this ?

**Comment by redguardtoo** [comment]
Search `my-org-open-at-point-hack`, you can comment out the setup.
