### ISSUE TITLE
How to disable rainbow-mode?

### ISSUE THREAD

**Issue by nahso** [redguardtoo/emacs.d#973]
Adding `(rainbow-mode 0)` to custom.el is not working, so I tried to delete `site-lisp/rainbow-mode` directly, but there was an error message occurring when I opened a cpp file. 

I didn't find any configurations referring to rainbow-mode. Is there any elegant way to disable it?

**Comment by redguardtoo** [comment]
`minor-mode` is usually disabled in hook of `major-mode`.

**Comment by nahso** [comment]
Thank you! It works. By the way, how can I remove this package?

**Comment by nahso** [comment]
I found it. Just commenting the autoload statement of rainbow-mode in init-autoload.el is enough.
