### ISSUE TITLE
Missing in ReadMe: need to comment out init-theme to disable random themes.

### ISSUE THREAD

**Issue by Stumble** [redguardtoo/emacs.d#974]
Hey Bin,

Simply adding `(load-theme ..)` at the end of init.el might not work because the random theme function was run with a idle-timer. IMHO, it is worth mentioning the Color Theme section of how to disable random (good) themes.

**Comment by redguardtoo** [comment]
`(setq my-enable-startup-color-theme-p nil) ` in `~/.custom.el`
