### ISSUE TITLE
emacs浮空显示输入的命令字符的插件

### ISSUE THREAD

**Issue by liuchanghui1987** [redguardtoo/emacs.d#978]
陈兄您好：
   请教个问题，在emacs输入命令时候，能实时显示输入命令的字符的插件叫什么名字，您不知道用没用过，特此请教一下
   目的是实时监测自己输入命令的正确性
   先谢谢了

**Comment by redguardtoo** [comment]
Do you have screenshot?

**Comment by liuchanghui1987** [comment]
已经确认，是mac的小软件-keycastr，谢谢了
