### ISSUE TITLE
是否可以把ranger整合到配置里面去？

### ISSUE THREAD

**Issue by hhcwyx** [redguardtoo/emacs.d#983]
陈老师你好，请问能否把ranger整合到配置里面去？

**Comment by redguardtoo** [comment]
You can add ranger or any other package in `~/.custom.el` or `init-elpa.el`.  I use Emacs bulti package system. So it's pretty simple.

I don't use ranger because I'm alreadying using dired (see `init-dired.el`).

**Comment by hhcwyx** [comment]
谢谢！
