### ISSUE TITLE
启动emacs时会自动链接melpa.org

### ISSUE THREAD

**Issue by hhcwyx** [redguardtoo/emacs.d#984]
陈老师你好，每次emacs gui启动时，在minibuffer显示：
  Contacting host:melpa.org:443
大概20秒左右，启动才完成，很不舒服，请问，怎么不让它这么干呢？

**Comment by redguardtoo** [comment]
That should not happen unless some package is not installed. See `require-package` definition at `init-elpa.el`.

If you have problem to to connect `melpa..org`, you could modify `init-elpa.el` to use another package repo.

**Comment by hhcwyx** [comment]
谢谢！
