### ISSUE TITLE
The Vue auto rebuild fails due to the #file generated by Emacs

### ISSUE THREAD

**Issue by nahso** [redguardtoo/emacs.d#985]
I use `yarn serve` to launch my Vue project. As long as the files are saved, yarn will rebuild the project automatically. It is fine to edit the code by using Vim, but when I use Emacs, yarn will fail instantly.

yarn is fine when using Vim:

https://user-images.githubusercontent.com/47053538/167432501-cbec3914-56e4-4dbc-b5f9-4a6ed39a7ef4.mp4

yarn fails after I insert a line by using Emacs:

https://user-images.githubusercontent.com/47053538/167432698-c6b28f8c-9835-453f-a3f9-bf0b536d7eff.mp4

I have already disabled the auto save and auto backup by this:

```lisp
(setq auto-save-default nil)
(setq make-backup-file nil)
```

but the problem still exists

**Comment by redguardtoo** [comment]
set up `.gitignore` to ignore the tmp file.
