### ISSUE TITLE
recentf can't save the file opened by ssh

### ISSUE THREAD

**Issue by nahso** [redguardtoo/emacs.d#990]
Hello,
I already have the `ssh` line commented in the init-misc.el, but the file opened with ssh didn't show in the `counsel-recentf` even though I execute `recentf-save-list` manually.

The `/ssh:192.168.56.105:/home/admin/scripts/test.sh` which is the file of current buffer doesn't display:

![image](https://user-images.githubusercontent.com/47053538/174823958-1833926e-6eff-4d8f-8d37-82cf4ac7a1a2.png)

Here is the recentf-mode section of my init-misc.el
```elisp
(setq recentf-keep '(file-remote-p file-readable-p))
(setq recentf-max-saved-items 2048
      recentf-exclude '("/tmp/"
                        ;; "/ssh:"
                        "/sudo:"
                        "recentf$"
                        "company-statistics-cache\\.el$"
                        ;; ctags
                        "/TAGS$"
                        ;; global
                        "/GTAGS$"
                        "/GRAGS$"
                        "/GPATH$"
                        ;; binary
                        "\\.mkv$"
                        "\\.mp[34]$"
                        "\\.avi$"
                        "\\.wav$"
                        "\\.docx?$"
                        "\\.xlsx?$"
                        ;; sub-titles
                        "\\.sub$"
                        "\\.srt$"
                        "\\.ass$"
                        ;; "/home/[a-z]\+/\\.[a-df-z]" ; configuration file should not be excluded
                        ))
``` 

Thanks!

**Comment by redguardtoo** [comment]
I guess it's because `(recentf-mode 1)`, it will do the clean up on on history (removing non-existing file, etc).  See `recentf-auto-cleanup`

**Comment by nahso** [comment]
Thank you! After doing some tests, it seems that the ssh files will be removed regardless of whether the ssh server is online or offline. 

Therefore I write my own `recentf-keep` function:
```elisp
(defun my-ssh-p (name)
  (equal (string-match "^/ssh:" name) 0))
```

It works!
