### ISSUE TITLE
Update how to disable vim key bindings in Readme

### ISSUE THREAD

**Issue by fenguoerbian** [redguardtoo/emacs.d#992]
Currently in readme about [how to disable vim key bindings](https://github.com/redguardtoo/emacs.d#disable-vim-key-bindings), it says to Comment out line containing `(require 'init-evil)` in init.el.

But now in a fresh install,  commenting out  `(require 'init-evil)`  results in an error when start up about missing `general-imap`

```
Warning (initialization): An error occurred while loading ‘~/.emacs.d/init.el’:

Symbol's function definition is void: general-imap

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

Previously when setting up my last laptop, this comment out procedure works, but it fails now so maybe something has changed. so I think it's necessary to update the corresponding part of readme. 

Currently I'm adding a `(evil-mode 0)` in `.custom.el` to set emacs mode as default for evil.

**Comment by redguardtoo** [comment]
84e43f23 generl setup is dependent on evil-mode (Chen Bin)

**Comment by fenguoerbian** [comment]
Yeah, I figured there must be something that's dependent on evil-mode. That's why I'm suggesting to update the readme about how to disable vim keybindings since directly comment `(require 'init-evil)` is not feasible.
