### ISSUE TITLE
emacs 28.1 cannot use wubi

### ISSUE THREAD

**Issue by pinvondev** [redguardtoo/emacs.d#997]
in expect, when I input "wq", it where returns "你"
but in fact, it return "wq"
![image](https://user-images.githubusercontent.com/34933730/188276249-232d3e3a-d92c-48e8-9d76-4eb2693676e7.png)
![image](https://user-images.githubusercontent.com/34933730/188276261-a4411b30-ca66-4928-9919-5525d3430d5e.png)

**Comment by redguardtoo** [comment]
`(setq my-pyim-enable-wubi-dict t)`

**Comment by redguardtoo** [comment]
08c34f3c fixed wubi ime (Chen Bin)

You also need upgrade the pyim-wbdict to the latest version.
